### DISCUSSION TITLE
Indent configuration not working for C++

### DISCUSSION THREAD

**Discussion by Ha5hBr0wn** [helix-editor/helix#10033] [General]
Hi I am using the Helix text editor and my indents in C++ are just 2 spaces and I want them to be 4. I can't figure out how to make it work

I have been adding the indent to the languages.toml file as the docs tell me to:

```
[[language]]
name = "cpp"
auto-format = true
formatter = {command = 'clang-format', args= ["--style=Google"]}
indent = { tab-width = 4, unit = "    " }
```

I was on version 20.05 at first and I also tried on latest master but I alway just get 2 spaces in auto indent and when I press tab

I know the languages.toml file is getting picked up because if I change the style for the formatter that does take effect as expected. So just the indent key is not working as expected for me

**Comment by woojiq** [comment]
If you have a file that already has an indent of 2 spaces, you will have 2 spaces despite your configuration. Try in a new file or format yours with 4 spaces manually (or using formatter).
Fyi, this configuration works for me:
```toml
 [[language]]
 name = "c"
 indent = { tab-width = 4, unit = "    " }
 [[language]]
 name = "cpp"
 indent = { tab-width = 4, unit = "    " }
```

Do you have 2 spaces identation only after saving file or even on typing?

**Comment by sbromberger** [comment]
I just noticed that my C++ code (both existing and new files) are using two spaces instead of four (which is what they used to have). How do I change this? I just added
```
indent = { tab-width = 4, unit = " " }
```
but it doesn't seem to have any effect.

This is `helix 24.7 (30fb63cc)`.

**Reply by woojiq** [reply]
It should work with new files. In older files it will detect that there is indentation = 2 and will not even look at your config.
Workaround: manually convert tab 2->4 on old files.

**Reply by sbromberger** [reply]
It doesn't work with new files. I wonder if it's clang-format that's causing the issue.

**Reply by woojiq** [reply]
```toml
# languages.toml
[[language]]
name = "cpp"

[language.indent]
tab-width = 4
unit = "    "

[[language]]
name = "c"

[language.indent]
tab-width = 4
unit = "    "
```
