### DISCUSSION TITLE
Format C/C++ automatically on save?

### DISCUSSION THREAD

**Discussion by 766F6964** [helix-editor/helix#10048] [Q&A]
I am working with a C codebase, and I have `clangd` installed - the autocompletion works just fine.
However, it seems that formatting doesn't, at least no the way I would like it to.

I have a `language.toml` file, that looks like this:
```toml
[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "clangd" ]
indent = { tab-width = 4, unit = " " }
```
I always want the indentation to be 4 spaces in my code - ideally automatically whenever I save.
As of now, it doesn't. The indentation stays at 2 spaces (which I believe is the default of helix).
Running `:format` manually also doesn't change the indentation to 4 spaces - am I missing something?

EDIT: It seems like the configuration doesn't have any affect at all? Changing the unit to e.g. two spaces also doesn't change anything?

**Comment by kirawi** [comment]
The file is `languages.toml` not `language.toml`

`clangd` will also automatically default to 2 (see https://github.com/helix-editor/helix/discussions/8426) and Helix will automatically use the indentation from formatting.

**Reply by 766F6964** [reply]
That was just a typo in my post here, the file is infact named `languages.toml`.
It also seems that the formatting only applies to new code being written, but it does not seem to reformat existing code?

So, bsaed on the issue you linked, it seems there is on way to reformat all the existing code?

**Reply by kirawi** [reply]
You need to configure clangd. The config is in one of the comments in that issue.

**Reply by 766F6964** [reply]
I am not sure which config you are referring to exactly.
I see this one: `language-server = { command = "clangd", args = ['--fallback-style=Webkit'] }` - which I already specified in my `languages.toml`

My `languages.toml` now looks like this:
```toml
[[language]]
name = "c"
scope = "source.c"
file-types = ["c"]
comment-token = "//"
language-server = { command = "clangd", args = ['--fallback-style=Webkit'] }
indent = { tab-width = 4, unit = "    " }
auto-format = true
```
But it does not seem to be valid, at least helix does not want to accept it? Starting helix with this config present, results in this error message:
```
Bad language config: unknown field `language-server`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`, `persistent-diagnostic-sources`
in `language`

Press <ENTER> to continue with default language config
```
Did the syntax for specifying the language server change? There is a field named `language-servers` (plural), but I am not sure how I would assign that?

I tried the following, but that didn't work: `language-servers = [{ command = "clangd", args = ['--fallback-style=Webkit'] }]`

**Reply by kirawi** [reply]
Yes, it changed with 23.10.

It's
```toml
[language-server.clangd]
args = [ ... ]
```
