### DISCUSSION TITLE
Don't remove whitespaces after pressing Enter

### DISCUSSION THREAD

**Discussion by DoctorRainer** [helix-editor/helix#10075] [General]
It's convenient to navigate indented code, it's better to implement an option that allows you to keep trailing spaces. Removing trailing spaces interferes with indentation and navigation

**Comment by DoctorRainer** [comment]
Fixed with (not quite but I'm trying to come up with a better way):
```toml
"S-ret" = "open_above"
"ret" = "open_below"
```
