### DISCUSSION TITLE
Rainbow CSV colouring

### DISCUSSION THREAD

**Discussion by Amparose** [helix-editor/helix#10190] [Ideas]
It would be useful to have some sugar for editing CSV files, which is difficult to do accurately a lot of the time without something like [mechatroner/rainbow_csv: 🌈Rainbow CSV - Vim plugin: Highlight columns in CSV and TSV files and run queries in SQL-like language](https://github.com/mechatroner/rainbow_csv).

**Comment by markstos** [comment]
There's already a published tree-sitter grammar that's been published for rainbow CSV coloring. Here's how it looks when used in Helix:

![image](https://github.com/helix-editor/helix/assets/25829/4e89cd7a-f3e5-438a-9314-a6a36e105259)

You can add it to Helix with this in ~/.config/helix/languages.toml:

```toml
[[language]]
name = "csv"
file-types = ["csv"]
scope = "source.csv"

[[grammar]]
name = "csv"
source.git = "https://github.com/weartist/rainbow-csv-tree-sitter"
source.rev = "896e6d09b23a1b0d87e45bf97ca34a249f41495c"
```
Then:

```
hx --grammar fetch
hx --grammar build
```

Then place this in `~/.config/helix/runtime/queries/csv/highlights.scm`

```scheme
; Literals
(second)@keyword
(third)@function.method
(fourth)@number
(fifth)@comment
(sixth)@type
(seventh)@operator
```

If there's interest in Helix supporting this "out of the box", I could see about figuring how to submit a PR to add this as one of the built-in supported languages. 

Yes, it's sort of abusing the query system to generate the rainbow colors, but as an exceptional case, this seems like the most useful way to look at CSV files in a text editor.
