### DISCUSSION TITLE
Trasparency/opacity should not be a part of the  theme.

### DISCUSSION THREAD

**Discussion by igor-petruk** [helix-editor/helix#10223] [General]
It should be a separate setting that could be applied to any theme, instead of creating transparent version like `base16_transparent`. Otherwise users have to customize every single theme if they want to try it on transparent terminal.

**Comment by the-mikedavis** [comment]
Since #3067, you can inherit any theme and unset the `ui.background` scope:

```toml
# ~/.config/helix/themes/dracula_transparent.toml
inherits = "dracula"
"ui.background" = {}
```

I don't like the idea of adding an extra config option for this.

**Reply by ghost** [reply]
If you still don't like the idea of adding a config option for this, how about generalizing the behavior of `base16_transparent`?

If someone writes
```toml
theme = "theme_transparent"
```
in their config.toml, the editor first looks for a file named exactly `theme_transparent`, if it can't find it it just runs
```toml
inherits = "theme"
"ui.background" = {}
```
This way people can easily get a transparent background for any theme they want just by adding `_transparent` at the end.
No need to fiddle with override files and no need for other config options.
