### DISCUSSION TITLE
Assign all keymap action into commands (ability to remap action utilize assigned number and register)

### DISCUSSION THREAD

**Discussion by NNBnh** [helix-editor/helix#10230] [General]
From the look of the current [key remapping docs](https://docs.helix-editor.com/remapping.html), there is currently no way remap action utilize assigned number/count or register.

There is 2 solution that i could thinks of:

### 1. Quick approach

```toml
"L" = [5, "move_next_word_end"] # move 5 word_end right
"A-l" = ["move_line_up", "number", "move_char_right"] # move up then move N char right
# N == assigned number before the key is pressed.

"Y" = ["a", "yank"] # yank to "a" slot
"A-y" = ["clipboard", "yank"] # yank to clipboard
"D" = ["nul", "delete_selection"] # delete selection without yank
"A-Y" = ["switch_to_uppercase", "register", "yank"] # upper case selected text then yank to R slot
# R == assigned register before the key is pressed.
```

This method feel kind of janky and i much prefer the 2nd approach:

### 2. Consistent approach (Emacs approach)

Emacs full name is "Editor MACroS" and as the name suggest, all action in Emacs is a macro/command. So remapping key is simply assign a command to a button:

```el
(global-set-key (kbd "M-l") 'forward-char)
```

I found this approach make the editor very consistent:
- The good news is there is already an PR #1169 that could make this be possible.
- The bad new is we need to turn all keymaps action in to commands (a mountain of work), then somehow hide them from the command mode so the command mode don't get polluted

```toml
"L" = ["goto word_end right 5"] # move 5 word_end right
"A-l" = ["goto char up", "goto right number"] # move up then move N char right
# N == assigned number before the key is pressed.

"Y" = ["yank a"] # yank to "a" slot
"A-y" = ["yank clipboard"] # yank to clipboard
"D" = ["delete nul"] # delete selection without yank
"A-Y" = ["case up", "yank register"] # upper case selected text then yank to R slot
# R == assigned register before the key is pressed.
```

Please consider implement this approach because this will improve the keybind and upgradability in the long run
