### DISCUSSION TITLE
Allow adding special variables to languages.toml

### DISCUSSION THREAD

**Discussion by haras-unicorn** [helix-editor/helix#10268] [General]
I was looking over issues and couldn't find anything similar so i hope I'm not duplicating anything because I love this editor and I don't wanna slow down the progress for anyone.

Anyway, [in vscode launch.json you can add variables to certain values](https://code.visualstudio.com/docs/editor/variables-reference). This is especially useful for setting up debugging scenarios. Here is the languages.toml for a rust project of mine (a bit abbreviated):

```toml
[[language]]
name = "rust"

[language.debugger.templates.args]
program = "target/debug/some-bin"
args = ["--config", "path/to/some/config"]
```

As you can see, I have to reference a binary from `target/debug` and also a config file in a directory relative to the repository root. This is a bit annoying because if I start helix from a subdirectory of my repository (a Rust workspace for example) I cannot debug this binary because it tries to find it from the directory i started in. If helix had something similar to vscode my languages.toml would look like this:

```toml
[[language]]
name = "rust"

[language.debugger.templates.args]
program = "${workspaceFolder}/target/debug/some-bin"
args = ["--config", "${workspaceFolder}/path/to/some/config"]
```

This is just a suggestion, but I found that [handlebars](https://github.com/sunng87/handlebars-rust) is a good way to add this kind of functionality in personal projects. It may be a bit of overkill for this, but it is a pretty well known format and easy to add to a project. I'd even be interested in adding this functionality in a PR if someone could point me to where config is loaded in helix.
