### DISCUSSION TITLE
Can I set "ZZ" shortcut to save & close file, just like vim?

### DISCUSSION THREAD

**Discussion by AllanZyne** [helix-editor/helix#10328] [Q&A] [answered]
I tried to configure this, but failed.

**Comment by kumawatdarshan** [comment, marked as answer]
```toml
[keys.normal.Z]
"Z" = ":x"
```
