### DISCUSSION TITLE
Suggestion: tab/shift-tab as ergonomic alias for alt+right/left arrow

### DISCUSSION THREAD

**Discussion by aral** [helix-editor/helix#10388] [General]
The select previous and next adjacent sibling key bindings are very useful for quickly navigating your code.

It feels like <kbd>tab</kbd> (for next adjacent sibling) and <kbd>shift</kbd><kbd>tab</kbd> for (previous adjacent sibling) would make ergonomic and semantically intuitive aliases for <kbd>alt</kbd><kbd>→</kbd> and <kbd>alt</kbd><kbd>←</kbd>.

**Comment by the-mikedavis** [comment]
This can be bound in a custom keymap:

```toml
# ~/.config/helix/config.toml
[keys.normal]
tab = "select_next_sibling"
S-tab = "select_prev_sibling"
```

But the sibling selection commands are already duplicated in the default keymap between `A-poin` and Alt + arrow keys. IMO the default keymap should be lean and if anything I think we should remove Alt + arrow keys from the keymap since the directionality can be confusing/unintuitive: https://github.com/helix-editor/helix/issues/2202
