### DISCUSSION TITLE
Python workspace symbols

### DISCUSSION THREAD

**Discussion by robyoung** [helix-editor/helix#10449] [Q&A]
## Context

I have just started trying out helix today. I have configured pylsp and it seems to be working for finding symbols within a file and auo-importing symbols from the wider workspace. However, when I try `<space>-S` (Open workspace symbol picker) I get the following message in red at the bottom of the screen "No configured language server supports workspace symbols".

I have tried with both pylsp and pyright to no avail.

## Question

How can I configure workspace symbols to work with pylsp?

## Configuration

<details>
<summary><code>~/.config/helix/config.toml</code></summary>

```toml
theme = "onedark"

[editor]
line-number = "relative"

[keys.normal]
A-s = ":w" # Save with Alt-s
```
</details>

<details>
<summary>
pylsp <code>~/.config/helix/languages.toml</code>
</summary>

```toml
[[language]]
name = "python"
language-servers = ["pylsp"]
roots = [".git"]
workspace-lsp-roots = ["apps/api", "."]
auto-format = true

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true
plugins.rope_autoimport.enabled = true
```
</details>

<details>
<summary>
pyright <code>~/.config/helix/languages.toml</code>
</summary>

```toml
[[language]]
name = "python"
language-servers = ["pyright"]
formatters = ["ruff"]
roots = [".git"]
workspace-lsp-roots = ["apps/api", "."]
auto-format = true
```
</details>

## Additional

I have pylsp installed with pipx. I have installed the following packages in the virtualenv.

- `python-lsp-server[all]`
- `pylsp-mypy`
- `python-lsp-ruff`

Pyright is also installed with pipx with no additional packages.

LSP health is this for pylsp
<img width="330" alt="Screenshot 2024-04-15 at 12 30 41" src="https://github.com/helix-editor/helix/assets/14287/3f98d938-0e84-4b91-a057-c68a48fcbcbb">

And this for pyright
<img width="597" alt="Screenshot 2024-04-15 at 12 57 37" src="https://github.com/helix-editor/helix/assets/14287/9bc68738-af80-407f-ab3f-41ff86fbe59a">
