### DISCUSSION TITLE
Allow key symbols in keybinding labels

### DISCUSSION THREAD

**Discussion by eugenesvk** [helix-editor/helix#10521] [Ideas]
Currently all keys in config are using letters for both modifiers and actual keys
This hurts readability when you have to deal with remapping in big batches

For example
```toml
'A-A'	= 'cmd' # the letters look the same
'h'  	= 'cmd' #
'H'  	= 'cmd' # H is ⇧h though for some reason ⇧ is not on the side with all other modifiers
'A-,'	= 'cmd' # 
'A-<'	= 'cmd' # < is ⇧, but it's not immediately visible
'C-h'	= 'cmd'
'C-x'	= 'cmd'
```

The better alternative would be to allow and __option__ to replace modifier __letters__ with modifier __symbols__
(you can also ditch the unnecessary quotes as there is already a separator between keys and values, and allow literal `=`)
↓ now it's obvious which modifier is used since the same modifier is in the same column
```
⇧ ⎇ a 	: cmd # the letters look the same... NOT, there is only one letter!
     h	: cmd #
⇧   h 	: cmd # the difference with h is much more apparent
   ⎇, 	: cmd # 
⇧ ⎇,  	: cmd # it's obvious that this is the same physical ,comma, key like in↑
 ⎈  h 	: cmd
 ⎈  x 	: cmd
```

- And in the future when you'd add differentiation between left and right modifiers, you could easily do this
```
‹⇧  ‹⎇ a	: cmd
       h	: cmd
⇧›     h	: cmd
     ⎇, 	: cmd
⇧   ⎇,  	: cmd
  ‹⎈  h 	: cmd
  ⎈›  x 	: cmd
```

- The same principle allows to use 1-symbol short (and easier to read) non-modifier keys

| Key name     | Representation | Symbol          	|
| ---          | ---            | ---             	|
| Backspace    | `"backspace"`  | ␈ or ⌫          	|
| Space        | `"space"`      | ␠ or ␣          	|
| Return/Enter | `"ret"`        | ⏎ or ↩ or ⌤ or ␤	|
| \-           | `"minus"`      | −               	|
| Left         | `"left"`       | ◀ or ←          	|
| Right        | `"right"`      | ▶ or →          	|
| Up           | `"up"`         | ▲ or ↑          	|
| Down         | `"down"`       | ▼ or ↓          	|
| Home         | `"home"`       | ⇤ or ⤒ or ↖     	|
| End          | `"end"`        | ⇥ or ⤓ or ↘     	|
| Page Up      | `"pageup"`     | ⇞               	|
| Page Down    | `"pagedown"`   | ⇟               	|
| Tab          | `"tab"`        | ⭾               	|
| Delete       | `"del"`        | ␡ or ⌦          	|
| Insert       | `"ins"`        | ⎀               	|
| Escape       | `"esc"`        | ⎋               	|

- ... an the command palette could display shorter and easier to visually differentiate messages,  so instead of 
  `<A-left>` you'd just have
  `⎇◀`
