### DISCUSSION TITLE
Elixir language server not working

### DISCUSSION THREAD

**Discussion by achenet** [helix-editor/helix#10530] [Troubleshooting] [answered]
Hello,

I'm trying to do some work in Elixir. When I enter an Elixir codebase, if I try to use LSP features, they don't work.
For example, if I try to use `goto-defintion`, I'll get `No configured language server supports goto-defintion`.

However, I have `elixir-ls` installed and setup:
```sh
 hx --health elixir
Configured language servers:
  ✓ elixir-ls: /home/utilisateur/.local/bin/elixir-ls
Configured debug adapter: None
Configured formatter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓

```
the general health of my install:

```sh
 hx --health
Config file: /home/utilisateur/.config/helix/config.toml
Language file: /home/utilisateur/.config/helix/languages.toml
Log file: /home/utilisateur/.cache/helix/helix.log
Runtime directories: /home/utilisateur/.config/helix/runtime;/home/utilisateur/.cargo/bin/runtime
Clipboard provider: wl-paste+wl-copy
System clipboard provider: wl-paste+wl-copy
```
if we look in `/home/utilisateur./.config/helix/languages.toml`, we have:
```toml
[[language]]
name = "elixir"
scope = "source.elixir"
file-types = ["ex", "exs"]
auto-format = true
diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
injection-regex = "(elixir|ex)"
shebangs = ["elixir"]
roots = ["mix.exs", "mix.lock"]
language-servers = [ "elixir-ls" ]

```
I also have `$HOME/helix/languages.toml`, which contains the same block.
Testing with other languages, namely Go and Rust, shows that `goto-defintion` works with these languages.

I'm curious as to why it's not working on Elixir, and how I can get it working.
