### DISCUSSION TITLE
Including a suggestion to Discussions in Issue Template chooser

### DISCUSSION THREAD

**Discussion by krish-r** [helix-editor/helix#10558] [Ideas] [answered]
I observed that Ideas / Q&A / Troubleshooting are sometimes being posted under Issues, requiring the maintainers to convert them into Discussions. 

I think including a suggestion to Discussions in the Issue Template chooser might encourage (new) users to post such topics directly into Discussions instead.

(User currently needs to choose `Issues > New issue > Enhancement` to see the comment - `If this is an idea for a feature, please open an "Idea" Discussion instead.`)

This also provides an option to - 
- disable blank issues.
- add additional links for ex. FAQ, Matrix space, etc.

Example `.github/ISSUE_TEMPLATE/config.yml` file:
```yaml
blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/helix-editor/helix/discussions
    about: For Ideas / Q&A / Troubleshooting.
```
GitHub Docs: [Configuring the template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

WezTerm:
https://github.com/wez/wezterm/blob/cce0706b1f2a9e2d1f02c57f2d1cd367c91df1ae/.github/ISSUE_TEMPLATE/config.yml

VS Code:
https://github.com/microsoft/vscode/blob/410e3fde6f669cd0a1a198326c4843c59657d74b/.github/ISSUE_TEMPLATE/config.yml
