### DISCUSSION TITLE
How to create add Go HTML templates to LSP?

### DISCUSSION THREAD

**Discussion by andradei** [helix-editor/helix#10665] [Q&A] [answered]
Helix's LSP has a general purpose `gotmpl` for LSP. But I want to make one specific for HTML, something that:
- Syntax highlight both the HTML file and the `{{}}` content
- Formats both HTML and Go template language inside `{{}}`

## How do I achieve that?

This is what I tried without success:

```toml
[[language]]
name = 'gohtml'
scope = 'text.html.basic'
injection-regex = 'html'
auto-format = true
language-servers = ['vscode-html-language-server', 'gopls']
file-types = ['gohtml']
```

**Comment by alexeypegov** [comment, marked as answer]
You can try something like this, it should give you highlighting and lsp support for both `gotmpl` and `html`:

in your languages.toml:
```toml
[[language]]
name = "gotmpl"
file-types = ["gohtml"]
language-servers = ["gopls", "vscode-html-language-server"]
```

And then in ~/.config/helix/runtime/queries/gotmpl/injections.scm:

```scm
((text) @injection.content
 (#set! injection.language "html")
 (#set! injection.combined))
```
