### DISCUSSION TITLE
Pipe commands and output

### DISCUSSION THREAD

**Discussion by xtrasmal** [helix-editor/helix#10724] [Ideas]
**Pipe commands and their output**

```toml
# Pipe the result of :pipe-sh to :vsplit 
[keys.normal]
C-n = [":pipe-sh ~/vault/personal/new_note.sh", ":vsplit"]
```

Let's take a script called `new_note.sh`, which returns a filename.
```bash
#!/bin/bash

# Folder with notes
folder="~/vault/personal"

# Filename for a new note
filename="$folder/$(date +%Y%m%d%H%M%S).md"
touch "$filename"

# Unix timestamp ID
timestamp=$(date +%s)

# Write the to the file
cat <<EOF > "$filename"
---
date: $(date +"%Y-%m-%d %H:%M:%S")
tags:
   -
urls:
   -
id: $timestamp
---

#

EOF

# Return the file name
echo -n  "$filename"

```

**Or maybe**

```toml
[commands.new-note]
pipe_this = "bash -c 'FILE=\$(~/vault/personal/new_note.sh; echo $FILE'"
into_this = "vsplit"

[keys.normal]
C-n = [":command new-note"]
```
