### DISCUSSION TITLE
Helix's built-in functionality replaced 35 of my Neovim plugins

### DISCUSSION THREAD

**Discussion by markstos** [helix-editor/helix#10729] [General]
I compared the 42 Neovim plugins I use to my needs with Helix:

- 35 plugins are already covered by native features, themes or language servers.
- 3 I wasn't actually using
- 1 rarely used
 
That leaves 3 plugins that I used on a regular basis that are waiting on the plugin system: [z.vim](https://github.com/lingceng/z.vim), [zen mode](https://github.com/helix-editor/helix/discussions/6468) and better git integration (like [Fugitive](https://github.com/tpope/vim-fugitive).

Maybe I could replace fugitive with some different workflows.

I found several of my vim plugins are already deprecated, obsolete or unmaintained.

**Comment by TornaxO7** [comment]
> Maybe I could replace fugitive with some different workflows.

I'm using [zellij](https://zellij.dev/) to easily create a new terminal and execute my git commands there. Some people are using [gitui](https://github.com/extrawurst/gitui) or [lazygit](https://github.com/jesseduffield/lazygit) there.

**Comment by kirawi** [comment]
See also https://github.com/helix-editor/helix/pull/9838

**Comment by Wilovy09** [comment]
Hi, I don't know if you still need the help.

But I hope this can help you, I use Lazygit to have an IDE-like experience and I have it configured with a shortcut.

(you need to install lazygit)
```toml
[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
```

I also use [xplr](https://xplr.dev/) or [lf](https://github.com/gokcehan/lf) (these are the ones I have tried that work) for all the folder creation, multiple file creation, deleting, or editing file names.
```toml
[keys.normal]
C-f = [":new", ":insert-output pwd | xplr", ":buffer-close!", ":redraw"]
```
