### DISCUSSION TITLE
I am unable to setup things for golang, new to helix

### DISCUSSION THREAD

**Discussion by icoderarely** [helix-editor/helix#10789] [Q&A]
I seem to like helix editor but as a newbie have some issues that needs to be fixed and I tried but couldn't
I tried several reddits, helix guide itself, tried to copy helix snippets from languages.toml file none works as I expect them to.

1. auto-pairs dont seem to work
2. how do I enable code actions for golang?
3. how to keep undo/redo history saved like in neovim
4. anything you would recommend to have, please let me know

pasted this from `languages.toml` of helix itself, and the commented one was the one i was trying
```toml
# [[language]]
# name = "go"
# lsp = "gopls"
# linter = "golangci-lint-langserver"
# command = "dlv"
# # debugger = "dlv"
# args = ["dap"]
# auto-format = false
# indent = { tab-width = 4, unit = "    " }

# [languages.go]
# lsp = "gopls"
# linter = "golangci-lint-langserver"
# debugger = "dlv"

[language-server.gopls]
command = "gopls"

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "gopls", "golangci-lint-lsp" ]
# TODO: gopls needs utf-8 offsets?
indent = { tab-width = 4, unit = "\t" }

[language.debugger]
name = "go"
transport = "tcp"
command = "dlv"
args = ["dap"]
port-arg = "-l 127.0.0.1:{}"

[language.auto-pairs]
'<' = '>'
"'" = "'"
"{" = "}"
"(" = ")"
'"' = '"'

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { mode = "exec", program = "{0}" }

[[language.debugger.templates]]
name = "test"
request = "launch"
completion = [ { name = "tests", completion = "directory", default = "." } ]
args = { mode = "test", program = "{0}" }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { mode = "local", processId = "{0}" }

[[language.debugger.templates]]
name = "core"
request = "launch"
completion = [ { name = "binary", completion = "filename" }, { name = "core", completion = "filename" } ]
args = { mode = "core", program = "{0}", coreFilePath = "{1}" }

[[grammar]]
name = "go"
source = { git = "https://github.com/tree-sitter/tree-sitter-go", rev = "64457ea6b73ef5422ed1687178d4545c3e91334a" }
```

main `config.toml` file
```toml
theme = "nord-night"

[editor]
line-number = "relative"
scroll-lines = 1
auto-pairs = false
mouse = true
# auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-A-down = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-up = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]

[editor.lsp]
display-messages = true
```

Also one more this when i do `hx --health` i get some kind of warning like, runtime directory does not exists. Hope that's okay thing or not?

my `hx --health | grep "go"` results
![image](https://github.com/helix-editor/helix/assets/166960965/5bafc0a1-7d2d-4b5f-bb4a-075201d43e70)
