### DISCUSSION TITLE
Strange error from typescript lsp: Unexpected token (parse-error)

### DISCUSSION THREAD

**Discussion by AlexNomadrg** [helix-editor/helix#10887] [Troubleshooting]
What it looks like:
![image](https://github.com/helix-editor/helix/assets/58301160/83561c02-d3a6-43a7-96d5-9084f6a6e4a2)

I use SvelteKit and typescript. I have `svelte-language-server` and `typescript-language-server` installed by pacman (arch linux, extra repository)

![image](https://github.com/helix-editor/helix/assets/58301160/3ba8228d-4f4d-4aac-968b-2fcfed55f47c)
![image](https://github.com/helix-editor/helix/assets/58301160/6ea073c0-4730-48f8-ac4c-e5a4e654724e)

<details>
<summary>My configs and such</summary>
Here's my code:

```ts
export async function load() {
	const res = await fetch("http://127.0.0.1:3228/latest");
	const item = await res.json();

	return { item };
}
```
Here's my global languages.toml:

```toml
[language-server]
pyright = { command = "pyright-langserver", args = ["--stdio"], config = {} }

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = [ "pyright" ]
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}

[language-server.emmet-ls]
args = ["--stdio"]
command="emmet-ls"

[language-server.vscode-eslint-language-server]
args = ["--stdio"]
command="vscode-eslint-language-server"

[language-server.vscode-eslint-language-server.config]
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-ls"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
```
...and local:

```toml
[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
language-servers = ["svelteserver", "typescript-language-server", "vscode-eslint-language-server"]


[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "    " }
```
</details>
