### DISCUSSION TITLE
Key aliases

### DISCUSSION THREAD

**Discussion by aslowwriter** [helix-editor/helix#10900] [Ideas]
So I have a keyboard with which I have "space" on one thumb and "backspace" on the other thumb in the same location. I would like to have identical behavior for backspace and space. (in normal mode). I could copy paste the config for space and replace it with backspace, but that is more work, and leaves a lot of possibility for inconsistencies. What I would love is the ability to alias keys such, for example like so:

```toml
[keys.normal."space"]
t = "signature_help"

[keys.normal."space".f]
"f" = "file_picker"
"r" = ":reload-all"
"w" = ":wa"
"b" = ":bc"
"B" = ":bca"

[keys.normal."space".l]
r = ":lsp-restart"

[keys.normal."backspace"] 
alias = "keys.normal.space"

```

The syntax isn't really that important to me it's just a suggestion but hopefully it makes it clear what my idea is. 

This does introduce the potential for infinite alias loops. Ideally this would be checked for at parse time, though not sure how well something like that would work with ownership or other constraints so at least initially I'd be happy with a simple solution such as not allowing keys in aliased spaces to be aliases themselves (again, just a suggestion). How do others think about this?
