### DISCUSSION TITLE
dim effect not working on WezTerm despite terminal support.

### DISCUSSION THREAD

**Discussion by masriomarm** [helix-editor/helix#11009] [Troubleshooting]
I'm using a modified `tokyonight` theme to dim matched bracket, main cursor is reversed while matched cursor bracket is dim. full theme file is below `~/.config/helix/themes/tokyonight-mod.toml`
``` toml
inherits  = "tokyonight"

string = { fg= "light-green", modifiers = ["italic"] }

# cursor configurations, all dim but main cursor
"ui.cursor" = { modifiers = ["dim", "reversed"] }
"ui.cursor.match" = { modifiers = ["dim", "reversed"] }
"ui.cursor.primary.normal" = { modifiers = ["reversed"] }
"ui.virtual.jump-label" = { modifiers = ["dim", "reversed"] }

# "ui.cursor" = { bg = "background_highlight" }
# "ui.cursor.match" = { bg = "background_highlight" }
# "ui.cursor.primary.normal" = { modifiers = ["reversed"] }

# "ui.statusline" = { fg = "foreground_highlight", bg = "background_highlight" }
# "ui.statusline.inactive" = { fg = "foreground", bg = "libadwaita_dark_alt" , modifiers = ["dim"] }

"ui.statusline.normal" = { fg = "dark_6", bg = "blue_3" }
"ui.statusline.insert" = { fg = "dark_6", bg = "green_3" }
"ui.statusline.select" = { fg = "dark_6", bg = "yellow_3" }

[palette]

libadwaita_dark_alt = "#303030" 
white = "#F6F5F4" # redifne clolor
# teal = "#93DDC2" # redifne clolor

blue_3 = "#3584E4"
green_3 = "#33D17A"
yellow_3 = "#F6D32D"
light_4 = "#DEDDDA"
dark_6 = "#000000"

```
This works well in `alacritty` and `windows-terminal` , but matched bracket is still bright in `gnome-terminal` `WezTerm` `Foot`.
Not sure what to debug.
attached is a screenshot showing `alacritty`  right side  vs `WezTerm` left side. You may notice the dimmed cursor at the most right, while its counterpart on `WezTerm` is bright on  right and out of focus on left.
![Screenshot from 2024-06-16 14-54-57](https://github.com/helix-editor/helix/assets/77388732/0f844a3d-b92b-493f-b8aa-1e8c0c775803)
I'm mainly interested in `WezTerm`, and it does support dim effect, but it referse to it as `Half`. Not sure if that could be a reason for the issue.
