### DISCUSSION TITLE
(config help) Swap the "<space>f" and <space>F" bindings

### DISCUSSION THREAD

**Discussion by leyloe** [helix-editor/helix#11023] [General] [answered]
this isnt working, any help?

[keys.space]                                                                                                                            
f = "file_picker_in_current_directory"                                                                                                  
F = "file_picker"

**Comment by krish-r** [comment]
The table key should be `[keys.normal.space]`. 

Docs: [Minor modes](https://docs.helix-editor.com/remapping.html#minor-modes)

```toml
[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
```
