### DISCUSSION TITLE
Why doesn't my keybinding code work

### DISCUSSION THREAD

**Discussion by godalming123** [helix-editor/helix#11059] [Q&A]
I have the following TOML code in my helix config:
```toml
[keys.normal]
x = ["select_mode", "move_line_down", "extend_to_line_bounds", "normal_mode"]
X = ["select_mode", "move_line_up",   "extend_to_line_bounds", "normal_mode"]
A-f = "flip_selections"
```
This is designed to be an easy to use replacement for the visual line mode that I have used in neovim, but without even having to exit normal mode. If I repeatedly press `x` when I am in normal mode with no selected text, the behaviour should be the same as the current helix keybindings (extend the selection to the line below). However, for some reason, when I press `x` several times, I cannot extend my selection to be more then one line. Does anyone know why this config is not working? Any help is appreciated.

**Comment by the-mikedavis** [comment]
`move_line_down` and `move_line_up` don't extend selections even when in select mode. There are separate commands for select mode: `extend_line_down` and `extend_line_up`. So you can avoid switching modes in this config and use the commands that extend instead:

```toml
[keys.normal]
x = ["extend_line_down", "extend_to_line_bounds"]
X = ["extend_line_up", "extend_to_line_bounds"]
```
