### DISCUSSION TITLE
AdonisJS / Edge support

### DISCUSSION THREAD

**Discussion by Wilovy09** [helix-editor/helix#11094] [Q&A] [answered]
Is there any way to support [AdonisJS](https://adonisjs.com/)/[Edge](https://edgejs.dev/docs/introduction)?

I have been trying with [duyluonglc/vscode-edge](https://github.com/duyluonglc/vscode-edge)

```toml
[[language]]
name = "edge"
file-types = ["edge"]
scope = ""
auto-format = true
language-servers = [ "emmet-lsp", "tailwindcss-ls", "typescript-language-server", "vscode-html-language-server", "css-language-server"]
formatter = { command = 'prettier', args = ["--parser", "html"] }
grammar = "edge"

[[grammar]]
name = "edge"
source = { git = "https://github.com/duyluonglc/vscode-edge", rev = "27c16fe5bc9216ee4853e5bf96d1ba1bc187e4d9" }
```

But at the moment of doing

```sh
hx -g fetch
```

```sh
hx -g build
```

I am currently getting this error:

```error
Building 188 grammars
187 grammars already built
Failure 1/1: edge Failed to compare source and binary timestamps
Error: 1 grammars failed to build
```

But before that I was getting an error about missing `src/parser.c`, i would like to know if anyone knows how I can add support for it.

I'm using NixOS, in case it's relevant to this (I don't think so).

> [!NOTE]
> This post was made with a translator, English is not my native language, so there may be grammatical errors.
