### DISCUSSION TITLE
LSP with injected languages. PHP, Blade, HTML

### DISCUSSION THREAD

**Discussion by EmranMR** [helix-editor/helix#11107] [Q&A] [answered]
Hi! 
I am a bit stuck here and I was wondering if someone more experienced with helix internals can help me!

#### Background
consider the following:
- To start with make sure you have the `intelephense` and `vscode-html` LSP installed
- now if you open a php file, everything is ok, when you type `<` you get the appropriate `html` autocompletion and so forth provided by `vscode-html`. When you type `<?php` you get the autocompletion provided by `intelephense`. 

#### Issue
- Issue starts when I open a `.blade.php` file. Here I get no autocompletion at all.

#### Things I have tried:
- I wrapped the injection language between `" x"` in `blade/injection.scm`. I do not think that matters anyways as Helix, correctly picks up injections and highlights for `blade` file
- Then I tried adding `intelephense` as a language server for `blade` file in `languages.toml`. that did not work as well...

I just do not understand how it works for `php` and not for `blade.php` Because in `php` same thing is happening looking at the `injections.scm`.
Many Thanks in Advance!

**Comment by EmranMR** [comment]
### Update:
adding `vscode-html` LSP to `blade` in `languages.toml` did the trick for the `html` but not sure how to get the intelephense working now, here is the config I used.

```toml                                                         
[[language]]                                           
name = "blade"                                         
language-servers = ["intelephense", "vscode-html-language-server"]
```

**Reply by kirawi** [reply]
From what I found, Blade is a templating language. `intelephense` would have to support it itself and AFAICT it advertises no such support

**Reply by EmranMR** [reply]
@kirawi  that is true, but consider the following, in normal `.php` file, when you type `<?php` the intelephensse kicks in, yet outside you get `html-lsp`.  I understand intelephense does not support `blade`, and I am not looking for blade or laravel completion, however I am expecting `php` support in injected `php-only` regions? 

because you could say that  for the`html-lsp` as well, (I do not think it supports `blade` per se) yet that one works in the `html` injected regions inside `.blade.php`  🤷🏻‍♂️  

I am also confused about how the built-in `php` gets the `html-lsp`! is that coming from the `intelephense`? 
when I looked at the `language.toml` provided by helix for built-in languages, I do not see any association of `vscode-html-language-server` for the `language-server` option!

```toml
# helix/languages.toml                                                                                                                      
[[language]]                                                                                                        
name = "php"                                                                                                        
scope = "source.php"                                                                                                
injection-regex = "php"                                                                                             
file-types = ["php", "inc", "php4", "php5", "phtml", "ctp"]                                                         
shebangs = ["php"]                                                                                                  
roots = ["composer.json", "index.php"]                                                                              
comment-token = "//"                                                                                                
language-servers = [ "intelephense" ]                                                                               
indent = { tab-width = 4, unit = "    " }                                                                           
```
