### DISCUSSION TITLE
Really confused with indent/tabs/whitespaces in helix

### DISCUSSION THREAD

**Discussion by EmranMR** [helix-editor/helix#11139] [Q&A]
Hi I dont seem to be able to properly set the spaces for when I press tab, indent or when it is automatically inserted after pressing `return` key... I really dont know what I am doing wrong, or what is overriding the behaviour

#### Things I have tried so far
- Changing the main `languages.toml`
- Changing the `languages.toml` at `~/config/helix/`

- I tried for `php` as well as `cpp` 
- Looking at the source code for `helix` the default for `cpp` is 2 spaces, I get `4 spaces` when I press tab
- for `php` it says `4 spaces` I get `12 spaces` when i press tab!
```toml
# defaults based on source code

[[language]]
name = "cpp"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "php"
indent = { tab-width = 4, unit = "    " }
```

Here you can see what happens when I press enter by enabling white space render. 
<img width="712" alt="image" src="https://github.com/user-attachments/assets/8de96d39-a21f-42fa-9e27-bc3150b8944d">

<img width="156" alt="image" src="https://github.com/user-attachments/assets/85341271-0d12-47cd-98af-9f6af13f668c">
