### DISCUSSION TITLE
unusual behaviour regarding indent configuration reflection, after updating languages.toml

### DISCUSSION THREAD

**Discussion by EmranMR** [helix-editor/helix#11143] [General]
### Summary

Hi

There is a bug whereby the changes in the indent setting is not reflected unless the file is forcefully formatted.

Please see #11139 for photos

### Reproduction Steps

 

I tried this:

1. `hx`
2. either use an old file or make a new one. 
3. write some code make sure there are tabs etc
4. change the indent configuration in `~/.config/helix/languages.toml`
 
here is an example for `php`
```toml
# the default is 4 we just change to 1 to see if it reflects
[[language]]                                                                                                                    
name = "php"                                                                                                                   
indent = { tab-width = 1, unit = " " }

[[language]]                                                                                                                    
name = "php-only"                                                                                                                   
indent = { tab-width = 1, unit = " " }
```
5. Now save the config
6. go to the editor that has the file open
   - You can either do `:config-reload` command
   - or even `quit` via `:q` and open the editor again to ensure the config has been refreshed
7. In the same file, try to press `return` or `tab` or whatever.
8.  You will see that the editor still adds `4` spaces!
9. The only way to **reflect** the **new config** is by doing the `:format` command to forcefully format the file, and from now on the indentation works as expected. 

I expected this to happen:

- Indentation to be reflected on files with codes in it after `:config-reload` or restarting `helix`

Instead, this happened:
- I have to manually force format the file, before I see the changes take in effect

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

MacOS

### Terminal Emulator

xterm-256color

### Installation Method

source

### Helix Version

24.03-237-gfc97ecc3
