### DISCUSSION TITLE
A mapping to open Markdown-formatted URL (like Vim's `gx`)

### DISCUSSION THREAD

**Discussion by aiman** [helix-editor/helix#11155] [Show and tell] [answered]
I wanted to share a shortcut to emulate Vim's `gx` mapping.

In Helix, the quickest way I found to open the link of a Markdown-formatted URL is to move the cursor inside the parentheses (the URL part) and then press these sequences:

- `mim`
- `gf`

But in Vim, it's a single key sequence `gx`, provided as [part of Vim's Netrw system](https://vimdoc.sourceforge.net/htmldoc/pi_netrw.html#netrw-gx). Due to its speed, convenience, and muscle memory, I wanted to emulate this in Helix. But it is not possible to map keys to key sequences.

However, I found another way to emulate `gx` in Helix:

```toml
[keys.normal.g]
x = ["match_brackets", "match_brackets", "move_char_right", "select_mode", "match_brackets", "extend_char_left", "goto_file"]
```

It is worth pointing out this isn't as powerful as Vim's `gx`, because the latter is a generic URL-opener, whereas the mapping above only works inside Markdown parentheses.

Another thing I tried is to use my terminal's link opening facility, but this doesn't work when the URLs is wrapped due to the gutter breaking up the URL with a gap.
