### DISCUSSION TITLE
How to map space a a to "scroll_up"

### DISCUSSION THREAD

**Discussion by 1925381584** [helix-editor/helix#11189] [Q&A] [answered]
I find space mode only supports one key after space, What can I do to achieve the effect I want?

**Comment by the-mikedavis** [comment, marked as answer]
```toml
[keys.normal.space]
a = { a = "scroll_up" }
```

should do what you're looking for, or you can use the shorthand:

```toml
[keys.normal.space]
a.a = "scroll_up"
```
