### DISCUSSION TITLE
How to link two commands in a configuration file

### DISCUSSION THREAD

**Discussion by 1925381584** [helix-editor/helix#11276] [Q&A] [answered]
hi, How to link two commands in a configuration file.like this  C-e = "scroll_down" + "scroll_down",
when i click C-e , will trigger twice scroll_down

**Comment by the-mikedavis** [comment, marked as answer]
See https://docs.helix-editor.com/master/remapping.html#key-remapping, you can use arrays of commands:

```toml
[keys.normal]
C-e = ["scroll_down", "scroll_down"]
```
