### DISCUSSION TITLE
How to interact with non-English language input with Helix?

### DISCUSSION THREAD

**Discussion by Kirirou** [helix-editor/helix#11336] [Q&A] [answered]
When using Helix I want to type in a different language other that English in `Input` mode. To do that I switch the input language layout in `fcitx5` (for example to Ukrainian) and type normally, but as soon as exit the insert mode with `esc` keybind and I try to perform any action that requires English letter to be inputted for (example `i` keybind to go back into `Insert` mode or `h, j, k, l` movement) in `Normal` mode input does not get through as Helix does not recognize the non-English input. (When instead of `i` the terminal gets Cyrillic letter `ш`, instead of `h, j, k, l` it gets Cyrillic letters `р, о, л, д` etc. )

How do I configure and fix this issue and have the other language input layout act only when in `Insert` mode, so I don't have to switch each time back to English to perform any actions in `Normal` mode?

I'm using `Kitty` Terminal.

Help would be very appreciated. :pray:

**Comment by Jackson-Nickk** [comment]
I don't know why there's no other discussion about this and no one commented on this issues. This is a very important subject for a multi purpose text editor.

**Comment by xbwwj** [comment, marked as answer]
@rotteegher @Jackson-Nickk 

Doesn't fcitx5 have a default keybinding `Ctrl+Shift` to switch between input methods?
Or if you want helix to automatically switch to English when in normal mode?

For the second case, you can try rebinding the keys for mode switching to also changing the fcitx5 state using `fcitx5-remote` cli tool.

```toml
[keys.normal]
i = [
  # switch to insert mode
  "insert_mode",
  # activate input method (throught shell command)
  # this line is not necessary in case you still want to input English in insert mode
  ":sh fcitx5-remote -o",
  # logging (testing only, should be removed)
  ":sh echo 'to insert mode' >> log.txt"
]
# `I`, `a`, `A`, `o` and `O` are similar.
# You can find the default keymaps at https://docs.helix-editor.com/keymap.html#changes

[keys.insert]
esc = [
  # switch back to normal mode
  "normal_mode",
  # inactivate input method
  ":sh fcitx5-remote -o",
  # logging (should be removed)
  ":sh echo 'to normal mode' >> log.txt"
]
```

I'm not sure whether the `fcitx5-remote` command call is correct here, as I no longer use it. 
But you can definitely get the idea. And you can find more details about this command using `fcitx5-remote --help`.
