### DISCUSSION TITLE
Is there a better way to switch LSPs between Deno (`deno lsp`) and Node.js (`typescript-language-server`)?

### DISCUSSION THREAD

**Discussion by ras0q** [helix-editor/helix#11418] [Q&A] [answered]
This discussion is similar to [this comment](https://github.com/helix-editor/helix/discussions/2536#discussioncomment-4628850).

By default languege settings, `typescript-language-server` LSP is used when you open the `.ts` file.
However, if `.ts` file is written for Deno, LSP will show errors for Deno-specific syntax.

![image](https://github.com/user-attachments/assets/ac2f163b-12f7-4ac7-8cdb-b653b02259df)

Thanks to [Wiki page](https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#deno), I already understand that writing these settings in `./.helix/languages.toml` under the project root can activate Deno LSP.

```toml
[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc"]
file-types = ["ts"]
language-servers = ["deno-lsp"]
auto-format = true

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "1" }

[language-server.deno-lsp.config.deno]
enable = true
```

It's hard to write this in the project setup every time...
Is it possible to write only the `[language-server.deno-lsp.config.deno]` setting in my project (and the rest in the global `~/.config/helix/languages.toml) to enable the Deno LSP?

I tried to create a new language setting with name `typescript_deno`, but syntax highlighting does not work (Is it a bug?)

![image](https://github.com/user-attachments/assets/cc349c51-3915-4857-adcf-c88dc6888440)

```bash
$ hx --health typescript_deno
Configured language servers:
  ✓ deno: /path/to/bin/deno
Configured debug adapter: None
Configured formatter: None
Highlight queries: ✘
Textobject queries: ✘
Indent queries: ✘
```

Settings:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "typescript_deno" # changed from typescript
scope = "source.ts" # added
grammar = "typescript" # added
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc"]
file-types = ["ts"]
language-servers = ["deno-lsp"]
auto-format = true

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
environment = { NO_COLOR = "1" }
```

```toml
# project/.helix/languages.toml
[language-server.deno-lsp.config.deno]
enable = true
```

**Comment by kirawi** [comment, marked as answer]
See https://github.com/helix-editor/helix/discussions/8372#discussioncomment-9716443

**Reply by ras0q** [reply]
Thank you! I got both LSPs working properly with the following minimal configuration without local `languages.toml`.

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["typescript-language-server", "deno-lsp"]

[language-server.typescript-language-server]
required-root-patterns = ["package.json"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config = { deno = { enable = true } }
required-root-patterns = ["deno.*"]
```

Is it possible to explicitly activate Deno LSP in open `.ts` files when there is no `deno.json`?

**Reply by ras0q** [reply]
As a work-around, I was able to activate it by overriding `required-root-patterns` in `.helix/languages.toml`.

```toml
# .helix/languages.toml
[language-server.deno-lsp]
required-root-patterns = []
```
