### DISCUSSION TITLE
Prettier not working

### DISCUSSION THREAD

**Discussion by Dronakurl** [helix-editor/helix#11473] [Q&A] [answered]
I am struggling to get prettier to work with anything. I don't know what is wrong.
Can anyone please help?

Here is what I tried: 
- I can verify that prettier works in the command line in the same shell.
- I verified that the command in the formatter option is run when I trigger a format, by replacing it by a `touch`command and checking that a a file was created 
- I started with a fresh (no config) helix instance and triggered ":format"
- I checked "--checkhealth" with resulted in green checks for prettier.
- in the formatter option Not calling prettier directly but with 'bash -c'

helix 24.7 (91e642ce)

```toml
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[[language]]
name = "html"
file-types = ["html", "xml"]
auto-format = true
formatter = { command = "prettier" }
```

**Comment by Dronakurl** [comment, marked as answer]
I've got it to work with this 

```toml
[[language]]
name = "html"
file-types = ["html", "xml"]
auto-format = true
formatter = { command = "bash", args = [
  "-c",
  "prettier --stdin-filepath xx.html ",
] }
```

For `yaml` this worked

```toml
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
auto-format = true
formatter = { command = "bash", args = ["-c", " prettier --parser yaml "] }

[[language]]
name = "docker-compose"
file-types = ["docker-compose"]
auto-format = true
formatter = { command = "bash", args = ["-c", " prettier --parser yaml "] }
```

Adding the file-type `docker-compose` to file-types of yaml did not work. You have to specify it in the docker-compose language.
