### DISCUSSION TITLE
Make clang-tidy work with helix editor

### DISCUSSION THREAD

**Discussion by haxfn** [helix-editor/helix#11495] [Troubleshooting] [answered]
Just like there is clippy for rust, I think [clang-tidy](https://clang.llvm.org/extra/clang-tidy/) is for C and C++. But unfortunately, I am not able to get clang-tidy to work in helix:

for a simple cpluplus file, there should be tons of linter warnings in this particular code snippet:
```cpp
// main.cpp
#include <iostream>
#include <memory>
#include <string>
#include <vector>

int main() {
  int a;

  std::string hello{"hello"};
  std::string world{"world"};
  if (hello + world == "")
    std::cout << "empty!\n";

  std::unique_ptr<std::string> ptr{new std::string{"abc"}};
  ptr.reset(new std::string{"xyz"});
  ptr.reset(NULL);

  std::vector<int> vec{1, 2, 3, 4};
  for (std::vector<int>::iterator it = vec.begin(); it != vec.end(); ++it)
    std::cout << *it << '\n';
}
```

One of these linter(clang-tidy) errors for example is:
```txt
/home/vishal/main.cc:15:7: warning: use std::make_unique instead [modernize-make-unique]
   15 |   ptr.reset(new std::string{"xyz"});
      |      ~^~~~~ ~~~~~~~~~~~~~~~~     ~
      |       = std::make_unique<std::string
```

To run clang-tidy, I normally do: `clang-tidy --checks='modernize*, readability*' main.cpp -- -std=c++14`.

Normally, Clion and other IDEs if setup properly can show these linter errors right in the editor, for helix however I am not able to reproduce this. Kindly help.

My config to try and get this fixed was as follows, what am I missing?:

```toml
[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.clangd.config.check]
command = "clang-tidy"
```

**Comment by kirawi** [comment]
I'm not sure if `clangd` has a `check.command` option for its config. Try setting the `clangd` command to have an arg of `--clang-tidy` instead

**Comment by haxfn** [comment, marked as answer]
Thanks @kirawi, this makes sense. 

So finally, the following got the clang-tidy diagnostics working for me on helix:

1. changing helix config languages.toml file to include:

```toml
[language-server]
clangd = { command = "clangd", args = [ "--clang-tidy" ] }
```

2. Changing clangd config file to include:

```yaml
Diagnostics:
  ClangTidy:
    Add: [modernize*, readability*]

CompileFlags:
  Add: [-std=c++14, -Wall, -Wextra, -Wshadow]
```

References:
1. [clangd configuration](https://clangd.llvm.org/config.html#clangtidy)
2. [list of all clang-tidy checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html)
