### DISCUSSION TITLE
Shorter alternative to  `mi)c`?

### DISCUSSION THREAD

**Discussion by txtyash** [helix-editor/helix#1153] [Q&A] [answered]
Suppose I want to change something between `(` or `'` then I would `mi(c` or `mi'c`. Which is one keystroke more than vim's `ci(` or `ci'`. 

Is there a shorter way to do it in helix?

If not then isn't helix supposed to have lesser keystrokes for similar actions in vim?

**Comment by archseer** [comment, marked as answer]
There's no shorter way, it's a keystroke longer. Per [`vision.md`](https://github.com/helix-editor/helix/blob/master/docs/vision.md): 

> We aren't playing code golf. It's more important for the keymap to be consistent and easy to memorize than it is to save a key stroke or two when editing.

**Reply by txtyash** [reply]
I'm not trying to be rude but `vgld` to delete till the end of the line and `miwc` to change in word are not as intuitive as their respective vim equivalents like `D` and `ciw`.

Is there a raw list of all possible key-bindings in helix? Literally every built-in key-binding in helix in at a single place?

**Reply by cole-h** [reply]
This should hold most, if not all, of them: https://docs.helix-editor.com/keymap.html

**Reply by txtyash** [reply]
tysm

**Reply by pickfire** [reply]
I think a better alternative with one keystroke lesser is `mipc` and `miqc` which replaces `(` with `p` and `'` with `q` like vim, easy to type also.

If you have any idea how to make it better while being consistent, feel free to suggest.

**Reply by kajuburfi** [reply]
If you want to, @zim0369, You can set the following in the `config.toml`
```toml
[keys.normal]

# For `vgld`
"D" = [ "select_mode", "goto_line_end", "delete_selection", "normal_mode" ] 

# For `ciw` 
# This would be simpler and fit within match mode..
m  = { "w" = ["select_textobject_inner", "change_selection"]}
```
