### DISCUSSION TITLE
"Support keymap command option for match mode"

### DISCUSSION THREAD

**Discussion by tendertree** [helix-editor/helix#11534] [Troubleshooting] [answered]
Currently, I'm using Colemak, where the keys 'mnei' are used in place of 'hijk' in the standard QWERTY layout. Other key mappings work out of the box, except for 'm', which enters the match mode

**Comment by the-mikedavis** [comment, marked as answer]
`m` is a minor mode meaning that it has many bindings underneath it. In order to move it you need to remap the commands under it, for example swapping M and H:

```toml
[keys.normal]
m = "move_char_left"

[keys.normal.h]
m = "match_brackets"
s = "surround_add"
r = "surround_replace"
d = "surround_delete"
a = "select_textobject_around"
i = "select_textobject_inner"
```

Though I thought Colemak left H and M in the same positions as QWERTY, so the HJKI equivalents would be HNEI
