### DISCUSSION TITLE
JSX/TSX Highlight/Comment being Broken

### DISCUSSION THREAD

**Discussion by LePichu** [helix-editor/helix#11549] [Troubleshooting] [answered]
### Summary

Hi! I recently switched my devices and reinstalled Helix, going up from version 22 -> 24, for some reason both the highlighting for JSX/TSX files are broken alongside the ability to comment code inside JSX scopes. 

Here are a few screenshots:
![image](https://github.com/user-attachments/assets/91ce855c-efcd-4a8c-bd0b-ebf3aede7116)
![Screenshot_20240821-094654](https://github.com/user-attachments/assets/cb0b0238-0b5f-41bc-9e95-4df7303f5b79)

### Reproduction Steps

1. Open a JSX or TSX File
2. See the highlighting being broken
3. Try to comment inside a JSX block using Ctrl-C, it also fails 

### Helix log
- [For macOS under macOS Terminal](https://github.com/user-attachments/files/16685991/helix.log)
- [For Fedora Proot under Termux](https://github.com/user-attachments/files/16685984/helix.log)

### Platform

Fedora Linux PRoot / macOS 

### Terminal Emulator

macOS Terminal.app / Termux 

### Installation Method

brew / dnf (Fedora)

### Helix Version

24.7

**Comment by Diogenesoftoronto** [comment]
Please output the result of hx --health

**Reply by davikayxx** [reply]
Hii

**Comment by LePichu** [comment]
> Please output the result of hx --health

![Screenshot_20240821-205319](https://github.com/user-attachments/assets/8114afcf-4fe7-4dae-a4da-354d7f68d32d)

This is my `languages.toml`:
```toml
[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts", "tsx", "js", "jsx"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["deno-lsp", "tailwindcss-ls"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { userLanguages = { astro = "html", "*.astro" = "html" } }

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/root/.pnpm-global/global/5/node_modules/typescript/lib/" }}

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls", "tailwindcss-ls"]
```

**Comment by gabydd** [comment, marked as answer]
there are seperate queries and a different grammar for tsx: https://github.com/helix-editor/helix/blob/38e6fcd5c51478635ffa405815c7b9bbeadc35a9/languages.toml#L790-L803 in your languages.toml you are causing tsx and jsx files to use the typescript grammar and queries

instead you can just have:
```toml
[[language]]
name = "typescript"
language-servers = ["deno-lsp", "tailwindcss-ls"]

[[language]]
name = "tsx"
language-servers = ["deno-lsp", "tailwindcss-ls"]

[[language]]
name = "javascript"
language-servers = ["deno-lsp", "tailwindcss-ls"]

[[language]]
name = "jsx"
language-servers = ["deno-lsp", "tailwindcss-ls"]
```
