### DISCUSSION TITLE
Incorrect indentation after opening new lines with braces in Golang

### DISCUSSION THREAD

**Discussion by HairlessVillager** [helix-editor/helix#11565] [Q&A] [answered]
### Description

When opening a new line directly after a `{` or `}`, the indentation is incorrect.

**Case 1**

```go
func main() {
	if true {
		fmt.Println("yes")
	} else {|} // press enter here
}
```
```
func main() {
	if true {
		fmt.Println("yes")
	} else {
	|
}
}
```
Note: Both the cursor (`|`) and the closing brace (`}`) are one tab indentation short.

**Case 2**

```go
func main() {
	if true {
		fmt.Println("yes")
	}| //press enter here
}
```

```go
func main() {
	if true {
		fmt.Println("yes")
	}
|
}
```
Note: The cursor (`|`) is one tab indentation short.

### Related issues or PRs

I've conducted a search on Google and found only one relevant pull request: #5713.

### Configure

My `helix --version`:

```text
helix 24.3 (2cadec0b)
```

My `helix --health go`:

```text
Configured language servers:
  ✓ gopls: C:\Users\hlsvillager\go\bin\gopls.exe
  ✘ golangci-lint-langserver: 'golangci-lint-langserver' not found in $PATH
Configured debug adapter: dlv
Binary for debug adapter: 'dlv' not found in $PATH
Configured formatter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

My `config.toml`:

```toml
theme = "mymolokai"

[editor]
line-number = "relative"
mouse = false
insert-final-newline = true
jump-label-alphabet = "asdfhjklqweuiopcm"

[editor.lsp]
display-messages = true

[editor.gutters]
layout = ["line-numbers", "spacer", "diff" ]

[editor.statusline]
left = [ "mode", "separator" ]
center = [ "version-control", "file-name", "file-modification-indicator" ]
right = ["diagnostics", "position", "total-line-numbers"]
separator = "|"
mode.normal = "NOR"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"
    
[editor.file-picker]
hidden = false

[keys.normal]
f = "goto_word"
H = "jump_backward"
L = "jump_forward"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
"X" = "select_line_above"
"x" = "select_line_below"
"minus" = "remove_primary_selection"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
```

My languages.toml does not contain any specific configuration related to Golang.

My `runtime/queries/go/indents.scm` stays default:

```scm
[
  (import_declaration)
  (const_declaration)
  (type_declaration)
  (type_spec)
  (func_literal)
  (literal_value)
  (literal_element)
  (keyed_element)
  (expression_case)
  (default_case)
  (type_case)
  (communication_case)
  (argument_list)
  (field_declaration_list)
  (block)
  (var_declaration)
] @indent

[
  "]"
  ")"
] @outdent

; Switches and selects aren't indented, only their case bodies are.
; Outdent all closing braces except those closing switches or selects.
(
    (_ "}" @outdent) @outer
    (#not-kind-eq? @outer "select_statement")
    (#not-kind-eq? @outer "type_switch_statement")
    (#not-kind-eq? @outer "expression_switch_statement")
)

; Starting a line after a new case should indent.
[
  (communication_case)
  (expression_case)
  (default_case)
  (type_case)
] @extend
```
