### DISCUSSION TITLE
Helix formatting not working for rust.

### DISCUSSION THREAD

**Discussion by bp7968h** [helix-editor/helix#11607] [Troubleshooting]
Hi, I have setup helix and rust languages in the config which are listed below:

> config.toml

```toml
theme = "autumn"

[editor]
line-number = "absolute"
mouse = false
text-width = 85

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "<->"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.cursor-shape]
normal = "hidden"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = true

[keys.normal.c]
r = ":sh cargo run 2>&1 || true"
c = ":sh cargo check 2>&1 || true"
b = ":sh cargo build 2>&1 || true"
t = ":sh cargo test 2>&1 || true"
```

> languages.toml

```toml
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rs|rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
shebangs = ["rust-script", "cargo"]
auto-format = true
comment-tokens = ["//", "///", "//!"]
block-comment-tokens = [
  { start = "/*", end = "*/" },
  { start = "/**", end = "*/" },
  { start = "/*!", end = "*/" },
]
language-servers = [ "rust-analyzer" ]
formatter = { command = "rustfmt" }
indent = { tab-width = 4, unit = "    " }
persistent-diagnostic-sources = ["rustc", "clippy"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[language-server.rust-analyzer.config.check]
command = "clippy"

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "9c84af007b0f144954adb26b3f336495cbb320a7" }
```

When I same my file with `:w`, `:write` or even when I use `:format` , my files are not being formatted. Am I missing something, thank you for your help.

Kind Regards,
Bhuwan
