### DISCUSSION TITLE
Anyone have any luck getting `Markdownlint` to work with Helix?

### DISCUSSION THREAD

**Discussion by jsco2t** [helix-editor/helix#11639] [Q&A] [answered]
Hello all.

I'm trying to add support for `Markdownlint` as an LSP in my local install of `Helix`. To be clear - `Markdownlint` doesn't explicitly advertise support for the LSP protocol. Which I suspect might be my issue here. Instead it describes itself as:

> markdownlint is a [static analysis](https://en.wikipedia.org/wiki/Static_program_analysis) tool for [Node.js](https://nodejs.org/)

From: https://github.com/DavidAnson/markdownlint

I decided to try to get it to work anyway - but am not having a lot of luck.

Here is what I added into my `languages.toml` file:

```toml
[language-server.markdownlint]
command = "markdownlint"
args = [ "--stdin", "--json" ]
``` 

And for the Markdown language (in the same `languages.toml` file):

```toml
[[language]]
name = "markdown"
language-servers = ["vale", "marksman", "markdownlint"] <------------------
file-types = ["md", "mdx"]
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
text-width = 100
rulers = [100]
auto-format = true
indent = { tab-width = 2, unit = "  " }
block-comment-tokens = { start = "<!--", end = "-->" }
```

When I check the health of Helix - it seems to understand the _"LSP"_ exists (the binary exists):

```bash
❯ hx --health markdown
Configured language servers:
  ✓ vale-ls: /Users/jscott/.cargo/bin/vale-ls
  ✓ marksman: /opt/homebrew/bin/marksman
  ✓ markdownlint: /opt/homebrew/bin/markdownlint <-----------------------
Configured debug adapter: None
Configured formatter: prettier
Binary for formatter: /Users/jscott/.nvm/versions/node/v18.12.1/bin/prettier
Highlight queries: ✓
Textobject queries: ✘
Indent queries: ✘
```

However - when I open a Markdown doc - I am seeing these errors reported from Helix:

```
❯ cat helix.log
2024-09-05T17:06:26.921 helix_lsp [ERROR] failed to initialize language server: request 0 timed out
2024-09-05T17:06:27.394 helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream
2024-09-05T17:06:27.408 helix_lsp::transport [ERROR] err: <- Other(failed to send a message to server

Caused by:
    channel closed)
2024-09-05T17:06:27.408 helix_lsp::transport [ERROR] vale err: <- StreamClosed
```

To be fair - I don't know why the last log line complains about `vale`. The errors are completely gone if I remove support for `markdownlint` as an LSP for `markdown`. 

Anyway - what I am trying might not work with `Markdownlint`. I'm not sure. I figured I would post to see if anyone else has tried it yet.

**Comment by kirawi** [comment, marked as answer]
It does not support the LSP protocol. You can use something like https://github.com/mattn/efm-langserver to use it instead

**Reply by jsco2t** [reply]
Thanks!

That was incredibly helpful.

For anyone else who stumbles over this - here is what I did on my machine to get this to work.

1. Create a file in `~/.config/efm-langserver/config.yaml`

2. Put this content into it:

```yaml
version: 2
#log-file: "/Users/some-user/.config/efm-langserver/log.log"
#log-level: 2

languages:
  markdown:
    - lint-command: "markdownlint -s"
      lint-stdin: true
      lint-after-open: true
      lint-on-save: true
      lint-formats:
        - "%f:%l %m"
        - "%f:%l:%c %m"
        - "%f: %l: %m"
```

Update your helix `languages.toml` as follows:

1. Add LSP server declaration:

```toml
[language-server.efm]
command = "efm-langserver"
```

2. Update your Markdown Language definition to include `efm` as an LSP:

```toml
[[language]]
name = "markdown"
language-servers = ["vale", "marksman", { name = "efm", only-features = [ "diagnostics" ] }]
file-types = ["md", "mdx"]
.........truncated
```
