### DISCUSSION TITLE
Harper-ls with git-commit files

### DISCUSSION THREAD

**Discussion by masriomarm** [helix-editor/helix#11653] [Troubleshooting] [answered]
I'm trying to run harper-ls for spell checking on git-commit. Doesn't seem to work, despite working for md files. Has anyone made it work?

**Comment by SkypLabs** [comment]
Helix has a built-in language configuration for Git commit and merge messages:

https://github.com/helix-editor/helix/blob/b6ccbddc77bc2e2c2d02cfd5444594e3cc46c938/languages.toml#L1925-L1933

All you need to do is to add Harper to the list of language servers of the `git-commit` language in your own `languages.toml` configuration file:

```toml
[[language]]
name = "git-commit"
language-servers = [ "harper-ls" ]
```
