### DISCUSSION TITLE
Helix not using gopls build.buildTags

### DISCUSSION THREAD

**Discussion by ghost** [helix-editor/helix#11756] [Q&A]
Anyone know how to set that option? My current attempt doesnt seem to work and I cant figure out why 

```toml
[language-server.gopls.config]
build.buildFlags = ["-tags=mage"]
```

**Comment by mikerhodes** [comment]
You don't need the leading `build.`. I am using this configuration successfully:

```toml
[language-server.gopls.config]
buildFlags = ["-tags=integration"]
```

Helix version:

```
> hx --version
helix 25.07.1 (a05c151b)
```
