### DISCUSSION TITLE
how to show key remapping info in "command palette" ?

### DISCUSSION THREAD

**Discussion by noor-tg** [helix-editor/helix#11809] [Q&A]
I have remap like this
```toml
[keys.normal.space]
z = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"] # Maps <space>z to lazygit
t = [":new", ":insert-output lf", ":buffer-close!", ":redraw"] # Maps <space>z to lf
```
when I click `<space>?`. I want to see `Maps <space>z to lazygit` when searching for lazygit.
