### DISCUSSION TITLE
Ruby config with Solargraph and StandardRB (instead of Rubocop)

### DISCUSSION THREAD

**Discussion by fagnerpereira** [helix-editor/helix#11814] [Show and tell]
```toml
[language-server.standardrb]
command = "standardrb"
args = ["--lsp"]

[[language]]
name = "ruby"
auto-format = true
language-servers = [ "solargraph", "standardrb" ]
```
helix 24.7 (079f5442)
[standardrb](https://github.com/standardrb/standard) 1.40.0
[solargraph](https://solargraph.org/) 0.50.0

```shell
❯ hx --health ruby
Configured language servers:
  ✓ solargraph: /Users/fagner/.asdf/shims/solargraph
  ✓ standardrb: /Users/fagner/.asdf/shims/standardrb
Configured debug adapter: None
Configured formatter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

Its important to add both gems in gemfile or simply install globally in terminal to make this work. (sorry for saying something a little obvious)
