### DISCUSSION TITLE
Colemak configs

### DISCUSSION THREAD

**Discussion by k4lizen** [helix-editor/helix#11832] [General]
Imo there isn't really a centralized place in the repo where one can find information about this so I'd like to create one here. The trouble with alternate keyboard layouts and modal editors is as old as time, particularly with what to do with hljk since they were chosen due to their position on qwerty rather than as a mneumonic.

Some discussion on this can be seen here: https://github.com/helix-editor/helix/discussions/10227
The main solutions that exist for colemak are:
1. Don't rebind hljk
2. Rebind them to HNEI
3. Rebind them to UNEI

The argument for not rebinding hljk is stronger when using vim, since it means logging into another computer (possibly remotely) and using vim (or vi, since they are always installed) will be painless. However it's hard to expect that a random computer you log in to will have helix installed, and if you can install it you can also bring your config with you. So imo it makes more sense with helix to rebind hljk. Especially nice is that it can be done without moving too much stuff around (when I was looking at vim solutions it looked much more painful).

The best rebind I found is this one: https://github.com/helix-editor/helix/discussions/10227#discussioncomment-9033046 and I particularly like UNEI since I use colemak-dh and so H is not on the home row so there isn't much point to HNEI. Also UNEI just sort of *feels right* to me as it's similar to WASD and the arrow keys. 

That comment doesn't give the whole story however since visual mode needs to be rebound as well. For the common pitfalls see https://github.com/helix-editor/helix/discussions/7700, https://github.com/helix-editor/helix/discussions/8906 and https://github.com/helix-editor/helix/discussions/11534.

In total these are my current bindings (that are relevant for colemak) (UNEI):
```toml
[keys.normal]
# -------------------------
# from @mattmc3 (https://github.com/helix-editor/helix/issues/5520#issuecomment-1386428351)
# QWERTY to Colemak remaps
# [JY] [LU] [UI] [..]
#  [..] [NJ] [EK] [IL]
#   [KN] [..] [..] [..]
# -------------------------
# N <=> K (K is in the QWERTY N position)
n = "move_char_left"
N = "keep_selections"
k = "search_next"
K = "search_prev"
# E <=> J (J now 'jumps words')
e = "move_line_down"
E = "join_selections"
j = "move_next_word_end"
J = "move_next_long_word_end"
# H <=> I (H is just a sideways I)
i = "move_char_right"
I = "no_op"
h = "insert_mode"
H = "insert_at_line_start"
# U <=> L (L is in the QWERTY U position)
u = "move_line_up"
U = "no_op"
l = "undo"
L = "redo"

[keys.select]
# -------------------------
# from @mattmc3 (https://github.com/helix-editor/helix/issues/5520#issuecomment-1386428351)
# QWERTY to Colemak remaps
# [JY] [LU] [UI] [..]
#  [..] [NJ] [EK] [IL]
#   [KN] [..] [..] [..]
# -------------------------
# N <=> K (K is in the QWERTY N position)
n = "extend_char_left"
N = "keep_selections"
k = "extend_search_next"
K = "extend_search_prev"
# E <=> J (J now 'jumps words')
e = "extend_visual_line_down"
E = "join_selections"
j = "extend_next_word_end"
J = "extend_next_long_word_end"
# H <=> I (H is just a sideways I)
i = "extend_char_right"
I = "no_op"
h = "insert_mode"
H = "insert_at_line_start"
# U <=> L (L is in the QWERTY U position)
u = "extend_visual_line_up"
U = "no_op"
l = "undo"
L = "redo"
```

Here are two other colemak configs: https://github.com/helix-editor/helix/discussions/10227#discussioncomment-9033048, https://github.com/helix-editor/helix/discussions/10227#discussioncomment-9033052.

Please share your (or others) solutions for using colemak(-dh) with helix, and config options related to this!

update:
The goto line end and goto line start bindings are gl and gh which are made with the hljk movement in mind, you can rebind those too (and gk, gj) if you want, here is how it would be done for UNEI:
```toml
# == Colemak (dh) UNEI goto minor modes (normal)
[keys.normal.g]
# gl (line end) <=> gi (implementation)
l = "goto_implementation"
i = "goto_line_end"
# gh (line start) <=> gn (next buffer)
h = "goto_next_buffer"
n = "goto_line_start"
# gj (down) <=> ge (last line)
j = "goto_last_line" 
e = "move_line_down"
# gk (up) => gu (no_op)
k = "no_op"
u = "move_line_up"

# == Colemak (dh) UNEI goto minor modes (select)
[keys.select.g]
# gl (line end) <=> gi (implementation)
l = "goto_implementation"
i = "goto_line_end"
# gh (line start) <=> gn (next buffer)
h = "goto_next_buffer"
n = "goto_line_start"
# gj (down) <=> ge (last line)
j = "goto_last_line" 
e = "extend_line_down"
# gk (up) => gu (no_op)
k = "no_op"
u = "extend_line_up"
```
