### DISCUSSION TITLE
How to disable syntax highlighting without disabling LSP capabilities?

### DISCUSSION THREAD

**Discussion by fidelicura** [helix-editor/helix#11892] [Q&A] [answered]
This question may sound strange, but I prefer not to use syntax highlighting because it allows me to better focus on the code as meaningful text. Is it possible to turn off the syntax highlight without loosing LSP autosuggestions/goto/etc? I tried `:set-language text`, but it disables LSP of course, because I set the language, not the syntax highlight language.

**Comment by pierrelgol** [comment, marked as answer]
I think that if you delete the grammar file than maybe it stops working ? I'm not sure but I remember one time, where I tried to install helix from source to test a branch, and everything worked well except for the syntax highlighting, which was fixed when doing a `hx --grammar fetch && hx --grammar build`, so maybe you could simply delete those files.
Another options could be to create your own theme and disable syntax highlighting by simply putting the same colour everywhere for each kind of tokens.

**Reply by fidelicura** [reply]
Yep, changing theme worked as needed, thanks. It still has to tree-sitter tokens, but I don't think it's that resource-intensive.

Here is my theme-based solution:
<details>
<summary>$XDG_CONFIG_HOME/helix/themes/flat_dark.toml</summary>

```toml
"ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.virtual.ruler" = { bg = "base01" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base05"
"ui.text.focus" = "base05"
"variable" = "base08"
"constant.numeric" = "base09"
"constant" = "base09"
"attribute" = "base09"
"type" = "base0A"
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"string"  = "base0B"
"variable.other.member" = "base0B"
"constant.character.escape" = "base0C"
"function" = "base0D"
"constructor" = "base0D"
"special" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"ui.help" = { fg = "base06", bg = "base01" }

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

[palette]
base00 = "#181818" # Default Background
base01 = "#282828" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#383838" # Selection Background
base03 = "#FFFFFF" # Comments, Invisibles, Line Highlighting
base04 = "#b8b8b8" # Dark Foreground (Used for status bars)
base05 = "#FFFFFF" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)
base08 = "#FFFFFF" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#FFFFFF" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#FFFFFF" # Classes, Markup Bold, Search Text Background
base0B = "#FFFFFF" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#FFFFFF" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#FFFFFF" # Functions, Methods, Attribute IDs, Headings
base0E = "#FFFFFF" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#FFFFFF" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
```

</details>
