### DISCUSSION TITLE
opening xcode/swift projects

### DISCUSSION THREAD

**Discussion by kujohn** [helix-editor/helix#11897] [Troubleshooting]
I've installed the lsp and formatters accordingly for swift language but when I open a project, the references to structure/classes are not found in scope. Has anyone successfully configured lsp without issue?

**Comment by kujohn** [comment]
I found [this tangential guide setup for neovim](https://wojciechkulik.pl/ios/the-complete-guide-to-ios-macos-development-in-neovim) that helped tremendously to work with helix.

**Comment by fluffybeing** [comment]
Hi @kujohn if you were able to achieve it, can you share your config?

**Comment by kujohn** [comment]
Follow the guide for installation and config. 

Here's mine LSP setup for helix:

``` toml
[language-server.swiftlint]
command = "swiftlint"

[[language]]
name = "swift"
auto-format = true
language-servers = ["sourcekit-lsp", "swiftlint"]
formatter = { command = "swiftformat", args = [ "--config", "/Users/johnku/.swiftformat"]}
[language.debugger]
command = "lldb-dap"
name = "lldp-dap"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true

[[grammar]]
name = "swift"
source = { git = "https://github.com/alex-pinkus/tree-sitter-swift", rev = "57c1c6d6ffa1c44b330182d41717e6fe37430704" }
```

And I have this in my project under buildServer.json
```json
{
        "name": "xcode build server",
        "version": "0.2",
        "bspVersion": "2.0",
        "languages": [
                "c",
                "cpp",
                "objective-c",
                "objective-cpp",
                "swift"
        ],
        "argv": [
                "/opt/homebrew/bin/xcode-build-server"
        ],
        "workspace": "<workspace>",
        "build_root": "<buildroot>",
        "scheme": "<scheme>",
        "kind": "xcode"
}
```

Run this for build server:
```
# if you use workspace:
xcode-build-server config -scheme <XXX> -workspace *.xcworkspace
# or if you only have a project file:
xcode-build-server config -scheme <XXX> -project *.xcodeproj
```
