### DISCUSSION TITLE
waiting for input in command line after keymap

### DISCUSSION THREAD

**Discussion by jarjk** [helix-editor/helix#11909] [Q&A] [answered]
I'm experimenting with keymaps for cargo commands, but I'm a bit stuck at `cargo add <pkg>`.
The problem is, I don't want to always type in the whole command: `:sh cargo add <pkg>`
but instead would like to use a keymap like: <kbd>Space</kbd>+<kbd>l</kbd>+<kbd>a</kbd> and then type the rest into the command-line of helix. 

NOTE: I've made up a workaround: select the crate name (text), yank it to system-clipboard and use that text in shell for `cargo add <system_clipboard>`

keymaps:

```toml
[keys.normal."space".l]
c = ":sh cargo check"
t = ":sh cargo test"
r = ":sh cargo run"
# FIXME: how could wait_for_input be done?
# a = [":sh cargo add ", "wait_for_input"]
# workaround:
a = ["yank_to_clipboard", ":sh cargo add (wl-paste)"]
d = ["yank_to_clipboard", ":sh cargo rm (wl-paste)"]
```

**Comment by jarjk** [comment, marked as answer]
fixed for some time now, leaving this here:

```toml
[keys.normal.' '.l]
a = "@:sh cargo add "
```
