### DISCUSSION TITLE
Statusline file-path truncation

### DISCUSSION THREAD

**Discussion by RodogInfinite** [helix-editor/helix#11969] [Ideas]
The file-absolute-path setting for statusline often shows too much information and just using the file-name often doesn't give enough information. Taking inspiration from [Starship's directory configuration](https://starship.rs/config/#directory):

```toml
[directory]
truncation_length = 3
truncation_symbol ='.../'
```
It would be nice to see these options available, maybe something like this:
```toml
[editor.statusline]
left = ["spinner", "mode", { file-path = { truncation_length = 3, truncation_symbol = ".../" } }]
```

The truncation_symbol can even be excluded and have it be helix opinionated and not customizable to make implementation simpler. 

Thoughts?
