### DISCUSSION TITLE
Terminology for actions like `normal_mode`, `extend_line`, `move_char_left`?

### DISCUSSION THREAD

**Discussion by haxfn** [helix-editor/helix#12050] [Q&A] [answered]
In helix(or in vim) things like `:wq` `:quit` are termed 'commands'. And helix has a documented page for all of these.

In helix, what are things like `code_action`, `normal_mode`, called? Is there a documented page for this?

Note that "these" usually come along with key remapping. Example from documentation:
```toml
# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
a = "move_char_left" # Maps the 'a' key to the move_char_left command
w = "move_line_up" # Maps the 'w' key move_line_up
"C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.insert]
"A-x" = "normal_mode"     # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
```
