### DISCUSSION TITLE
Write buffer close all

### DISCUSSION THREAD

**Discussion by dogunbound** [helix-editor/helix#12066] [Ideas]
This shouldn't be too hard to do. I think `wbca` should also be apart of the commands. 

Use case:
Finished completing a section of code, and it is time to move on to the next task. I don't feel comfortable just doing `bca` because I might miss something I wrote on accident. I normally do `wa` then `bca`. I could save a couple keystrokes by doing `wbca`. 

`wbca` isn't being used as a command, and it doesn't seem like it "breaks" any of the standards helix has. What do ya'll think? It is totally not necessary. It is mostly a "it would be cool" or "nice" thing to add.

Could be a good newbie task too!

**Comment by david-crespo** [comment]
The maintainers are unlikely to want to add commands that are just a combination of existing ones. You can give yourself this feature with a keybind:

```toml
[keys.normal]
L = [":wa", ":bca"]

# or if you want it to be two keypresses
[keys.normal.L]
w = [":wa", ":bca"]
```

When #8675 eventually lands you will also be able to make a custom command for it.
