### DISCUSSION TITLE
"Normal" mod key in insert mode `config.toml` !!!

### DISCUSSION THREAD

**Discussion by NNBnh** [helix-editor/helix#1211] [Show and tell]
I turn #1064 into the reality, currently i don't tackle any conflict <kbd>Alt-...</kbd> key and insert-mode key yet. Here is the `config.toml`:

<details>
<summary>=== Open full config ===</summary>

```toml
# Note:
#   #HX5 : Not support on Helix 0.5.0
#   #ALT : Conflict with alt key

[keys.insert]

# Movement
"left" = "move_char_left"
"down" = "move_line_down"
"up" = "move_line_up"
"right" = "move_char_right"
"A-h" = "move_char_left"
"A-j" = "move_line_down"
"A-k" = "move_line_up"
"A-l" = "move_char_right"
"A-w" = "move_next_word_start"
"A-b" = "move_prev_word_start"
"A-e" = "move_next_word_end"
"A-W" = "move_next_long_word_start"
"A-B" = "move_prev_long_word_start"
"A-E" = "move_next_long_word_end"
"A-t" = "find_till_char"
"A-f" = "find_next_char"
"A-T" = "till_prev_char"
"A-F" = "find_prev_char"
#ALT "A-." = "repeat_last_motion"
"home" = "goto_line_start"
"end" = "goto_line_end"
"pageup" = "page_up"
"pagedown" = "page_down"
"C-u" = "half_page_up"
"C-d" = "half_page_down"
"C-i" = "jump_forward"
"C-o" = "jump_backward"
"A-v" = "select_mode"
"A-:" = "command_mode"

# Changes
"A-r" = "replace"
"A-R" = "replace_with_yanked"
"A-~" = "switch_case"
"A-`" = "switch_to_lowercase"
#ALT "A-`" = "switch_to_uppercase"
"A-i" = "insert_mode"
"A-a" = "append_mode"
"A-I" = "prepend_to_line"
"A-A" = "append_to_line"
"A-o" = "open_below"
"A-O" = "open_above"
"A-u" = "undo"
"A-U" = "redo"
#ALT "A-u" = "earlier"
#ALT "A-U" = "later"
"A-y" = "yank"
"A-p" = "paste_after"
"A-P" = "paste_before"
"A-\"" = "select_register"
"A-gt" = "indent"
"A-lt" = "unindent"
"A-=" = "format_selections"
"A-d" = "delete_selection"
#ALT "A-d" = "delete_selection_noyank"
"A-c" = "change_selection"
#ALT "A-c" = "change_selection_noyank"
#HX5 "C-a" = "increment"
#HX5 "C-x" = "decrement"

# Shell
"A-|" = "shell_pipe"
#ALT "A-|" = "shell_pipe_to"
"A-!" = "shell_insert_output"
#ALT "A-!" = "shell_append_output"

# Selection manipulation
"A-s" = "select_regex"
"A-S" = "split_selection"
#ALT "A-s" = "split_selection_on_newline"
#HX5 "A-&" = "align_selections"
#ALT "A-_" = "trim_selections"
"A-semicolon" = "collapse_selection"
#ALT "A-semicolon" = "flip_selections"
"A-," = "keep_primary_selection"
#ALT "A-," = "remove_primary_selection"
"A-C" = "copy_selection_on_next_line"
#ALT "A-C" = "copy_selection_on_prev_line"
"A-(" = "rotate_selections_backward"
"A-)" = "rotate_selections_forward"
#ALT "A-(" = "rotate_selection_contents_backward"
#ALT "A-)" = "rotate_selection_contents_forward"
"A-percent" = "select_all"
"A-x" = "extend_line"
"A-X" = "extend_to_line_bounds"
"A-J" = "join_selections"
"A-K" = "keep_selections"
#ALT "A-K" = "remove_selections"
"A-$" = "shell_keep_pipe"
"C-c" = "toggle_comments"

# Search
"A-/" = "search"
#HX5 "A-?" = "rsearch"
"A-n" = "search_next"
#HX5 "A-N" = "search_prev"
"A-*" = "search_selection"

# View mode
"A-z" = { "z" = "align_view_center", "c" = "align_view_center", "t" = "align_view_top", "b" = "align_view_bottom", "m" = "align_view_middle", "down" = "scroll_down", "j" = "scroll_down", "up" = "scroll_up", "k" = "scroll_up", "f" = "page_down", "b" = "page_up", "d" = "half_page_down", "u" = "half_page_up" }

# Goto mode
"A-g" = { "g" = "goto_file_start", "e" = "goto_last_line", "h" = "goto_line_start", "l" = "goto_line_end", "s" = "goto_first_nonwhitespace", "t" = "goto_window_top", "m" = "goto_window_middle", "b" = "goto_window_bottom", "d" = "goto_definition", "y" = "goto_type_definition", "r" = "goto_reference", "i" = "goto_implementation", "a" = "goto_last_accessed_file" }
#HX5 "f" = "goto_file"
#HX5 "n" = "goto_next_buffer"
#HX5 "p" = "goto_previous_buffer"
#HX5 "." = "goto_last_modification"

# Match mode
"A-m" = { "m" = "match_brackets", "s" = "surround_add", "r" = "surround_replace", "d" = "surround_delete", "a" = "select_textobject_around", "i" = "select_textobject_inner" }

# Window mode
"C-w" = { "w" = "rotate_view", "C-w" = "rotate_view", "v" = "vsplit", "C-v" = "vsplit", "s" = "hsplit", "C-s" = "hsplit", "left" = "jump_view_left", "h" = "jump_view_left", "C-h" = "jump_view_left", "down" = "jump_view_down", "j" = "jump_view_down", "C-j" = "jump_view_down", "up" = "jump_view_up", "k" = "jump_view_up", "C-k" = "jump_view_up", "right" = "jump_view_right", "l" = "jump_view_right", "C-l" = "jump_view_right" }
#HX5 "f" = "goto_file"
#HX5 "F" = "goto_file",
#HX5 "q" = "wclose"
#HX5 "C-q" = "wclose"
#HX5 "o" = "wonly"
#HX5 "C-o" = "wonly"

# Space mode
"space" = { "f" = "file_picker", "b" = "buffer_picker", "k" = "hover", "s" = "symbol_picker", "a" = "code_action", "'" = "last_picker", "p" = "paste_clipboard_after", "P" = "paste_clipboard_before", "y" = "yank_joined_to_clipboard", "Y" = "yank_main_selection_to_clipboard", "R" = "replace_selections_with_clipboard", "/" = "global_search" }
#HX5 "S" = "workspace_symbol_picker"
#HX5 "r" = "rename_symbol"

# Unimpaired
"A-[" = { "d" = "goto_prev_diag", "D" = "goto_first_diag", "space" = "add_newline_above" }
"A-]" = { "d" = "goto_next_diag", "D" = "goto_last_diag", "space" = "add_newline_below" }
```

</details>

**💌 Credit to @python128 for encourage me to done this config!**
