### DISCUSSION TITLE
How to execute `:format` and `:write` sequentially in Helix on escape?

### DISCUSSION THREAD

**Discussion by allaboutevemirolive** [helix-editor/helix#12136] [Q&A]
**First Question:**  
How can I properly combine `:format` and `:write` in a single keybinding? At the moment, my keybinding only runs `:format` but does not execute `:write` afterward. The original keybinding setup can be found here:  

https://github.com/helix-editor/helix/discussions/2542#discussioncomment-2959010  

This is what I want to achieve:  

```toml
# Format and autosave on `esc` key.
[keys.normal]
"esc" = ["collapse_selection", ":format", ":w"]

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":format", ":w"]

[keys.insert]
"esc" = ["normal_mode", ":format", ":w"]
```

**Second Question:**  
Why doesn't the following command execute both actions sequentially?  

```toml
[keys.normal]
"f" = [":format", ":write"]
```  

Currently, I rely on this workaround, but it isn't ideal (and it's unrelated to the first question):  

```toml
[keys.normal]
"f" = [":format"]
"r" = [":write"]
```  

Does anyone know why the original combined command doesn't work as expected?
