### DISCUSSION TITLE
How to insert an empty line?

### DISCUSSION THREAD

**Discussion by txtyash** [helix-editor/helix#1213] [Q&A] [answered]
I press `o` to insert a new line and then hit `escape` and boom the new line I just inserted is not gone. It doesn't happen when the lines are auto indented, in which case the cursor jumps back to the beginning of the line.

**Comment by sudormrfbin** [comment, marked as answer]
`]space` adds an empty line after the current line and `[space` adds one above.

**Reply by txtyash** [reply]
In neovim I had bindings for `o` and `O` to insert new line below and above respectively and still be in normal mode which is more convenient than vim's defaults. How can I have this mapping in helix?

__EDIT__ -> I made a mapping myself and it works very well.
```
    o = ["add_newline_below", "move_line_down"]
    O = ["add_newline_above", "move_line_up"]
```

**Reply by NNBnh** [reply]
`]space` adds an empty line after the current line and _`[space`_ adds one above.

**Reply by kajuburfi** [reply]
If you want, you can have kakoune-style binding(which I use) as such:
```toml
[keys.normal]
A-o = ["add_newline_below", "move_line_down"]
A-O = ["add_newline_above", "move_line_up"] # Though this doesn't work..
```
