### DISCUSSION TITLE
Why is this highlight configuration invalid

### DISCUSSION THREAD

**Discussion by ofzo** [helix-editor/helix#12303] [Q&A]
```toml
[[language]]
name = "less"
scope = "source.less"
injection-regex = "less"
file-types = ["less"]
block-comment-tokens = { start = "/*", end = "*/" }
comment-token = "//"
language-servers = [ "vscode-css-language-server" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'prettier', args = ["--parser", "less"] }

[[grammar]]
name = "less"
source = { git = "https://github.com/rhino1998/tree-sitter-less", rev="2bd739e106a3485bca210cf7b6d25ba09fd10dff" }
```
