### DISCUSSION TITLE
also allow file-types option in language-server section

### DISCUSSION THREAD

**Discussion by lucasew** [helix-editor/helix#12346] [General]
There are some issues reported around about Helix coupling heavily the LSP selection with the language

I'd like to suggest also allowing one to link a LSP to a file pattern using an option like `file-types` instead of only a language. That way a LSP could be
defined to be used in all files, like lsp-ai, or a markdown spell checker could be configured to use a specific language if the file
matches with `*.en.md` and one, like me, can have automatic spell checker configured in a simple way on a Hugo multi language project.

Configuration example that should work:

```toml
[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[language-server.ltex-ls-pt]
command = "ltex-ls"
file-types = [ {glob = "*.pt.md" } ]

[language-server.ltex-ls-pt.config.ltex]
language = "pt-BR"


[language-server.ltex-ls-en]
command = "ltex-ls"
file-types = [ {glob = "*.en.md" } ]

[language-server.ltex-ls-en.config.ltex]
language = "en-US"
```

**Comment by beeb** [comment]
Agreed, I could see this being useful for things like `crates-lsp` which should only trigger inside `Cargo.toml` files but not any other TOML file.

I would suggest to also (or only) be able to override this on a per-language basis for more flexibility:

```toml
[language-server.crates-lsp]
command = "crates-lsp"

[[language]]
name = "toml"
language-servers = ["taplo", { name = "crates-lsp", only-files = [ { glob = "Cargo.toml" } ] }]
```

I think the easiest would be if that pattern would be a filter on the normally matched files for the language.
