### DISCUSSION TITLE
How to configure helix to use system wide tree-sitter?

### DISCUSSION THREAD

**Discussion by elde-n** [helix-editor/helix#12433] [Q&A] [answered]
I have tree-sitter languages in my `/usr/lib/` path, eg. `/usr/lib/libtree-sitter-rust.so` but using the configuration below it doesn't work, probably because `source.local` refers to a git path?

`~/.config/helix/languages.toml`
```toml
[[grammar]]
name = "rust"
source.local = { path = "/usr/lib/libtree-sitter-rust.so" }
```
