### DISCUSSION TITLE
Helix ingnores `language-server.jdtls.args`

### DISCUSSION THREAD

**Discussion by h4-h** [helix-editor/helix#12449] [Troubleshooting] [answered]
### Summary

I am using the [Lombok](https://projectlombok.org/) library to generate methods, but [JDTLS](https://github.com/eclipse-jdtls/eclipse.jdt.ls) reports errors such as `<method> is undefined`.

<details>
<summary>Versions</summary>

- JDTLS: 1.42.0-1  
- Gradle: 8.12  
- Java: OpenJDK 21.0.5 2024-10-15 (64-bit)  
- Lombok: 1.18.36  

</details>

I am not an experienced Java developer, but after some research, I found that JDTLS requires the Lombok JAR file path to be specified. [Source](https://github.com/helix-editor/helix/issues/3145#issuecomment-1238049866).

I downloaded the latest Lombok JAR and configured it as follows:

```toml
[language-servers.jdtls]
command = "jdtls"
args = ["--jvm-arg=-javaagent:/home/hash/.cache/lsp/java/lombok.jar"]
```

However, this does not work. The Lombok JAR path is correct, but the argument is not applied when Helix starts JDTLS.

<details>
	<summary>`ps aux | rg java` output</summary>

	```
	hash      4947  1.4  4.8 7814300 794068 ?      Ssl  08:24   0:56 /usr/lib/jvm/java-21-openjdk/bin/java --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp /home/hash/.gradle/wrapper/dists/gradle-8.9-bin/90cnw93cvbtalezasaz0blq0a/gradle-8.9/lib/gradle-daemon-main-8.9.jar -javaagent:/home/hash/.gradle/wrapper/dists/gradle-8.9-bin/90cnw93cvbtalezasaz0blq0a/gradle-8.9/lib/agents/gradle-instrumentation-agent-8.9.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.9
	hash      8892  1.1  4.2 7800888 692784 ?      Ssl  08:42   0:34 /usr/lib/jvm/java-21-openjdk/bin/java --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.xml/javax.xml.namespace=ALL-UNNAMED -XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp /opt/gradle/gradle-8.12/lib/gradle-daemon-main-8.12.jar -javaagent:/opt/gradle/gradle-8.12/lib/agents/gradle-instrumentation-agent-8.12.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.12
	hash     21267  249  5.7 11629644 934848 pts/1 Sl+  09:29   0:21 -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dosgi.checkConfiguration=true -Dosgi.sharedConfiguration.area=/usr/share/java/jdtls/config_linux -Dosgi.sharedConfiguration.area.readOnly=true -Dosgi.configuration.cascaded=true -Xms1G --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -jar /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.900.v20240613-2009.jar -data /tmp/jdtls-3d02fcedf108fed8e45b1da21d15eb47abe81a19
	```
	
	If you do not want to read this entire output, you can filter it with `ps aux | rg lombok`, but it returns nothing.

</details>

### Reproduction Steps

0. Install JDTLS & Lombok JAR, configure it

```toml
[language-servers.jdtls]
command = "jdtls"
args = ["--jvm-arg=-javaagent:/home/hash/.cache/lsp/java/lombok.jar"]
```

1. Initialize Gradle project (java 21, single application project) and add a Lombok plugin

<details>
	<summary>Step-by-step instructions</summary>

	1.1 Initialize Gradle project

	```bash
	mkdir jdtls_lombok_helix_test
	cd jdtls_lombok_helix_test
	gradle init
	Select type of build to generate: 1 (Application)
	Select implementation language: 1 (Java)
	Enter target Java version: 21
	Select application structure^ 1 (Single application project)
	Select build script DSL: 2 (Groovy)
	Select test framework: 1 (JUnit 4)
	```

	1.2 Add Lombok plugin

	```groovy
	# app/build.gradle`

	plugins {
		id 'application'
		id 'io.freefair.lombok' version "8.11"
    }
	```

	1.3 Write some code using Lombok

	```java
	@Data
	@AllArgsConstructor
	public class MyDataClass {
		private String username;
	}
	```

	1.4 Use this code

	```java
	public class App {
  		public static void main(String[] args) {
    	    MyDataClass data = new MyDataClass("aniki");
    	    System.out.println(data.getUsername()); // "aniki"
    	}
	}
	```

</details>

Alternatively, you can clone the test repository: https://github.com/h4-h/jdtls_lombok_helix_test

2. Run the project with `./gradlew run` (Linux/macOS) or `.\gradlew.bat run` (Windows) to ensure it works.

3. Open `App.java` file and see errors.

![screenshot](https://i.imgur.com/pcbsRoI.png)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2025-01-07T09:28:14.108 helix_lsp::transport [ERROR] jdtls err <- "WARNING: Using incubator modules: jdk.incubator.vector\n"
2025-01-07T09:28:14.564 helix_lsp::transport [ERROR] jdtls err <- "Jan 07, 2025 9:28:14 AM org.apache.aries.spifly.BaseActivator log\n"
2025-01-07T09:28:14.564 helix_lsp::transport [ERROR] jdtls err <- "INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic\n"
2025-01-07T09:28:14.566 helix_lsp::transport [ERROR] jdtls err <- "Jan 07, 2025 9:28:14 AM org.apache.aries.spifly.BaseActivator log\n"
2025-01-07T09:28:14.566 helix_lsp::transport [ERROR] jdtls err <- "INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic\n"
2025-01-07T09:28:17.761 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
2025-01-07T09:28:21.679 helix_lsp::client [WARN] language server failed to terminate gracefully - failed to parse: invalid type: map, expected unit
```

</details>

### Platform

Linux (Artix/dinit)

### Terminal Emulator

foot 1.20.1

### Installation Method

Release page - app image

### Helix Version

helix 25.1 (dabfb6ce)

**Comment by kirawi** [comment]
Just in case, are you sure the `languages.toml` filename is not mistyped? It's a common mistake to forget the trailing `s`.

**Comment by h4-h** [comment]
> Just in case, are you sure the `languages.toml` filename is not mistyped? It's a common mistake to forget the trailing `s`.

I'm sure because I have other language configurations that work

```bash
❯ ls ~/.config/helix
 config.toml   languages.toml   themes
```

**Comment by h4-h** [comment, marked as answer]
# UPD

After reading my own post, I realized that I had used `language-servers.jdtls` instead of `language-server.jdtls`. By removing the extra **s**, I fixed the error. Sorry! It's funny how @kirawi was almost right.

I think it would be nice to have some type of warning for situations like this.

<hr>


I’m not sure if this will help, but the [Extension Pack for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) in VS Code supports Lombok without requiring any additional configuration.

This extension also uses JDTLS. They ship their own Lombok ` -javaagent:/home/hash/.vscode-oss/extensions/redhat.java-1.38.0-linux-x64/lombok/lombok-1.18.34.jar`.

I think either something is wrong with my `languages.toml`, or Helix does not process `args` for JDTLS or any other LSPs (I have only JDTLS configured with `args`).

![Image](https://i.imgur.com/VxPcoXP.png)

<details>
  <summary>`cat ~/.config/helix/languages.toml`</summary>

	```toml
	[[language]]
	name = "rust"
	auto-format = false

	[language-server.rust-analyzer]
	config.check.command = "clippy"
	cargo.features = ["--all-features"]

	[[language]]
	name = "markdown"
	language-servers = ["mdpls"]
	file-types = [ "md" ]

	[language-server.mdpls]
	command = "mdpls"
	config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }

	[[language]]
	name = "astro"
	scope = "source.astro"
	injection-regex = "astro"
	file-types = ["astro"]
	roots = ["package.json", "astro.config.mjs"]
	language-servers = [ "astro-ls", "tailwindcss-ls" ]

	[language-server.astro-ls]
	command = "astro-ls"
	args = [ "--stdio" ]
	config = { "typescript" = { "tsdk" = "/home/hash/.local/share/pnpm/global/5/node_modules/typescript/lib"}, "environment" = "pnpm" }

	[language-server.tailwindcss-ls]
	command = "tailwindcss-language-server"
	args = ["--stdio"]
	config = { userLanguages = { astro = "html", "*.astro" = "html" } }

	[language-servers.jdtls]
	command = "jdtls"
	args = ["--jvm-arg=-javaagent:/home/hash/.cache/lsp/java/lombok.jar"]
	```

	I know that `languages.toml` is being loaded because MDPLS automatically opens Markdown files, and Astro works with Tailwind. If I remove these configurations, they stop working.

</details>
