### DISCUSSION TITLE
How can I run an external command and then run a Helix command when the external command exits?

### DISCUSSION THREAD

**Discussion by David-Else** [helix-editor/helix#12646] [Q&A]
I have this shortcut:
```toml
l   = ":sh kitty @ launch --no-response --cwd=current --type=overlay --copy-env lazygit"
```
but I need to run `reload-all` after it exits to update git gutters and git branch on the statusline.

I can't run the following because apparently `:sh` is async and `reload-all` is run right after the shell command is started:

```toml
[keys.normal.C-t]
l = [ ":sh kitty @ launch --no-response --cwd=current --type=overlay --copy-env lazygit", ":reload-all" ]
```

Can I somehow use a macro keybinding to overcome this problem, or some other cleverness I have not considered? `insert-output` does not work in my terminal Kitty.

Thanks!
