### DISCUSSION TITLE
Clipboard provider option gives 'unknown field'

### DISCUSSION THREAD

**Discussion by uben0** [helix-editor/helix#12661] [Q&A] [answered]
I try to specify a different clipboard provider than the default. But my configuration is not reloaded successfully:

```toml
theme = "ayu_dark"

[editor]
clipboard-provider = "my-clipboard-util"
```

Which gives:

```
Bad config: unknown field `clipboard-provider`, expected one of `scrolloff`, `scroll-lines`, `mouse`, `shell`, `line-number`, `cursorline`, `cursorcolumn`, `gutters`, `middle-click-paste`, `auto-pairs`, `auto-completion`, `auto-format`, `auto-save`, `text-width`, `idle-timeout`, `completion-timeout`, `preview-completion-insert`, `completion-trigger-len`, `completion-replace`, `auto-info`, `file-picker`, `statusline`, `cursor-shape`, `true-color`, `undercurl`, `search`, `lsp`, `terminal`, `rulers`, `whitespace`, `bufferline`, `indent-guides`, `color-modes`, `soft-wrap`, `workspace-lsp-roots`, `default-line-ending`, `insert-final-newline`, `smart-tab`, `popup-border`, `indent-heuristic`, `jump-label-alphabet`
```

But the Helix documentation says there is such an option:

https://docs.helix-editor.com/editor.html#editorclipboard-provider-section

What is going on?

I am using helix 24.7 (079f5442)

**Comment by TornaxO7** [comment, marked as answer]
This config option was merged in Nov 20, 2024 (https://github.com/helix-editor/helix/pull/10839#issuecomment-2477623376) so it wasn't added in 24.7.

**Reply by uben0** [reply]
Thank you!

Wow, I'm victim from the Mandela effect. I'm 100% sure I used this option more than a year ago 🧐

**Reply by TornaxO7** [reply]
> Thank you!

You're welcome :)

Please don't forget to mark my answer as "Answer" to mark your question as "answered" ;)

**Reply by uben0** [reply]
But I don't understand why they call copying `paste` and pasting `yank`:

```toml
[editor.clipboard-provider.custom]
paste = { command = "wl-copy", args = [] }
yank = { command = "wl-paste", args = [] }
```
It works like this. At first I used the opposite and it didn't work. And I double checked the command, `wl-copy` copies and `wl-paste` pastes.

**Reply by uben0** [reply]
This is super strange, because it cannot be a bug as anyone would have noticed. Could someone try on its side?

**Reply by the-mikedavis** [reply]
The naming is not really ideal - "paste" here means the command called when pasting to the clipboard program, so the clipboard program should accept input, while "yank" is the command used when yanking from the clipboard program.

We could reverse it but it would be a breaking change to any existing clipboard configurations.

**Reply by uben0** [reply]
Is it planed to have an auto migration? That Helix automatically updates the config?

The retro-compatibility could be preserved if the current names are preserved but aliases are introduced. For instance:

```toml
push-to-clipboard = { command = "wl-copy" }
pull-from-clipboard = { command = "wl-paste" }
```
