### DISCUSSION TITLE
Add selection at next match: a handy keybind

### DISCUSSION THREAD

**Discussion by ArthaTi** [helix-editor/helix#12683] [Show and tell]
In my config, under `[keys.normal]` and `[keys.select]` I added two bindings:

```toml
"A-n"   = ["search_selection", "extend_search_next"]
"S-A-n" = ["search_selection", "extend_search_prev"]
```

This makes `Alt+N` search for the next occurrence of whatever is under the cursor, and create a new selection for this occurrence. This is very similar to VSCode's `Ctrl+D` "Add Selection To Next Find Match".

https://github.com/user-attachments/assets/6d265bf4-d7fc-4b6e-a0ee-bf705f8fd34f

The next best thing is that sometimes you need to skip a match. No binds are needed, a regular `N` press does the job:

https://github.com/user-attachments/assets/f5339c1b-5cf2-42fe-9b87-674b24cccc9e

I'm a bit surprised the above two aren't defaults. It's worth nothing`Alt+N` is normally bound to "Select next sibling node in syntax tree (TS)," but it's not something have I ever used.
