### DISCUSSION TITLE
Add typos workflow

### DISCUSSION THREAD

**Discussion by nik-rev** [helix-editor/helix#12691] [Ideas]
Typos: https://github.com/crate-ci/typos

Would make it easy to catch all typos with a github action. There is a PR that used this to fix 68 typos: https://github.com/helix-editor/helix/pull/12690

It would be handy to have this run on every PR to catch possible typos

**Comment by szepeviktor** [comment]
```yaml
steps:
  - uses: actions/checkout@v4
  - uses: crate-ci/typos@master
```

It is so easy.
But I have to work on false positives a little more.
