### DISCUSSION TITLE
can't set languages

### DISCUSSION THREAD

**Discussion by donnieparka** [helix-editor/helix#12765] [Troubleshooting]
```toml
theme = "gruvbox"
[editor]
line-number = "relative"
[language-server]
elixir-ls = { command = "elixir-ls", config = { elixirLS.dialyzerEnabled = false } }
```
i get this error
![image](https://github.com/user-attachments/assets/a3c41d57-5594-4baf-a563-741fd07fc188)

why?
