### DISCUSSION TITLE
How to choose target for the workspace's rust analyzer

### DISCUSSION THREAD

**Discussion by KySpace** [helix-editor/helix#12799] [Q&A] [answered]
Say, if I want to set the target to `wasm32-unknown-unknown`.
Which configuration file do I write into, and what do I add? Thanks.

**Comment by theridane** [comment, marked as answer]
Helix supports per-workspace overrides, just place the relevant config into a directory named `.helix` in the root of the workspace (so next to `Cargo.toml` etc).

In your case, you'd have a file `.helix/languages.toml` with:

```toml
[language-server.rust-analyzer.config]
cargo.target = "wasm32-unknown-unknown"
check.allTargets = false
```
