### DISCUSSION TITLE
eslint language server not working? Check this. vscode-eslint-language-server with flat config

### DISCUSSION THREAD

**Discussion by samankittani** [helix-editor/helix#12805] [General]
I spent a great deal of time tracking down why my installed vscode-eslint-language-server from vscode-langservers-[extracted@4.8](https://www.npmjs.com/package/vscode-langservers-extracted/v/4.8.0) was not working, including patching using the to-be-merged [PR](https://github.com/hrsh7th/vscode-langservers-extracted/pull/10). I learned some new things I did not know about helix, and I will use this opportunity to help someone get out of the rabbit hole early. 

Make sure your language.toml file includes an eslint lsp config with the bare minimums discussed in this [discussion](https://github.com/helix-editor/helix/discussions/8452):
```toml
[language-server.eslint-lsp.config]
# format = true # optional
nodePath = ""
# onIgnoredFiles = "off" # optional
# packageManager = "yarn" # optional
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false # optional
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
# codeActionsOnSave = { mode = "all" } # optional
experimental = { useFlatConfig = true } ### NEEDED FOR FLAT CONFIG 
problems = { shortenToSingleLine = false }
# workingDirectory = { mode = "auto" } # optional
```

I learned that I need to have the bare minimum config for the lsp to work. I didn't experiment with what exactly is required. I also learned that I can look at the vscode eslint settings to find all the configuration options available for this LSP. Importantly, I learned that I needed the useFlatConfig flag in the experimental object in order for the flat config to be registered. This may seem obvious to some, but I hope this helps someone. 

Also, make sure you configure the lsp command and apply it to a language:
```toml
[language-server.eslint-lsp]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint-lsp"]
formatter = { command = 'prettier' }
auto-format = false
```

**Comment by Rudxain** [comment]
Update for everyone: Since a few releases ago, ESL should work out-of-the-box:
https://github.com/helix-editor/helix/blob/e7ac2fcdecfdbf43a4f772e7f7c163b43b3d0b9b/languages.toml#L221-L241

However, for some reason, it randomly decides to work on my install.

Relevant log (timestamp removed):
```log
helix_term::application [ERROR] Language Server: Method eslint/noLibrary not found in request 2
```

**Reply by stravo1** [reply]
same issue :(

**Reply by Ssaely** [reply]
I was getting this when I didn't have ESLint installed locally, even though I had it installed globally. Make sure you install it locally with `npm i -D eslint` in your project.

The minimum config for `languages.toml` I have with helix 24.07:
```toml
[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server", "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server", "vscode-eslint-language-server",
]
```
