### DISCUSSION TITLE
Continue markdown lists as a default configuration

### DISCUSSION THREAD

**Discussion by nik-rev** [helix-editor/helix#12812] [Ideas]
I've been really enjoying having markdown lists and blockquotes automatically continue with this config:

```toml
[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "1.", ">", "- [ ]"]
```

We can also extend this to other languages that have lists. Such as typst, asciidoc, etc.

Should this be the default? I decided to open this discussion instead of a PR to see what people think in general. This is a great usability improvement, at least for me and [some other people](https://github.com/helix-editor/helix/issues/12782#issuecomment-2639644408). I would love to see this as a default. My only concern is that it says "comment tokens" despite these not actually being comments. Thoughts?
