### DISCUSSION TITLE
*Not* continue comment on enter

### DISCUSSION THREAD

**Discussion by lambda-dom** [helix-editor/helix#12815] [Q&A] [answered]
In the newest Helix version, if I am in insert mode in a comment line and hit enter, it continues the comment, e.g. using Haskell line comments for illustration (^ denotes cursor position):

```haskell
-- a comment.^
```

Hitting enter, produces

```haskell
-- a comment.
-- ^
```

But I want:

```haskell
-- a comment.
^
```

Backing out to normal mode and hitting o also produces the same effect; in other words, the only way now is to "undo" the comment. Is there a keybinding available which I managed to *not* find? Or can one be made?

**Comment by the-mikedavis** [comment]
You can turn the feature off: https://docs.helix-editor.com/master/editor.html#editor-section

```toml
# ~/.config/helix/config.toml
[editor]
continue-comments = false
```

**Reply by k4lizen** [reply]
Ideally I would like to be able to use the feature at my discretion

**Comment by nik-rev** [comment, marked as answer]
You can also create keybindings to create a newline without adding a comment token:

```toml
[keys.normal.g]
O = ["open_above", "delete_word_backward"]
o = ["open_below", "delete_word_backward"]

[keys.insert]
A-ret = ["insert_newline", "delete_word_backward"]
```

This is what I use and it's quite effective
