### DISCUSSION TITLE
Reusing existing grammar for custom language config?

### DISCUSSION THREAD

**Discussion by senekor** [helix-editor/helix#12820] [Q&A] [answered]
I would appreciate some help getting syntax highlighting to work for a custom language definition.

So I'm working on [ec2hx](https://github.com/senekor/ec2hx) to provide EditorConfig support for Helix. One of the most difficult features is to customize stuff based on arbitrary globs instead of for individual languages. My idea was to configure a _new language_ for each glob and copy-paste most of the config from the original language. This mostly works, except for syntax highlighting.

For example, the Linux kernel has the following editorconfig section:
```
[tools/{perf,power,rcu,testing/kunit}/**.py,]
indent_style = tab
indent_size = 8
```

From that, `ec2hx` generates several synthetic languages like the following:

```toml
[[language]]
name = "ec2hx-glob-lang-tools/perf/**.py" # <--- generated name
scope = "source.python"
injection-regex = "py(thon)?"
file-types = [{ glob = "tools/perf/**.py" }] # <--- custom glob
shebangs = ["python", "uv"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["ruff", "jedi", "pylsp"]
indent = { unit = "\t", tab-width = 8 } # <--- actual customization
grammar = "python" # <--- my attempt to get syntax highlighting to work ❌
```

Does anybody have an idea what about this language configuration is preventing the syntax highlighting from working? Thanks for any help!
