### DISCUSSION TITLE
Allow use of Environment variables in languages.toml (and/or config.toml)

### DISCUSSION THREAD

**Discussion by tahir-hassan** [helix-editor/helix#12851] [Ideas] [answered]
It would be cool if I could do:

```toml
[[language]]
name = "markdown"
formatter = { command = "pwsh", args = ["-noprofile", "-f", "${env:PS_SCRIPTS}\\format_md.ps1"]}
auto-format = true
```

Where `${env:PS_SCRIPTS}` is a reference to a variable.  It might make configuration a bit easier for people.

**Comment by leo-unglaub** [comment]
I am always a little bit nervous when config files can evaluate code from an environment variable. That can lead to potential security problems later on.

Out of curriosity, what would you use that feature for?

**Comment by tahir-hassan** [comment]
> I am always a little bit nervous when config files can evaluate code from an environment variable. That can lead to potential security problems later on.

I would say that in this case, it is only evaluating the environment variable, nothing more. 

> Out of curriosity, what would you use that feature for?

It just makes the config files easier to edit, especially the `languages.toml` where I want to use PowerShell scripts from a specific folder as formatters without having to use the absolute path.

**Comment by the-mikedavis** [comment]
I believe this should already be possible if you provide a formatter that executes a shell command. For example on linux:

```toml
[[language]]
name = "markdown"
auto-format = true
formatter = { command = "sh", args = ["-c", "echo $PWD"] }
```

**Comment by tahir-hassan** [comment, marked as answer]
@the-mikedavis yes, thank you for the solution.  It is dependent on the shell you are targeting.  With `pwsh`, you have to use `-c` flag (for command) to run a file:

```toml
[[language]]
name = "markdown"
formatter = { command = "pwsh", args = ["-noprofile", "-c", ".", "$env:PS_SCRIPTS\\format_md.ps1"]}
auto-format = true
```
`. <script path>.ps1` is PowerShell's syntax of executing a script, that is why you have `.` as the first argument to `-c`.

I hereby mark this as solved.
