### DISCUSSION TITLE
yaml github actions schema isn't respected

### DISCUSSION THREAD

**Discussion by i-am-logger** [helix-editor/helix#12868] [Troubleshooting]
### Summary

adding the folowing: 
```toml
[[language]]
auto-format = true
file-types = ["yml", "yaml"]
language-servers = ["yaml-language-server"]
name = "yaml"
scope = "source.yaml"
```
and

``` toml

[language-server.yaml-language-server]
args = ["--stdio"]
command = "/nix/store/zh8pl4xx9nw9d957b4h0vjbyaw0kgp41-yaml-language-server-1.15.0/bin/yaml-language-server"

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-action.json" = ["action.yml", "action.yaml"]        

```

i'm getting errors that are not true

![Image](https://github.com/user-attachments/assets/0baaba12-ff07-46b8-b783-aa7c85b8c640)

### Platform

linux nixos

### Terminal Emulator

ghostty

### Installation Method

nix-shell -p helix

### Helix Version

25.1
