### DISCUSSION TITLE
Is there anyway to disable a formatter included in the default languages.toml

### DISCUSSION THREAD

**Discussion by mtoohey31** [helix-editor/helix#12957] [Q&A] [answered]
Title. I wanted to try disabling the external swift-format binary (and using the language server instead), but I couldn't figure out how to do this.

This is potentially related to #9543.

**Comment by the-mikedavis** [comment, marked as answer]
You can change the command to anything that doesn't exist, for example the empty string:

```toml
[[language]]
name = "swift"
formatter.command = ""
```
