### DISCUSSION TITLE
How can I do `x` without the buffer scrolling horizontally to the end of the line?

### DISCUSSION THREAD

**Discussion by willfaught** [helix-editor/helix#12974] [Q&A] [answered]
When it does that, I can't see the start of the next (shorter) line to decide whether to press `x` again to select it.

**Comment by tpm-cd** [comment, marked as answer]
Would `Alt-;` to pull the anchor to the start solve your use case?

If it helps, maybe a remap like

``` toml
[keys.normal]
x = ["extend_line_below", "flip_selections"]
```

Note that this is not great, since repeated `x` will not scroll the text (the anchor will always stay at the beginning of the line where you first typed `x`).
