### DISCUSSION TITLE
Multiple cursor "add next occurrence" similar to VSCode "Ctrl+D"

### DISCUSSION THREAD

**Discussion by AllanZyne** [helix-editor/helix#13006] [Q&A] [answered]
Does helix have this shortcut? I read helix tutorial but haven't fount it.
Thanks.

**Comment by pasteley** [comment, marked as answer]
```toml
[keys.normal]
C-n = ["search_selection", "extend_search_next"]
```
