### DISCUSSION TITLE
Helix -g fetch & build not pulling the latest on main

### DISCUSSION THREAD

**Discussion by MaxBeaud** [helix-editor/helix#13011] [Troubleshooting]
### Summary

In the `language.toml`  file when specifying the main branch instead of a commit hash. When running helix -g fetch it appears as `language-x on main` it is never built. 

Iv'e opened issues on the C3 

### Reproduction Steps

```toml
[[grammar]]
name = "c3"
[grammar.source]
git = "https://github.com/c3lang/tree-sitter-c3.git"
rev = "main"

[[language]]
name = "c3"
scope = "source.c3" 
file-types = [ "c3", "c3i" ]
roots = ["project.json"]
comment-token = "//"
indent = { tab-width = 4, unit="    "}
language-servers = [ "c3-lsp" ]
grammar = "c3"

[language.block-comment-tokens]
end = "*/"
start = "/*"

[language-server]
c3-lsp = { command = "c3lsp" }
```

This is the specific toml file I was using. It was originally a tree-sitter issue, but then since the change. For more context you can refer to the now closed [treesitter issue](https://github.com/c3lang/tree-sitter-c3/issues/22) and the [lsp issue](https://github.com/pherrymason/c3-lsp/issues/119)

### Platform

Arch Linux

### Terminal Emulator

Ghostty

### Installation Method

pacman extra/helix

### Helix Version

helix 25.01.1
