### DISCUSSION TITLE
AutoHotkey syntax or auto-completion

### DISCUSSION THREAD

**Discussion by Lateralus138** [helix-editor/helix#13030] [General] [answered]
I am curious if there were any plans to implement ***AutoHotkey*** Syntax and/or auto-completion? I know it's not the most popular language, but I write a considerable amount of it and I am starting to like Helix. There's already syntax and auto completers in other editors/IDE so I know there's potential for one here, just not sure if anyone has it planned.

Sorry if this is the wrong section to put this in, I almost put it in ideas, but wasn't sure.

**Comment by masriomarm** [comment]
Hi, sorry for the inconvenience.
But, since  you're an autohotkey expert, would you please help in implementing a dual key role for `capslock`.
I need it when pressed to be `ctrl` and when tapped to be `esc`.
But, I need to work with other remaps. For example, I remaped `alt-j` as down arrow, I need when using caps dual role to be able to send `ctrl-down` when holding `ctrl-alt-j`.
Thanks in advance, and I apologize for the inconvenience.

**Reply by Lateralus138** [reply]
> I need it when pressed to be `ctrl` and when tapped to be `esc`.

Do you mean ***held for an extended period of time*** versus ***pushed***?

Or do you mean when the state is toggled?

If so then this should be the AutoHotkey part (adjust timing as needed):
```AutoHotkey
*CapsLock::
{
  Send "{LControl down}"
}

*CapsLock up::
{
  Send "{LControl Up}"
  if (A_PriorKey == "CapsLock")
  {
    if (A_TimeSincePriorHotkey < 1000)
    {
      Suspend "1"
      Send "{Esc}"
      Suspend "0"
    }
  }
}
```

**Reply by masriomarm** [reply]
Thank you so much.

**Comment by IllyStable** [comment]
I think there may already be support, just with some effort; helix works with LSPs to support languages. It looks like there's a few AHK LSPs on github, but personally haven't tried any.

**Reply by Lateralus138** [reply]
Thanks, I did do a quick web search before I asked this and all I could find was an LSP for using OpenAI/CoPilot for auto-completions and I don't care to use AI much. I will check it out anyway just to see what it's about. I will search here specifically at GH for some, but they didn't come up in my initial search. Thanks again!

**Comment by Lateralus138** [comment]
So I read that the AutoHotkey LSP plugin for VS Code should work (which I already had installed), but I I can't seem to get it working. I also tried installing the plugin using the plugins repository node installation instructions, but with the same results. I am very new to Helix and have been reading through the documentation for installing a new language, but I don't think I've done it right. Would anyone mind helping?

Here's my config in *languages.toml*:
```TOML
[[language]]
name = "autohotkey"
file-types = ["ahk"]
scope = "source.autohotkey"
indent = { tab-width = 2, unit = " " }
comment-tokens = ";"
formatter = { command = "node", args = ["</MY/USER/PATH>/.vscode-oss/extensions/mark-wiemer.vscode-autohotkey-plus-plus-6.5.0-universal/ahk2/server/dist/server.js", "--node-ipc"] }
language-servers = [ { name = 'vscode-autohotkey2-lsp' } ]
```
I tried changing `name` in `language-servers` to the *server.js* path with no different result.

Results of the health check:

```PWSH
PS> hx --health autohotkey
Configured language servers: None
Configured debug adapter: None
Configured formatter: node
Binary for formatter: C:\Program Files\nodejs\node.exe
Tree-sitter parser: None
Highlight queries: ✘
Textobject queries: ✘
Indent queries: ✘
```
Result:
![Screenshot 2025-03-05 085206](https://github.com/user-attachments/assets/d111719e-ce49-4675-8f6d-521599492426)

**Reply by sibouras** [reply, marked as answer]
first you need to download the lsp, follow the instructions from the readme https://github.com/thqby/vscode-autohotkey2-lsp?tab=readme-ov-file#use-in-other-editors,

assuming you created a `~/src` folder and installed the lsp in that folder, this is what the lsp config will look like

```toml
[[language]]
name = "autohotkey"
scope = "source.ahk"
file-types = ["ahk"]
comment-token = ";"
indent = { tab-width = 2, unit = " " }
language-servers = ["ahk2"]


[language-server.ahk2]
command = "node"
args = ["c:/Users/your_username/src/vscode-autohotkey2-lsp/server/dist/server.js", "--stdio"]
```

the lsp includes a formatter so you don't need to configure one, it also includes some syntax highlighting with semantic tokens but helix only highlights using treesitter so you won't have highlighting, and i don't know if there's treesitter highlighting for ahk2

note: the lsp needs to detect ahk v2 or it exists so make sure to have `#Requires AutoHotkey v2.0`
