### DISCUSSION TITLE
How to combine HTML LSPs and gopls in Go HTML Templates?

### DISCUSSION THREAD

**Discussion by Nintron27** [helix-editor/helix#13035] [Q&A] [answered]
I'm currently trying to combine my HTML LSPs and Golang (gopls) LSP in HTML files, but I'm not having great success. The path I've taken so far is this:

## First attempt
My first attempt was to just use HTML LSPs, but I unfortunately don't get syntax highlighting for any of the Go Template parts of the file, and if I use the vscode html LSP then it tries formatting my Go template sections, for example it thinks line 9 is real CSS, so it breaks up all the curly braces to format it as such.
![image](https://github.com/user-attachments/assets/a664f7da-fdba-4790-b557-b367520d970a)
The configuration for this attempt is:
```toml
[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = [
	"html",
	"htm",
	"shtml",
	"xhtml",
	"xht",
	"jsp",
	"asp",
	"aspx",
	"jshtm",
	"volt",
	"rhtml",
	"cshtml",
]
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = [
	"vscode-html-language-server",
	"tailwindcss-ls",
	"emmet-lsp",
]
auto-format = true

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.emmet-lsp]
command = "emmet-ls"
args = ["--stdio"]
```

## Second Attempt
My second attempt is to treat this as a gotmpl file, and then use tree sitter to inject the language as HTML for everything that's not a go template. Before the runtime injections the file looks like this (note, now the extension is `.tmpl` not `.html` as in the first attempt):
![image](https://github.com/user-attachments/assets/3401caf9-10f2-4434-ab70-6c929e73e266)
However once I set up these injections:
```scm
((text) @injection.content
 (#set! injection.language "html")
 (#set! injection.combined))
```
and my `languages.toml` to this:
```toml
[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = [
	"html",
	"htm",
	"shtml",
	"xhtml",
	"xht",
	"jsp",
	"asp",
	"aspx",
	"jshtm",
	"volt",
	"rhtml",
	"cshtml",
]
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = [
	"vscode-html-language-server",
	"tailwindcss-ls",
	"emmet-lsp",
]
auto-format = true

[[language]]
name = "gotmpl"
scope = "source.gotmpl"
injection-regex = "gotmpl"
file-types = ["gotmpl", "tmpl"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["gopls"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.emmet-lsp]
command = "emmet-ls"
args = ["--stdio"]
```
Now my file looks like this:
![image](https://github.com/user-attachments/assets/52b252f2-8dc9-4678-b0a9-fe0d92acd610)
Syntax highlighting is all there, YAY! But it's not actually using my HTML LSPs on the HTML sections :(
For example, hover documentation isn't coming from the vscode LSP:
![image](https://github.com/user-attachments/assets/b907adeb-bcdc-4e0d-a3d4-b60d387261de)
And tailwind isn't giving any suggestions on class lists:
![image](https://github.com/user-attachments/assets/0c63c0c6-01b2-47b3-a788-2e2c3faa350b)

It's as if it's just using the gopls lsp for these sections as well. (For example, the hover doc saying "constant" is the exact same behavior as without the injections).

I feel like I'm close, but I'm just missing how to get the HTML LSPs actually taking precedence on the HTML sections of the document.

_Happy to provide any additional information that may be needed to figure out how to configure this._

**Comment by chico1992** [comment]
for your 2nd attempt you didn't add the html lsp to the gotmpl language
```toml
[[language]]
name = "gotmpl"
scope = "source.gotmpl"
injection-regex = "gotmpl"
file-types = ["gotmpl", "tmpl"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["gopls","vscode-html-language-server"]
```

this should work to get the html lsp to work for tmpl files

**Comment by yayolande** [comment]
Use a dedicated [Go-Template LSP](https://github.com/yayolande/go-template-lsp) instead of the Golang (gopls) LSP. 

That LSP is still in development, but it might be useful enough

**Reply by AxelRHD** [reply]
Sounds great. Do you have a working setup for the helix language configuration?

**Reply by yayolande** [reply]
Hello @AxelRHD , below is a simple setup for helix.

```toml
[[language]]
name = "html"
# name = "gotmpl"

scope = "text.html.basic"
roots = ["go.mod"]
file-types = ["html"]
language-servers = ["go-template-lsp", "vscode-html-language-server"]

[language-server.go-template-lsp]
command = "/path/to/go-template-lsp"
```
With this config, both LSP are working properly

However, I was not able to make the syntax highlighting work for both languages. Currently, it only highlight HTML elements. To enable GO TEMPLATE highlighting instead, uncomment `name = "gotmpl"` and comment the other one.

As a reminder, you need to first compile the executable for the go template LSP. Look at the repo for more details.

**Reply by AxelRHD** [reply]
Thanks a lot! I will give it a try the next days. Syntax highlighting for HTML is fine.

**Reply by Nintron27** [reply]
I wasn't originally really looking for a different LSP, however, the support gotmpl has LSP wise is criminal, so I will certainly give this LSP a look when I have some time!

**Comment by David-Else** [comment, marked as answer]
I added the HTML injection and more with https://github.com/helix-editor/helix/pull/14746 , please comment if there is a problem.

Add these to your project files for full power syntax highlighting and formatting, tested in a Hugo project:

`.helix/languages.toml` 
```toml
[[language]]
name = "gotmpl"
file-types = ["gotmpl", "html"]
language-servers = ["vscode-html-language-server", "gopls"]
formatter = { command = 'prettier', args = ["--parser", "go-template"] }
```
`package.json`
```json
  "devDependencies": {
    "prettier-plugin-go-template": "^0.0.15"
  }
```
