### DISCUSSION TITLE
Can not remap Ctrl+k. (bug?)

### DISCUSSION THREAD

**Discussion by oxcrow** [helix-editor/helix#13107] [Troubleshooting] [answered]
I'm trying to remap Ctrl+j and Ctrl+k to scroll down and up.

Ctrl+j works well.

Ctrl+k does not.

I set this in `config.toml`.
```toml
C-j = "half_page_down"
C-k = "half_page_up" # << Error: Does nothing.
```

**Comment by oxcrow** [comment]
Alt+j and Alt+k works well by the way.

```toml
A-j = "half_page_down"
A-k = "half_page_up" # << Works well.
```
