### DISCUSSION TITLE
Integrating tree-sitter-lilypond into Helix

### DISCUSSION THREAD

**Discussion by AlexHarter** [helix-editor/helix#13120] [Q&A] [answered]
How can I go about integrating [nwhetsell/tree-sitter-lilypond](https://github.com/nwhetsell/tree-sitter-lilypond) into Helix?  I'm assuming I would need to write Helix-specific queries. ([Related issue in the grammar's repo.](https://github.com/nwhetsell/tree-sitter-lilypond/issues/1#issuecomment-1874750690)) Does #12972 affect that?

Here is the relevant section in my `languages.toml`:
```toml
[[language]]
name = "lilypond"
scope = "scope.lilypond"
file-types = ["lilypond", "ly"]
comment-tokens = "%"
indent = { tab-width = 2, unit = " " }

[[grammar]]
name = "lilypond"
source = { git = "https://github.com/nwhetsell/tree-sitter-lilypond" }
```
