### DISCUSSION TITLE
Why isn't an `underline` or `hidden` secondary cursor possible?

### DISCUSSION THREAD

**Discussion by 00-kat** [helix-editor/helix#13168] [Q&A] [answered]
From the [Helix Docs § \[`editor.cursor-shape`\]][docs]:
> 💡 Due to limitations of the terminal environment, only the primary cursor can change shape.

Which makes perfect sense, since you can only have one cursor, and the other artificial cursors have to take up an entire cell.  *But*, a<ins>rbit</ins>ra<ins>ry</ins> te<ins>x</ins>t <ins>ca</ins>n <ins>be</ins> underl<ins>ine</ins>d, so why is it not possible to use an `underline` cursor[^1]?

Similarly with `hidden`: all it requires is for the artificial cursor to not be drawn, so I don't see why that is not possible either.

Kakoune, for example, allows changing any cursor to an underline, and it works just fine:
![image](https://github.com/user-attachments/assets/a3350c25-f081-4d32-baf4-868ef20c796d)
<sup>(N.B.: the weird alternating colours are because I have the cursor colour set to be the reverse of the foreground.)</sup>

[docs]: https://docs.helix-editor.com/editor.html#editorcursor-shape-section

[^1]: Well, other than the fact that it's not implemented, I mean; I'm only talking about whether it is possible in theory.

**Comment by 00-kat** [comment, marked as answer]
Actually, it seems to already be possible through the theming system:

Underline:
```toml
"ui.cursor.normal" = { modifiers = ["underlined"], underline.color = "your-cursor-color" }
"ui.cursor.insert" = { modifiers = ["underlined"], underline.color = "your-cursor-color" }
"ui.cursor.select" = { modifiers = ["underlined"], underline.color = "your-cursor-color" }
```
(Of course, this does require the [coloured underlines extension] to be supported by one's terminal emulator.)

Hidden:
```toml
"ui.cursor.normal" = {}
"ui.cursor.insert" = {}
"ui.cursor.select" = {}
```

[coloured underlines extension]: https://sw.kovidgoyal.net/kitty/underlines/
