### DISCUSSION TITLE
React UMD error

### DISCUSSION THREAD

**Discussion by meclondrej** [helix-editor/helix#13209] [Q&A]
I installed `typescript-language-server` globally with npm and opened up a tsx file with helix. All html tags have red underlines and log this:

```
'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

I tried putting `"jsx": "react-jsx"` and `"allowUmdGlobalAccess": true` in my `compilerOptions`, but nothing worked. The project itself, however, compiles just fine in any case. I really don't want to put a React import on top of every tsx file when this is only a helix issue. Does anybody know what's wrong?

**Comment by meclondrej** [comment]
Solved by [justanothercommylovr](https://www.reddit.com/user/justanothercommylovr/) in a [reddit post](https://www.reddit.com/r/HelixEditor/comments/1jkh23b/react_umd_error/):

```toml
[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "emmet-ls" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true
```
