### DISCUSSION TITLE
Helix LSP Not Scrolling on Definition of a Function or Object.

### DISCUSSION THREAD

**Discussion by abeni-csa** [helix-editor/helix#13333] [Troubleshooting]
![Image](https://github.com/user-attachments/assets/c2c3def7-fb07-4689-ad78-84514c3adc21)

**Comment by RoloEdits** [comment]
Huh, this is the first time I discovered that this can support mouse scroll. I have tried myself and it seems to work fine.   What terminal are you using? What helix version? In the future, please use the template. It may be annoying, but often you dont need to fill everything out, but terminal and versions are a must. 

You can "scroll" with `ctrl+d` and `ctrl+u` in the meantime.

**Comment by abeni-csa** [comment]
helix = Version:  25.01.1 
Windows Terminal = Version: 1.22.10731.0
"scroll" with `ctrl+d` and `ctrl+u` is not working for me.

can you share your config file

**Comment by abeni-csa** [comment]
still am struggling to fix this issue

**Comment by RoloEdits** [comment]
```toml
[editor]
shell = ["nu", "-l", "-c"]
line-number = "relative" 
color-modes = true
undercurl = true
true-color = true
completion-timeout = 5
completion-trigger-len = 1
completion-replace = true
preview-completion-insert = false
rulers = [121]
end-of-line-diagnostics = "hint"
jump-label-alphabet = "asdfqwezxcrtgv"

[keys.normal]
";" = ["collapse_selection", "keep_primary_selection"]

# Move line up or down
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

x = "select_line_below"
X = "select_line_above"

"'"="goto_word"

[keys.insert]
C-right = "move_next_word_end"
C-left = "move_prev_word_start"
```

I have also tried Windows Terminal and helix and it works fine for me.
