### DISCUSSION TITLE
Find all references in C# solution if one is loaded

### DISCUSSION THREAD

**Discussion by LyndonGingerich** [helix-editor/helix#13536] [Ideas]
I am using [csharp-ls](https://github.com/razzmatazz/csharp-language-server) for C#. When I use `gr` to find references, I get only the references in the current project, not in the current solution.

My `languages.toml` (in the repository root directory, with the `slnx` file):
```toml
[language-server.csharp-ls]
command = 'csharp-ls'
args = ['-s MySolution.slnx']
```

Could I get references in the solution rather than just in the project?
