### DISCUSSION TITLE
Folder specific LSP settings

### DISCUSSION THREAD

**Discussion by dionysiusmarquis** [helix-editor/helix#13579] [Q&A] [answered]
Hey,

I'm trying to switch from eslint/prettier to biome in a monorepo project. Unfortunately biome does not support svelte yet. Therefore all packages using biome except one web app that still uses eslint/prettier. I now try to use different LSP settings for the svelte web app.

What I tried:
- using a nested `apps/web/.helix/languages.toml`

I was going through some issues and PRs. It seems a per folder overwrite was possible at some time, but it was removed due to lsp workspace-root implementation, if I understood correctly.

- using glob to filter different `[[language]]` settings in one `languages.toml`

Default:
```toml
[[language]]
name = "typescript"
language-servers = [
  { name = "typescript-language-server", except-features = ["format"] },
  "biome",
]
```

Web app specific:
```toml
[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
file-types = [{ glob = "apps/web/**/*.{ts,mts,cts}" }]

```
This seems to only use the last entry. The whole "Default" settings seem to be  overwritten entirely.

So far I'd say it's not possible to override lsp settings per subfolder other than openening another Helix instance in the nested `/apps/web` folder with a specific nested `languages.toml` file. Am I right or did I overlook somthing?
