### DISCUSSION TITLE
C# OmniSharp LSP

### DISCUSSION THREAD

**Discussion by Eragra3** [helix-editor/helix#13623] [Troubleshooting]
I hate to revive [unanswered discussion](https://github.com/helix-editor/helix/discussions/7385), but I see a lot of people struggling with C# LSP and no good solution for that.

So far I tried adding OmniSharp to `path`, configuring it directly (see below) and playing around with switches and configuration.
```toml
[[language]]
name = "c-sharp"
language-servers = [ "omnisharp" ]

[language-server.omnisharp]
command = "C:/cli/omnisharp/OmniSharp.exe"
args = [ "--languageserver" ]
```

I can't make it work, I only found following logs:
1. `helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream.` with generic `System.InvalidOperationException: Enumeration already finished.` exception on OmniSharp side
2. `helix_lsp·[ERROR]·failed·to·initialize·language·server:·request·0·timed·out`
3. `helix_term::application·[ERROR]·Discarding·publishDiagnostic·notification·sent·by·an·uninitialized·server:·omnisharp`

I run Windows and tried various versions of OmniSharp and dotnet SDKs.

Is there anybody that has working C# LSP with OOTB configuration of Helix?
Are you guys using additional configuration for the LSP?

**Comment by akarel-mb** [comment]
I have omnisharp working with no issues. The only default config override I added was to increase the timeout, since omnisharp can take a while to start up on larger projects.

```toml
# Default LSP Overrides

[language-server.omnisharp]
timeout = 120
```

The couple times I have had issues I just navigated to the solution directory and ran `omnisharp` without any params. A reasonable error was always written to stdout for me, and it was usually related to an omnisharp bug instead of anything else.

My global config is this...
```json
{
  "FormattingOptions": {
    "EnableEditorConfigSupport": true,
    "OrganizeImports": true
  },
  "RoslynExtensionsOptions": {
    "enableImportCompletion": true,
    "enableDecompilationSupport": true
  }
}
```

**Reply by Eragra3** [reply]
Thanks, that works fine on smaller projects.
I wonder if that should be the default timeout in Helix config.

OmniSharp still doesn't work on medium to large projects for me, I even get things like StackOverflow from OmniSharp.
I even increased Timeout to 240s and my machine is rather beefy PC.

I would appreciate if you have any more tips, but I understand this seems to be weird OmniSharp issue, not Helix.

**Reply by akarel-mb** [reply]
Not really sure how to help without a stacktrace from omnisharp. What is the error in the helix logs? Could be a lot of things. Older .NET framework apps won't work at all. Maybe missing VS build tooling or looking in the wrong path for the dotnet sdks depending on how you installed them. Check the output from running the bare `omnisharp` command in the solution directory. It will have an error there. If it doesn't than try increasing the helix timeout config to something ridiculous to see if it works. The larger the project the longer it takes. 🤷

**Comment by ap-fee** [comment]
There's also dotnet's [`roslyn-language-server`](https://github.com/dotnet/roslyn/blob/b0fac0d5945f5a695227e5deea23750545d41fba/src/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/README.md) available as prerelease now. It should be easy to set up:

Install via `dotnet tool install --global roslyn-language-server --prerelease` and set the language server in `languages.toml`:

```toml
[language-server.roslyn-language-server]
command = "roslyn-language-server"
args = [ "--stdio", "--autoLoadProjects" ]

# ...

[[language]]
name = "c-sharp"
language-servers = ["roslyn-language-server"]
```
