### DISCUSSION TITLE
Package manager for plugins/themes?

### DISCUSSION THREAD

**Discussion by corigan01** [helix-editor/helix#13669] [Ideas]
I looked around the previous discussions and issues and couldn't find any references to talk about a package manager to go along with the plugin system. I saw some references to possibly removing some themes from the main repo and thought that maybe a centralized package management option (like Rust's) would be the perfect fit. 

Something similar to _this_ in your `config.toml`:
```toml
[packages]
# could be centralized like crates.io...
my_package = "1.0.0" 

# or just a link to a git repo with some helix specific scheme or toml config?
other_package = {git = "https://github.com/someone/helix-package"} 
```

Personally, my experience with other editors supporting plugins/externals is a fragmented ecosystem. I would love to see helix adopt something that would make adding themes/plugins easy and standardized. This could maybe even ease community pressure with backwards compatibility with version tags like `edition` since you know all packages will have them.

I am sure the direction helix takes is going to be awesome, just wanted to throw this out as an idea if no one has brought it up before. A technical discussion could get me started on a PR if there were genuine interest (I would love to contribute if I could).
