### DISCUSSION TITLE
How to get this grammar working? Grammar doesn't seem to work, but no errors

### DISCUSSION THREAD

**Discussion by bbarker** [helix-editor/helix#13677] [Q&A] [answered]
I've tried adding:

```toml
[[language]]
name = "cobweb"
scope = "source.cobweb" # also tried "source.cob"
file-types = [ "cob", "cobweb" ]
auto-format = true
roots = []
#
[[grammar]]
name = "cobweb"
source = { git = "https://github.com/FabricSoul/tree-sitter-cobweb", rev = "main" }
```

Also, I've tried a few variants to this, but whenever I open a .cob file, I don't seem to have any evidence that tree-sitter is working:

```
$ hx --version
helix 25.01.1 (e7ac2fcd)
```

That seems to be using this version of tree-sitter:
https://github.com/tree-sitter/tree-sitter/tree/v0.22.0

I've also tried opening a file with `:log-open`, but don't see any `cob`-related errors. Rust highlighting works, for instance
