### DISCUSSION TITLE
PIOASM syntax highlighting not working when using  `tree-sitter-pioasm`.

### DISCUSSION THREAD

**Discussion by crabdancing** [helix-editor/helix#13720] [Q&A] [answered]
I'm trying to get syntax highlighting on `.pio` files for hardware RP2040 Programmable Input-Output state machines. I'm not sure if I'm doing something wrong, if there's something wrong with [tree-sitter-pioasm](https://github.com/leo60228/tree-sitter-pioasm), or if there's something wrong with my config.

Here's what I tried in my `languages.toml`:

```toml
[[language]]
name = "pioasm"
scope = "source.pioasm"
file-types = ["pio", "pioasm"]
indent = { tab-width = 4, unit = " " }
comment-tokens = ";"

[[grammar]]
name = "pioasm"
source = { git = "https://github.com/leo60228/tree-sitter-pioasm", rev = "afece58efdb30440bddd151ef1347fa8d6f744a9" }
```

Then I built Helix from source. I saw `tree-sitter-pioasm` get pulled, and later found its `.so` in my runtime dir -- so it's definitely building correctly. 

Here's a basic file that _should_ have syntax highlighting when named e.g. `sm0.pio`:

```asm
.program main
loop:
    in pins 1
    mov osr, isr
    push
    jmp loop
```

My Helix version, if that's relevant:

```
helix 25.01.1 (fe03376a)
```

Relevant links:

https://github.com/leo60228/tree-sitter-pioasm
https://github.com/leo60228/tree-sitter-pioasm/issues/2
