### DISCUSSION TITLE
syntax highliting broken after `hx --grammar fetch && hx --grammar build`

### DISCUSSION THREAD

**Discussion by AQMpolyface** [helix-editor/helix#13797] [Troubleshooting]
everything is in the title. the only difference is that ive put 
```toml
[[grammar]]
name = "crystal"
source = { git = "https://github.com/aqmpolyface/tree-sitter-crystal", rev = "76afc1f53518a2b68b51a5abcde01d268a9cb47c" }
[[language]]
name = "crystal"
file-types = ["cr"]
auto-format = true
language-servers = ["ameba-ls", "crystalline "]
formatter = {command = "crystal", args = ["tool", "format", "-"] }
scope = "source.cr"
roots = ["shard.yml", "shard.lock"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
grammar = "crystal"

```

in my config to add the crystal tree sitter.  hx -v doesnt give any info on this, and hx --health crystal also doesnt give any clues
```
Configured language servers:
  ✓ ameba-ls: /usr/bin/ameba-ls
Configured debug adapter: None
Configured formatter:
  ✓ /usr/bin/crystal
Tree-sitter parser: ✓
Highlight queries: ✘
Textobject queries: ✘
Indent queries: ✘
```
