### DISCUSSION TITLE
Keymap to immediately global search current selection

### DISCUSSION THREAD

**Discussion by sadamczyk** [helix-editor/helix#13842] [Q&A] [answered]
I have the following keymap:
```toml
[keys.normal]
C-f = ["search_selection_detect_word_boundaries", "global_search"]
```

This opens my current selection in the global search, so I don't need to hit `* -> space -> / -> enter`, because I do this searching a ton. I can just hit `C-f -> enter`.

But as you see, I still need to hit enter to confirm the pre-filled "/" register for the search.
Is there any way to not have to hit enter?
When I hit this keybind I immediately want the search to start.

Unfortunately none of these worked: `ret`, `return`, `Return`, `enter`, `Enter`:
```toml
C-f = ["search_selection_detect_word_boundaries", "global_search", "ret"]
```

**Comment by the-mikedavis** [comment, marked as answer]
You can use a macro keybinding for this so it's equivalent to hitting the keys `*<space>/<ret>`:

```toml
[keys.normal]
C-f =  "@*<space>/<ret>"
```
