### DISCUSSION TITLE
Unnecessary Inlay Hints in Svelte.

### DISCUSSION THREAD

**Discussion by shetty-tejas** [helix-editor/helix#13868] [Troubleshooting]
### Summary

When using helix for svelte, there's a lot of unnecessary inlay hints when writing the template. Especially when I write the `{#snippet ...}` syntax:

This is with Inlay Hints turned on:

<img width="1904" alt="Image" src="https://github.com/user-attachments/assets/3ed17392-c2b3-4b50-9940-50177ba2e42c" />

and this is the same template with it off:

<img width="1904" alt="Image" src="https://github.com/user-attachments/assets/13722192-a3f5-485d-9f61-5f033f2aa7b2" />

It works as expected when writing `ts` or `js` code within the `<script>` tags, but breaks as soon as I start writing the template.

<img width="1904" alt="Image" src="https://github.com/user-attachments/assets/e434d015-9ee1-4688-9bad-7cce01e92b89" />

The below code-block has the config.toml and languages.toml currently in use:
```toml
theme = "catppuccin_mocha_transparent"

[editor]
auto-format = false
bufferline = "always"
color-modes = true
cursorcolumn = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
mouse = false
rulers = [150]
true-color = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "file-modification-indicator", "version-control"]
right = ["position", "total-line-numbers"]
mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"
```

```toml
# Bash Configuration
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }

# GoLang Configuration
[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.json.path=stdout", "--show-stats=false", "--issues-exit-code=1"]

[language-server.gopls.config]
gofumpt = true
hints = { assignVariableTypes = true, compositeLiteralFields = true, compositeLiteralTypes = true, constantValues = true, functionTypeParameters = true, rangeVariableTypes = true }

[[language]]
name = "go"
formatter = { command = "goimports" }

# JSON Configuration
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "jsonc"
formatter = { command = 'prettier', args = ["--parser", "jsonc"] }

# Ruby Configuration
[language-server.ruby-lsp]
command = "ruby-lsp"
config = { diagnostics = true, formatting = true, inlayHint = true }

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]

# Frontend Configuration
[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]

[[language]]
name = "svelte"
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-svelte", "--parser", "svelte"] }
language-servers = ["svelteserver", "tailwindcss-ls", "vscode-eslint-language-server"]

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]
```

### Platform

macOS 15.5

### Terminal Emulator

Ghostty 1.1.3

### Installation Method

brew

### Helix Version

helix 25.01.1
