### DISCUSSION TITLE
Distinction between line comments and block/doc comments

### DISCUSSION THREAD

**Discussion by dssgabriel** [helix-editor/helix#1867] [Q&A] [answered]
Hello helix community!
I've looked around the documentation and the repo but I wasn't able to find how to configure `helix` to make a distinction between *single-line comments* and *block/documentation comments*.
This a snippet from my theme configuration (which is correctly loaded):
```toml
"comment.block.documentation" = "light-gray"
"comment.block" = "light-gray"
"comment" = "gray"

[palette]
gray = "#3d3837"
light-gray = "#413c3a"
```
However, when I have two different types of comments in a file, there is no color difference as you can see from these screenshots of C and Rust code:
![screenshot_c](https://user-images.githubusercontent.com/55387403/160178450-c6e40242-d759-43a7-a82a-50469d3d8c52.png)
![screenshot_rust](https://user-images.githubusercontent.com/55387403/160178311-7ee468fa-1d60-474f-afd1-7e995f3ed57d.png)
I've seen that when adding languages to `helix`, it is possible to define *"comment tokens"*. Is it also possible to create "comment block/doc tokens" so that the editor can display them differently depending on the user's configurations?

**Thanks in advance!**
