### DISCUSSION TITLE
is there any way to set change the language for a specific file?

### DISCUSSION THREAD

**Discussion by smason** [helix-editor/helix#1916] [Q&A] [answered]
I couldn't see anything, but it might be nice to have a `:language` or maybe `:set language` command

in my case I was editing a Cython `.cyx` file recently, so I added:

```toml
[[language]]
name = "python"
file-types = ["py", "pyx"]
```

to my `languages.toml` file, which mostly worked.  I got some syntax errors from it, not sure if it was from `pylsp` or the grammar, but this isn't a file type I regularly edit, so didn't look too hard.
