### DISCUSSION TITLE
Python is not supported?

### DISCUSSION THREAD

**Discussion by juniway** [helix-editor/helix#2191] [Q&A]
I try to use helix to edit a python file, but it does not auto-indent for me, also, it does not prompt auto-completion candidates for me. Trying other operations, it says `Language server not active for current buffer`.

<img width="669" alt="CleanShot 2022-04-20 at 20 20 35@2x" src="https://user-images.githubusercontent.com/3980841/164229149-8dd503cf-543c-4506-85b4-ff39bb6a2073.png">

**Comment by juniway** [comment]
worth to mention, I have `/usr/local/bin/pyls` installed on my computer already. According to [this](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#tsserver), I don't think any extra config is needed to make the LSP work.

**Comment by winkee01** [comment]
what's the `hx --heath` result?

**Reply by juniway** [reply]
![image](https://user-images.githubusercontent.com/3980841/164236279-f6b45f92-a92e-4f94-a53c-d5bf2014d69c.png)
I have `pyls` installed, but why?

**Reply by winkee01** [reply]
I am not sure, but maybe try `pip install python-lsp-server`, it's `pylsp`, a fork of `pyls`.

**Reply by the-mikedavis** [reply]
https://github.com/helix-editor/helix/pull/834 `pyls` appears to be unmaintained so the default python LS is now `pylsp`

**Reply by juniway** [reply]
ok, now, `pylsp` is installed. but seems **auto-indent** still not working, `<space>r` to rename a symbol works but produce a delay of about 1-2 seconds, very unpleasant.

![image](https://user-images.githubusercontent.com/3980841/164237976-c95fddec-a41a-4a49-963f-799d41c75f22.png)

**Reply by juniway** [reply]
I have `pyright` and `black` installed on my computer, both should have an active community, they are not supported in helix?

**Reply by the-mikedavis** [reply]
Pyright may work - it's just not the default LSP for python. You can override the config with something like

```toml
# ~/.config/helix/languages.toml`
[[language]]
name = "python"
language-server = { command = "pyright" }
```

Auto-formatting is currently only available through LSP so `black` will not work.

Auto-indent is done through tree-sitter which currently doesn't work well for python. https://github.com/helix-editor/helix/issues/763

**Reply by juniway** [reply]
typing `hx --health` will show that `pyright` is correctly detected and setup, but open a python file and do `<space>r` to rename a symbol, it still tells an error saying `Language Server not active for current buffer`.
<img width="1060" alt="CleanShot 2022-04-20 at 22 13 22@2x" src="https://user-images.githubusercontent.com/3980841/164250449-bdfe4ce8-1450-4b85-b222-9c2c18e60b6b.png">

**Reply by the-mikedavis** [reply]
https://github.com/helix-editor/helix/issues/1898 looks like there are some problems integrating pyright

**Reply by tmke8** [reply]
Pyright works for me on Helix master (but not the 22.03 release) with this config:

```toml
 [[language]]
 name = "python"
 scope = "source.python"
 injection-regex = "python"
 file-types = ["py"]
 shebangs = ["python"]
 roots = ["pyproject.toml", "setup.py", "Poetry.lock"]
 comment-token = "#"
 language-server = { command = "pyright-langserver", args = ["--stdio"] }
 auto-format = false
 indent = { tab-width = 4, unit = "    " }
 config = """
   {
       "python": {}
   }
 """
```

(Maybe you can leave out most of the lines; I wasn't sure how merging with the default config works)
