### DISCUSSION TITLE
How to disable automatic insertion of pairs

### DISCUSSION THREAD

**Discussion by BonfireAtNight** [helix-editor/helix#2383] [Q&A] [answered]
I feel a bit embarrassed to ask this here, but I don't really understand how to disable the auto-pairing. I'm aware that there is a [section](https://docs.helix-editor.com/configuration.html#editorauto-pairs-section) on this in the Documentation, but I cannot quite figure out what it says exactly. I've tried things like `'"' = false` or `'"' = ''`, but these won't work.

Are `true` and `false` really intended as the _keys_ (as is written there)? And why are there no default values mentioned?

**Comment by the-mikedavis** [comment, marked as answer]
The docs are trying to say that you could configure:

```toml
# ~/.config/helix/config.toml
[editor]
auto-pairs = false # completely disable auto-pairs
# or
auto-pairs = true # enable default auto-pairs
```

or you can use a table to configure which pairs should close each other:

```toml
[editor.auto-pairs]
"(" = ")" # use ) to close (
"[" = "]"
# other pairs here ...
```
