### DISCUSSION TITLE
open file relative to current buffer

### DISCUSSION THREAD

**Discussion by smason** [helix-editor/helix#2481] [Q&A] [answered]
is there a way to easily open a file relative to the path of the current buffer?

this is motivated by "goto definition" ending up in a dependency/system directory and then wanting to open a file relative to that rather than the current working directory

**Comment by the-mikedavis** [comment, marked as answer]
There's a PR for it: https://github.com/helix-editor/helix/pull/1352

**Reply by smason** [reply]
thanks, not sure how I didn't notice that when I was searching around!

default binding is <kbd>space</kbd>+<kbd>F</kbd>

quick reminder to help others: <kbd>space</kbd>+<kbd>?</kbd> gives an interface that allows fuzzy searching for bindings

**Reply by gf3** [reply]
This has been closed & superseded by a new mechanism (which is still in draft as of Feb 2024): https://github.com/helix-editor/helix/pull/2412

**Comment by gf3** [comment]
There's a built-in command to open a file picker in the current buffer's directory, but it's not mapped to anything by default (as of Feb 2024). You can enable it with the following configuration:

```toml
[keys.normal."space"]
"o" = "file_picker_in_current_buffer_directory"
```

Personally, I prefer to overwrite the <kbd>Space</kbd> <kbd>F</kbd> shortcut as it's not terribly useful for me:

```toml
[keys.normal."space"]
"F" = "file_picker_in_current_buffer_directory"
```
