### DISCUSSION TITLE
add to dictionary action in ltex-ls language server

### DISCUSSION THREAD

**Discussion by smason** [helix-editor/helix#2492] [Q&A]
Just wondering if the "Add ... to dictionary " code action work for other people?

I've just configured helix to use this language server, and it's flagging some technical words.  I tried using the above action which silently fails.  Setting the log file:

```toml
[[language]]
name = "markdown"
language-server = { command = "ltex-ls", args=["--log-file=/tmp"] }
```

allowed me to see:

```json
{"jsonrpc":"2.0","method":"workspace/executeCommand","params":{"arguments":[{"uri":"file:///home/smason/foo.md","words":{"en-US":["Smalltalk"]}}],"command":"_ltex.addToDictionary"},"id":13}

{"jsonrpc":"2.0","id":13,"result":{"success":false,"errorMessage":"Unknown command \u0027_ltex.addToDictionary\u0027, ignoring"}}
```

which suggests the problem could be in ltex-ls, but thought I should try here first
