### DISCUSSION TITLE
`deno lsp` support

### DISCUSSION THREAD

**Discussion by DrSensor** [helix-editor/helix#2536] [Q&A] [answered]
Hi! 👋
Anyone got it works using `deno lsp`?

In my case, the type checker and autocompletion doesn't works but it still trigger the formatter.
I'm using the master branch via `nix build github:helix-editor/helix`.

**Comment by the-mikedavis** [comment]
If you have `deno` installed, you can configure typescript to use it as the language server with:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "typescript"
language-server = { command = "deno", args = ["lsp"] }
```

Then you can check that everything is configured correctly with `hx --health typescript`. If completion is still not working after that, you can consult [the log](https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file) which shows LSP request/response when in verbose mode.

**Reply by imtheaman** [reply]
Hey Michael,
would you please tell me how can i enable auto-completion and error message?
my config.toml looks like this and have the default languages.toml.
```
theme = "rose_pine"

[editor]
line-number = "absolute"
mouse = false
shell = ["fish"]
auto-completion = true
idle-timeout = 400

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"
```

**Reply by the-mikedavis** [reply]
You should check out the troubleshooting wiki on LSP: https://github.com/helix-editor/helix/wiki/Troubleshooting#lsp-isnt-working

**Reply by imtheaman** [reply]
my highlights.scm is blank in runtime/queries/tsx

**Reply by DrSensor** [reply]
Is there a way to set/send `initializationOptions`?
Based on [here](https://deno.land/manual/language_server/overview#settings) and [this](https://deno.land/manual/getting_started/setup_your_environment#sublime-text) seems like the client need to send `{ "enable": true }` 🤔

**Reply by the-mikedavis** [reply]
> my highlights.scm is blank in runtime/queries/tsx

Is it actually empty or does it just contain

```scm
; inherits: typescript
```

?

> Is there a way to set/send `initializationOptions`?

IIRC you can use the `config` key in `languages.toml`, for example: https://github.com/helix-editor/helix/blob/c429ed660f62e59f0c00115efd03543f3ae3ba8f/languages.toml#L130

**Reply by imtheaman** [reply]
> 

it's empty doesn't contain anything

**Reply by the-mikedavis** [reply]
you can copy the queries from `runtime/queries/tsx/highlights.scm`: https://github.com/helix-editor/helix/blob/master/runtime/queries/tsx/highlights.scm

**Reply by imtheaman** [reply]
Thanks.💟

**Comment by DrSensor** [comment, marked as answer]
Alright it works now!

Here is my `.config/helix/languages.toml`
```toml
[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "^(js|javascript)$"
file-types = ["js", "jsx", "mjs"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
comment-token = "//"
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "javascript" }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "jsx"
scope = "source.jsx"
injection-regex = "jsx"
file-types = ["jsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
comment-token = "//"
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "javascriptreact" }
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescript" }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "^(tsx)$" # |typescript
file-types = ["tsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescriptreact" }
indent = { tab-width = 2, unit = "  " }
```

**Comment by sigmaSd** [comment]
minimal working configuration
```toml
[[language]]
name = "typescript"
file-types = ["ts","js"]
language-server = { command = "deno", args = ["lsp"]}
config = { deno = { enable = true, lint = true } }
```

**Reply by David-Else** [reply]
Lint is true by default now https://deno.com/blog/v1.22#linting-enabled-by-default-in-the-lsp

**Reply by Siilwyn** [reply]
Or:
```toml
[[language]]
name = "javascript"
language-server = { command = "deno", args = ["lsp"] }
config = { enable = true }

[[language]]
name = "typescript"
language-server = { command = "deno", args = ["lsp"] }
config = { enable = true }

```

Not sure what benefits the more verbose version in the wiki gives... :thinking:

**Comment by sigmaSd** [comment]
Note that not all deno lsp commands are supported in particular `go_to_definition` since they require custom deno lsp extensions https://deno.land/manual/language_server/overview

**Reply by David-Else** [reply]
We need https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/denols.lua converting for Helix.

**Reply by Siilwyn** [reply]
Do you by any chance know if this is a decision to not include this in the LSP or could `go_to_definition` be supported by the LSP in the future?

**Reply by David-Else** [reply]
I think the Deno crew need to sort this out, [they seem to be making their lsp better recently](https://github.com/denoland/deno/pull/20111), but it would be best if you go and ask them directly, I don't know what the current status is.

**Comment by jakenvac** [comment]
Has anyone managed to get import_maps working with Deno and Helix? adding the importMap key in the config doesn't seem to make it work. I've tried relative and absolute paths to it.

EDIT: I'll leave this here as it took me a while to figure out that you need to be in a git repo for the LSP to pick up your import_map. I'm assuming other options to scope the workspace would also work.

**Reply by dcompoze** [reply]
It seems to work for me - I have the following configuration:

```toml
[[language]]
name = "typescript"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescript" }
indent = { tab-width = 2, unit = "  " }
```

And added the `importMap` key inside `deno.json`:

```json
{
    "compilerOptions": {},
    "importMap": "import_map.json"
}
```

Though when you place the `deno.json` in a different directory than the import map, the path to the import map needs to be relative from the `deno.json` file to the `import_map.json` file.

With a project layout like this:

```
project
├── deno.json
└── subproject
    ├── import_map.json
    └── src
        └── main.ts
```

The import map path would be:

```json
"importMap": "subproject/import_map.json"
```

And if the `import_map.json` file is at the root (which is normally where it would be): 
```
project
├── deno.json
├── import_map.json
└── src
    └── main.ts
```

The import map path would be:

```json
"importMap": "import_map.json"
```

**Reply by nathansmith11170** [reply]
Sorry to necromance this thread, but it comes up on Google search for deno lsp in Helix and I had issues figuring out the import map.

This is passed to deno lsp in the config, like so:
```
[[language]]
name = "typescript"
roots = ["deno.json"]
language-server = { command = "deno", args = ["lsp"] }
config = { enable = true, importMap = "deno.json" }
```

**Reply by David-Else** [reply]
Would be great to get all info on Deno import map setup in [the wiki](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#deno) :)

**Comment by AumyF** [comment]
I would like Helix to attach typescript-language-server when I editing Node.js projects...  How to achieve it?  Adding a new language like `typescript_deno` may help?

[Neovim's builtin LSP client has ability to switch the servers according to `root_pattern`](https://deno.land/manual@v1.29.2/getting_started/setup_your_environment#neovim-06-using-the-built-in-language-server).

**Reply by AumyF** [reply]
Just for my project configuring using project's `.helix/languages/toml` solved the problem, but not all Deno projects have a .helix directory.

**Reply by jakenvac** [reply]
You can always add the `.helix` directory. That's my preferred way of working on deno with helix.

However, similarly to the link you shared, helix also lets you configure the root for different projects. See [here](https://docs.helix-editor.com/languages.html#language-configuration)

**Reply by jakenvac** [reply]
That said, Helix still doesn't support Deno fully. Go to definition doesn't work as the Deno lsp uses a custom url schema for locating the files.

**Comment by hemedani** [comment]
It's throw error when setup import in `deno.json`
```json
﻿﻿﻿﻿﻿﻿﻿  "imports": {
    "deps": "../../../libs/bc/dbs/deps.ts",
    "share/": "../../../libs/bc/dbs/",
    "utils/": "../../../libs/bc/utils/",
    "interfaces/": "../../../libs/bc/interfaces/"
  }
```
```
relative import path "deps" not prefixed with / or ./ or ../ (import-prefix-missing)
```
![Screen Shot 1402-04-31 at 13 49 42](https://github.com/helix-editor/helix/assets/6236123/0fa8bc5a-80b1-478c-970f-603c62d4ad64)

**Reply by ar37-rs** [reply]
@DrSensor  thank you, this is currently ```languages.toml``` working fine for me on helix version 23.10:
```rust
[[language]]
name = "javascript"
language-id = "javascript"
scope = "source.js"
injection-regex = "^(js|javascript)$"
file-types = ["js", "jsx", "mjs"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"
language-servers = ["deno-lsp"]

[[language]]
name = "jsx"
language-id = "javascriptreact"
scope = "source.jsx"
injection-regex = "jsx"
file-types = ["jsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"
language-servers = ["deno-lsp"]

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
grammar = "typescript"
language-servers = ["deno-lsp"]

[[language]]
name = "tsx"
language-id = "typescriptreact"
scope = "source.tsx"
injection-regex = "^(tsx)$" # |typescript
file-types = ["tsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
grammar = "typescript"
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp", "--unstable"]
config = { enable = true, lint = true, unstable = true }
```

**Comment by jakenvac** [comment]
I've not used deno in a while. Does anyone know if goto-definition on external packages works yet?
iirc it's not a failing of helix, but rather deno using extended features of the lsp.

**Comment by ling0x** [comment]
I've just setup deno-lsp in helix, however, all .tsx file lost all colours:

here is my languages.toml:

```toml
[language-server.deno-lsp]
command = "deno"
args = ["lsp", "--unstable"]

[language-server.deno-lsp.config.deno]
enable = true
unstable = true
lint = true
suggest.imports.hosts = { "https://deno.land" = true }
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes.enabled = true
inlayHints.enumMemberValues.enabled = true

[[language]]
name = "javascript"
language-id = "javascript"
scope = "source.js"
injection-regex = "^(js|javascript)$"
file-types = ["js", "jsx", "mjs"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "package.json", "tsconfig.json"]
comment-token = "//"
language-servers = ["deno-lsp"]
grammar = "javascript"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "jsx"
language-id = "javascriptreact"
scope = "source.jsx"
injection-regex = "jsx"
file-types = ["jsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "package.json", "tsconfig.json"]
comment-token = "//"
language-servers = ["deno-lsp"]
grammar = "javascript"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "package.json", "tsconfig.json"]
comment-token = "//"
language-servers = ["deno-lsp"]
grammar = "typescript"
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "tsx"
language-id = "typescriptreact"
scope = "source.tsx"
injection-regex = "^(tsx)$"                                          
file-types = ["tsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "package.json", "tsconfig.json"]
comment-token = "//"
language-servers = ["deno-lsp"]
grammar = "typescript"
indent = { tab-width = 2, unit = "  " }
auto-format = true
```

**Reply by ling0x** [reply]
Alright, I fixed it by remove the "grammar" lines

**Comment by noahfraiture** [comment]
Hello, since deno 2 came out, is there a new way of doing ?

**Reply by sigmaSd** [reply]
Hi, nope it's still the same (the same as what's in the helix wiki)

**Comment by mahmoud-eltahawy** [comment]
hello,
in solidjs files. deno lsp assumes it is react and gives me the error

Cannot find name 'React'

**Reply by sigmaSd** [reply]
Hi, it's probably not related to helix, you should ask on deno discord server

**Comment by noahfraiture** [comment]
I can't find the information. Do you know how to configure deno lsp to work with svelte files ?

**Comment by mahmoud-eltahawy** [comment]
currently i quit using deno lsp for tsx files

and i just use compiler errors on the terminal

**Comment by aminnairi** [comment]
Here is what worked for me as of today 

```toml
[language-server.deno-language-server]
command = "deno"
args = ["lsp"]
required-root-patterns = ["deno.json", "deno.jsonc"]

[[language]]
name = "typescript"
file-types = ["ts", "tsx"]
language-servers = ["deno-language-server"]

[[language]]
name = "javascript"
file-types = ["js", "jsx"]
language-servers = ["deno-language-server"]
```

Minimal configuration for making Deno work with JavaScript, JSX, TypeScript, TSX files to add to your `~/.config/helix/languages.toml` file.
