### DISCUSSION TITLE
how to enable auto save?

### DISCUSSION THREAD

**Discussion by imtheaman** [helix-editor/helix#2542] [Q&A]
how to enable auto save?
when a file is changed, save it immediately or after some seconds of delay.

**Comment by kirawi** [comment]
This is not yet implemented, but feel free to create an issue for it.

**Comment by joegm** [comment]
Someone in the Matrix chat suggested this as a workaround, essentially saving on escape. So escaping out of insert mode saves, as does normal and select mode:

```toml
[keys.normal]
"esc" = ["collapse_selection", ":w"]

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]

[keys.insert]
"esc" = ["normal_mode", ":w"]
```

This doesn't directly fix your issue but hopefully helps.

**Reply by 7flash** [reply]
Wow love it

**Reply by kirawi** [reply]
Auto-save after delay is possible on 24.07: https://docs.helix-editor.com/editor.html#editorauto-save-section

**Comment by dessalines** [comment]
@kirawi mentioned that you can add this now:

```toml
[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 3000 
```
