### DISCUSSION TITLE
Remap Ctrl+space

### DISCUSSION THREAD

**Discussion by CptPotato** [helix-editor/helix#2574] [Q&A] [answered]
I'm trying to remap <kbd>Ctrl</kbd> <kbd>space</kbd> to open the completion popup, like this:

```toml
[keys.insert]
C-space = "completion"
```

However, this doesn't seem to work. Am I missing anything or is this keybind not possible?
