### DISCUSSION TITLE
How to keymap `find_till_char "\n"`?

### DISCUSSION THREAD

**Discussion by DrSensor** [helix-editor/helix#2706] [Q&A] [answered]
Hi, I'm trying to recreate Vim <kbd>Ctrl</kbd> + <kbd>d</kbd> which in helix normal mode is equivalent to <kbd>t</kbd> -> <kbd>Enter</kbd> -> <kbd>Alt</kbd> + <kbd>d</kbd>.

I try this config but it give me an error
```toml
[keys.normal]
C-d = ["find_till_char \n", "delete_selection_noyank"]
# C-d = ["find_till_char <ret>", "delete_selection_noyank"] # same error
# C-d = ["find_till_char '\n'", "delete_selection_noyank"] # same error
```
```
Bad config: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 24 column 1
Press <ENTER> to continue with default config
```

**Comment by the-mikedavis** [comment, marked as answer]
`extend_to_line_end` behaves roughly the same as <kbd>t</kbd><kbd>Enter</kbd>

```toml
[keys.normal]
C-d = ["extend_to_line_end", "delete_selection_noyank"]
```

In general you can't remap key sequences where a key is used as an argument for a command like <kbd>t</kbd><kbd>Enter</kbd> or <kbd>m</kbd><kbd>a</kbd><kbd>w</kbd> yet. For those we would need #1383
