### DISCUSSION TITLE
"Match Line" Command

### DISCUSSION THREAD

**Discussion by joegm** [helix-editor/helix#2783] [Ideas]
The behaviour of `cc` in vim is very useful, and something less comfortable to replicate in Helix: `X_c`. I always just `XdO` which avoids having to stretch to the `_`. I was trying to come up with a sensible keymap and I landed on:

```toml
[keys.normal]
m = { l = ["extend_to_line_bounds", "trim_selections"] }
```

This lets you change, yank, or replace the contents a line without having to chop of the indentation before it and newline after with `_`:

https://asciinema.org/a/fWCn2NmI1uWhLXqY0tPqFhTaa

I was wondering if people would like this as a default keymap?
