### DISCUSSION TITLE
how to remap command?

### DISCUSSION THREAD

**Discussion by theowenyoung** [helix-editor/helix#3004] [Q&A] [answered]
I know how to remap keymap to command, but how to remap command? For example, I want to remap `qq` to `q!`

**Comment by the-mikedavis** [comment, marked as answer]
Typable commands (ones you input with `:<command>` in normal mode) can be mapped by putting `:` at the front of the command name:

```toml
[keys.normal]
C-q = ":q!"
```

Key sequences can be bound by using TOML sub-tables:

```toml
[keys.normal]
q = { q = ":q!" }
# or more simply
q.q = ":q!"
```

You cannot currently make custom aliases for commands though, so there's no way to map `:qq` to `:q!`
