### DISCUSSION TITLE
File type aliases

### DISCUSSION THREAD

**Discussion by aral** [helix-editor/helix#3109] [Q&A] [answered]
Hi folks,

Is there a way to configure Helix with file type aliases so that, say, files with `.my-custom-extension` are interpreted as, say, JavaScript?

(I’ve been looking through the docs but haven’t been able to see anything but wondering if there’s some undocumented way at the moment – I might also have missed it in the docs.)

## Use case

I want files with the `.page` extension to be seen as JavaScript files. I want to do this without adding a separate language and grammar definition and tree-sitter queries (and thereby basically adding a redundant copy of the information that’s already in the JavaScript definitions).

## Suggested implementation

If there isn‘t a way to do this, here’s my initial (naive) suggested implementation:

In languages.toml (e.g., for NodeKit aliases):

```toml
[[alias]]
name = "nodekit"
file-types = ["page"]
language = "javascript"
```

The result of this would be to effectively extend (concatenate) the `file-types` array of the JavaScript language definition with the entries in the aliases `file-types` array.

Thoughts? :)

**Comment by eulerdisk** [comment]
You can do this already by putting these lines in your `~/.config/helix/languages.toml`:
```
[[language]]
name = "javascript"
file-types = ["js", "jsx", "mjs", "cjs", "page"]
```
(Take a look at the `languages.toml` in Helix repo.)

More info [here](https://docs.helix-editor.com/languages.html).

**Reply by aral** [reply]
@eulerdisk Thanks, that’s a good short-term workaround but it’s an override not an extension. So you have to make sure you keep it updated, say, if the original language itself adds some file types in the future. Also it’s not very maintainable and prone to errors. Aliases would add to the file type mappings instead of replacing them.

In VSCode, for example, you would use a file association mapping: https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language

I also should have made it clearer that my use case here is to eventually submit those aliases for inclusion in Helix to support a framework I’m working on. And this would create a maintainability issue for Helix for the reasons I mention above.

**Comment by kirawi** [comment, marked as answer]
You can do:
```toml
[[language]]
name = "mylang"
grammar = "javascript"
```

**Reply by aral** [reply]
Ah, I’m going to try that out when I’m at my computer @kirawi, thank you :)

I hadn’t realised you can explicitly specify a grammar property when defining a language (I assumed it was based on a naming convention). If that works, it should be all I need. Thanks again :)

**Reply by aral** [reply]
Were you able to get that to work?

The minimum Helix accepts for a language definition includes `scope` and `root` for me. When I tried the following:

```toml
[[language]]
name = "nodekit"
scope = "source.nodekit"
roots = []
file-types = ["page", "get", "post", "delete", "patch"]
language-server = { command = "typescript-language-server", args = ["--stdio"], language-id = "javascript" }
grammar = "javascript"
```

I got:

```
thread 'main' panicked at 'Could not parse queries for language "nodekit". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 0, column: 1, offset: 1, message: "required_parameter", kind: NodeType }', helix-core/src/syntax.rs:379:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(Which leads me to believe that its doesn’t automatically use the tree-sitter queries for JavaScript.

**Reply by aral** [reply]
Mind you, having just written that, I see that the language definition for jsx, for example, is written exactly as you suggest and doesn’t have its own grammar `so` but it _does_ have its own tree-sitter queries in _runtime/queries/jsx_ 🤔

**Reply by aral** [reply]
Aha, and all the query files just have:

```
; inherits: javascript
```

in them. So I’m going to try doing the same :)

**Reply by aral** [reply]
Eureka! That works. Thanks for your help @kirawi, appreciate it :)

For anyone else reading this, here’s the language definition I ended up with:

```toml
[[language]]
name = "nodekit"
scope = "source.nodekit"
injection-regex = "nodekit"
file-types = ["page"]
roots = []
comment-token = "//"
language-server = { command = "typescript-language-server", args = ["--stdio"], language-id = "javascript" }
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"
```

And I simply copied _runtime/queries/jsx_ to _runtime/queries/nodekit_. All the tree-sitter queries files there simply have the following content:

```
; inherits: javascript
```
