### DISCUSSION TITLE
Created transparent theme

### DISCUSSION THREAD

**Discussion by GreasySlug** [helix-editor/helix#3142] [Ideas] [answered]
I created base16_transparent based on base16_default
What do you think about this?

![transparent_theme](https://user-images.githubusercontent.com/106496265/180348788-a3d64702-8f52-4dcb-9a9c-ebfe22b154d4.png)

Currently, I can only check it on windows terminal.

```toml:base16_transparent.toml
"ui.background" = { fg = "white"}
"ui.background.separator" = { fg = "gray" }  
"ui.menu" = { fg = "greay" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.linenr" = { fg = "light-grey" }
"ui.linenr.selected" = { fg = "white",  modifiers = ["bold"] }
"ui.popup" = { fg = "light-gray" }
"ui.window" = { fg = "black" }
"ui.selection" = { fg = "gray", modifiers = ["reversed"] }

"comment" = { fg = "gray", modifiers = ["italic"] }
"ui.statusline" = { fg = "white" }
"ui.statusline.inactive" = { fg = "gray" }
"ui.statusline.normal" = { fg = "blue" , modifiers = ["reversed"]}
"ui.statusline.insert" = { fg = "green" , modifiers = ["reversed"]}
"ui.statusline.select" = { fg = "magenta" , modifiers = ["reversed"]}
"ui.help" = { fg = "light-gray" }
"ui.cursor" = { fg = "light-gray", modifiers = ["reversed", "slow_blink"] }
"ui.cursor.primary" = { fg = "light-gray", modifiers = ["reversed", "slow_blink"] }

"ui.virtual.whitespace" = "gray"
ui.virtual.indent-guide = "light-gray"
"variable" = "light-red"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attributes" = "yellow"
"type" = "light-yellow"
"ui.cursor.match" = { fg = "light-yellow", modifiers = ["underlined"] }
"string"  = "koke-light"
"variable.other.member" = "light-green"
"constant.character.escape" = "light-cyan"
"function" = "light-blue"
"constructor" = "light-blue"
"special" = "light-blue"
"keyword" = "light-magenta"
"label" = "light-magenta"
"namespace" = "light-magenta"

"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"

"diff.plus" = "light-green"
"diff.delta" = "yellow"
"diff.minus" = "light-red"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { fg = "gray" }
"info" = "light-blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "light-red"
```
