### DISCUSSION TITLE
How can I change the tab size for all Dart files?

### DISCUSSION THREAD

**Discussion by eboatwright** [helix-editor/helix#3195] [Q&A] [answered]
I know the "standard" is 2 spaces, but I hate that look and I've always used 4 spaces for everything. I've tried editing the languages.toml file, but that hasn't seemed to work.

Any help appreciated!

**Comment by the-mikedavis** [comment, marked as answer]
You'll want to create a custom `languages.toml` that overrides the indentation settings for dart:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "dart"
indent = { tab-width = 4, unit = "    " }
```
