### DISCUSSION TITLE
Color column?

### DISCUSSION THREAD

**Discussion by distobs** [helix-editor/helix#3687] [Q&A] [answered]
Is there a Helix equivalent to vim's "colorcolumn"? I like to restrict C lines to <80 characters, and a visual representation of the limit column helps a lot.

**Comment by the-mikedavis** [comment, marked as answer]
You can use rulers: https://docs.helix-editor.com/configuration.html#editor-section

```toml
# ~/.config/helix/config.toml
[editor]
rulers = [80]
```
