### DISCUSSION TITLE
How to configure `remove unsed import` for `rust`

### DISCUSSION THREAD

**Discussion by AndyJado** [helix-editor/helix#3847] [Q&A]
[related issued](https://github.com/helix-editor/helix/issues/3250)

**Comment by AndyJado** [comment]
Well I guess I figured it out, it worked.

---

# Helix lsp config:
```toml
config.checkOnSave.overrideCommand = ["python3", "x.py", "check", "--json-output"]

config.rustfmt.overrideCommand = [
          "./build/aarch64-apple-darwin/stage0/bin/rustfmt",
                  "--edition=2021"
]

config.procMacro.enable = true

config.cargo.buildScripts.enable = true

config.cargo.buildScripts.overrideCommand = ["python3", "x.py", "check", "--json-output"]

config.rustc.source = "./Cargo.toml"
```

# vscode config:
```
{
    "rust-analyzer.checkOnSave.overrideCommand": [
        "python3",
        "x.py",
        "check",
        "--json-output"
    ],
    "rust-analyzer.rustfmt.overrideCommand": [
        "./build/$TARGET_TRIPLE/stage0/bin/rustfmt",
        "--edition=2021"
    ],
    "rust-analyzer.procMacro.enable": true,
    "rust-analyzer.cargo.buildScripts.enable": true,
    "rust-analyzer.cargo.buildScripts.overrideCommand": [
        "python3",
        "x.py",
        "check",
        "--json-output"
    ],
    "rust-analyzer.rustc.source": "./Cargo.toml",
}
```
