### DISCUSSION TITLE
How to add PowerShellEditorService support to helix?

### DISCUSSION THREAD

**Discussion by leimath** [helix-editor/helix#3956] [Q&A] [answered]
I tried looking into adding proper command completion for powershell scripts and looks like https://github.com/PowerShell/PowerShellEditorServices is the way to go. Not sure on how to make this work out.

Any steps on how to connect the services together would be appreciated. Thanks!

**Comment by lrottach** [comment, marked as answer]
Hi @leimath 

After several hours I got the PowerShell services up and running.
My setup is a MacBook Pro (Mac OS 12.6) with PowerShell 7.2.6 installed.
I downloaded the PowerShell editor services and extracted it under /usr/local/bin/powershell-es.

My languages.toml looks like this:
```toml
[[language]]
name = "pwsh"
scope = "source.ps1"
roots = [".git"]
file-types = ["ps1"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "pwsh", args = ["-NoLogo", "-NoProfile", "-Command", "/usr/local/bin/powershell-es/PowerShellEditorServices/Start-EditorServices.ps1 -BundledModulesPath /usr/local/bin/powershell-es -SessionDetailsPath /usr/local/bin/powershell-es/powershell_es.sessions.json -LogPath /usr/local/bin/powershell-es/powershell_es.log -FeatureFlags @() -AdditionalModules @() -HostName helix -HostProfileId 0 -HostVersion 1.0.0 -Stdio -LogLevel Normal"] }
```

Now when I edit a script, it looks something like this:
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/50323692/194867668-e5b0dbac-94c2-4920-b573-0723d9649b9d.png">

Hope this helps you
Lukas
