### DISCUSSION TITLE
How to set clangd for c17

### DISCUSSION THREAD

**Discussion by stokhos** [helix-editor/helix#4033] [Q&A] [answered]
Hi,

How can I set clangd standards for helix, I tried `args = [--std=gnu17]`  but this doesn't work.

**Comment by the-mikedavis** [comment, marked as answer]
This should be similar to setting it up for coc-clangd: https://github.com/clangd/coc-clangd/issues/20. It looks like you can specify the standard in the build instructions in `compile_flags.txt` / `compile_commands.json` or you should be able to set it globally through the LSP configuration:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "cpp"
config = { "clangd.fallbackFlags" = [ "-std=c++17" ] }
# ^ I haven't tried this. It might instead be
# config = { clangd.fallbackFlags = [ "-std=c++17" ] }
# or
# config = { fallbackFlags = [ "-std=c++17" ] }
```
