### DISCUSSION TITLE
Solargraph context: `bundle exec`

### DISCUSSION THREAD

**Discussion by williamtstanley** [helix-editor/helix#4034] [Q&A] [answered]
I am trying to get Solargraph up and running for my project but I am stalled at the moment.
It "works" with the default configuration but doesn't load the project config properly. Wrong ruby version and missing gem errors etc.

[helix_default.log](https://github.com/helix-editor/helix/files/9676917/helix_default.log)

Solargraphs documentation recommends running it with `bundle exec solargraph` if that problem occurs.

```toml
[[language]]
name = "ruby"
language-server = { command = "bundle exec solargraph", args = ["stdio"] }
config = { solargraph = { diagnostics = true, formatting = true } }
auto-format = true
```

Updating my toml to the above also doesn't work.
[helix_bundler.log](https://github.com/helix-editor/helix/files/9676932/helix_bundler.log)

I am hoping I just have the config args incorrect. Is there a way to make sure the command is running in the cwd and should the command differ?

**Comment by the-mikedavis** [comment, marked as answer]
The command should be only the name of the binary:

```toml
language-server = { command = "bundle", args = ["exec", "solargraph", "stdio"] }
```

**Reply by williamtstanley** [reply]
Thank you! that solved my issue.

**Comment by mandarvaze** [comment]
@the-mikedavis 
I'm referring to https://github.com/helix-editor/helix/blob/master/languages.toml#L506 - which has a LOT of options. Are those all needed ?
Does the `languages.toml` in `master` need to be updated based on the above ?

@williamtstanley is using `config = { solargraph = { diagnostics = true, formatting = true } }` which is not shown above.
Is `config` needed ?

**Reply by williamtstanley** [reply]
```toml
[[language]]
name = "ruby"
language-server = { command = "bundle", args = ["exec", "solargraph", "stdio"] }
file-types = ["rb", "rake", "rakefile", "irb", "gemfile", "gemspec", "Rakefile", "Gemfile", "rabl", "jbuilder", "jb", "builder"]
config = { solargraph = { diagnostics = true } }
formatter = { command = "prettier", args = ["--parser", "ruby"] }
auto-format = true
```
Is my full setup for ruby. To be honest the `config` line may not be needed as IIRC I added that earlier when trying to get it to work and I do not recall if after updating the command I tested without it.
