### DISCUSSION TITLE
Syntax highlighting for `just` files

### DISCUSSION THREAD

**Discussion by CptPotato** [helix-editor/helix#4049] [Q&A]
I tried adding syntax highlighting for [`just`](https://github.com/casey/just) files but can't seem to get it to work.

I took the tree-sitter queries from [this repository](https://github.com/IndianBoy42/tree-sitter-just) and added a `[[language]]` section to `languages.toml` like this:

```toml
[[language]]
name = "just"
scope = "source.just"
injection-regex = "(just|justfile)"
file-types = ["just"]
roots = []
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
```

`hx --health` reports that highlights and text objects were found for the language. The file type is also correctly detected but I get no syntax highlighting whatsoever.

I'm not very familiar with tree-sitter so maybe I'm missing something?
