### DISCUSSION TITLE
Disabling modes

### DISCUSSION THREAD

**Discussion by raphhawk** [helix-editor/helix#4059] [Q&A] [answered]
Is there a functionality to disable modes in helix, i am used to using Z-z for save quit in vim and i want to achieve the same in helix and i also feel like helix is getting too verbose with all the key binding suggestions.

**Comment by the-mikedavis** [comment]
You can set `editor.auto-info` to false:

```toml
# ~/.config/helix/config.toml
[editor]
auto-info = false
```

https://docs.helix-editor.com/configuration.html#editor-section
