### DISCUSSION TITLE
Equivalent of vim `dk`?

### DISCUSSION THREAD

**Discussion by SOF3** [helix-editor/helix#4190] [Q&A] [answered]
It is very frequent for me to want to delete a few lines together. For example, when editing a TOML file,

```toml
{previous entry}
{blank line}
[editor]
mouse = false {cursor is here}
```

I can delete the whole block with `d2k` in vim. If my cursor is on the blank line above, I could `2xd` in helix, but there doesn't seem to be any option to select a whole line above (or something similar to `V2kd` in vim).

**Comment by Ordoviz** [comment]
`mapd` to delete the paragraph or `vkkxd`.

**Comment by Omnikar** [comment, marked as answer]
> there doesn't seem to be any option to select a whole line above

There is `extend_line_above`, which is `x` but going upwards. It's just that it isn't bound to any key by default. I myself have it bound to `X`
```toml
[keys.normal]
"X" = "extend_line_above"
```
