### DISCUSSION TITLE
Shortcut to add doc comments (e.g. '///' for Rust, and '/** */' for TypeScript)

### DISCUSSION THREAD

**Discussion by d4h0** [helix-editor/helix#4195] [Ideas]
Hi,

It would be great, if there was a shortcut to start a doc comment, similar to how regular comments can be added, currently.

I tried to create a shortcut myself, but that doesn't seem to be possible (or the documentation is missing the required information).

I tried the following:

```toml
C-S-c = ["insert_mode", "/** */", "find_prev_char space"]
C-S-c = ["insert_mode", '''insert-output "echo '/** */'"''', "find_prev_char space"]
```
