### DISCUSSION TITLE
How do I add the following to rust-analyzer in helix?  { "rust-analyzer.diagnostics.disabled": [ "inactive-code" ] }

### DISCUSSION THREAD

**Discussion by boroicamarius** [helix-editor/helix#4314] [Q&A] [answered]

**Comment by the-mikedavis** [comment, marked as answer]
You can use custom [`languages.toml` configuration](https://docs.helix-editor.com/master/languages.html#languages) to add to the configuration passed to rust-analyzer on initialization:

```toml
[[language]]
name = "rust"

[language.config]
diagnostics.disabled = [ "inactive-code" ]
```

**Reply by Baarsgaard** [reply]
After multiple language-servers support was merged: https://github.com/helix-editor/helix/commit/71551d395b4e47804df2d8ecea99e34dbbf16157
(Which hasn't been officially released yet)
```toml
[language-server.rust-analyzer.config]                                                                                                               
diagnostics.disabled = ["inactive-code"]
```
