### DISCUSSION TITLE
Pylsp not using `.flake8` file inside project for error checking.

### DISCUSSION THREAD

**Discussion by hitblast** [helix-editor/helix#4347] [Q&A] [answered]
Hello! I'm new to Helix and I've just set it up for coding in Python. I've been trying to configure flake8 with pylsp for showing me errors within the editor and this is the configuration I've used inside `~/.config/helix/languages.toml`:

```toml
[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
roots = []
comment-token = "#"
language-server = { command = "pylsp" }
# TODO: pyls needs utf-8 offsets
config = { pylsp.plugins.flake8.config = ".flake8" }
indent = { tab-width = 4, unit = "    " }
```

Even though I've set the path for the flake8 configuration to be `.flake8`, Helix still ends up using the default configuration and doesn't really show proper errors. Any thoughts?
