### DISCUSSION TITLE
How to configure Prettier in workspace-like project?

### DISCUSSION THREAD

**Discussion by gyzerok** [helix-editor/helix#4358] [Q&A]
Hello! I am new to `helix` and am excited to try it out for my daily development.

The only blocker I've found so far is `prettier` configuration. While simple setup as written in docs works it does not fit in the way my repository is organized. My repo is sort of a monorepo with various subfolders. Each folder has its' own `prettier` config (because different projects need different plugins installed for it).

Also in practice each subfolder might has its' own prettier version installed, so using one global one won't work.

Is there a way to tell helix to use "local" prettier if installed and to use closest upper prettier config?

**Comment by dimas-cyriaco** [comment]
I'm working in a monorepo (using Nx) and this setup is working for me:

```toml
 [[language]]
name = "typescript"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }


[[language]]
name = "tsx"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--config", ".prettierrc", "--parser", "typescript"] }
```
