### DISCUSSION TITLE
gopls configuration

### DISCUSSION THREAD

**Discussion by mway** [helix-editor/helix#4681] [Q&A]
I'm trying to configure `gopls` similar to how I have it configured in nvim, namely:

```lua
{
  goimports   = true,
  gofumpt     = true,
  staticcheck = true,
  analyses = {
    unusedparams = true,
    unreachable  = true,
  },
}
```

But despite adding the following to `languages.toml`:

```toml
[[language]]
name = "go"
config = { goimports = true, gofumpt = true, staticcheck = true, analyses = { unusedparams = true, unreachable = true } }
```

it seems that the default behavior of gopls is unchanged. Specifically, what I want to do is:

- run goimports on save
- run gofumpt on save
- use gopls analyzers

The latter works out of the box, which is awesome. The former two, however, I personally consider to be baseline functionality. I don't want to use the `%`,`:pipe goimports` strategy because (1) LSP can already handle this and (2) it crashes in some scenarios, such as when I'm trying to do it on a project that uses Bazel.

Any help would be appreciated, or if there's a better way to do it, that'd be great too!

Happy to provide any other info.

**Comment by joetrimble** [comment]
Try passing in something like the following. Check out the example on [this](https://github.com/golang/tools/blob/master/gopls/doc/settings.md) page. If it works just make sure you are prefixing it and you should be able to find the prefixes (formatting, ui., etc) on the settings page.

`[[language]]
   name = "go"
   config = { "formatting.gofumpt" = true, "ui.diagnostic.staticcheck" = true }
`

**Reply by mway** [reply]
Thanks, that's helpful! Unfortunately I'm still not able to get gopls to run goimports on save - do auto-imports work for you?

**Reply by joetrimble** [reply]
Hmm so looking at this closer I get auto imports the first time I use a module. What I am not seeing is auto removal of an import when I get rid of all usage. What I have to do to fix it is space-a and then use the organize imports code action. It won't happen on save though.

**Reply by mway** [reply]
What I've found is that it will auto-import IFF you use autocomplete on an _unimported_ package or qualified type name that it can find (which is great).

I also hadn't noticed the "organize imports" action until now and that seems to work really well, except that (1) I don't know if it's possible to keybind explicitly (vs needing to navigate the menus) and (2) ~it seems that the only way to organize imports is by finding an unimported package reference and then using `space`>`a`. Definitely better than nothing, though.~ this seems to have been user error, I can do this from anywhere now.

I also just found https://github.com/helix-editor/helix/issues/1565, which is pretty much what I'm after, so hopefully that's something that is implemented soon!

**Reply by btvoidx** [reply]
Hey! I am having the same issue and can not get staticcheck to work. I feel like I've tried everything. Does it work for you? If so, can you share your config?

**Reply by iztsv** [reply]
Hello! I have the same issue - cannot enable `goimports` during `:w`

**Reply by yakomisar** [reply]
This works for me, please try
[[language]]
name = "go"
formatter = { command = "goimports" }
config = { "formatting.gofumpt" = true }

But the main problem here - if you would like to use golines, then you need to choose what is more important for you, because you cannot call formatter twice
[[language]]
name = "go"
formatter = { command = "golines" } or this line formatter = { command = "goimports" }
config = { "formatting.gofumpt" = true }

**Reply by miranquil** [reply]
@yakomisar Hey, does this work till now? I've tried your configs and helix returns this:
```
Bad language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`
```

And my helix version is `helix 23.10 (f6021dd0)`

**Reply by yakomisar** [reply]
No it does not

**Comment by jgardona** [comment]
> Hey! I am having the same issue and can not get staticcheck to work. I feel like I've tried everything. Does it work for you? If so, can you share your config?

here reloading helix config after changing languages.toml triggers an error that says config is not a key and doesnt exists

**Reply by karan-savla-deltatre** [reply]
Hi, 
I have a working config with helix 23.10. 

[language-server.gopls]
command = "gopls"
config = { "gofumpt" = true, "local" = "goimports", "semanticTokens" = true, "staticcheck" = true, "verboseOutput" = true, "analyses" = { "fieldalignment" = true, "nilness" = true, unusedparams = true, unusedwrite = true, useany = true }, usePlaceholders = true, completeUnimported = true, hints = { "assignVariableType" = true, "compositeLiteralFields" = true, "compositeLiteralTypes" = true, "constantValues" = true, "functionTypeParameters" = true, "parameterNames" = true, "rangeVariableTypes" = true } }

[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = [ "gopls"] 


Hope it helps

**Reply by fpauser** [reply]
I have no formatter with this config:

```shell
$ hx --health go
Configured language servers:
  ✓ gopls: /home/fpauser/.local/share/mise/installs/go/1.23.0/bin/gopls
Configured debug adapter: dlv
Binary for debug adapter: /home/fpauser/.local/share/mise/installs/go/1.23.0/bin/dlv
Configured formatter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

Helix version:

```shell
$ hx --version
helix 24.7 (079f5442)
```

**Reply by HoangNguyen689** [reply]
me too, can't get the formatter worked.

**Reply by BrownNPC** [reply]
yeah the formatter isnt there 
![image](https://github.com/user-attachments/assets/d0f7433a-0eb9-4370-964d-a7a085db6f59)

**Comment by OldManFroggy** [comment]
try the following in your languages file `languages.toml` in the `.config/helix` folder/directory

```toml
[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
formatter = ["gofmt"]
comment-token = "//"
language-servers = [ "gopls", "golangci-lint-lsp" ]

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]
```

and you should get

```shell
Configured language servers:
  ✓ gopls: /home/oldmanfroggy/go/bin/gopls
  ✓ golangci-lint-langserver: /home/oldmanfroggy/go/bin/golangci-lint-langserver
Configured debug adapter: dlv
Binary for debug adapter: /home/oldmanfroggy/go/bin/dlv
Configured formatter: gofmt
Binary for formatter: /usr/local/go/bin/gofmt
Tree-sitter parser: ✓
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

for static check stuff just change formatter to `gofumpt` and add your config options for it; I do not use this so is not in my config.

yeah, I was late to the party... but the above should solve issues (or at least does for me on Ubnuntu base, and snap version of helix on the edge ;) )

**Comment by vfaberd** [comment]
Leaving it here in case someone else is also looking for that.

I wanted Helix to add missing import on save and put local imports in a separate group from third-party packages.

All I had to do is to add this to my `~/.config/helix/languages.toml`

```
[[language]]
name = "go"
formatter = { command = "goimports", args = ["-local", "mydomain.com"] }
```

**Comment by bbrodriges** [comment]
Hey, has someone being able to enable staticcheck in gopls config on helix 25.01.1 (e7ac2fcd) ? I have tried every possible variation but still no success :(

**Comment by A-caibird** [comment]
now(25.07.17) ,  go formatter command : `go fmt file`, stdout
so:
```
[[language]]
name = "go"
formatter = { command = "gofmt" }
```
like it, just ok

**Comment by burgesQ** [comment]
If you've updated golangci-lint to v2+ (`v2.1.5` here), you should use these parameters instead: 

```
[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--path-mode=abs", "--output.json.path=stdout", "--output.text.path=/dev/null","--show-stats=false", "--issues-exit-code=1"]
```

**Comment by kendfss** [comment]
quite late, but this should work for you

```toml
# ~/.config/helix/languages.toml
[[language]]
name        = "go"
auto-format = true
file-types  = ["go", "kage"]
formatter   = { command = "zsh", args = ["-c", 'gofumpt | goimports -local "github.com/kendfss/$(basename $PWD)"'] }

[language-server.gopls.config]
diagnosticsTrigger          = "Save"
vulncheck                   = "Imports"
gofumpt                     = true
"ui.diagnostic.staticcheck" = true

[language-server.gopls.config.hints]
compositeLiteralTypes = true
```

the key lines are:
- `formatter = ...` which shows how to setup your formatter pipeline. you'll need to setup for your preferred shell
- `"ui.diagnostic.staticcheck" ...`

**Comment by vrrel** [comment]
## Working Go (Golang) Configuration for Helix
After some troubleshooting, here's a working `gopls` configuration that works reliably in both Helix 24.07 and 25.07.1:


### First, make sure you have the required tools installed:

```bash
# Install gopls (Go language server)
go install golang.org/x/tools/gopls@latest

# Install gofumpt (formatter)
go install mvdan.cc/gofumpt@latest

# Install Delve (debugger) - optional but recommended
go install github.com/go-delve/delve/cmd/dlv@latest

# Add Go bin directory to PATH (if not already)
echo 'export PATH="$HOME/go/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
```

```toml
# ~/.config/helix/languages.toml

[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
# diagnosticsTrigger = "Save"
usePlaceholders = true
staticcheck = true
vulncheck = "Imports" # or "All"
gofumpt = true

[language-server.gopls.config.analyses]
unusedfunc = true
unusedparams = true
unreachable = true
unusedvariable = true

[language-server.gopls.config.hints]
compositeLiteralTypes = true

[[language]]
name = "go"
indent = { tab-width = 2, unit = " " }
auto-format = true
language-servers = ["gopls"]
formatter = { command = "gofumpt" }
```

### Verification

After installing dependencies and applying the configuration, run:

`hx --health go`

You should see:

```console
Configured language servers:
  ✓ gopls: /home/vrl/go/bin/gopls
Configured debug adapter:
  ✓ /home/vrl/go/bin/dlv
Configured formatter:
  ✓ /home/vrl/go/bin/gofumpt
Tree-sitter parser: ✓
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

### Notes:

- Tested and working in both Helix 24.07 and 25.07.1
- The structure avoids TOML parsing errors that can occur with nested tables
- Comment out `diagnosticsTrigger` if you prefer on-save diagnostics
- Make sure `$HOME/go/bin` is in your `PATH` environment variable
