### DISCUSSION TITLE
Python Auto-completion Setup

### DISCUSSION THREAD

**Discussion by childishPT** [helix-editor/helix#4689] [Q&A]
Sorry, completely new to this editor, and with the lack of videos on this fairly new text editor, I require some step by step and clear help on how to setup up Python Auto-completion on Mac M1 for Helix text editor. I tried copying from the repo area, but this led to nothing. Also, am I missing a command that I should type to toggle Auto-completion?

Thank you very much, and I look forward to using this text editor and being one of the first few people to get onto this!

**Comment by the-mikedavis** [comment]
If you haven't already, you'll need to install the python language server `pylsp`: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#pylsp

With that installed, auto-complete and other language server driven features like goto-definition should work without any extra configuration or commands.

**Comment by childishPT** [comment]
> If you haven't already, you'll need to install the python language server `pylsp`: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#pylsp
> 
> With that installed, auto-complete and other language server driven features like goto-definition should work without any extra configuration or commands.

Thank you very much, that worked, is there anyway to fix error : W191, indentation contains tab

**Comment by the-mikedavis** [comment]
I'm not too familiar with python but I think it comes from this PEP https://peps.python.org/pep-0008/#tabs-or-spaces

Seems like the language server wants you to use spaces for indentation instead of tabs.

**Comment by childishPT** [comment]
> I'm not too familiar with python but I think it comes from this PEP https://peps.python.org/pep-0008/#tabs-or-spaces
> 
> Seems like the language server wants you to use spaces for indentation instead of tabs.

Is there any way I can turn off the error messages, there are so many (E303, W141, my whole code is just underlined) if so how do I do it, because the tutorial given by the website "https://github.com/python-lsp/python-lsp-server" is not very clear, and I was unable to find a file called pycodestyle in my configs.

**Comment by the-mikedavis** [comment]
Oh hmm, I'm not sure how configurable pylsp is for turning those of or tuning them. As far as I know, there isn't an option within Helix to disable diagnostics.

**Comment by tmke8** [comment]
If possible, I would recommend you use pyright instead of pylsp if you don't care about the linters. Pyright is much better in terms of autocompletion and correctness checks, but it doesn't have any style linting or code formatting (which you seem to not want anyway).

If you have node.js installed, you can install pyright globally with

```
sudo npm install -g pyright@latest
```

But there is also a wrapper package on pypi: https://pypi.org/project/pyright/ which I believe installs a per-project node.js.

Then set up pyright like this:

```toml
 [[language]]
 name = "python"
 scope = "source.python"
 injection-regex = "python"
 file-types = ["py"]
 shebangs = ["python"]
 roots = ["pyproject.toml", "setup.py", "Poetry.lock"]
 comment-token = "#"
 language-server = { command = "pyright-langserver", args = ["--stdio"] }
 auto-format = false
 indent = { tab-width = 4, unit = "    " }
 config = {}
```

You need to specify `config` (even if empty) because of this unresolved issue: #1898 . And you also need to build from master – not the recent release – because of that same issue.
