### DISCUSSION TITLE
tree-sitter ssh client config

### DISCUSSION THREAD

**Discussion by midnightexigent** [helix-editor/helix#4690] [Q&A]
I am looking into adding the [tree-sitter-ssh-client-config](https://github.com/metio/tree-sitter-ssh-client-config) but am having trouble, specifically making helix detect the file (it's the `.ssh/config` file), I have no idea what to put in `file-types` and `root`

```toml
[[language]]
name = "ssh-client-config"
scope = "source.ssh-client-config"
file-types = [] # I tried .ssh/config with no success
roots = []
[[grammar]]
name = "ssh-client-config"
source = { git = "https://github.com/metio/tree-sitter-ssh-client-config.git", rev = "769d7a01a2e5493b4bb5a51096c6bf4be130b024" }
```

**Comment by the-mikedavis** [comment]
This may need a bit of work in the function that chooses a language configuration for a given file type, here: https://github.com/helix-editor/helix/blob/ae19aaf1a65cf761e4669df8f7349cae6aad79e4/helix-core/src/syntax.rs#L475-L491

This would be useful as well for git config where you can highlight `.git/config` as git-config.

You could set `file-types = [ "config" ]` as a temporary workaround but that would highlight all files called `config` or with an extension name of `.config` as ssh-config.

**Comment by midnightexigent** [comment]
hmm, are you aware of any previous discussions on how this part of the config is resolved ? I can't think of a clean way to do this.. 

A "meh" solution would be to `shellexpand` the strings passed to `file-types` so that a user can provide something like 

```toml
name = "ssh-client-config"
file-types = ["~/.ssh/config"] 

name = "git-config"
file-types = ["~/.gitconfig", "${workspace}/.git/config"]
```

With that, we can add an `or_else` in the function `language_config_for_file_name` that matches files by exact path
