### DISCUSSION TITLE
(Question) Setting up custom commands?

### DISCUSSION THREAD

**Discussion by lukepighetti** [helix-editor/helix#4692] [Q&A]
I want to setup custom commands to do Flutter development with `helix`. I'm guessing this will have to wait for https://github.com/helix-editor/helix/issues/998 or https://github.com/helix-editor/helix/issues/122, but I will describe the use case here for tracking.

- Adding `flutter` command line tool commands to command palette, keybindings etc.
- Run `flutter devices`, store a list of devices in editor state, then dispatch run commands on these devices
- After running `flutter run`, it allows pressing keys to dispatch subsequent commands to the device, would be nice to hook these into command pallet entries, or hooks like saving a file triggering `hot reload`

A few more ideas

- It would be nice if we could setup context menus like `space` and `g` menus for these tasks
- some way to indicate connection status and selected device (could be in context menus)
- a quick way to see long running debug output

For reference: here's a `CoC` plugin that achieves most of these items in vim https://github.com/iamcco/coc-flutter

**Comment by tmke8** [comment]
The first item on the list should be possible to do already, but the other two seem to require scripting capabilities.

**Reply by ptrcnull** [reply]
> The first item on the list should be possible to do already

is there a way to actually add custom commands? i wasn't able to find anything in the documentation

**Comment by joegm** [comment]
If by context menus you mean the bottom-right popups which show available follow up keybindings, you can already make these. E.g, to add an item to the space menu:
```toml
[keys.normal]
space = { foo = "bar" }
```
You can also construct your own menus, I have this for example:
```toml
[keys.normal.A-t]
# opening test files
p = ':vs ~/dev/test/python.py'
h = ':vs ~/dev/test/html.html'
r = ':vs ~/dev/test/rust.rs'
m = ':vs ~/dev/test/markdown.md'
```

**Reply by highFreqSurfer** [reply]
> If by context menus you mean the bottom-right popups which show available follow up keybindings, you can already make these. E.g, to add an item to the space menu:
> 
> ```toml
> [keys.normal]
> space = { foo = "bar" }
> ```
> 
> You can also construct your own menus, I have this for example:
> 
> ```toml
> [keys.normal.A-t]
> # opening test files
> p = ':vs ~/dev/test/python.py'
> h = ':vs ~/dev/test/html.html'
> r = ':vs ~/dev/test/rust.rs'
> m = ':vs ~/dev/test/markdown.md'
> ```

How to get selection in “bar” as the command parameter in example 1 
```toml
[keys.normal]
space = { foo = "bar" }
```

**Comment by diktomat** [comment]
Support for adding custom commands for command mode (I think that's what op wants) is possible even before having a plugin system for having shortcuts one doesn't want to add as keybinds. Later these could be enhanced for calling API or plugin functions. I have something like this in mind:

```toml
# config.toml
[commands]
"ToggleMyGreatPlugin" = "myPlugin.toggle()"

# maybe better in languages.toml
[commands.rust]
"Test" = ":sh cargo test"
"Lint" = ":sh cargo clippy"
[commands.go]
"Test" = ":sh go test"
```

**Reply by ilyagr** [reply]
I might prefer something closer to git aliases. E.g., you would do:

```toml
[aliases]
test = "sh cargo test --color=none"
```

Thes, you should be able to do `:test`, `:test --workspace`, etc.

**Update:** I guess this is now discussed in https://github.com/helix-editor/helix/issues/4423
