### DISCUSSION TITLE
Example for integrating eslint/prettier

### DISCUSSION THREAD

**Discussion by mkastner** [helix-editor/helix#4903] [Q&A]
I'd like to integrate eslint/prettier support.

I've tried this in languages.toml

```
[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
```

and also this

```
[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "javascript"] }
```

but nothing happens. And

```
hx --health
```

doesn't show any errors.

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration#prettier

There isn't a `javascript` parser for prettier, only `typescript`, but the typescript one works for javascript.

For further debugging you can look at the log file https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file and see if there are any errors that pop up when you save the file.

**Reply by Proful** [reply]
@the-mikedavis does it work with tsx file (Typescript + React + JSX)?

I'm having trouble getting it to work.

**Reply by the-mikedavis** [reply]
TSX is a separate filetype:

```toml
[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
```

**Reply by Proful** [reply]
Tried above, not working.

Below worked fine
```toml
[[language]]
name = "tsx"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx" ] }
auto-format = true
```
