### DISCUSSION TITLE
How should I use numeric prefixes in `config.toml`

### DISCUSSION THREAD

**Discussion by geometryolife** [helix-editor/helix#4919] [Q&A] [answered]
In Vim. I use the configuration below to move up/down quickly:

```vim
noremap K 5k
noremap J 5j
```

But I don't know how to set up in Helix configuration.

**Comment by the-mikedavis** [comment, marked as answer]
This will be possible with macro keybinding #1383:

```toml
[keys.normal]
K = "@5k"
J = "@5j"
```

Until then it is also possible to accomplish this by repeating the commands in config:

```toml
[keys.normal]
K = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
J = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
```
