### DISCUSSION TITLE
Syntax highlighting (Crystal)

### DISCUSSION THREAD

**Discussion by Jomy10** [helix-editor/helix#4945] [General] [answered]
I'm currently trying to add support for Crystal to helix.

In the Helix repo I cloned:
I've added the following to `language.toml`:
```toml
[[language]]
name = "crystal"
scope = "source.cr"
file-types = ["cr"]
roots = ["shard.yml", "shard.lock"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "crystal"
source = { git = "https://github.com/will/tree-sitter-crystal", rev = "15597b307b18028b04d288561f9c29794621562b" }
```

And added a file `runtime/queries/crystal/highlights.scm` which currently only holds:
```scm
[
  "def"
  "end"
  "if"
  "else"
  "while"
] @keyword
```

I then ran `cargo install --path helix-term`.

I then opened a file ending in `.cr`. There's no syntax highlighting for the keywords, but using `Ctrl + C` uses the correct comment token.
