### DISCUSSION TITLE
Absolutely nonsensical keymap error

### DISCUSSION THREAD

**Discussion by ghost** [helix-editor/helix#5029] [General] [answered]
My `config.toml` is as follows:
```toml
theme = "onelight"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"left" = "no_op"
"right" = "no_op"
"up" = "no_op"
"down" = "no_op"

j = "move_char_left"
k = "move_char_down"
l = "move_char_up"
";" = "move_char_right"
h = "collapse_selection"

[keys.insert]
"tab" = "normal_mode"
```

When I try to run Helix I get `Bad config: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 24 column 1`. Line 24 column 1 is the `[` of `[keys.insert]`. DDG turned up some `Bad config` errors but none of the causes apply to this case. I am completely lost.
