### DISCUSSION TITLE
How to setup Rust development on NixOS?

### DISCUSSION THREAD

**Discussion by flosse** [helix-editor/helix#5326] [Q&A] [answered]
I installed helix with `nix-env -iA nixos.helix` and `nix-env -iA nixos.rust-analyzer` and I added this to `languages.toml`:

```toml
[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" }
```

But nothing happens.

`hx --health`:

![Bildschirmfoto vom 2022-12-28 14-31-04](https://user-images.githubusercontent.com/276043/209819934-3dd12183-c4fb-4014-a47c-08929ac12333.png)
