### DISCUSSION TITLE
How to accept language server suggestions?

### DISCUSSION THREAD

**Discussion by ghost** [helix-editor/helix#5389] [Q&A] [answered]
How can i accept "fix available" suggestions by the language server?

**Comment by the-mikedavis** [comment, marked as answer]
These might be available as code-actions using `<space>a`

**Reply by ghost** [reply]
Oh thanks! Is it possible to map this to a more accessible key?

**Reply by the-mikedavis** [reply]
You can re-map the `code_action` command:

```toml
# ~/.config/helix/config.toml
[keys.normal]
A = "code_action"
```

For future reference: you can look up command names, descriptions and keybinds within helix with the command palette `<space>?`
