### DISCUSSION TITLE
Signature Help Hides Autocompletions

### DISCUSSION THREAD

**Discussion by AlexNomadrg** [helix-editor/helix#5477] [Q&A] [answered]
When signature help shows up I can't see autocomplete suggestions

![image](https://user-images.githubusercontent.com/58301160/211430428-9ff78503-f821-4ab0-ac48-a28afff1136f.png)

my config
```toml
theme = "nord"

[editor]
bufferline = "multiple"
cursorline = false
color-modes = true
idle-timeout = 0

[editor.indent-guides]
render = true
character = "▏"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
"S-tab" = ":buffer-previous"
space = {x = ":buffer-close"}

[keys.insert]

[keys.select]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

```
