### DISCUSSION TITLE
Curly underlines do not work

### DISCUSSION THREAD

**Discussion by AlexNomadrg** [helix-editor/helix#5517] [Q&A] [answered]
I have helix 22.12 (c988bd96) and kitty 0.26.5 installed on Arch Linux. For some reason curly underlines do not work (I see just regular underlines).

![image](https://user-images.githubusercontent.com/58301160/212168955-d2aa3f36-e38f-4abe-99ca-7974b6104d6c.png)

My Helix config (The issue persists even on default)
```toml
theme = "nord"

[editor]
bufferline = "multiple"
cursorline = false
color-modes = true
mouse = false
idle-timeout = 0

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
auto-signature-help = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
"S-tab" = ":buffer-previous"
space = {x = ":buffer-close"}

[keys.insert]
"C-s" = "signature_help"
"C-space" = "completion"

[keys.select]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
```

My Kitty config (Again, the issue persists even on default)
```conf
include ./nord.conf

kitty +kitten icat image.jpeg
cursor_shape block
font_family JetBrains Mono
font_size 10
window_margin_width 3
background_opacity 0.85
```

My Kitty theme
```
# Nord Colorscheme for Kitty
# Based on:
# - https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192
# - https://github.com/arcticicestudio/nord-hyper

foreground            #D8DEE9
background            #2E3440
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #81A1C1

# black
color0   #3B4252
color8   #4C566A

# red
color1   #BF616A
color9   #BF616A

# green
color2   #A3BE8C
color10  #A3BE8C

# yellow
color3   #EBCB8B
color11  #EBCB8B

# blue
color4  #81A1C1
color12 #81A1C1

# magenta
color5   #B48EAD
color13  #B48EAD

# cyan
color6   #88C0D0
color14  #8FBCBB

# white
color7   #E5E9F0
color15  #ECEFF4
```
