### DISCUSSION TITLE
How to change hjkl to knei/neio (colemak-dh)

### DISCUSSION THREAD

**Discussion by ghost** [helix-editor/helix#5620] [Q&A]
Hi! I'm new to modal editors and helix, just getting started with shortcuts. Most of them are manageable but hjkl just isn't reasonable for me. Is there any way to remap those keys in a nondestructive, futureproof way that won't break later?

I found something similar to what I'm looking for but it seems a bit hacky
https://github.com/helix-editor/helix/issues/2396

**Comment by kirawi** [comment]
https://docs.helix-editor.com/remapping.html
https://github.com/helix-editor/helix/pull/5046

**Reply by CptPotato** [reply]
There's also some discussion here that might be helpful starting point: https://github.com/helix-editor/helix/issues/5520#issuecomment-1386428351

**Reply by faldor20** [reply]
This is my current colemak-dh setup:
```toml
[keys.normal]
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"

h="insert_mode"
H="insert_at_line_start"

l="open_below"
L="open_above"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"

[keys.normal.g]
n="goto_line_start"
o="goto_line_end"

[keys.normal.space.w]
n="jump_view_left"
e="jump_view_down"
i="jump_view_up"
o="jump_view_right"

[keys.normal.C-w]
n="jump_view_left"
e="jump_view_down"
E="join_selections"
"A-E"="join_selections_space"

i="jump_view_up"
I="keep_selections"
"A-I"="remove_selections"

o="jump_view_right"

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode

[keys.select]
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"

h="insert_mode"
H="insert_at_line_start"

l="open_below"
L="open_above"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"

[keys.normal.z]
e="scroll_down"
i="scroll_up"

[keys.normal.Z]
e="scroll_down"
i="scroll_up"

```

**Reply by robrecord** [reply]
There was an error in C-w, now fixed I think:
Some bindings from normal had been pasted incorrectly.

```toml
[keys.normal]
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"

h="insert_mode"
H="insert_at_line_start"

l="open_below"
L="open_above"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"

E="join_selections"
"A-E"="join_selections_space"

I="keep_selections"
"A-I"="remove_selections"

[keys.normal.g]
n="goto_line_start"
o="goto_line_end"

e="move_line_down"
i="move_line_up"

[keys.normal.space.w]
n="jump_view_left"
e="jump_view_down"
i="jump_view_up"
o="jump_view_right"

[keys.normal.C-w]
n="jump_view_left"
e="jump_view_down"
i="jump_view_up"
o="jump_view_right"

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode

[keys.select]
n="move_char_left"
e="move_line_down"
i="move_line_up"
o="move_char_right"

h="insert_mode"
H="insert_at_line_start"

l="open_below"
L="open_above"

k="move_next_word_end"
K="move_next_long_word_end"

j="search_next"
J="search_prev"

E="join_selections"
"A-E"="join_selections_space"

I="keep_selections"
"A-I"="remove_selections"

[keys.normal.z]
e="scroll_down"
i="scroll_up"

[keys.normal.Z]
e="scroll_down"
i="scroll_up"
```
