### DISCUSSION TITLE
How to enable `isort` for Python?

### DISCUSSION THREAD

**Discussion by aspizu** [helix-editor/helix#5637] [Q&A]
isort is a formatter for import statements

**Comment by Ordoviz** [comment]
Installing [pyls-isort](https://github.com/paradoxxxzero/pyls-isort) *should* work, but I didn't test.

**Reply by aspizu** [reply]
im not using pylsp, im using pyright

**Reply by kirawi** [reply]
pyright doesn't support isort
You can, however, override formatting via an external formatter: https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration

**Reply by aspizu** [reply]
i alrady have setup black
how to add another formatter?

**Reply by gabydd** [reply]
You could make a script that calls both black and isort and

**Reply by kirawi** [reply]
https://pycqa.github.io/isort/docs/configuration/black_compatibility.html

**Comment by CobaltCause** [comment]
If you use `pyright` and want to use `black` and `isort` together, I found that this works well:

```toml
[[language]]
name = "python"
auto-format = true
formatter = { command = "sh", args = ["-c", "black --quiet - | isort -"]}
```

Edit: here's one that also works with `ruff` and will only run commands that are actually available:

```toml
[[language]]
name = "python"
auto-format = true

[language.formatter]
command = "bash"
args = [
    "-c",
    """
    set -eou pipefail

    COMMAND="cat"

    if command -v black &> /dev/null; then
        COMMAND+=" | black --quiet -"
    fi

    if command -v isort &> /dev/null; then
        COMMAND+=" | isort -"
    fi

    if command -v ruff &> /dev/null; then
        COMMAND+=" | ruff check --select I --fix -"
    fi

    echo "$COMMAND" >&2

    eval "$COMMAND"
    """,
]
```

**Reply by Rhylan2333** [reply]
Here is my configuration with `ruff` and `isort` working😄:
```toml
[[language]]
name = "python"
# …
formatter = { command = "zsh", args = ["-c", """
  ruff format --stdin-filename python | isort -d -
  """] }
```
