### DISCUSSION TITLE
How to auto-format Latex with a prettier plugin?

### DISCUSSION THREAD

**Discussion by trgsv** [helix-editor/helix#5690] [General] [answered]
I have installed prettier and this plugin: https://github.com/siefkenj/prettier-plugin-latex
If I run `prettier main.tex --write` in the terminal, everything works and prettier correctly formats my `.tex` file.

How can I configure `languages.toml` so that it automatically works on save.

This doesn't work:

```
[[language]]
name = "latex"
formatter = { command = 'prettier' }
auto-format = true
indent = { tab-width = 4, unit = "\t" }
config = { texlab = { build = { onSave = true, forwardSearchAfter = true } } }
```

**Comment by the-mikedavis** [comment]
Prettier needs to know which parser to use: the file is passed through prettier on stdin so it doesn't know the filename. This configuration might work using a similar trick as TSX: https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration#prettier

```toml
[[language]]
name = "latex"
formatter = { command = 'prettier', args = ["--stdin-filename", "file.tex"] }
auto-format = true
```
