### DISCUSSION TITLE
unable to setup "yaml-language-server" configuration on helix

### DISCUSSION THREAD

**Discussion by ghost** [helix-editor/helix#5704] [Q&A] [answered]
I'd like to Enable Kubernetes on YAML via [yaml-language-server](https://github.com/redhat-developer/yaml-language-server).

However It's tricky (for me that I'm new to TOML Languages :cry: ) to add configuration on `languages.toml`, how can I add json configuration to enable this feature?

for example

```json
yaml.schemas: {
    "kubernetes": ["*.yaml"]
}
```

Thanks.

**Comment by David-Else** [comment]
I would also love to know the answer to this, I have tried the following to add formatting and it does not work:
```
[[language]]
name = "yaml"

# [language.config]
# yaml = { format.enable = true }

# OR

# config = { yaml.format.enable = true} 
```
There are many settings: https://github.com/redhat-developer/yaml-language-server#language-server-settings

**Comment by ghost** [comment, marked as answer]
![2023-01-27-233659_screenshot](https://user-images.githubusercontent.com/108667785/215112891-4619bed7-9413-4ff4-8698-2cc3cf614941.png)

Ah! I've found a solution from "nvim-lspconfig" Repository's [Issue](https://github.com/neovim/nvim-lspconfig/issues/1207)!

Here is my configuration to Enable Kubernetes from YAML.

```toml
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
config = { yaml = { schemas = { kubernetes = "/*.yaml" }, format = { enable = true } } }
```

But, when I type **`:format`** command on helix. It doesn't formatted. and on log (a.k.a `.cache/helix/helix.log`), helix got a malformed notification from LSP Server.

```
2023-01-27T23:48:26.086 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2023-01-27T23:48:26.086 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
```

Anyway, It worked!

**Comment by robrecord** [comment]
config has been deprecated it would seem - how do we configure this now?

**Comment by nilsherzig** [comment]
this works for me (current master branch) 

```config
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = [ "yaml-language-server" ]

[language-server.yaml-language-server]
config = { yaml = { schemas = { kubernetes = "/*.y{a,}ml" }, format = { enable = true } } }
```

**Reply by nikaro** [reply]
Does the formatter also work?

**Comment by David-Else** [comment]
Just adding:
```yml
[language-server.yaml-language-server.config]
yaml = {  format = { enable = true } }
```
Does not seem to work as far as I can tell, I add a bunch of random spaces in the document and `:format` and nothing happens, maybe I misunderstand `yaml` formatting as I don't use it for much.

It would be great to get it working and add it to the default config.

**Comment by nilsherzig** [comment]
This works for me 
```toml
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = [ "yaml-language-server" ]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
```

@David-Else @nikaro

**Reply by nilsherzig** [reply]
[import * as prettier from 'prettier';](https://github.com/redhat-developer/yaml-language-server/blob/3a74bdc22a1ae8a752e89cbf32616eacae163cea/src/languageservice/services/yamlFormatter.ts#L10)

**Reply by nilsherzig** [reply]
```toml 
[language-server.yaml-language-server]
config = {  yaml = {  schemas = { kubernetes = "*.yaml", "http://json.schemastore.org/github-workflow" = ".github/workflows/*", "http://json.schemastore.org/github-action" = ".github/action.{yml,yaml}", "https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json" = "azure-pipelines.yml", "http://json.schemastore.org/ansible-stable-2.9" = "roles/tasks/*.{yml,yaml}", "http://json.schemastore.org/prettierrc" = ".prettierrc.{yml,yaml}", "http://json.schemastore.org/kustomization" = "kustomization.{yml,yaml}", "http://json.schemastore.org/ansible-playbook" = "*play*.{yml,yaml}", "http://json.schemastore.org/chart" = "Chart.{yml,yaml}", "https://json.schemastore.org/dependabot-v2" = ".github/dependabot.{yml,yaml}", "https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json" = "*gitlab-ci*.{yml,yaml}", "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json" = "*api*.{yml,yaml}", "https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json" = "*docker-compose*.{yml,yaml}", "https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json" = "*flow*.{yml,yaml}" }, format = {  enable = false  } } } 
```

Maybe we can compile an entire list of these :) 
https://www.schemastore.org/json/
