### DISCUSSION TITLE
auto-format not running on write

### DISCUSSION THREAD

**Discussion by nemoos0** [helix-editor/helix#5735] [Q&A]
### Summary

The command `:format` works fine but even if `editor.auto-format` is set to `true` the file is not formatted on `:write`.
Am I missing something?

### Reproduction Steps

Set `editor.auto-format = true` (it should be the default).

Run this to install the python lsp and all its extensions: `pip install "python-lsp-server[all]"`

Copy/paste this code in a pyton file and open it
```py
def f(x):
    return x



def g(y):
    return y
```

A warning should appear: `E303 too many blank lines`.

Running `:write` does not format the file, but running `:format` will.

### Helix log

Nothing was written in the log file

### Platform

Linux

### Terminal Emulator

wezterm 20221119-145034-49b9839f

### Helix Version

helix 22.12

**Comment by the-mikedavis** [comment]
`auto-format` is not enabled by default for python in the language configuration block: https://github.com/helix-editor/helix/blob/482cc22fecc109773882d3e0fd6251c33862e89e/languages.toml#L472-L482

You can set this in your config to enable formatting through the language server on save:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "python"
auto-format = true
```

**Reply by Mofiqul** [reply]
I am having the same issue with typescript

**Reply by the-mikedavis** [reply]
Typescript also has `auto-format` disabled by default. You can try:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "typescript"
auto-format = true
```

You could also configure prettier as an external formatter: https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration#prettier

**Reply by askeladd123** [reply]
Shouldn't `editor.auto-format = true` override the defaults for every language?

**Reply by andreaskrath** [reply]
@askeladd123 you can find the reasoning [here](https://github.com/helix-editor/helix/discussions/9043#discussioncomment-7811497).

**Comment by statusunknown418** [comment]
having the same issue, even after configuring it with prettier, doing `:w` doesn't format the file (`.tsx`)
``` toml
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript", "--printWidith", "100"] }
auto-format = true
```

**Reply by David-Else** [reply]
Did you look at the WIKI recently? There is a new section added reg `.tsx`, does it work for you OK? https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration#prettier

**Reply by statusunknown418** [reply]
it works!!, however I don't know why it's extremely slow, vscode is able format the same file 10x faster 😢

**Comment by peteringram0** [comment]
Does anyone have a list of LSP that have auto-format as disabled by default at all?

**Reply by tennox** [reply]
You can check here:
https://github.com/helix-editor/helix/blob/master/languages.toml

**Comment by n8henrie** [comment]
This seems very confusing to me.

The docs say that `auto-format` defaults to `true`: https://docs.helix-editor.com/configuration.html?highlight=auto-format#editor-section

The default languages.toml does **not** override this default: (in this case for python): https://github.com/helix-editor/helix/blob/e76020ddb93eeb051de606c24f92189c3fc55547/languages.toml#L807

The editor tells me that auto-format is enabled:

```
:get-option auto-format   
true
```

And yet `:w` doesn't format my python file unless I manually put `auto-format = true` into my Python section of my `languages.toml`.

**Reply by Lisible** [reply]
Got bitten by the same issue today. I agree that the documentation is confusing about it.

**Comment by fraunos** [comment]
IMO no language should have auto-format by default. If someone adds auto-format = true to their config, it should work for all languages straight away, and then you can override it in language.toml.

**Comment by askeladd123** [comment]
Why was this issue closed? I can't see how this is not a bug.

---

On *helix 24.7* I enabled format on write in *config.toml*: 
```toml
[editor]
auto-format = true
``` 

... but my python code will only format with the `:fmt` command.

I enable format-on-write to python specifically in *languages.toml* by adding the line:
```toml
[[language]]
name = "python"
auto-format = true
```

I do `:config-reload` and `:w` and the code is formatted. It seems that global `auto-format = true` is ignored by python. You find the same problems in other languages as well [as mentioned above](https://github.com/helix-editor/helix/discussions/5735#discussioncomment-5066534), but languages like rust seem to work as expected.
