### DISCUSSION TITLE
Highlighted code get wrong indentation but none highlighted code is indented right.

### DISCUSSION THREAD

**Discussion by H4ckint0sh** [helix-editor/helix#5757] [Q&A]
### Summary

We have a 4 spaces indentation setup in our project. As seen in picture below when code in not highlighted its being rendered wright but when its highlighted it is being rendered with 2 spaces only.

<img width="1538" alt="Screenshot 2023-01-31 at 10 17 36 PM" src="https://user-images.githubusercontent.com/44159647/215885941-714dd5cf-e213-4431-832a-a4907ac195d3.png">

### Reproduction Steps

 

I tried this:

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

Kitty 26.5

### Helix Version

22.12 (96ff64ab)

**Comment by CptPotato** [comment]
> ### Summary
> 
> Self explanatory.

Please provide more information. The title is not self explanatory at all.

**Comment by pascalkuthe** [comment]
This is not an actual bug but intentional. Your code is probably indented with tabs rather than spaces. Helix allows configuring the amounts of spaces used to render a tab per language. Without highlight usually means that no language config was found for a file which means that tabwidth default to 4 but for json the `tab-width` is set to `2` on purpose.

If you are unahppy with this default you can change it by adding the following to your languages.toml:
``` toml
[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" } # by default helix inserts two spaces when pressing tab in json this changes the setting to insert a tab instead and render a tab with a width of 4 instead of 2. 
```

**Reply by H4ckint0sh** [reply]
https://user-images.githubusercontent.com/44159647/215892495-28d11467-3cbf-4b1a-be8d-8ed71ba9b78f.mp4

**Reply by CptPotato** [reply]
I think this clarifies it, thanks.

It looks like the preview uses the default indent and only switches to the language specific one when the document was highlighted after the timeout.

**Comment by H4ckint0sh** [comment]
@pascalkuthe Problem is that I already have that in my language.toml and its happening regardless of that.

**Reply by CptPotato** [reply]
In your screenshot, the open file is a json file wheras the file in the picker is `.hbs` (handlebars I think).

Did you add a `[[language]]` section for the `.hbs` file format in your language config? As far as I know it's not included by default.

If not, you can add one like this for example:

```toml
[[language]]
name = "handlebars"
scope = "source.handlebars"
injection-regex = "(handlebars|hbs)"
file-types = ["hbs"]
roots = []
indent = { tab-width = 2, unit = "  " }
```
