### DISCUSSION TITLE
how to move current line up or down

### DISCUSSION THREAD

**Discussion by setop** [helix-editor/helix#5764] [Q&A] [answered]
I have that: 

```
line a
line c
line b
```

I want to put cursor on "line b" (resp. "line c") and have a shortcut to move it up (resp. down). To obtain

```
line a
line b
line c
```

[Some editor](https://cudatext.github.io/) map it to `alt+up` and `alt+down`

**Comment by CptPotato** [comment]
I'm not aware of a way to move the current line in the way you've described.

Another way to approach this is deleting the whole line and inserting it somewhere else. In your example you can do this by moving your cursor somewhere on `line c` and performing `xdp` (effectively swapping the current line with the next).

Edit: Moving the line up would be `xdkP` (or `xdkkp`)

**Reply by CptPotato** [reply]
Here's how you can map this to <kbd>Alt</kbd><kbd>j</kbd> and <kbd>Alt</kbd><kbd>k</kbd> in your `config.toml`:

```toml
[keys.normal]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
```

Note that this will overwrite what you have currently yanked.

(feels pretty convenient to me to be honest :eyes:)

**Reply by goyalyashpal** [reply]
> Note that this will overwrite what you have currently yanked.

ohw that's sad... can't some additonal temp buffer/register be used to avoid that?

**Reply by CptPotato** [reply]
You can switch to a different register manually. But I'm not aware of a way to do this using a keybind.

**Comment by maxsz** [comment, marked as answer]
I have this in my config:

```
[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
```

works like in other editors 👍

**Reply by goosy** [reply]
But there will be a problem when moving down to the last line if the last line is a non-blank line

**Reply by vwkd** [reply]
Somehow this adds a newline to the end of the file if there isn't one already, even if moving lines around just in the middle of the file.

**Reply by aral** [reply]
Very nice, thank you.

PS. I altered the keybinding for my needs, in case it makes sense for anyone else, I’m using shift-up and shift-down (semantic, innit?) ;)

```
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
```

**Reply by servufi** [reply]
```
[keys.normal]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "select_mode",
  "goto_line_start",
  "normal_mode",
] # Move line(s) down
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "flip_selections",
] # Move line(s) up
```
Keeps cursor at start of line too if there is ever longer lines.. I wonder if there is way to move line in insert mode and keep cursor pos?

**Comment by goyalyashpal** [comment]
One more way to do this - though, a _very_ different one can be to 
1. select all the lines from source (the line where it's originally at) 
and destination (where the line has to go) 
the terminals (source line, and destination line) both included in selection, 
2. `Alt-s` : break the selection at new line
3. `Alt-(` or `Alt-)` : "rotate" contents of the selection 
4. [deselect] `;` (collapse selection) and close multicursor `,` (keep primary selection only) 
**Addend:** [#5912 (comment)](https://github.com/helix-editor/helix/discussions/5912#discussioncomment-4945138) by @ brixy mentions `esc`

Tips:
- [selection collapse, and de-multicursor][deselect] (in step 4) can be done in either order
- rotate selection contents _in opposite direction_ (i.e. rotate down if u've to move up)
this will move the line to its destination in just 1 rotation, rather than moving/rotating up up up again and again...

This last tip above makes it _extremely_ efficient method <code>[O(1)]</code> for moving in long spans, and doesn't interfere with registers etc.

[O(1)]: https://www.bing.com/search?q=O%281%29

Source of confusions:
- efficiently making the line selection: which i asked in #5612, and will expand on there itself in some days
- forgetting command names for step 4
- [command palette] `<Space> ?` is ur friend for any forgotten command or keybind

[deselect]: https://github.com/helix-editor/helix/issues/3162#issuecomment-1364644777
[command palette]: https://github.com/helix-editor/helix/discussions/5548#discussioncomment-4694127


### Screen record:


https://user-images.githubusercontent.com/19423063/216425410-665c47df-75e5-4601-a5d0-01373a9fdafb.mp4



### Old

<details>
<summary>Resolved/thanks @ CptPotato for sharing <tt>A-s</tt></summary>

<strike>
i am not sure if this (breaking selection at newline) is possible _yet_, haven't tried it... 
but this just came in my mind, thought to share....

will confirm a bit later
</strike>
</details>

**Reply by CptPotato** [reply]
Good point, this *should* also work!

> i am not sure if this (breaking selection at newline) is possible yet, haven't tried it yet...

Yes, you can split the selection into one selection per line, using `A-s`.

**Reply by CptPotato** [reply]
Here's the above binding with your method:

```toml
"A-j" = [ "extend_to_line_bounds", "extend_line_below", "split_selection_on_newline", "rotate_selection_contents_forward", "rotate_selections_backward", "keep_primary_selection" ]
"A-k" = [ "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "rotate_selection_contents_forward", "keep_primary_selection" ]
```

However, the big issue with this is that ***empty lines break this sequence***.

This one is even more convoluted, but still works with empty lines present:

```toml
"A-j" = [ "keep_primary_selection", "move_line_down", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection", "move_line_down" ]
"A-k" = [ "keep_primary_selection", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection" ]
```

<sup>The first `keep_primary_selection` is used to prevent multiple selections from breaking this keybind.</sup>

So I guess there are two options now. One works with multiple cursors (but overwrites the yank register), the other doesn't touch any register but can only handle a single selection (and is too complicated for my liking).
