### DISCUSSION TITLE
Helix for prose

### DISCUSSION THREAD

**Discussion by glow12121** [helix-editor/helix#5830] [Ideas]
I use Helix to write long markdown-formatted texts - you could call them prose. I have been experimenting with console text editors in the past couple of months. Previously had been working in Sublime Text. Just wanted to share my observations as to what features make writing and editing prose comfortable. Writing prose is different from code in that it involves sentences with punctuation of a human language, long uninterrupted sentences that can span through many lines, and paragraphs that form chapters of a longer text.

Nor many things are in fact needed:

* Built-in soft-wrapping functionality. This includes setting arbitrary line length, moving to the beginning of next line after the end of current line with cursor movement keys, and avoidance of jumps and visual glitches while scrolling.
* In Normal mode - intuitive operations with words, groups of words, sentences, and groups of sentences. This includes selecting, substituting, yanking, pasting, cutting. My impression is that editing operations with prose are way simpler that those with code, but their intuitive character and precision are very important.
* Hotkeys mirrored from Latin to other alphabets, Cyrillic for example.
* Simple folding of markdown sections with hotkeys.
* Simple option to yank, cut, and past exclusively to and from the system clipboard.
* Navigation column with table of contents based on markdown formatting.
* Functionality to build office documents from markdown with a hotkey.
* The option to exit the editor (not buffers one by one) and easily reopen it with same documents opened in the same layout.

That's about it. Because Hx is a developing project, perhaps this list will be useful in some way. I will be updating it in case more ideas come to me :)

**Comment by pascalkuthe** [comment]
> Built-in soft-wrapping functionality. This includes setting arbitrary line length, moving to the beginning of next line after the end of current line with cursor movement keys, and avoidance of jumps and visual glitches while scrolling.

Softwrap has recently been merged with #5420 and can be eneabled when building from current master by setting `editor.soft-wrap.enable = true`

**Reply by glow12121** [reply]
Yes, I know. That's great news, can't wait to start using the new functionality.

**Comment by kirawi** [comment]
> Table of contents based on markdown formatting.

https://github.com/artempyanykh/marksman auto-generates TOC for you.

**Reply by glow12121** [reply]
I implied a separate navigation column.

**Reply by goyalyashpal** [reply]
try using symbols browser in helix

**Comment by getreu** [comment]
The blog post [Note talking with Helix, Tp-Note and LanguageTool](https://blog.getreu.net/20220828-tp-note-new8/) might help:

* [Tp-Note] adds clipboard based note file generation and live Markdown rendering, while
* [LanguageTool] adds spell and grammar checking

[LanguageTool]: https://languagetool.org/
[Tp-Note]: https://blog.getreu.net/projects/tp-note/tpnote--manual.html

**Reply by andreatitolo** [reply]
Would the LanguageTool server that comes with [LTeX-LS](https://valentjn.github.io/ltex/ltex-ls/installation.html) works even when the language is not specified in the YAML? I'm thinking about README.md files that usually do not have a front matter, but would still benefit from grammar checking, especially for non-native English speakers. 

Edit: not sure if the `language-id` argument in the [Language Server configuration](https://docs.helix-editor.com/languages.html#language-server-configuration) might be use for this.

**Reply by getreu** [reply]
My `~/.config/helix/languages.toml`:

```toml
[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG", "mkd", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "workbook"]
roots = [".tpnote.toml"]
language-servers = [{ name = "ltex"}]

[language-server.ltex]
command = "ltex-ls"
#ltex.dictionary = { "en-US" = [ "ltex-ls",], "en-GB" = [ "ltex-ls",], "de-DE" = [ "ltex-ls",], "et-ET" = [ "ltex-ls",], "fr" = [ "ltex-ls",] }

[language-server.ltex.config.ltex.dictionary]
"en-US" = ["Tp-Note","Zettelkasten"]
"en-GB" = ["Tp-Note","Zettelkasten"]
```
