### DISCUSSION TITLE
Is there a key binding for git add & git commit?

### DISCUSSION THREAD

**Discussion by Martin15135215** [helix-editor/helix#6032] [Q&A]
I searched in the documentation and here in the wiki and did not find, if there is a keybinding to do git add & git commit.

Do you have any ideas?

**Comment by kirawi** [comment]
You can create one, the instructions are in the documentation.

**Comment by Martin15135215** [comment]
You mean with key remapping? https://docs.helix-editor.com/remapping.html

```toml
[keys.normal]
C-g = ":sh git add @thisfile & git commit @promt_to_write_message"
```

I have two questions about that. what is right command for @thisfile and how to wirte in a promt the commit message

**Reply by LEI** [reply]
The [command expansions](https://github.com/helix-editor/helix/pull/3393) feature would allow to expand the current file name in some way.

For the commit message, `:pipe-to` can send the current selection (#5499). Ideally a prompt should be displayed if there is no stdin.

**Reply by Martin15135215** [reply]
Thanks for the info!

the new toml config

```toml
[keys.normal]
C-g = ":sh git add '%val{filename}' & :pipe-to git commit"
```
would that function?
