### DISCUSSION TITLE
How do I send a shell command to another Kitty window from Helix when $'\n' for newline is not working?

### DISCUSSION THREAD

**Discussion by David-Else** [helix-editor/helix#6035] [Q&A] [answered]
If I type `kitty @ send-text --match 'title:^Terminal' cargo run$'\n'` in a Kitty terminal window it will send the command `cargo run` to the correct terminal in Kitty and execute it.

If I use `:sh kitty @ send-text --match 'title:^Terminal' cargo run$'\n'` in Helix in a Kitty Window, in the destination window  it displays:
```
cargo runn
```
and does not execute. What is happening to the `$'\n'` and how can I make it work? Thanks.

**Comment by bbodi** [comment, marked as answer]
This worked for me: `:sh kitty @ send-text --match 'num:0' cargo test \\\\n`

**Comment by bbodi** [comment]
Btw, thanks for your question! 

I am beginner at using Kitty, and didn't know about its remote control functionality, now thanks to your question I digged into it, and could make my Helix workflow even better with these shortcuts (run all tests / run selected test only)
```
[keys.select.space]
t = ":sh kitty @ send-text --match 'num:0' cargo test \\\\n"
T = ":pipe-to xargs -I {} kitty @ send-text --match 'num:0' cargo test {}\\\\n"
```

**Reply by David-Else** [reply]
Excellent, glad to hear I helped, and thanks for the `\\\\n` fix!

You might like the project I am working on to integrate things further: https://github.com/David-Else/kitty-terminal-project-launcher , would love to hear what you make of it.

The docs don't really explain things very well, and there needs to be some changes, but you might be able to take some code from it to add to your setup. I love Kitty, Helix and Lazygit together, best work flow ever! :)

Using my script you could use:

```toml
c = ":sh kitty @ send-text --match 'title:^Terminal' cargo run \\\\n" 
t = ":sh kitty @ send-text --match 'title:^Terminal' cargo test \\\\n"
T = ":pipe-to xargs -I {} kitty @ send-text --match 'title:^Terminal' cargo test {}\\\\n"
```
I added that to my project repo docs, cheers!
