### DISCUSSION TITLE
Need more detailed guide on how to set up helix as external editor for Godot

### DISCUSSION THREAD

**Discussion by Multirious** [helix-editor/helix#6190] [General] [answered]
I'm trying to set up Helix as external editor for Godot 4.0. It works a little bit but there's still some problem involving the LSP.

It's seems like not a simple job. The steps I need to get through is not documented and I've solved it with some trial and error.
This is what I did:

1. Helix need a terminal to run with. I've tried to use Window's cmd and powershell but for the life of me can't figure out how to make the command work (like "/C" flag and stuffs). I decided to installed Cmder (I'm gonna install it later anyways) and find some [batch script](https://github.com/cmderdev/cmder/issues/457#issuecomment-1144782767) that allows me to run command as input for Cmder executable.
2. LSP config. I configured Helix language with the `How to install the default language servers` guide with no additional settings and some `nc` and `ncat` path problem, nothin' much.

After has been done, at first, it seems to work. Then for awhile, Godot saids that `Max client limits reached` which is 8 in the source code.
My theory is that the LSP didn't disconnect when I `:q` in Helix. What's next?

**Comment by erasin** [comment]
Read [helix#installation](https://github.com/helix-editor/helix#installation).

create `CONFIG_PATH/helix/languages.toml`, add content of setting.

```toml
[[language]]
name = "gdscript"
language-server = { command = "nc", args = [
  "127.0.0.1",
  "6005",
], language-id = "gdscript" }
```

Append `nc` into PATH of environment variable.

**Reply by Multirious** [reply]
> Read [helix#installation](https://github.com/helix-editor/helix#installation).

I don't understand. What do I need to specifically need to read?


This is my previous setting.
```toml
[[language]]
name = "gdscript"
roots = ["project.godot"]
language-server = { command = "ncat", args = ["localhost", "6005"], language-id = "gdscript" }
```

What should be the path for `nc`? I'm assuming I need to put path of `ncat` into `nc`
