### DISCUSSION TITLE
How do I add arguments to checkOnSave?

### DISCUSSION THREAD

**Discussion by Artewald** [helix-editor/helix#6252] [Q&A]
My current languages.toml looks like this:
```[[language]]
name = "rust"

[language.language-server]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language.config.checkOnSave]
command = "clippy"
args = ["--workspace", "--", "-W clippy::unwrap_used", "-W clippy::expect_used", "-W clippy::pedantic", "-W clippy::nursery", "-Dwarnings"]
```

When I run `cargo clippy --workspace --verbose -- -W clippy::unwrap_used -W clippy::expect_used -W clippy::pedantic -W clippy::nursery -Dwarnings`, I get lots of errors. However, helix does not show these errors after saving, with my current languages.toml. I've tried adding "--message-format=json" to the args with no success. I also don't get any errors in the logs.

How would I go about setting up the languages.toml correctly so that the errors are shown in the editor?

**Comment by cd-a** [comment]
Try this, it works just fine and is what I am using:

```toml
[language-server.rust-analyzer.config]
check = {command = "clippy", extraArgs = ["--", "-W", "clippy::unwrap_used", "-W", "clippy::expect_used", "-W", "clippy::pedantic", "-W", "clippy::nursery"]}
```
