### DISCUSSION TITLE
Is it possible to yank or copy to clipboard while in Insert mode?

### DISCUSSION THREAD

**Discussion by maxchisto** [helix-editor/helix#6264] [Q&A]
I read through shortcuts page several times and my conclusion is "no", but wanted to doublecheck.
I'm on Mac and can do Command+V to paste from system clipboard while in Insert mode, but I want to be able to yank/copy too.

If I highlight some text with mouse while in Insert mode, status at the bottom says `yanked main selection to primary clipboard`, but the text actually doesn't make into the system clipboard (🤔 maybe I found a bug).

**Comment by koyeung** [comment]
I have insert mode worked like on emacs, with key bindings:

```toml
[keys.insert]
A-w = "yank_to_clipboard"
C-y = "paste_clipboard_after"
```
