### DISCUSSION TITLE
How to enable format on save for svelte(kit) ?

### DISCUSSION THREAD

**Discussion by beeb** [helix-editor/helix#6319] [Q&A] [answered]
I installed the svelte language server which works, but the code doesn't get auto formatted on save.

Is there something specific I need to do to enable this?

I tried to add the following to my `languages.toml` to no avail:

```toml
[[language]]
name = "svelte"
formatter = { command = "prettier" }
auto-format = true
```

**Comment by beeb** [comment, marked as answer]
It seems the following is working:

```toml
[[language]]
name = "svelte"
auto-format = true
```
