### DISCUSSION TITLE
Add window mode mapping

### DISCUSSION THREAD

**Discussion by rcorre** [helix-editor/helix#6328] [Q&A] [answered]
Can I add a mapping to window mode? I'd like to bind `ctrl+w, O` to `:buffer-close-others`, but neither of these seem to work:

```
[keys.window]  # invalid mode 'window'
O = ":buffer-close-others"

[keys.normal.w] # fine, but does nothing
O = ":buffer-close-others"
```

**Comment by the-mikedavis** [comment, marked as answer]
You can rebind within `C-w`:

```toml
[keys.normal]
C-w.O = ":buffer-close-others"
```
