### DISCUSSION TITLE
Other ways to load LSP snippets?

### DISCUSSION THREAD

**Discussion by dcompoze** [helix-editor/helix#6449] [General]
I'm able to define LSP snippets inside of a `languages.toml` file like so:

```toml
[language.config.completion.snippets.custom.foo]
prefix = ["foo"]
body = ["foo!($0)"]
description = "Foo function call"
requires = "std::foo::bar"
scope = "expr"
```

This makes the snippet show up as part of auto-completion in the editor.

However, it's quite cumbersome to maintain a large list of snippets inside of a single `languages.toml` configuration file, especially when the snippets are large (e.g. lots of boilerplate for HTML).

VSCode has a way of loading snippets from `~/.config/VSCode/User/snippets/*.json` but I'm not aware of Helix doing anything similar.

Also, to my understanding, most language servers don't provide a way to independently load global configuration outside of the editor (e.g. something like `~/.rust-analyzer/snippets.json`), since the LSP client is supposed to load and provide the configuration to the language server, including any custom snippets.

Hence, the only option seems to be to use the `languages.toml` file to provide custom configuration to the language server - together with the custom snippets.

Are there other ways of loading LSP snippets other than specifying them inside of the `languages.toml` file as shown above (ideally each snippet would be in a separate file)?
