### DISCUSSION TITLE
cargo run shortcut?

### DISCUSSION THREAD

**Discussion by matthiasdebernardini** [helix-editor/helix#6477] [Q&A]
How would I make a key combo to run something like `cargo run`? (or any other custom runners)

I'd like a small window to pop up and show the progress.

The `sh` command doesn't have a window that pops up and shows the output. 

What's a good way to enable this functionality?

Thanks

Should I instead go about this a different way?

**Comment by LEI** [comment]
If the program is not interactive, redirecting stderr to stdout and ensuring the exit code is 0 should always display the output in helix:

```toml
[keys.normal.space]
r = ":sh cargo run 2>&1 || true"
```

Another flexible workaround but requiring an external program like tmux, sending `!!` to the last active pane works well in many cases:

```toml
[keys.normal.space]
# Create a new vertical split
T = [":sh tmux split-window"]
# Repeat last command in the previously selected pane
t = [":sh tmux send-keys -t :.! !! C-m"]
```

**Comment by David-Else** [comment]
Use [Kitty](https://sw.kovidgoyal.net/kitty/) and add this for cargo run and cargo test. You need to first create a Window called `Terminal`, you can have that as a split and toggle it on and off no problem:

```toml
[keys.normal.space]
c = { r = ":sh kitty @ send-text --match 'title:^Terminal' cargo run \\\\n", t = ":sh kitty @ send-text --match 'title:^Terminal' 'clear \\ncargo test \\n'" }
```
![Screenshot from 2023-03-29 19-02-52](https://user-images.githubusercontent.com/12832280/228628210-1bb5dc73-4ef7-4f10-b40d-1ee6c16178ef.png)
