### DISCUSSION TITLE
configuring pylsp

### DISCUSSION THREAD

**Discussion by JurajLieskovsky** [helix-editor/helix#6623] [Q&A] [answered]
Hi, I'm trying to make some modifications to the default pylsp settings as I do not strictly follow PEP in my personal projects. I googled some examples but I cannot get them to work, so I am wondering where I'm going wrong.

As an excepted answer for setting the `maxLineLenght` I found:
```
[[language]]
name = "python"
config = {pylsp={plugins={pycodestyle={enabled=false},flake8={enabled=true,maxLineLength=120},pyflakes={enabled=false}}}}
```
which I have copied to my otherwise empty `~/.config/helix/languages.toml` file. Then I saved the file `:w`, reloaded the config `:config-reload` and restarted the lsp `:lsp-restart` but I still get the warning of a too long line.

If I understand correctly this should also be equivalent to:
```
[[language]]
name = "python"

[language.config.pylsp.plugins.pycodestyle]
enabled = false

[language.config.pylsp.plugins.flake8]
enabled = true
maxLineLength = 120

[language.config.pylsp.plugins.pyflakes]
enabled = false
```
but that also doesn't work.

**Comment by JurajLieskovsky** [comment]
I should have probably included
```
~> hx --health python
Configured language server: pylsp
Binary for language server: /home/liesk/.local/bin/pylsp
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

**Comment by guicanat** [comment, marked as answer]
I have this and it works pretty well (disabling everything except ruff).

```
[[language]]
name = "python"

[language.config.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }

```

**Reply by JurajLieskovsky** [reply]
@guicanat thank you for providing an example of what works for you. It did not work for me so I started looking for the problem in my lsp install and managed to find it.

Also you sent me down a rabbit hole of configuring pylsp with ruff + yapf instead of manually formatting files.

**Reply by jpsecher** [reply]
Erh, the configuration above is not accepted by Helix 23.05: unknown field 'config'

**Comment by SpecificProtagonist** [comment]
> Erh, the configuration above is not accepted by Helix 23.05: unknown field 'config'

Language and language server configuration got separated to allow for multiple LSPs per file, so I think putting `language-servers = ["pylsp"]` under the Python config and then using `[language-server.pylsp.config.pylsp.plugins]` should work.

**Reply by jpsecher** [reply]
Thanks!  So a complete example that works for me:
```
[[language]]
name = "python"
language-servers = ["pylsp"]
roots = [".git"]
workspace-lsp-roots = ["src/updater"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true, ignore = ["E501"]}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = false}
```

**Reply by unartig** [reply]
I'm using Helix 23.10, the languages.toml is accepted without complaints by helix, but after reloading the config and restarting the lsp nothing changes

**Reply by kirawi** [reply]
The LSP config not reloading was a bug fixed in 24.03

**Reply by nandoflorestan** [reply]
> The LSP config not reloading was a bug fixed in 24.03

I am running helix 24.3 (2cadec0b).  The command `:config-reload` did not make the warnings disappear. They only disappeared when I restarted helix.

The following is the configuration I am keeping, even with the inactive "flake8" line:

```toml
[[language]]
name = "python"
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true
plugins.flake8.maxLineLength = 88
plugins.pycodestyle.maxLineLength = 88

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
```

**Reply by peterjc** [reply]
Very helpful. I'm trying to use ``ruff`` (as a formatter and as a linter), with ``pylsp`` as a language-server for autocompletion etc - but disabling its linters (which become redundant with ruff - for example E501 from lines which are fine with ruff's default length settings but not the flake8 default settings). This _seems_ to work in Helix 25.1:

```toml
[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = {enabled = false}
```

**Reply by funnes** [reply]
When ordering `ruff` first in the `language-servers` list, symbol documentation does not show up when pressing `Space-k`.

edit: landed on this:
```toml
[[language]]
name = "python"
language-servers = [ { name = "pylsp", except-features = [ "format" ] }, "ruff"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
ruff.enabled = false
autopep8.enabled = false
flake8.enabled = false
mccabe.enabled = false
pycodestyle.enabled = false
pyflakes.enabled = false
pylint.enabled = false
yapf.enabled = false
```
