### DISCUSSION TITLE
Soft wrap by language

### DISCUSSION THREAD

**Discussion by kj** [helix-editor/helix#6680] [Q&A]
Is there a way to enable soft wrap by language? I'd like to enable it by default for Markdown, but not for any other language. Related to that, is there any way to set Helix editor options based on the language?

**Comment by the-mikedavis** [comment]
It isn't documented currently but you can configure the `soft-wrap` key in language config (`languages.toml`) per language:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "markdown"
soft-wrap.enable = true
```

It takes the same options as the [`editor.soft-wrap`](https://docs.helix-editor.com/master/configuration.html#editorsoft-wrap-section) config option.
