### DISCUSSION TITLE
How to properly setup helix for godot 4.0.2(gdscript) in windows

### DISCUSSION THREAD

**Discussion by ash-hashtag** [helix-editor/helix#6701] [Q&A] [answered]
I've followed the 'how to setup default languages server', and it doesn't seem to work. I tried manually connecting to the lsp, with ncat in powershell, and it did connect successfully, and godot editor output shows "[LSP] Connection Taken". But when I open the project with helix, the ncat command from languages.toml is not executing or got some problem? there is no confirmation of LSP connection in the godot output.

https://github.com/helix-editor/helix/discussions/6190#discussioncomment-5263261 this seems more like a workaround then an answer.

**Comment by erasin** [comment]
~Start with helix 23.05~, helix(master) has supported more lsp server, languages.toml need to change.

I has update godot part of  [how to setup default languages server](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#gdscript) .

Edit config file `languages.toml` ,append following content .

```toml
[language-server.godot]
command = "ncat" # or nc
args = [ "127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = ["godot"] 
```

**Reply by ash-hashtag** [reply]
I am on helix 23.05, but I get this error. and I switched to linux, so I'm on linux now.

```
Bad language config: unknown field `language-servers`, expected one of `name`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `config`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-server`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`

```

**Reply by the-mikedavis** [reply]
Support for multiple language servers (#2507) was merged after the 23.05 release so that config will only work on master builds for now.

**Reply by erasin** [reply, marked as answer]
I was wrong.   helix 23.05 has use old `languages.toml`

```toml
[[language]]
name = "gdscript"
language-server = { command = "nc", args = [
  "127.0.0.1",
  "6005",
], language-id = "gdscript" }
```

lsp takes message only after the godot project is opened.
