### DISCUSSION TITLE
Del key should delete (in normal mode, too)

### DISCUSSION THREAD

**Discussion by vp2177** [helix-editor/helix#6749] [Ideas]
### Summary

The <kbd>Del</kbd> key should delete the selection(s), in normal mode. I expect it to behave exactly like `d`. Currently, it only deletes in insert mode.

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.46.2

### Helix Version

23.03

**Comment by the-mikedavis** [comment]
You can map this in your config:

```toml
# ~/.config/helix/config.toml
[keys.normal]
del = "delete_selection"
```

I don't like adding extra keys for something that already has a keybinding though and `d` is already very easy to hit.
