### DISCUSSION TITLE
Inlay Hints in Java

### DISCUSSION THREAD

**Discussion by jrmoulton** [helix-editor/helix#6770] [Q&A]
The eclipse lsp jdtls support inlay hints for parameter names. In vscode the setting for enabling inlay hints is `"java.inlayHints.parameterNames.enabled": "all"` and so in my languages.toml I added 
```toml
[language.config.java.inlayHints]
parameterNames.enabled = "all"
```
I don't get any inlay hints and in my log file I see `2023-04-16T00:57:33.300 helix_term::application [ERROR] Language Server: Method workspace/inlayHint/refresh not found in request 3`

Is this even how I would go about adding support for inlay hints in Java or is there something else I need to add?

**Comment by the-mikedavis** [comment]
It looks like jdtls is sending a [`workspace/inlayHint/refresh`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_inlayHint_refresh) request. We declare that we don't support the refresh request [in the client capabilities](https://github.com/helix-editor/helix/blob/4cdba7cccdd6a9fe5fbb3d15c9db3edc147b7a90/helix-lsp/src/client.rs#L445-L447) so jdtls should not be sending this request. Alternatively I think that implementing that request would not be so much work to implement in Helix.

That config looks ok but I haven't tried using jdtls. Make sure that is under a `[[language]]` section for java:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "java"
[language.config.java.inlayHints]
parameterNames.enabled = "all"
```

and also that inlay hints is enabled in config:

```toml
# ~/.config/helix/config.toml
[editor.lsp]
display-inlay-hints = true
```

**Comment by jrmoulton** [comment]
Verified and still not working. Seems like jdtls is expecting the editor to request the update before it will actually provide inlay hints. 

> Alternatively I think that implementing that request would not be so much work to implement in Helix.

I'll look into supporting workspace/inlayHint/refresh in helix and see if that fixes the issue.

**Comment by devanlooches** [comment]
Putting this in case it helps anyone:

The following configuration works for me with the jdtls language server:
```toml
[language-server.jdtls.config.java.inlayHints]
parameterNames.enabled = "all"
```
