### DISCUSSION TITLE
Inlay hints not working if set in the config.toml?

### DISCUSSION THREAD

**Discussion by AverageLinuxEnjoyer** [helix-editor/helix#6777] [Q&A]
So, I placed the following snippet inside my ~/.config/helix/config.toml: 
```toml
[editor.lsp] 
display-inlay-hints = true
```
But that didn't seem to work. Using the `:set lsp.display-inlay-hints true` does work though. Other settings in that same config file work as well. Any ideas?
