### DISCUSSION TITLE
[ Partially SOLVED] Rust inlay Hints does not work

### DISCUSSION THREAD

**Discussion by MrMic** [helix-editor/helix#6815] [General] [answered]
Hi,

I see that release 23.03 bring us inlay hints. 
It works fine for JS and Typescript but I cannot 
make it work with Rust!

--- config.toml ------
[editor.lsp]
display-messages = true
display-inlay-hints = true

--- languages.toml ---
[[language]]
name = "rust"
auto-format = true

[language.config]
hostInfo = "helix"

[language.config.rust.inlayHints]
enable = true
type_hints = true

[language.config.check]
command = "clippy"

What am I doing wrong?

Thanks for the reply.
Rgds,

BTW, great work anyway for all you have done!  👍

**Comment by truongvan** [comment]
my `languages.toml`
```toml
[[language]]
name = "rust"
auto-format = true

[language.language-server]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]


[language.config]
inlayHints.bindingModeHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
```

**Comment by David-Else** [comment]
@truongvan You are duplicating a lot of settings for nothing, these are already built in defaults:

https://github.com/helix-editor/helix/blob/080f85c34f7bfc3de8b8441d51d434623a4a9f79/languages.toml#L22-L28

**Reply by MrMic** [reply]
OK, but that doesn't explain to me why I got no inlay with rust!  Even without config, I got nothing, 
but with other languages (i.e: JS, TS ...) I got inlays.

**Reply by David-Else** [reply, marked as answer]
I toggle it on and off like this, I don't think you need any other settings, I suggest you delete yours and try just:

`config.toml`
```toml
[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
```
