### DISCUSSION TITLE
pyright + ruff

### DISCUSSION THREAD

**Discussion by predmijat** [helix-editor/helix#6816] [General]
Is there a way to use ruff with pyright? I read that ruff should probably be used with an LSP, but I've only found examples for pylsp, not pyright.

**Comment by alphastrata** [comment]
just change the args from the pylsp to ruff & make sure it's installed on path (both ruff and ruff-lsp)

**Comment by vazw** [comment]
Hey now that Helix  support multi LSP. my setting are working well with Pyright + ruff as LSP and black + ruff as formatter
```toml
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
python.analysis.venvPath = "."
python.analysis.venv = ".venv"
python.analysis.lint = true
python.analysis.inlayHint.enable = true
python.analysis.autoSearchPaths = true
python.analysis.diagnosticMode = "workspace"
python.analysis.useLibraryCodeForType = true
python.analysis.logLevel = "Error"
python.analysis.typeCheckingMode = "off"
python.analysis.autoImoprtCompletion = true
python.analysis.reportOptionalSubscript = false
python.analysis.reportOptionalMemberAccess = false


[language-server.ruff]
command = "ruff"
args = ["server", "-q", "--preview"] 


[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json", "requirements.txt", ".venv/"]
comment-token = "#"
language-servers = [ {name = "pyright", except-features=["diagnostics"]}, "ruff" ]
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter =  { command = "bash", args = ["-c", "ruff format --line-length 80 -q . && black --line-length 80 -q -"] }

```

**Reply by a3lem** [reply]
Simply out of curiosity: what's the reason for using both Ruff and Black for formatting? Doesn't Ruff's formatter more or less mirror Black already?

Also, check out https://github.com/DetachHead/basedpyright if you haven't already. It's like pyright but without the arbitrary restrictions on features that for some reason belong in Pylance instead.

**Reply by vazw** [reply]
`ruff format` just deleted all my code while formatting with helix I think it doesn't support stdout format yet

**Reply by a3lem** [reply]
Sure it does! Just need to add a `-` to the args list, which pipes the stdin in.

```toml
formatter = { command = "ruff", args = ["format", "-" ] }
```

**Reply by vazw** [reply]
oh that it's 😆🙏

**Reply by schlich** [reply]
a lot of people are gonna run into this problem, i think it's worth adding to the wiki

**Reply by 57Ajay** [reply]
> Sure it does! Just need to add a `-` to the args list, which pipes the stdin in.
> 
> ```toml
> formatter = { command = "ruff", args = ["format", "-" ] }
> ```

This one works

**Comment by j-dominguez9** [comment]
This is my current setup that works nicely, in case anybody wants to see a full example:

```toml
[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", ".git", ".jj", ".venv/"]
language-servers = ["ruff", "pyright"]
auto-format = true
# formatter = { command = "black", args = ["--quiet", "-", "--line-length=80"] }
formatter = { command = "ruff", args = ["format", "-" ] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
environment = { "RUFF_TRACE" = "messages" }

[language-server.ruff.config.settings]
lineLength = 80
logLevel = "debug"

[language-server.ruff.config.settings.lint]
select = ["E", "F", "W", "B", "I", "RUF", "N", "LOG", "ERA", "W", "D", "UP", "ANN", "ASYNC", "S", "RET", "TCH", "ARG", "PTH", "DOC"]
preview = true

[language-server.ruff.config.settings.format]
preview = true
quote-style = "double"
docstring-code-format = true
indent-style = "space"
```

**Reply by eliasbenaddou** [reply]
Hey nice one! I am using poetry virtualenvs and i can't see my imports (reportMissingImport error) any ideas why that may be? Also, how do you get to apply ruff formatting on save automatically? Having auto-format = true in the [[language]] table did not seem to enable it for me..

**Reply by j-dominguez9** [reply]
Yeah, it's kind of an annoying thing. I wish there was a way to invoke the virtual environment from the helix side, but right now what I do is activate my virtual environment and then open the file(s) on helix that way it's responding to whatever dependencies are and are not available. Actually, there's also a bug(?) where if I'm on the file and I don't have a certain package in my venv I'm trying to import, even after I install/add it in another terminal, it doesn't update to reflect those changes. I have to close the file and open it again. I wonder what causes that

**Reply by eliasbenaddou** [reply]
I've setup a function in my .zshrc file to run my poetry env before opening helix like so:

poetry_run_hx() {
  if command -v poetry >/dev/null 2>&1 && [ -f "poetry.lock" ]; then
    poetry run hx "$@"
  else
    hx "$@"
  fi
}
alias h='poetry_run_hx'

**Reply by j-dominguez9** [reply]
Actually, i just figured it out (at least, for my use case). I'm using uv intstead of poetry, which lets you install system-wide tools. So I install ruff and basedpyright as a tool and then in the languages.toml file instead of `formatter = { command = "ruff", args = ["format", "-" ] }` , I just do `formatter = { command = "uvx ruff", args = ["format", "-" ] }`. And the equivalent for basedpyright command. This way it runs it inside the venv environment.

**Reply by j-dominguez9** [reply]
nvm, I lied, that didn't fully work, but this did:

```
[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", ".git", ".jj", ".venv/"]
language-servers = ["ruff", "basedpyright"]
auto-format = true
formatter = { command = "uvx", args = ["ruff","format", "-" ] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]

[language-server.basedpyright]
command = "uv"
args = ["run", "basedpyright-langserver", "--stdio"]

[language-server.basedpyright.config]


[language-server.ruff]
command = "uvx"
args = ["ruff","server"]
environment = { "RUFF_TRACE" = "messages" }
```

**Reply by eliasbenaddou** [reply]
nice one! Any chance of including auto import sorting within this on save?

**Reply by j-dominguez9** [reply]
I haven't figured that out and it does bother me, as well. Im pretty sure I have it specified in my "ruff" config, but it doesn't do it. I've had to do `:sh uvx ruff check --fix` or `:sh uvx isort` while inside helix. Let me know if you come up with something

**Reply by eliasbenaddou** [reply]
This worked!
formatter = { command = "uvx", args = ["sh", "-c", "ruff check --fix - | ruff format -"] }

**Reply by thomasaarholt** [reply]
I have a mostly working config for using basedpyright with uvx / uv tool using a local (unactivated) virtual environment, with one caveat*.

basedpyright runs with uvx using
```toml
[language-server.basedpyright]
command = 'uvx'
args = ['--from', 'basedpyright', 'basedpyright-langserver', "--stdio"]
```
You can then target the local venv as follows. I could not get the venvPath and venv config to work.

```toml
[language-server.basedpyright.config]
python.pythonPath = ".venv/bin/python"
```

* The only caveat is that basedpyright resolves "." relative to the root **of any git repo**. So if you call at `hx /my-git-repo/foo/bar/.`, then you need to have the venv at `my-git-repo/.venv`

**Reply by nanxingke** [reply]
> This worked! formatter = { command = "uvx", args = ["sh", "-c", "ruff check --fix - | ruff format -"] }

it doesn`t works for me, but this works
formatter = { command = "sh", args = ["-c","ruff check --quiet --select I --fix - | ruff format -"] }

**Reply by nanxingke** [reply]
> > This worked! formatter = { command = "uvx", args = ["sh", "-c", "ruff check --fix - | ruff format -"] }
> 
> it doesn`t works for me, but this works formatter = { command = "sh", args = ["-c","ruff check --quiet --select I --fix - | ruff format -"] }

this works too
formatter = { command = "sh", args = ["-c","uvx ruff check --quiet --select I --fix - | ruff format -"] }

**Comment by nrbnlulu** [comment]
How did you guys installed pyright / ruff lsp's?

**Reply by vazw** [reply]
I was using system packages manager itself.

**Reply by nrbnlulu** [reply]
ended up using `pipx` ubuntu has no package for ruff lsp

**Reply by j-dominguez9** [reply]
You're probably better off using just ruff, as it has the lsp server + linter and formatter, as noted in their readme:

> Note

> As of Ruff v0.4.5, Ruff ships with a built-in language server written in Rust: ⚡ ruff server ⚡

> ruff server supports the same feature set as ruff-lsp, but with superior performance and no installation required. ruff server was marked as stable in Ruff v0.5.3

And you can install it with a curl command.

**Reply by schlich** [reply]
ruff does not do type checking like pyright does.  while you can use `ruff server` instead of `ruff-lsp` it is not a replacement for pyright

**Reply by nrbnlulu** [reply]
> ruff does not do type checking like pyright does. while you can use `ruff server` instead of `ruff-lsp` it is not a replacement for pyright

who said it was? :eyes:

**Reply by schlich** [reply]
for sure nobody, just clarifying for folks at home 😉

**Comment by jochumdev** [comment]
Thank you all! After all the inspirations here I came up with this.

Goals was/is:

- Be compatible with other Editor's on lsp settings.
- Do not auto-format except a project is configured to do so.
- Works on single files, projects and uv workspaces.

### `~/.config/helix/config.toml`:
```toml
[editor]
# Disable auto-format per default
auto-format = false
``` 

### `~/.config/helix/languages.toml`:
```toml
[language-server.basedpyright]
command = "uvx"
args = ["--from", "basedpyright", "basedpyright-langserver", "--stdio"]

[language-server.ruff]
command = "uvx"
args = [
  "ruff",
  "server",
  "--preview",
]
environment = { "RUFF_TRACE" = "messages" }

# https://github.com/helix-editor/helix/discussions/6816#discussioncomment-11102574
[[language]]
name = "python"
roots = ["pyproject.toml", ".git", ".jj", ".venv/"]
file-types = ["py", "ipynb"]
language-servers = ["ruff", "basedpyright"]
formatter = { command = "sh", args = [
  "-c",
  "uvx ruff check --fix - | uvx ruff format -"
] }
auto-format = true
comment-token = "#"
shebangs = ["python"]
```

### `~/Projects/foo/pyproject.toml`
```toml
[tool.pyright]
# TODO(jochumdev): find a method to report "implicit" any
reportAny = "hint"
reportExplicitAny = "hint"

[tool.ruff]
exclude = [".venv", ".git", ".ruff_cache", ".vscode", ".helix"]
# line-length = 88
# target-version = "py310"

# From: https://github.com/fastapi/fastapi/blob/master/pyproject.toml
[tool.ruff.lint]
# select = [
#   "E",  # pycodestyle errors
#   "W",  # pycodestyle warnings
#   "F",  # pyflakes
#   "I",  # isort
#   "B",  # flake8-bugbear
#   "C4",  # flake8-comprehensions
#   "UP",  # pyupgrade
# ]
select = [
  "F",
  "E",
  "W",
  # TODO(jochumdev): enable this!
  #  "D",
  "S",
  "UP",
  "PL",
  "ERA",
  "YTT",
  "ANN",
  "ASYNC",
  "BLE",
  "B",
  "A",
  "C4",
  "DTZ",
  "T10",
  "EM",
  "EXE",
  "FIX",
  "INT",
  "ISC",
  "ICN",
  "LOG",
  "G",
  "PIE",
  "T20",
  "PYI",
  "PT",
  "Q",
  "RSE",
  "RET",
  "SLF",
  "SIM",
  "SLOT",
  "TID",
  "TD",
  "TC",
  "ARG",
  "PTH",
  "FLY",
  "I",
  "C90",
  "N",
  "PERF",
  "FURB",
  "RUF",
  "TRY",
]
preview = true
ignore = [
  # "E501",  # Line length
  "B008",  # do not perform function calls in argument defaults
  "C901",  # too complex
  "W191",  # indentation contains tabs
  # TODO(jochumdev): enable this
  "ANN401",
  "TD003",  # https://docs.astral.sh/ruff/rules/TD003 - https://docs.astral.sh/ruff/rules/missing-todo-link/
  # "TC002",  # https://docs.astral.sh/ruff/rules/typing-only-third-party-import/
  # "TC003",  # https://docs.astral.sh/ruff/rules/typing-only-standard-library-import/
]

[tool.ruff.lint.pylint]
max-public-methods = 25

[tool.ruff.lint.pyupgrade]
# Preserve types, even if a file imports `from __future__ import annotations`.
keep-runtime-typing = true

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
preview = true

[tool.uv.workspace]
members = ["packages/*"]
```

### `~/Projects/foo/.helix/config.toml`:
```toml
[editor]
auto-format = true
rulers = [88, 120]
```

### `~/Projects/foo/.helix/languages.toml`:
```toml
# Only required for projects using uv workspaces where I want to use the global "pyproject.toml"
[language-server.basedpyright]
args = [
  "--from",
  "basedpyright",
  "basedpyright-langserver",
  "-p",
  "$HOME/Projects/foo",
  "--stdio"
]

[language-server.ruff]
args = [
  "ruff",
  "server",
  "--preview",
  "--config",
  "$HOME/Projects/foo/pyproject.toml"
]
```
