### DISCUSSION TITLE
Suggest tree-sitter for Django Template

### DISCUSSION THREAD

**Discussion by truongvan** [helix-editor/helix#6864] [Q&A]
![image](https://user-images.githubusercontent.com/3089035/233817771-34671b67-925b-4044-8643-0117592dff8e.png)
_I want Helix use `htmldjango` for all html files in `templates` folder, but don't know how._

My install `htmldjango`:
- copy `highlights.scm` and `injections.scm` to `.config/helix/runtime/queries/htmldjango` 

- add to `language.toml`
```toml
[[language]]
name = "htmldjango"
scope = "source.htmldjango"
injection-regex = "htmldjango"
roots = []
file-types = [ "html" ]
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "htmldjango"
source = { git = "https://github.com/interdependence/tree-sitter-htmldjango" , rev = "b2dba02eddab66be669022320273d0dfe1ff923d" }
```
