### DISCUSSION TITLE
no line numbers

### DISCUSSION THREAD

**Discussion by ghost** [helix-editor/helix#6995] [Q&A]
i am brand new to helix and i want no line numbers.. please what to do??

**Comment by CptPotato** [comment]
Check out the [editor section](https://docs.helix-editor.com/master/configuration.html#editor-section) of the config docs. Specifically the `gutters` setting is what you're looking for.

This is the default without line numbers for example:

```toml
[editor]
gutters = ["diagnostics", "spacer", "diff"]
```

**Reply by ghost** [reply]
the bar did appeared.. setting theme to base16_transparent fixed this along with gutter. the behaviour might be diffrent because i used 256 color terminal

```toml
theme = "base16_transparent"

[editor]
gutters = ["diagnostics", "spacer", "diff"]
true-color = true
```
