### DISCUSSION TITLE
how to add several schemas to yaml language configuration

### DISCUSSION THREAD

**Discussion by ovitor** [helix-editor/helix#7066] [General]
Hey there, I'm currently using one schema (for Kubernetes) for the Yaml language, as described [here](https://github.com/helix-editor/helix/discussions/5704).

I would like to know if I can add other schemas, like, a schema for gitlab-ci, another one for docker-compose, and so on.

My configuration now is:

```toml
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
auto-format = true
config = { yaml = { schemas = { kubernetes = "/*.yaml" },  format = { enable = true }   }   }
```

**Comment by matiu2** [comment]
This is a work in progress but it's what I'm using right now:

```toml
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = [ "yaml-language-server" ]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }

[language-server.yaml-language-server.config.yaml]
completion = true
validation = true
hover = true

## If I uncomment this I get errors
# [language-server.yaml-language-server.config.yaml.schemaStore]
# enable = true

[language-server.yaml-language-server.config.yaml.schemas]
kubernetes = [ "*deployment*.yaml",
 "*service*.yaml",
 "*configmap*.yaml",
 "*secret*.yaml",
 "*pod*.yaml",
 "*namespace*.yaml",
 "*ingress*.yaml" 
]
"https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json" = [
  "*kustomization.yaml",
  "*kustomize.yaml"
]
"https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json" = [
  "*workflow*.yaml",
  "*template*.yaml"
]
```
