### DISCUSSION TITLE
Inlay hints not working

### DISCUSSION THREAD

**Discussion by cem-al** [helix-editor/helix#7075] [Q&A] [answered]
I have been unable to get inlay-hints working, my config is as follows:

### Config

```toml
theme = "jellybeans"

[editor]
idle-timeout = 0
line-number = "relative"
mouse = false
auto-format = true
true-color = true
color-modes = true
scrolloff = 25

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
git-ignore = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "file-name"]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.search]
smart-case = true

[editor.soft-wrap]
enable = true

[keys.normal]
C-space = "goto_last_accessed_file" # Maps the Ctrl-s to the typable command :w which is an alias for :write (save file)
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
C-r = ":reload"
n = ["search_next", "align_view_center"]
N = ["search_prev", "align_view_center"]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
x = "extend_line"
L = "repeat_last_motion"

[keys.select]
";" = ["collapse_selection", "normal_mode"]
x = "extend_line"
V = "extend_to_line_end"

[keys.normal.space]
w = ":write"
q = ":buffer-close"
space = "goto_last_accessed_file" 
```

### Logs

Clearing my logs and then opening a typescript file, I get the error:

```
2023-05-19T12:40:43.387 helix_lsp::transport [ERROR] typescript-language-server err: <- StreamClosed
```

![image](https://github.com/helix-editor/helix/assets/60609268/c4a91415-6ebb-40fd-bc44-c1027cf428d2)
