### DISCUSSION TITLE
Issue with language settings

### DISCUSSION THREAD

**Discussion by bq-wrongway** [helix-editor/helix#7101] [General] [answered]
After update from 23.03 to 23.05, i get always warning when trying to run helix :

```
Error parsing user language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`

Using default language config
Configured language server: rust-analyzer
Binary for language server: /usr/local/bin/rust-analyzer
Configured debug adapter: lldb-vscode
Binary for debug adapter: 'lldb-vscode' not found in $PATH
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```
And here is language. toml file settings 
https://pastebin.com/bx592Ugk

**Comment by gabydd** [comment]
Looks like you are running from master, https://github.com/helix-editor/helix/pull/2507 was recently merged which changes language server config to be per language server instead of per language, so you would need something like:

```toml
[language-server.rust-analyzer]
config = {}
```
See https://docs.helix-editor.com/master/languages.html#language-server-configuration

**Comment by bq-wrongway** [comment]
I managed to get most of it working , but i dont know how (or where to add) 

[language.config.check]
command = "clippy"

when i enable this it complains right away
here is new pastebin link https://pastebin.com/wqCQLAy9

**Comment by gabydd** [comment, marked as answer]
It should be 
```toml
[language-server.rust-analyser.config.check]
command = "clippy"
```

(Switched analyzer to analyser cause that's what your config used)

**Reply by bq-wrongway** [reply]
Thanks a lot, this helped a lot and i also corrected analyser to analyzer .

**Comment by chkilel** [comment]
Hello, I need some help please 🙏🏻.
I'm running master to try out multiple language servers, I converted the config that I had for `Vue - Volar` to the new one format but I didn't manage to make it work, here are my old and new `languages.toml` configuration:

- Old
```toml
[[language]]
name = "vue"
file-types = ["vue"]
language-server = { command = "vue-language-server", args = ["--stdio"] }
formatter = { command = "prettier", args = ["--parser", "vue"] }
scope = "text.html.vue"
roots = ["package.json"]
injection-regex = "vue"
auto-format = true

[language.config.typescript]
tsdk = "/opt/homebrew/lib/node_modules/typescript/lib"

[language.config.languageFeatures]
semanticTokens = true
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
completion = { defaultTagNameCase = 'both', defaultAttrNameCase = 'kebabCase' }
schemaRequestService = true
documentHighlight = true
documentLink = true
codeLens = true
diagnostics = true

[language.config.documentFeatures]
documentColor = false
selectionRange = true
foldingRange = true
linkedEditingRange = true
documentSymbol = true
documentFormatting = { defaultPrintWidth = 100 }
```

- New

``` toml
[[language]]
name = "vue"
scope = "text.html.vue"
injection-regex = "vue"
file-types = ["vue"]
auto-format = true
roots = ["package.json"]
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["vue-language-server"]

# Language Server configuration
[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]

[language-server.vue-language-server.config]
typescript = { tsdk = "/opt/homebrew/lib/node_modules/typescript/lib" }

[language-server.vue-language-server.config.languageFeatures]
semanticTokens = true
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
completion = { defaultTagNameCase = 'both', defaultAttrNameCase = 'kebabCase' }
schemaRequestService = true
documentHighlight = true
documentLink = true
codeLens = true
diagnostics = true

[language-server.vue-language-server.config.documentFeatures]
documentColor = false
selectionRange = true
foldingRange = true
linkedEditingRange = true
documentSymbol = true
documentFormatting = { defaultPrintWidth = 100 }
```
I appreciate your help.

**Comment by gabydd** [comment]
Try putting the ``[[language]]`` table at the bottom of your ``languages.toml`` also check what ``:log-open`` shows

**Reply by chkilel** [reply]
Thanks @gabydd , that was the issue 👍🏻 .

**Reply by gabydd** [reply]
looking at this again I want to confirm if moving the ``[[language]]`` table is actually what fixed the issue here. Did you change anything else when moving it as well could you try moving it back before and see if it still works?

**Reply by chkilel** [reply]
I moved back the `[[language]]` table to the beginning of the file and it's still working, this is my new config for refernece.

```TOML
# Language Server configurations
# Vue language
[[language]]
name = "vue"
scope = "source.vue"
file-types = ["vue"]
injection-regex = "vue"
roots = ["package.json", "tailwind.config.js", "tailwind.config.cjs"]
language-servers = ["volar", "tailwindcss-vue"]
formatter = { command = "prettier", args = ["--parser", "vue"] }
auto-format = true

# React language
[[language]]
name = "tsx"
language-id = "typescriptreact"
roots = ["package.json", "tailwind.config.js", "tailwind.config.cjs"]
language-servers = [{ name = "typescript-language-server", except-features = [ "format" ] }, "tailwindcss-react"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

# Volar
[language-server.volar]
command = "vue-language-server"
args = ["--stdio"]

[language-server.volar.config]
typescript = { tsdk = "/opt/homebrew/lib/node_modules/typescript/lib" }


# tailwind vue
[language-server.tailwindcss-vue]
# Using a modified Tailwindcss LS, see https://github.com/helix-editor/helix/issues/2213#issuecomment-1556235820
# command = "tailwindcss-language-server"
command = "hx-tw"
args = ["--stdio"]
timeout = 3

# tailwind react
[language-server.tailwindcss-react]
command = "hx-tw"
args = ["--stdio"]
timeout = 5
```
