### DISCUSSION TITLE
Error getting code actions.

### DISCUSSION THREAD

**Discussion by H4ckint0sh** [helix-editor/helix#7135] [Q&A]
Getting this error when trying to show code actions

```
Async job failed: protocol error: InternalError: Request textDocument/codeAction failed with message: Cannot read properties of undefined (reading 'useFlatConfig')
```

Any one hade this before ?

**Comment by amritk** [comment]
@H4ckint0sh this actually worked for me

https://github.com/helix-editor/helix/issues/3520#issuecomment-1439987347

```toml
[language-server.eslint.config]
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""
```
