### DISCUSSION TITLE
grammars must have a file src/parser.c

### DISCUSSION THREAD

**Discussion by jonassmedegaard** [helix-editor/helix#7200] [General]
### Summary

`helix-loader` grammar compiler supports grammars that omit `src/scanner.c` but fail to compile if `src/parser.c` is missing.

### Reproduction Steps

I tried switching to the alternative Perl grammar in `languages.toml`:
```toml
[[grammar]]
name = "perl"
source = { git = "https://github.com/tree-sitter-perl/tree-sitter-perl", rev = "7dab73715fa18309102892eda2b190bcb3c7b9b4" }
```

`hx --grammar fetch` succeeded, but `hx --grammar build` failed.

[Patching helix to tolerate missing parser.c](https://salsa.debian.org/debian/hx/-/blob/debian/latest/debian/patches/1001_tree-sitter_parser_optional.patch) makes the build succeed, (and the resulting experience is a more reliable Perl grammar - I'll file a separate issue about that).

### Platform

Linux

### Terminal Emulator

alacritty 0.11.0

### Helix Version

helix 23.05
