### DISCUSSION TITLE
Sharing Themes

### DISCUSSION THREAD

**Discussion by CptPotato** [helix-editor/helix#727] [Show and tell] [answered]
I haven't found a Github issue or discusson for people to share their themes so I thought why not create one?

**Comment by CptPotato** [comment]
Everforest Dark (original by [sainnhe](https://github.com/sainnhe/everforest))

<details> 
<summary>everforest.toml</summary>

```toml
# Everforest (Dark Hard)
# Author: CptPotato

# Original Author:
# URL: https://github.com/sainnhe/everforest
# Filename: autoload/everforest.vim
# Author: sainnhe
# Email: sainnhe@gmail.com
# License: MIT License

## theme

"attribute" = "aqua"
"keyword" = { fg = "red" }
"keyword.directive" = "red"
"namespace" = "aqua"
"punctuation" = "grey2"
"punctuation.delimiter" = "grey2"
"operator" = "orange"
"special" = "purple"
"property" = "fg"
"variable.property" = "fg"
"variable" = "fg"
"variable.builtin" = "blue"
"variable.parameter" = "grey2"
"type" = "yellow"
"type.builtin" = "yellow"
"constructor" = { fg = "purple", modifiers = ["bold"] }
"function" = { fg = "green", modifiers = ["bold"] }
"function.macro" = "aqua"
"function.builtin" = "yellow"
"comment" = { fg = "grey0" }
"constant" = { fg = "purple" }
"constant.builtin" = { fg = "purple", modifiers = ["bold"] }
"string" = "green"
"number" = "purple"
"escape" = { fg = "fg", modifiers = ["bold"] }
"label" = "aqua"
"module" = "aqua"

"warning" = { fg = "yellow" }
"error" = { fg = "red" }
"info" = { fg = "aqua" }
"hint" = { fg = "blue" }

"ui.background" = { bg = "bg0" }
"ui.linenr" = { fg = "grey0" }
"ui.linenr.selected" = { fg = "fg" }
"ui.statusline" = { fg = "grey2", bg = "bg2" }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg1" }
"ui.popup" = { fg = "grey2", bg = "bg1" }
"ui.window" = { fg = "grey2", bg = "bg1" }
"ui.help" = { fg = "fg", bg = "bg1" }
"ui.text" = { fg = "fg" }
"ui.text.focus" = { fg = "fg" }
"ui.selection" = { bg = "bg3" }
"ui.cursor" = { fg = "bg0", bg = "fg" }
"ui.cursor.match" = { fg = "orange", bg = "bg3" }
"ui.cursor.insert" = { fg = "bg0", bg = "grey1" }
"ui.cursor.select" = { fg = "bg0", bg = "blue" }
"ui.menu" = { fg = "fg", bg = "bg2" }
"ui.menu.selected" = { fg = "bg0", bg = "green", modifiers = ["bold"] }

"diagnostic" = { modifiers = ["underlined"] }

## palette

[palette]

# hard
bg0 = "#2b3339"
bg1 = "#323c41"
bg2 = "#3a454a"
bg3 = "#445055"
bg4 = "#4c555b"
bg5 = "#53605c"
bg_visual = "#503946"
bg_red = "#4e3e43"
bg_green = "#404d44"
bg_blue = "#394f5a"
bg_yellow = "#4a4940"

# medium
# bg0 = "#2f383e"
# bg1 = "#374247"
# bg2 = "#404c51"
# bg3 = "#4a555b"
# bg4 = "#525c62"
# bg5 = "#596763"
# bg_visual = "#573e4c"
# bg_red = "#544247"
# bg_green = "#445349"
# bg_blue = "#3b5360"
# bg_yellow = "#504f45"

fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
aqua = "#83c092"
blue = "#7fbbb3"
purple = "#d699b6"
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"
```
</details>

*edit:* [the theme is included now](https://github.com/helix-editor/helix/wiki/Themes#everforest)
