### DISCUSSION TITLE
Optional LSP

### DISCUSSION THREAD

**Discussion by egorchakov** [helix-editor/helix#7298] [General] [answered]
Hey folks 👋  Helix has been my daily driver for several months now after a decade of (neo)vim and I'm a fan!

I often have to switch between several Python projects/virtualenvs with different LSPs installed (e.g. project A with `pyright` and project B with `pylsp`). Is there a way of handling this workflow more gracefully than toggling lines in `languages.toml` every time I switch between projects? Perhaps some kind of an optional LSP feature?

A simplified version of my current `languages.toml`:
```toml
[[language]]
name = "python"
scope = "source.python"
language-servers = [
  { name = "pyright" },
  { name = "pylsp" },
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pylsp]
command = "pylsp"

```
