### DISCUSSION TITLE
Svelte Comment Tags

### DISCUSSION THREAD

**Discussion by themixednuts** [helix-editor/helix#7363] [Troubleshooting]
In the "html" portion of svelte files, the comment tag doesn't change to wrapping the block in \

**Comment by the-mikedavis** [comment]
Block comments are not currently supported (#1505). C-c also does not add `<!--`/`-->` comments within HTML.

Once that is supported though we will need to choose comment tokens based on the injection layer: within the javascript and CSS portions we should use the tokens for those languages. (edit: https://github.com/helix-editor/helix/issues/7364)

**Comment by Ashton-Sidhu** [comment]
With the addition of block comments, I got it working in Svelte with:

```toml
# languages.toml

[[language]]
name = "svelte"
block-comment-tokens = {start = "<!--", end = "-->"}
```
