### DISCUSSION TITLE
Copy/paste delete some of the first character in the copied text

### DISCUSSION THREAD

**Discussion by FenosoaTiavina** [helix-editor/helix#7667] [General]
### Summary

When copying from outside of the terminal some character are note pasted inside the file.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `config-open`
3. Copy config from the helix documentation, eg: 
    ```toml
      [editor]
      line-number = "relative"
   ```
4. Paste it in the config.toml file
I expected this to happen:
```toml
      [editor]
      line-number = "relative"
   ```
Instead, this happened:
```toml
      tor]
      line-number = "relative"
   ```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

Windows terminal

### Helix Version

helix 23.05
