### DISCUSSION TITLE
C-a and C-x aren't as ergonomic to use as could be, when only one digit is selected

### DISCUSSION THREAD

**Discussion by vp2177** [helix-editor/helix#7686] [Ideas]
### Summary

C-a and C-x work in an unexpected way (for _ex-Vim_ users), when only one character is selected.

It's almost never the case that the user wants to only increment/decrement one digit in a number, instead of the whole number:

### Reproduction Steps

 

1. On a line containing, for example, `209km`
2. With the cursor on `9`, press `^a` (`C-a`)
3. The number now reads `2010km` (**expected** `210km`)
4. Move the cursor to the `1` in `2010`, press `^x`
5. The number now reads `2000km` (**expected** `2009km`)
6. Select the entire _word_ `2000km`, and press `^a`
7. Nothing happens. (**expected** `2001km`)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

Nothing relevant in helix.log

</details>

### Platform

Linux

### Terminal Emulator

_any_

### Helix Version

23.03

**Comment by the-mikedavis** [comment]
This behavior is intentional: increment/decrement act on the selection so you should select the number you want to increment/decrement before using C-a/C-x

**Comment by vp2177** [comment]
@the-mikedavis 
Ok, cheers! Selecting the number (just the number without the `km` suffix) works. 
Still somewhat unexpected but I guess this is the Helix way

**Comment by vp2177** [comment]
Actually I think this makes the C-a/C-x feature less useful than it could be, reopening. I've reworded the description a bit

**Comment by CptPotato** [comment]
If the number you want to increment/decrement is a separate word (i.e. "1234 km"), you can do this with a key bind:

```toml
C-a = [ "move_prev_word_start", "collapse_selection", "move_next_word_end", "increment" ]
C-x = [ "move_prev_word_start", "collapse_selection", "move_next_word_end", "decrement" ]
```
