### DISCUSSION TITLE
Some key remapping doesn`t work in select mode

### DISCUSSION THREAD

**Discussion by WhirlBean** [helix-editor/helix#7700] [Troubleshooting] [answered]
### Summary

some key remapping doesn`t work in select mode

### Reproduction Steps

 

I'm using colemak keyboard layout, so i make some remapping in helix.
most of them work well, but some doesn't work in select mode.

here is a part of my config:
```
[keys.select]
j = "yank"
n = "move_visual_line_down"
e = "move_visual_line_up"
i = "move_char_right"
k = "search_next"
K = "search_prev"

[keys.select.g]
i = "goto_line_end"
l = "goto_last_line"
```

selection doesn't extend when i use `n`, `e`, `i`, `k`, `K`, it worked like normal mode, and `gi`, `gl` are good.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

manjaro

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Helix Version

helix 23.05

**Comment by the-mikedavis** [comment, marked as answer]
The `move_*` functions should be `extend_*` in select mode instead:

```toml
[keys.select]
n = "extend_visual_line_down"
e = "extend_visual_line_up"
# ...
```

**Comment by WhirlBean** [comment]
```toml
k = "extend_search_next"
K = "extend_search_prev"
```

use `Space + ?` to check out all the commands.
