### DISCUSSION TITLE
ruby-lsp diagnostic

### DISCUSSION THREAD

**Discussion by Stanislav-Lapata** [helix-editor/helix#7725] [Q&A]
I have problem with diagnostic with ruby-lsp. Diagnostics are not shown 
ruby-lsp [supports diagnostic](https://shopify.github.io/ruby-lsp/RubyLsp/Requests/Diagnostics.html)
features are [enabled by default](https://github.com/Shopify/ruby-lsp/blob/main/lib/ruby_lsp/executor.rb#L471-L472)
Has somebody set ruby-lsp up with helix? 
I also found [that information](https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md#neovim-lsp)
> Ruby LSP only supports pull diagnostics

Does helix support pull diagnostics?
```
ruby-lsp --version                                                                                                                                                                       
0.7.3

hx --version
helix 23.05 (48d57dad)

hx --health ruby
Configured language server: ruby-lsp
Binary for language server: /Users/stanislavlapata/.local/share/rtx/installs/ruby/3.2.2/bin/ruby-lsp
Configured debug adapter: rdbg
Binary for debug adapter: /Users/stanislavlapata/.local/share/rtx/installs/ruby/3.2.2/bin/rdbg
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```
my config
```toml
[language-server]
[language-server.ruby-lsp]
command = "ruby-lsp" 
args = ["--debug"] 

# ... 

[[language]]
name = "ruby"
language-servers = [ { name = "ruby-lsp", only-features = ["format", "diagnostics"]}, {name = "solargraph", except-features = ["format", "diagnostics"]} ]
auto-format = true
```
