### DISCUSSION TITLE
Deno LSP relative import path

### DISCUSSION THREAD

**Discussion by hemedani** [helix-editor/helix#7734] [General] [answered]
when we setup `import` section on `deno.json`:
```json
﻿﻿﻿﻿﻿﻿﻿  "imports": {
    "deps": "../../../libs/bc/dbs/deps.ts",
    "share/": "../../../libs/bc/dbs/",
    "utils/": "../../../libs/bc/utils/",
    "interfaces/": "../../../libs/bc/interfaces/"
  }
```
and wants to use import path throw below errors:
```
relative import path "deps" not prefixed with / or ./ or ../ (import-prefix-missing)
```
![Screen Shot 1402-04-31 at 13 49 42](https://github.com/helix-editor/helix/assets/6236123/0fa8bc5a-80b1-478c-970f-603c62d4ad64)

**Comment by pascalkuthe** [comment]
Helix does not control deno, it seems like your configuration file is incorrect but this relates to deno-lsp not to helix

**Comment by sigmaSd** [comment, marked as answer]
In this discussion https://github.com/helix-editor/helix/discussions/2536 its mentioned how to override default importmap path you need something like 

```toml
[[language]]
name = "typescript"
roots = ["deno.json"]
language-server = { command = "deno", args = ["lsp"] }
config = { enable = true, importMap = "deno.json" } //this part
```
