### DISCUSSION TITLE
How to add multiple formatters to languages.toml

### DISCUSSION THREAD

**Discussion by AH-Merii** [helix-editor/helix#7749] [General] [answered]
I am currently using `black` formatter to autoformat my python code on save. Is it possible to add `isort` as a formatter in order to format my imports?

Here is part of my `languages.toml` file:

```toml
[[language]]
name = "python"
rulers = [79,88]
auto-format = true
formatter = {command = "black", args = ["-",  "--quiet","--line-length=88",]}
```

**Comment by pascalkuthe** [comment]
you can create a shell scpit that calls both

**Reply by AH-Merii** [reply]
Thanks for your prompt reply @pascalkuthe , do you mind providing me an example. I tried to get it to work but couldn't figure it out.

>langauges.toml
```toml
[[language]]
name = "python"
rulers = [79,88]
auto-format = true
formatter = {command = "~/.config/helix/python_formatter.sh"}
```

> python_formatter.sh
```bash
#!/bin/bash

# Check if there are any arguments
if [ "$#" -eq 0 ]; then
    isort --profile black . && black . "--quiet","--line-length=88"
    exit 1
fi

isort --profile black $1 && black $1 "--quiet","--line-length=88"
```
