### DISCUSSION TITLE
Help configuring haskell-language-server

### DISCUSSION THREAD

**Discussion by 0rphee** [helix-editor/helix#7759] [Q&A] [answered]
I've had trouble trying to configure hls...  my`languages.toml` looks like this:

```toml
[language-server.haskell-language-server] # hls config docs: https://haskell-language-server.readthedocs.io/en/latest/configuration.html#example-with-settings
config.haskell.formattingProvider = "stylish-haskell" # default is "ormolu"
config.haskell.checkParents = "NeverCheck" # default is "OnSave"
config.haskell.maxCompletions = 2 # default  is 40

[[language]]
name = "haskell"
roots = ["Setup.hs", "stack.yaml", "*.cabal"]
auto-format = true

```

but when using helix, this config is ignored, and the only relevant message that i find with hx -vvv is this, given vi hls, (emphasis on clientSettings):

```
2023-07-26T15:27:25.971 helix_term::application [DEBUG] received editor event: LanguageServerMessage((0, Notification(Notification { jsonrpc: Some(V2), method: "window/logMessage", params: Map({"message": String("Registering IDE configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri 7016388738248152297 \"file:///Users/roger/Documents/Dev/haskell-proj/xolsh\"], clientSettings = hashed Nothing}"), "type": Number(3)}) })))
```
I've tried looking for other people's config, without success...

Any help is appreciated!
