### DISCUSSION TITLE
How do I set Rust-Analyzer to do all features?

### DISCUSSION THREAD

**Discussion by Multirious** [helix-editor/helix#7787] [Q&A]
```toml
[[language]]
name = "rust"

[language.config]
cargo = { extraArgs = ["--all-features"], features = "all", allFeatures = true  }
check = { extraArgs = ["--all-features"] }
```
I've tried all of these at the same time and any of these with any combination in my `.helix/languages.toml` in my project directory.
I've insert some random invalid args and Rust-Analyzer did crashed so I know that it is listening.

**Comment by Multirious** [comment]
Does anyone have any config that works?

**Reply by kirawi** [reply]
`cargo.allFeatures = true` worked fine for me

**Reply by bbarker** [reply]
Where do you set this?

**Reply by TornaxO7** [reply]
you can try my answer: https://github.com/helix-editor/helix/discussions/7787#discussioncomment-7919199

**Comment by TornaxO7** [comment]
You can make use of [rust-analyzer.cargo.features]. You can add this to your `language.toml` file:
```toml
[language-server.rust-analyzer]
config = { cargo = { features = "all" } }
```

[rust-analyzer.cargo.features]: https://rust-analyzer.github.io/manual.html#rust-analyzer.cargo.features

**Reply by Multirious** [reply]
I've tried everything including this. I've just now tested this again with the above config in version `helix 23.10 (f6021dd0)` and the problem still persisted.
The message is `code is inactive due to #[cfg] directives: feature = "..." is disabled`

**Reply by Multirious** [reply]
I also tried
```toml
[language-server.rust-analyzer]
config = { cargo = { features = ["a_feature"] } }
```
and it doesn't seem to works too?

**Reply by TornaxO7** [reply]
May I ask where you have put this?
```toml
[language-server.rust-analyzer]
config = { cargo = { features = ["a_feature"] } }
```
Do you have an entry of `rust-analyzer` where you renamed it, hence `language-server.rust-analyzer` should be something like `language-server.rust`?
Could you please post your config?
