### DISCUSSION TITLE
I think the `ui.selection` and `markup.heading` colors are not easily distinguishable in the `emacs theme` in helix

### DISCUSSION THREAD

**Discussion by vagreargnatry** [helix-editor/helix#7797] [General] [answered]
![sample](https://github.com/helix-editor/helix/assets/104709852/68ef5239-2b3a-4997-b6c0-369fa4818cb0)

source file: https://guides.nyu.edu/LaTeX/sample-document

may be related:
* https://github.com/helix-editor/helix/blob/master/runtime/themes/emacs.toml
* https://github.com/search?q=repo%3Ahelix-editor%2Fhelix%20%40markup.heading&type=code

**Comment by vagreargnatry** [comment]
@Yevgnen Hello! Could you please help me modify the color in your free time? I am not good at choosing colors. I am currently using [this method](https://docs.helix-editor.com/themes.html#inheritance)

``` toml
inherits = "emacs"

"markup.heading" = { fg = "lightsteelblue1", modifiers = ["bold"] }
```
