### DISCUSSION TITLE
Questions related to remapping

### DISCUSSION THREAD

**Discussion by waldauf** [helix-editor/helix#7898] [Q&A] [answered]
Hello,

I would like to ask you for help with how to add new keyboard shortcuts:

1. Add shortcut for buffer switching: Ctrl-tab/Control-shift-tab. I tried this config, but it doesn't work.
```toml
[keys.normal]
C-tab = ":bn"
C-S-tab = ":bp"
```
2. How to remap the shortcut for code commenting? I would like to remap C-c to Space-c, but I didn't find out how because there isn't a command for commenting.
I tried:
```toml
[keys.normal]
space-c = { C-c }
```

Generally, is there a way how to list all existing keyboard shortcuts?

**Comment by woojiq** [comment, marked as answer]
1. `C-tab` doesn't work for me too. This works: 
```toml
[keys.normal]
A-h = ":buffer-previous"
A-l = ":buffer-next"
A-w = ":buffer-close"
```
Probably related to https://github.com/helix-editor/helix/issues/7533
2. Right now there is no way to map to another key. There was issue or PR but I can't find. You need to write command, not another key press. Like: `space-c = "toggle_comments"`.

You can look at list of all commands using `<space>?` shortcut.
