### DISCUSSION TITLE
How to setup lsp for scheme

### DISCUSSION THREAD

**Discussion by Esnos33** [helix-editor/helix#7927] [Q&A]
I want to learn scheme with chicken implementation and I wanted to have working lsp for that. Does somebody have working lsp for this scheme? I have found this lsp: https://codeberg.org/rgherdt/scheme-lsp-server#chicken, but after installing I can't make it work. Here is my current languages.toml:
```
[[language]]
name = "scheme"
language-server = [ "chicken-lsp-server" ]
```
and my current error is:
```
Bad language config: invalid length 4, expected struct LanguageServerConfiguration with 5 elements
in `language.language-server`

Press <ENTER> to continue with default language config
```

**Comment by woojiq** [comment]
If you look at [`languages.toml`](https://github.com/helix-editor/helix/blob/master/languages.toml) you will find, you need to provide configuration for the language server not only for the language itself.
Like: 
```toml
[language-server]

awk-language-server = { command = "awk-language-server" }
bash-language-server = { command = "bash-language-server", args = ["start"] }
...
```

**Comment by Esnos33** [comment]
Ok, so my config looks now like this:
```
[language-server.scheme]
command = "chicken-lsp-server"

[[language]]
name = "scheme"
```
I got this format of languages.toml from here: https://docs.helix-editor.com/master/languages.html
I'm on version 23.05 if that matters
Now I don't have any errors from helix, but I think helix don't see my lsp, because when I run helix --health scheme I got:
```
 hx --health scheme
Configured language server: None
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✘
Indent queries: ✘
```
but I can run lsp from command promt, so I should have lsp added to path, for example:
```
~/.c/helix> chicken-lsp-server --help
usage: chicken-lsp-server [--log-level <log-level>] [--socket <port-num>] [--stdio] [--version].
Example: chicken-lsp-server --log-level debug --socket 4222
Arguments:
    --log-level <level>: one of [error, warning, info, debug]. Default: error.
    --stdio <port-num>: use stdio for communication with a client. If stdio and socket are ommitted, stdio is used.
    --socket <port-num>: listen on tcp port <port-num> instead of stdio.
    --help (or -h):    display this help and exit.
    --version (or -v): display version information and exit.
```
And after creating new file lsp_test.scm and trying to edit there anything I have message "Language server not active for current buffer".
Should I try something else or do you know if there is some problem with my configurations?

**Reply by woojiq** [reply]
Sorry for not explaining clearly. Normally you don't need to write the lsp configuration in a config file because there are many in `languages.toml`. But your case is different, if you run `hx --health` you will see that there is no preconfigured lsp for `scheme`. This is why you can't just install a binary and everything will work out of the box.
So to work, you need to add an lsp for the scheme ([language]) and also configure this lsp ([language-server]). For example, run `ctrl-f` + `rust` in `languages.toml`, you will see `language-servers = [ "rust-analyzer" ]` inside `[[language]]` and a separate language server configuration:
```toml
[language-server.rust-analyzer]
command = "rust-analyzer"
```
In your case I think you will need something like this:
```toml
[language-server.chicken-lsp-server]
command = "chicken-lsp-server"
args = [ "--stdio" ]

[[language]]
name = "scheme"
language-servers = [ "chicken-lsp-server" ]
```

**Comment by Esnos33** [comment]
I have this weird bug, that says there shouldn't be "s" at the end in "language-servers":
```
hx lsp_test.scm
Bad language config: unknown field `language-servers`, expected one of `name`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `config`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-server`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language` 
```
I don't know why it is like that, but even if I change "language-servers" to "language-server" I got this weird error:
```
hx lsp_test.scm
Bad language config: invalid length 4, expected struct LanguageServerConfiguration with 5 elements
in `language.language-server`
```
So either way, it doesn't work. Do you know what else I can try?

**Reply by woojiq** [reply]
Make sure you use the master helix, https://github.com/helix-editor/helix/pull/2507 introduced the concept of multiple language servers and changed the syntax a bit.


**EDIT**: if you don't want to install master, try this:
```toml
[[language]]
name = "scheme"
language-server = { command = "chicken-lsp-server" }
```
