### DISCUSSION TITLE
static commands remap without user input

### DISCUSSION THREAD

**Discussion by nilsherzig** [helix-editor/helix#7938] [Q&A] [answered]
Hi, great editor. 

I would like to map something like this 

```toml
[keys.normal.tab]
"a" = ["select_regex", "align_selections"]
``` 

Without having to enter my select_regex pattern every time. Is this possible? I have to align comments & markdown tables quite a lot and this would be a very nice quality of life improvement.
