### DISCUSSION TITLE
Dart lsp Server Configuration Bug or Help

### DISCUSSION THREAD

**Discussion by nathananderson98** [helix-editor/helix#7969] [Troubleshooting] [answered]
I'm trying to change the default dart lsp formatter line length from 80 (default) to 120.

Sources:
- Looking at the base language config [here](https://github.com/helix-editor/helix/blob/master/languages.toml)
- Looking at the Dart lsp documentation [here](https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec#client-workspace-configuration)
- And the helix documentation [here](https://docs.helix-editor.com/languages.html#language-configuration)

Would lead me to believe that I can change the default `dart.lineLength` for my formatter, but I have not been able to ge anything to work.

I know my `.config/helix/languages.toml` is working because I can change the autoformat option on and off. Any help on this? Is this possible?

My `languages.toml`:
```toml
[[language]]
name = "dart"
# formatter = { command = "format", args = [ "-l", "120"] }  # I tried changing the format command, didn't work either
config = { lineLength = 120 }
# I tried all of these, refreshing the config each time, to no avail.
# config = { dart.lineLength = 120 }
# config = { "dart.lineLength" = 120 }
# config = { dartls.settings.dart.lineLength = 120 }
# config = { dart = { lineLength = 120 } }
# config = { settings = { dart = { lineLength = 120 } } }
# config = { dartls = { settings = { dart = { lineLength = 120 } } } }
```

**Comment by nathananderson98** [comment]
Only relevant Stack Overflow I could find, gave me the idea to try those other variations: [link](https://stackoverflow.com/questions/73573009/how-do-i-change-the-formatter-line-length-with-neovim-lsp-dart)

**Reply by solgar** [reply, marked as answer]
So I have achieved custom line length in dart using helix by specifying custom formatter that is actually `dart format`. I also couldn't force dart lsp to format with custom line length.

I have added following text to my `~/.config/helix/languages.toml`:

```toml
[[language]]
name = "dart"
formatter = {command = "dart", args = ["format", "-l", "120"]}
```

Funny thing is that `-l` or `--line-length` is actually hidden parameter of `dart format` https://github.com/dart-lang/dart_style/pull/1147/files#diff-81a62ea70b958516746798f662af162668e50464f0faf9d076cc17e2c6e73bd3 and is not printed when `dart format --help -v`.

**Reply by nathananderson98** [reply]
Ah, I can't believe I didnt try that. Thank you my good sir. I was manually calling `dart format -l 120` before merging code at work, this will save me :)

**Comment by kirawi** [comment]
Saw this, and there is a special `config.format` section: https://docs.helix-editor.com/languages.html#language-server-configuration

**Comment by ncdm-stldr** [comment]
@nathananderson98 Late answer sorry, but in case it helps someone:

The `config` field for the LSP should be in the language server section, not the language section. Like this:

```toml
[language-server.dart]
config = { dart.lineLength = 120 }
```

I may be wrong, but it seems to me that the formatting is faster when using the LSP rather than the custom `formatter = {command = "dart", args = ["format", "-l", "120"]}`
