### DISCUSSION TITLE
Is there a way to allow rust-analyzer to work on nightly?

### DISCUSSION THREAD

**Discussion by connortsui20** [helix-editor/helix#7987] [Q&A] [answered]
I tried to sort of follow the rust-analyzer `docs` with this:
```toml
# mimicking this: { "rust-analyzer.server.extraEnv": { "RUSTUP_TOOLCHAIN": "stable" } }
[language-server.rust-analyzer.server.extraEnv]
RUSTUP_TOOLCHAIN = "nightly"
```
But that didn't work out. Also, it doesn't work for the beta toolchain either.

Anyone have a solution to this?
