### DISCUSSION TITLE
Use of 0 and $ for line start / end

### DISCUSSION THREAD

**Discussion by Wisermans** [helix-editor/helix#801] [General] [answered]
Same as VI/VIM, the use of '0' to go at start of line and '$' to go at end of line would be useful as it is much quicker than Home / End, the same way JKLM is already used in spite of arrows.

**Comment by sudormrfbin** [comment, marked as answer]
We have `gh` and `gl` respectively for goto line start/end (inspired from kakoune) and it's possible to remap if you really want to emulate vim with a caveat for `0`:

```toml
# ~/.config/helix/config.toml

[keys.normal]
"0" = "goto_line_start" # Note that this will not work because 0 will be taken as a count
"$" = "goto_line_end"
```
