### DISCUSSION TITLE
My Helix seems to ignore newlines provided by Prettier. Perhaps I've misconfigured something?

### DISCUSSION THREAD

**Discussion by Teajey** [helix-editor/helix#8042] [Q&A]
I've noticed that Helix is only "half" formatting my TS/JS files, and I've boiled it down to this:

Given the file `formatThis.js`:
```js
console.log("123");

function                 helloWorld() { console.log("Hello, world!"); }
```
Running it directly through Prettier I get this:
```
[thomas@thomas-mbp ~/code/js] cat formatThis.js | prettier --parser=typescript
console.log("123");

function helloWorld() {
  console.log("Hello, world!");
}
[thomas@thomas-mbp ~/code/js]
```
If I run `:fmt` on this file in Helix, only the excess whitespace is removed after `function`, but the newlines aren't inserted:
```js
console.log("123");

function helloWorld() { console.log("Hello, world!"); }
```

My Typescript config in `~/.config/helix/languages.toml` looks like this:
```toml
[[language]]
name = "typescript"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser=typescript"]
```
I haven't filed this a bug report, because I don't know if I'm just doing something wrong on my end, or maybe this is a known issue? Either way, can't find anything about this, and it's very confusing.

**Comment by erasin** [comment]
your file `formatThis.js` is javascript, and your config is `typescript` lanauge.

```
[[language]]
name="javascript"

[language.formatter]
command = "prettier"
args = ["--parser=typescript"]

[[language]]
name = "typescript"

[language.formatter]
command = "prettier"
args = ["--parser=typescript"]

[[language]]
name = "tsx"

[language.formatter]
command = "prettier"
args = ["--parser=typescript"]

[[language]]
name = "jsx"
[language.formatter]
command = "prettier"
args = ["--parser=typescript"]



```

**Reply by Teajey** [reply]
Hmm, I assumed it would target all of these under the umbrella of Typescript

Regardless, the problem still persists even if I target each language specifically as you suggest

**Reply by Teajey** [reply]
It does have the same behaviour even if I remove Prettier from the config entirely... So I guess I've just failed to configure it at all. Although I can't find anything in the logs about this

**Reply by erasin** [reply]
Try use command `:format`, or add config `auto-format = true` and reload config.

**Reply by Teajey** [reply]
`:fmt` is just an alias for `:format`. At the end of the original post I showed my config, where you'll see `auto-format = true` is already set

**Reply by givenergy-dexter** [reply]
I've noticed this too. I have the following config:
```toml
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
```

Formatter runs but I've noticed it's not flagging project specific configuration (e.g. requiring the use of `unknown` rather than `any`).

**Reply by Teajey** [reply]
I wish I could remember how I resolved this, it's not a problem for me anymore. For what it's worth, here's what my prettier-related config looks like now. I'm using [efm-langserver](https://github.com/mattn/efm-langserver) as per the Helix docs: https://docs.helix-editor.com/languages.html#language-server-configuration

And I'm using the Prettier daemon [prettierd](https://github.com/fsouza/prettierd) because it's a lot faster than running Prettier from a cold start on every format

```toml
[language-server.efm-lsp-prettier]
command = "efm-langserver"
[language-server.efm-lsp-prettier.config]
documentFormatting = true
[[language-server.efm-lsp-prettier.config.languages.typescript]]
formatCommand ="prettierd --stdin-filepath ${INPUT}"
formatStdin = true
[[language-server.efm-lsp-prettier.config.languages.typescriptreact]]
formatCommand ="prettierd --stdin-filepath ${INPUT}"
formatStdin = true
[[language-server.efm-lsp-prettier.config.languages.css]]
formatCommand ="prettierd --stdin-filepath ${INPUT}"
formatStdin = true
[[language-server.efm-lsp-prettier.config.languages.scss]]
formatCommand ="prettierd --stdin-filepath ${INPUT}"
formatStdin = true
[[language-server.efm-lsp-prettier.config.languages.html]]
formatCommand ="prettierd --stdin-filepath ${INPUT}"
formatStdin = true


[[language]]
name = "typescript"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "typescript-language-server", "eslint" ]
auto-format = true


[[language]]
name = "tsx"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "typescript-language-server", "eslint" ]
auto-format = true


[[language]]
name = "css"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "vscode-css-language-server" ]
auto-format = true


[[language]]
name = "scss"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "vscode-css-language-server" ]
auto-format = true


[[language]]
name = "html"
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] }, "vscode-html-language-server" ]
auto-format = true
```
