### DISCUSSION TITLE
duplicate line/selection command

### DISCUSSION THREAD

**Discussion by tkkcc** [helix-editor/helix#8052] [Ideas]
`duplicate line/selection` is a common function for text editor. 

current i use `,d` to do this, and `,D` to do this with old selection comment out. also keep cursor position.

```toml
[keys.normal.","]
d=["save_selection", "extend_to_line_bounds", "yank", "paste_before", "jump_backward" ]
D=["save_selection", "extend_to_line_bounds", "toggle_comments", "yank", "paste_before", "jump_backward","toggle_comments" ]
```

however, this still mess undo history and clipboard. should this be builtin or as plugin?
