### DISCUSSION TITLE
How do I get highlights working for templ files?

### DISCUSSION THREAD

**Discussion by Teajey** [helix-editor/helix#8154] [Q&A] [answered]
I want to edit .templ files in Helix for my Go server: https://github.com/a-h/templ

I've gotten as far as successfully adding the language and grammar:
```toml
[[language]]
name = "templ"
auto-format = true
scope = "source.templ"
injection-regex = "templ"
grammar = "templ"
file-types = ["templ"]
roots = ["go.sum"]
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
language-server = { command = "templ", args = ["lsp"] }
formatter = { command = "templ" , args = ["fmt"] }

[[grammar]]
name = "templ"
source = { git = "https://github.com/vrischmann/tree-sitter-templ", rev = "6ab863186d1ba91718125f59deae6cf68d765fcb" }
```
The tree-sitter grammar appears to have support for highlights: https://github.com/vrischmann/tree-sitter-templ/tree/master/queries

But after running `hx --grammar fetch` and `hx --grammar build` I'm still not seeing highlights in the editor, or under `--health`:
```
[thomas@thomas-mbp ~/.config/helix] hx --health templ
Configured language server: templ
Binary for language server: /Users/thomas/go/bin/templ
Configured debug adapter: None
Highlight queries: ✘
Textobject queries: ✘
Indent queries: ✘
[thomas@thomas-mbp ~/.config/helix]
```
Any ideas what I might be missing?
