### DISCUSSION TITLE
rust-analyzer does not pick up the `overrideCommand` setting

### DISCUSSION THREAD

**Discussion by rohel01** [helix-editor/helix#8168] [Troubleshooting]
Hello,

I am using Helix 23.05 and want to configure Helix to use clippy to compute diagnostics. I have the following configuration in the `.helix/languages.toml` file at the root of my Rust project

```toml
[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
overrideCommand = [
        "cargo",
        "clippy",
        "--quiet",
        "--message-format=json",
        "--workspace"
    ]
```

Yet, no clippy diagnostics are displayed by Helix. When I run clippy through bacon, I do see them.

What am I doing wrong?
