### DISCUSSION TITLE
Scrolling with constant cursor vertical positioning

### DISCUSSION THREAD

**Discussion by rohel01** [helix-editor/helix#8179] [Q&A] [answered]
Hello,

I would like to scroll in a file while maintaining my cursor at a constant vertical position. This is pure ergonomic improvement as I no longer need to look for the cursor on the screen after I moved.

To do so, I created the following mapping on my Helix `config.toml`, inspired by a previous vim config.

```toml
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
C-b = ["page_up", "align_view_center"]
C-f = ["page_down", "align_view_center"]
```

This works fine except when scrolling up near the top of the file: the window does not move at all.
Do you know a better way to achieve a similar effect?
