### DISCUSSION TITLE
efm-langserver

### DISCUSSION THREAD

**Discussion by pivoshenko** [helix-editor/helix#8188] [Troubleshooting]
Hi guys 👋🏻 Hope you are ok!

I just started using `helix` and I absolutely love it 🔥 But I faced a really weird problem with using [`efm-langserver`](https://github.com/mattn/efm-langserver) in `helix`.
The problem is next: the LSP server shows the error, I am fixing the error but `helix` still shows the error, so I need to run `:lsp-restart` so it will disappear. Basically, I need to run `:lsp-restart` on every code change 🙂

I tested `efm-langserver` in other editors and it works as expected, so I am only encountering this problem in `helix`. Would be super grateful if someone could assist ❤️

**Examples**
![Screenshot 2023-09-05 at 23 21 58](https://github.com/helix-editor/helix/assets/40499728/1679aaa0-d16b-4bdd-abfd-361fccc49a76)
![Screenshot 2023-09-05 at 23 22 26](https://github.com/helix-editor/helix/assets/40499728/06454c42-baaa-42bf-9691-9787d633e0d3)

```toml
# ~/.config/helix/config.toml
theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
bufferline = "always"
shell = ["zsh", "-c"]
true-color = true
color-modes = true
cursorline = true
mouse = true
rulers = [100]
completion-trigger-len = 1

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = [
    "selections",
    "primary-selection-length",
    "position",
    "position-percentage",
    "spacer",
    "diagnostics",
    "workspace-diagnostics",
    "version-control"
]
separator = "│"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
C-f = [
    ":new",
    ":insert-output lf-pick",
    ":theme default",
    "select_all",
    "split_selection_on_newline",
    "goto_file",
    "goto_last_modified_file",
    ":buffer-close!",
    ":theme catppuccin_macchiato"
]
```

```toml
# ~/.config/helix/languages.toml
[language-server.efm]
command = "efm-langserver"

[[language]]
name = "python"
language-servers = [
  { name = "efm", only-features = [ "diagnostics", "format" ] },
]
```

```yaml
#  .config/efm-langserver/config.yaml
version: 2
root-markers:
  - .git/
  - .svn/
  - pyproject.toml
  - Cargo.toml

tools:
  codespell: &codespell
    lint-command: 'codespell'
    lint-formats:
      - '%f:%l: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --show-column-numbers'
    # lint-formats:
    #   - '%f:%l:%c: %trror: %m'
    #   - '%f:%l:%c: %tarning: %m'
    #   - '%f:%l:%c: %tote: %m'

languages:
  python:
    - <<: *codespell
    - <<: *python-mypy
```
