### DISCUSSION TITLE
How to refer to the current directory and filepath when running a command?

### DISCUSSION THREAD

**Discussion by rochacbruno** [helix-editor/helix#8203] [Q&A] [answered]
On vim we can use `getcwd()` and `expand('%:p:h')` to read current dir and filepath.

Is there any filename-modifiers for helix to use when binding commands?

I want to do something like this

```toml
[keys.normal]
o = [":cd {current_buffer_dir}", "global_search"]
```
