### DISCUSSION TITLE
"hx --health" is overbearing, with 189 lines currently. Why not allow what is shown to be user-configured?

### DISCUSSION THREAD

**Discussion by luccahuguet** [helix-editor/helix#8313] [Ideas] [answered]
the user could have a config variable holding the names of languages/tools that he is most interested in

for example: 

```toml
[editor.health]
focus = ["HTML", "JavaScript", "Python", "Java", "C", "C++", "CSS", "SQL", "bash", "Go"]
```

so running `hx --health` would only show those.

and when the user needs to see all of them (rarely), they could just `hx --health all` or `hx --health-all`

this feature could have sinergies or be implemented together with https://github.com/helix-editor/helix/issues/7401
