### DISCUSSION TITLE
pylsp plugin configuration

### DISCUSSION THREAD

**Discussion by staticf0x** [helix-editor/helix#8337] [Q&A]
How do I configure pylsp plugins properly?

This is my `~/.config/helix/languages.toml`:

```toml
[[language]]
name = "python"

[language.config.pylsp.plugins]
flake8 = {enabled = false}
ruff = {enabled = true}
```

Now if I open any python file, I can see errors coming from flake8 (with or without ruff enabled, because they share the same error codes).

I followed [this discussion](https://github.com/helix-editor/helix/discussions/6623) but it didn't work for me.
