### DISCUSSION TITLE
Multiple LSPs for the same file type based on roots

### DISCUSSION THREAD

**Discussion by brielov** [helix-editor/helix#8372] [Q&A] [answered]
Hi, I'm running helix from master with multiple lsp support. I need to configure both `typescript-language-server` and `deno` for typescript files based on different roots. For example `roots = ["package.json"]` would use `typescript-language-server` (and others) and `roots = ["deno.json", "deno.jsonc"]` would use `deno lsp`.

Can't seem to figure out how to setup this.

My current `languages.toml` file

```toml
[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.emmet-ls]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.deno-ls]
language-id = "typescript"
command = "deno"
args = ["lsp"]

[language-server.deno-ls.config]
enable = true
lint = true
unstable = true

[language-server.eslint-ls]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint-ls.config]
format = true
nodePath = ""
onIgnoredFiles = "off"
packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = { }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[language-server.typescript-language-server.config]
documentFormatting = false
hostInfo = "helix"

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "emmet-ls"]
auto-format = true

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls", "emmet-ls"]
auto-format = true

[[language]]
name = "json"
language-servers = [ "vscode-json-language-server" ]
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["deno-ls"]
auto-format = true
roots = ["deno.json", "deno.jsonc"]

# [[language]]
# name = "typescript"
# language-servers = ["typescript-language-server", "tailwindcss-ls", "eslint-ls", "emmet-ls"]
# formatter = { command = "prettier", args = ["--parser", "typescript" ]}
# auto-format = true
# roots = ["package.json"]

# [[language]]
# name = "tsx"
# language-servers = ["typescript-language-server", "tailwindcss-ls", "eslint-ls", "emmet-ls"]
# formatter = { command = "prettier", args = ["--parser", "typescript" ]}
# auto-format = true
# roots = ["package.json"]

# [[language]]
# name = "javascript"
# language-servers = ["typescript-language-server", "tailwindcss-ls", "eslint-ls", "emmet-ls"]
# formatter = { command = "prettier", args = ["--parser", "typescript" ]}
# auto-format = true
# roots = ["package.json"]
```

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/issues/8119

**Comment by kirawi** [comment]
Sorry, I realize I misread and this issue is not related to the linked issue. There is a new issue covering this: https://github.com/helix-editor/helix/issues/8505

**Comment by stefanfrede** [comment]
@brielov I have the same problem as you. Have you found a solution?

This is what I tried, which is quite similar to yours:
```toml
[[language]]
name = "typescript"
file-types = ["ts"]
shebangs = ["node"]
roots = ["package.json"]
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  { name = "biome" },
  { name = "scls" },
]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "a.ts",
] }

[[language]]
name = "typescript"
file-types = ["ts"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc"]
auto-format = true
language-servers = [
  { name = "deno-lsp", except-features = [
    "format",
  ] },
  { name = "biome" },
  { name = "scls" },
]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "a.ts",
] }
```

**Reply by brielov** [reply]
I ended up making a simple script that initializes a new deno project with deno-specific lsp stuff inside a local `.helix` folder. So example, I have `.local/bin` on my path and inside a script named `dix` (deno init helix) with the following:

```sh
#!/bin/bash

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Emojis
CHECK_MARK="\xE2\x9C\x94"
X_MARK="\xE2\x9D\x8C"

# Configuration content
config_content=$(cat <<EOF
[language-server.deno-ls]
command = "deno"
args = ["lsp"]
config = { enable = true, unstable = true }

[[language]]
name = "typescript"
language-servers = ["deno-ls"]
auto-format = true
EOF
)

# Banner
echo -e "${YELLOW}===============================${NC}"
echo -e "${YELLOW}  Deno Project Initialization  ${NC}"
echo -e "${YELLOW}===============================${NC}"
echo -e "This script will initialize a new Deno project"
echo -e "and create a hidden '.helix' directory with"
echo -e "configuration for the 'helix' editor for optimal"
echo -e "integration with 'deno lsp'.${NC}"

# Specify the binary name
binary_name="deno"

# Find the path of the binary
binary_path=$(command -v "$binary_name")
directory_path="$(pwd)/.helix"
file_name="$directory_path/languages.toml"

# Check if the binary is not found or not executable
if [ ! -x "$binary_path" ]; then
    echo -e "${RED}${X_MARK} Error:${NC} Binary '$binary_name' not found or not executable."
    exit 1
fi

# If the script hasn't exited, it means the binary was found and is executable
echo -e "${GREEN}${CHECK_MARK}${NC} Binary '$binary_name' found at: $binary_path"

# Initialize using deno init (hide the output)
"$binary_path" init > /dev/null 2>&1

# Check if the directory exists
if [ ! -d "$directory_path" ]; then
    # If the directory does not exist, create it
    mkdir -p "$directory_path"
    echo -e "${GREEN}${CHECK_MARK}${NC} Directory '$directory_path' created."
else
    echo -e "${GREEN}${CHECK_MARK}${NC} Directory '$directory_path' already exists."
fi

# Check if the file exists and has content
if [ -f "$file_name" ] && [ -s "$file_name" ]; then
    # File exists and has content, check if the lines to append are already present
    if ! grep -q "\[language-server.deno-ls\]" "$file_name"; then
        # Lines are not present, append them
        echo -e "$config_content" >> "$file_name"
        echo -e "${GREEN}${CHECK_MARK}${NC} Configuration appended to '$file_name'."
    else
        echo -e "${GREEN}${CHECK_MARK}${NC} Configuration already present in '$file_name'."
    fi
else
    # File does not exist or is empty, create it
    echo -e "$config_content" > "$file_name"
    echo -e "${GREEN}${CHECK_MARK}${NC} File '$file_name' created with configuration."
fi
```

So, any time I want to write some deno, I create an empty folder and run `dix` from my terminal and it is ready to go. I would love to be able to configure this in `languages.toml` but it seems it is not yet possible. Hope this helps though.

**Reply by kirawi** [reply]
https://github.com/helix-editor/helix/pull/8696 should have implemented a way to this within Helix

**Reply by stefanfrede** [reply]
~`required-root-patterns` did the trick!~ Thank you :pray:

***
Edit:
I was too enthusiastic, and unfortunately it still does not work with `required-root-patterns` as expected (I forgot to remove my Helix configuration for the project).
***

Here is an extract from my configuration:
```toml
[language-server.deno-lsp]
required-root-patterns = ["deno.json", "deno.jsonc", "deno.lock"]

[language-server.typescript-language-server]
required-root-patterns = ["tsconfig.json"]

[[language]]
name = "typescript"
file-types = ["ts"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "tsconfig.json"]
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  { name = "biome" },
  { name = "scls" },
]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "a.ts",
] }
```
***
Edit:
I don't understand why the `required-root-patterns` is for the language-server and not for the language, as this would solve the problem (I guess).
***

**Reply by kirawi** [reply]
You might also have to add deno to the list of LSPs for TS

**Reply by stefanfrede** [reply, marked as answer]
I'm cautiously optimistic that this is it:
```toml
[language-server.biome]
args = ["lsp-proxy"]
command = "biome"

[language-server.deno-lsp]
args = ["lsp"]
command = "deno"
required-root-patterns = ["deno.*"]

[language-server.deno-lsp.config.deno]
enable = true
suggest = { completeFunctionCalls = false, imports = { hosts = { "https://deno.land" = true } } }

[language-server.typescript-language-server]
required-root-patterns = ["package.json", "tsconfig.json"]

[[language]]
name = "javascript"
language-id = "javascript"
scope = "source.js"
injection-regex = "^(js|javascript)$"
file-types = ["js"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "package.json", "tsconfig.json"]
auto-format = true
language-servers = [
  { name = "deno-lsp", except-features = [
    "format",
  ] },
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "a.js",
] }

[[language]]
name = "jsx"
language-id = "javascriptreact"
scope = "source.jsx"
injection-regex = "^(jsx)$"
file-types = ["jsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "package.json", "tsconfig.json"]
auto-format = true
language-servers = [
  { name = "deno-lsp", except-features = [
    "format",
  ] },
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "a.jsx",
] }

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "package.json", "tsconfig.json"]
auto-format = true
language-servers = [
  { name = "deno-lsp", except-features = [
    "format",
  ] },
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "a.ts",
] }

[[language]]
name = "tsx"
language-id = "typescriptreact"
scope = "source.tsx"
injection-regex = "^(tsx)$"
file-types = ["tsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "deno.jsonc", "package.json", "tsconfig.json"]
auto-format = true
language-servers = [
  { name = "deno-lsp", except-features = [
    "format",
  ] },
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
formatter = { command = "biome", args = [
  "format",
  "--stdin-file-path",
  "a.tsx",
] }

```
