### DISCUSSION TITLE
How to pass input while debugging?

### DISCUSSION THREAD

**Discussion by bencornia** [helix-editor/helix#8387] [Q&A] [answered]
I am able to debug c just fine in helix. However, I haven't been able to figure out how to pass input to the binary at the same time as debugging. For example, when running from the command line I typically would do:
`/path-to-binary < input.txt`

How would I recreate this in helix. I am assuming I need to create a custom language debugger template in languages.toml. Thanks for any suggestions.

**Comment by bencornia** [comment, marked as answer]
After digging around the documentation a little bit, I stumbled onto the wiki for [Debugger Configurations](https://github.com/helix-editor/helix/wiki/Debugger-Configurations). It links to the docs for lldb-vscode [Launch Configuration Settings](https://github.com/llvm/llvm-project/tree/main/lldb/tools/lldb-vscode#launch-configuration-settings).

I was able to figure out how to redirect input using plain lldb. After futzing with my languages.toml, I was able to map the commands correctly. Here is what I landed on:

```toml
[[language.debugger.templates]]
name = "binary with input"
request = "launch"
completion = [ { name = "binary", completion = "filename" }, { name = "Absolute Path to Input File", completion = "filename"} ]
program = "{0}"
args = { console = "internalConsole", program = "{0}", preRunCommands = ["settings set target.input-path {1}"] }
```

I am brand spanking new to both helix and lldb, so it was a baptism by fire. Fortunately, everything is working smoothly now!
