### DISCUSSION TITLE
Selection of injections via textobjects

### DISCUSSION THREAD

**Discussion by carrascomj** [helix-editor/helix#8429] [Ideas]
https://github.com/helix-editor/helix/issues/2311 is a very nice unintended behavior when working with notebook-like (markdown/quarto/org) files, where one can just `Alt-o` and press another keybind that sends the selection to a REPL (currently doing this with wezterm, it can be done with tmux or similar). 

```toml
[keys.normal]
ret = ":pipe-to cat - <(echo ) | wezterm cli send-text --pane-id `wezterm cli get-pane-direction right`"
```

Once the issue is fixed, it would be great if there was a textobject to select the injection block at the cursor.
