### DISCUSSION TITLE
Can we get a basic working eslint config into Helix by default? Discussion on what it should be...

### DISCUSSION THREAD

**Discussion by David-Else** [helix-editor/helix#8452] [General]
JS is probably the world's most used language now, and everyone that uses it will probably want to use ESlint. It is installed by default with the https://github.com/hrsh7th/vscode-langservers-extracted package that contains our defaults for CSS, HTML and JSON.

Now we have multiple language server support I propose we should have working defaults built in so users can easily add things like ESLint if they want.

The best source I have found for setting ESLint up is @Philipp-M 's excellent https://github.com/helix-editor/helix/pull/2507#issuecomment-1280823623 (@cd-a had some great input in the thread) which I have boiled down to:

```toml
[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
# format = true
nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "yarn"
quiet = false
rulesCustomizations = []
run = "onType"
# useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
# codeActionsOnSave = { mode = "all" }
experimental = {}
problems = { shortenToSingleLine = false }
# workingDirectory = { mode = "auto" }
```
Then the user can add it easily:
```toml
[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "eslint" ]
```
The references to what these settings are doing is all at https://github.com/microsoft/vscode-eslint#settings-options. The lines I have commented out seem to be optional, but I could be mistaken. Can we agree on what is the bare most unopinionated settings to get it working and add it to Helix by default? It would save people from the config hell that Helix is trying to deliver them from :)

**Comment by cd-a** [comment]
I totally agree, great point. Should't we also include prettier here? Since Eslint + Prettier is pretty much the combo everyone uses?

**Reply by David-Else** [reply]
Prettier is a CLI app specifically for formatting so can be set easily by the user without any config:
```
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
```
As it conflicts with the default language servers formatting it might need an additional Helix config setting like `"use prettier as default formatter": true` which activates it for all the languages available. That would be cool, but I am not sure if maintainers want that type of 3rd party integration?

**Reply by Rudxain** [reply]
> [If you've installed it locally only, it won't be in `PATH`, so replace all `command = 'prettier'` by `command = 'npx'` and add `"prettier"` as the 1st element of `args`.](https://github.com/helix-editor/helix/wiki/External-formatter-configuration/aec63570c0e42eabe7494523912797a64c5685fe#Prettier)

**Reply by EmrysMyrddin** [reply]
For ones working with actual projects, the version of prettier is most likely pined in the repo itself. So you must use your package manager to resolve the correct version of prettier to use.
You must use something like this, depending of the package manager used:

- Pnpm:
```toml
[[language]]
name = "typescript"
formatter = { command = "pnpm", args = ["exec", "prettier", "--parser", "typescript"] }
````

- Yarn
```toml
[[language]]
name = "typescript"
formatter = { command = "yarn", args = ["exec", "prettier --parser typescript"] }
```

- Npm
```toml
[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
```

**Reply by victorz** [reply]
We should be able to set this on a per-project basis, kind of like a .vscode folder but for helix. Maybe that's possible already?

**Reply by Rudxain** [reply]
`.helix/languages.toml`

**Reply by EmrysMyrddin** [reply]
I've since switched to use [prettierd](https://github.com/fsouza/prettierd). It starts a prettier instance in the background to avoid the cost of spawning a new process each time you format your code.
It leads to much more responsive formatting requests ! Nearly instantaneous :-)
And the last but not least: You can configure it to always prefer the directory local prettier instance instead of any global one, without wondering if the repo uses yarn, pnpm or something else.

**Comment by morlinbrot** [comment]
Thanks for opening this discussion, I would love for Helix to provide some web dev capabilities out of the box at some point.

I created an example NextJS project which is correctly configured for Typescript + ESLint + Prettier/dprint and a corresponding Helix config which you can find here: https://github.com/morlinbrot/helix-webdev-config (I never new if it was Helix or the project not being configured correctly).

I wanted to share it here as a reference for the discussion and would be happy to update it to eventually arrive at something that could be considered a default Helix web dev config. It is building on @Philipp-M's original config (but simplified) and @David-Else's minimal set of options for the ESLint langserver.

Unfortunately, _**I did not yet get ESLint auto-formatting to work**_. It's mostly fine for me because dprint is taking care of most auto-formatting but there are some things that ESLint will lint but not auto-format, for example:
```
const obj = {
  foo,
  bar
  baz,
}
```
The missing comma in the middle is being detected by ESLint but not auto-formatted and this also keeps dprint from adding a semicolon on the last line.

My config is slightly different from @David-Else's but both are not working for me. According to the docs, these options should make it work:
```
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
```
(Btw, @David-Else, you have a typo in your config, it's `codeActionsOnSave`, not `codeActionOnSave`.)

_**Does anybody have a working, auto-formatting `vscode-eslint-language-server` that they could share here?**_ That is the last puzzle piece to complete my minimal web dev config.

**Reply by Rudxain** [reply]
FYI (and anyone reading this), [ESL no longer supports formatting](https://eslint.org/blog/2023/10/deprecating-formatting-rules) :( . It's sad, but reasonable

**Comment by dusty-phillips** [comment]
I also tried digging into this; it seems like `codeActionsOnSave` will not work without https://github.com/helix-editor/helix/pull/6486

**Comment by Rudxain** [comment]
I thought this was already fixed in [24.7](https://github.com/helix-editor/helix/releases/tag/24.07), because of this:
https://github.com/helix-editor/helix/blob/35f1c2a55f2cdf396c26cbe5a8433b009e1b9f01/languages.toml#L202-L222

So [I added it to the Wiki](https://github.com/helix-editor/helix/wiki/Language-Server-Configurations/2819483545c091602895b5318bab03d7f6aae79f#ESlint), but I've noticed it doesn't work, so I simply linked back to this discussion

**Reply by Rudxain** [reply]
- https://github.com/hrsh7th/vscode-langservers-extracted/pull/11
- https://github.com/helix-editor/helix/pull/11315

**Reply by Rudxain** [reply]
https://github.com/helix-editor/helix/wiki/Language-Server-Configurations/38d848b68d4f8a5d7a7b9e8a6adf71bb2f6e0774#ESLint

**Comment by samankittani** [comment]
Just FYI to anyone struggling. If you use the new flat config `eslint.config.{js,ts}`, make sure you include `experimental = { useFlatConfig = false }`. As things roll towards flat-config format, the  `experimental = { useFlatConfig = false }` should at least be mentioned as needed if using the flat config format, if not default.

**Reply by ggobbe** [reply]
Can you send your whole languages.toml file? I installed vscode-langservers-extracted 4.8.0 but can't make it work for formatting. Currently fails on `Cannot read file "......./tsconfig.json"` because it tries to read tsconfig.json files in weird locations.

**Reply by samankittani** [reply]
There is a lot of fluff in my langauges.toml file. So I just included the tsconfig parts. Hope this helps, and sorry for the delay.
```toml
[language-server.eslint-lsp]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint-lsp.config] # Complementary from https://github.com/helix-editor/helix/discussions/8452
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
experimental = { useFlatConfig = true } # THIS is the line I mentioned above.
problems = { shortenToSingleLine = false }

# JAVASCRIPT:
[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "eslint-lsp"] # ADD eslint-lsp to your langauge. 
formatter = { command = 'prettier', args = ['--parser', 'babel'] }
auto-format = false

# TYPESCRIPT:
[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "eslint-lsp"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

```
