### DISCUSSION TITLE
Theme can't be set in the config file

### DISCUSSION THREAD

**Discussion by CastilloDel** [helix-editor/helix#8530] [Troubleshooting] [answered]
### Summary

The theme can be updated at runtime, but not from the config

### Reproduction Steps

 

I tried this:

1. Add the following `.config/helix/config.toml`:
```toml
theme = "github-dark-dimmed"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode
j = "normal_mode" # Maps `jj` to exit insert mode

[keys.insert.k]
j = "normal_mode" # Maps `kj` to exit insert mode
k = "normal_mode" # Maps `kk` to exit insert mode

```
2. Use `hx`

I expected this to happen:
To see the "github-dark-dimmed" theme

Instead, this happened:
The default theme appeared.

I also tried this with other themes. They seem to work at runtime, but not if I set them from the config

### Platform

Ubuntu Linux 23.04

### Terminal Emulator

Alacritty 0.11.0

### Helix Version

helix 23.05 (7f5940be)
