### DISCUSSION TITLE
How to setup pylsp with black formatter?

### DISCUSSION THREAD

**Discussion by MarkuBu** [helix-editor/helix#8567] [Q&A]
Hi, I try to configure the Python LSP for Helix. The LSP itself is running. But I want to add the black formatter plugin, but it doesn't work automatically.

I created a venv and activated it. Then I installed pylsp with pip. If I open a file in Helix the LSP is working. I installed the black lsp plugin and I can run black manually. But I don't know how to run it automatically inside Helix, e.g. if I save a file, and reload the new version.

How can I set this up?

Edit: found the answer

https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration#black

**Comment by akhilman** [comment]
Black formatter can be integrated to pylsp itself. Here is my configuration ~~(not tested, just ported from NeoVIM)~~:

languages.toml
```toml
[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pylint.enabled = true
plugins.pyflakes.enabled = false
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true
```

And requirements.txt to install everything needed:
```
black
isort
jedi
pyflakes
pylint
pyls-isort
python-lsp-black
python-lsp-server[rope,pylint]
rope
```

Update Dec 11 2023:
Tested it in a virtual environment. everything works fine. The ending of the `language-server.pylsp.config.pylsp` is required, without this extra `.pylsp` auto-import does not work.
