### DISCUSSION TITLE
Unable to load ruff-lsp since upgrade of helix from 23.05 to 23.10

### DISCUSSION THREAD

**Discussion by jawuku** [helix-editor/helix#8619] [Troubleshooting]
Sorry for my newbie question.

I have just upgraded `helix` from `23.05` to `23.10` on macOS Homebrew.
I had previously configured my ruff-lsp according to the guidelines on the [ruff-lsp github.](https://github.com/astral-sh/ruff-lsp)
which in `languages.toml`
```toml
# languages.toml
[[language]]
name = "python"
scope = "source.python"
language-server = { command = "ruff-lsp" }
config = { settings = { args = [] } }
```
This worked fine in 23.05, and `ruff-lsp` displayed in green with `hx --health`.

Since upgrading, I was greeted with this error message:
```
Bad language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`

Press <ENTER> to continue with default language config
```
I've tried to configure following the documentation at https://docs.helix-editor.com/languages.html
```toml
[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
scope = "source.python"
injection_regex = "python"
language-servers = [ "ruff-lsp" ]
```
but `ruff-lsp` does not show when I type `hx --health`

Could you please show me how to setup ruff-lsp?

**Comment by gabydd** [comment]
this is probably because you have: ``injection_regex = "python"``

you should only need:
```toml
[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
language-servers = [ "ruff-lsp" ]
```

**Comment by danriedl** [comment]
I do have the same error for the key `config` after upgrade.
Is there a quick workaround to have my previous setting on typescript?
```toml
[[language]]
name = "python"
formatter = { command = "sh", args = ["-c", "black --quiet - | isort --profile black -"]}
auto-format = true

[[language]]
name = "typescript"
[language.config.preferences]
importModuleSpecifierPreference = "non-relative"
```

**Reply by the-mikedavis** [reply]
`config` moved to the language server's configuration, see https://docs.helix-editor.com/languages.html#language-server-configuration.

So you want to basically update this definition now: https://github.com/helix-editor/helix/blob/ef1f4f31b6e0d8338a9f5b8932de9b07ac7bb0a0/languages.toml#L132-L135

which should look like:

```toml
# ~/.config/helix/languages.toml
[language-server.typescript-language-server.config]
hostInfo = "helix"
preferences.importModuleSpecifierPreference = "non-relative"
```
