### DISCUSSION TITLE
typstfmt configuration

### DISCUSSION THREAD

**Discussion by ramdomPTM** [helix-editor/helix#8629] [Show and tell]
Hi all. Just noticed that `typst` support was added to Helix and it's great! Plus I figured out how to use [`typstfmt`](https://github.com/astrale-sharp/typstfmt) formatter and I'd like to share it with you.

First install `typstfmt` using cargo:

```sh
cargo install --git https://github.com/astrale-sharp/typstfmt.git
```

Then add the following to `languages.toml`:

```toml
[[language]]
name = "typst"
formatter = { command = "typstfmt", args = ["--output", "-"] }
auto-format = true
```
