### DISCUSSION TITLE
Python linting not working after 23.10 update

### DISCUSSION THREAD

**Discussion by AH-Merii** [helix-editor/helix#8679] [Q&A]
After updating to helix v23.10, I had to update my `languages.toml` to support the new multi-lsp structure. My config is as follows:

```toml
[[language]]
name = "python"
rulers = [88]
auto-format = true
formatter = {command = "bash", args = ["-c", "isort --profile black - | black --quiet -"]}

[language-servers.pylsp]
configurationSources = ["pyproject.toml", "setup.cfg"]

[language-servers.pylsp.plugins]
pycodestyle.enabled = false
pyflakes.enabled = false
yapf.enabled = false
pylint.enabled = true
args = ["--rcfile=pyproject.toml", "--rcfile=setup.cfg"]
flake8.enabled = true

[[language]]
name = "hcl"
file-types = ["tf"]
auto-format = true
formatter = { command = "terraform fmt %f" , args = ["--stdin"] }


[[language]]
name = 'toml'
```

Linting was working prior to the update so I am not sure what is going on.
