### DISCUSSION TITLE
ruby solargraph config example (post 23.10 config change)

### DISCUSSION THREAD

**Discussion by jakswa** [helix-editor/helix#8680] [Show and tell]
just wanted to put this somewhere I can reference if I'm not at my machine, and thought other ruby devs might find it useful:

`.config/helix/languages.toml`:
```toml
[language-server.solargraph]
config.diagnostics=true
config.formatting=false

[[language]]
name = "ruby"
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal"] }
auto-format = true
language-servers=[{name="solargraph"}]
```

NOTE: I had to `gem install solargraph` in one case it was missing in

**Comment by sebashwa** [comment]
Hey, thanks for providing this example. It helped me configure my LSP for ruby. Additionally one could use the `--server` flag for the rubocop formatter command:

```
formatter = { command = "rubocop", args = ["--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal", "--server"] }
```

This [starts rubocop in the background](https://docs.rubocop.org/rubocop/usage/server.html) and uses it on every subsequent call, which speeds up the formatting by *a lot*.

**Comment by wassson** [comment]
Noob question here.. @jakswa I have your exact config and solargraph installed. `hx --health` seems to show me that solargraph is set up properly, but I'm still getting issues like "no configured language server supports goto-declaration". Did you run into this, and could there be something I'm missing?

**Reply by wassson** [reply]
To be clear, rubocop definitely works, but I'm missing all of the "goto" related stuff for some reason.

**Reply by jakswa** [reply]
I forget the timing of the recent update. Things might've changed since I opened this thread. I can look at my config later on and report back if changed.

**Reply by wassson** [reply]
Thank you! I would love to know. It is likely that something is wrong on my end, though.

**Reply by richcorbs-ncino** [reply]
I'd love to see a solution for this too.

**Reply by fagnerpereira** [reply]
Hey I have faced this message "no configured language server supports goto-declaration" too. Im not gonna say my solution is gonna work for you because I just could make it works with a lot of tries. 

Im currently using helix with solargraph and standardrb (instead of rubocop for diagnostics and formating)
Basically I set both as language servers. This way I have solargraph working for autocompleting, go to definition, etc, while standardrb takes care about formatting. I hope this helps you in someway.

```toml
[language-server.standardrb]
command = "standardrb"
args = ["--lsp"]

[[language]]
name = "ruby"
auto-format = true

# I have no idea why, but this simply crashes my editor when I save it.
# formatter = { command = "standardrb", args = ["--fix"]  } 

language-servers = [ "solargraph", "standardrb" ]
```
By the way this is my output of `hx --health ruby`. Notice that helix does identify the standardrb as formatter explicitly, but the formatter works nicely, probably because of standardrb lsp server that is also setted.

Configured language servers:
  ✓ solargraph: /Users/fagner/.asdf/shims/solargraph
  ✓ standardrb: /Users/fagner/.asdf/shims/standardrb
Configured debug adapter: None
Configured formatter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓

**Comment by jakswa** [comment]
closing this as pretty outdated (and because my job moved me to standardrb / ruby-lsp :weary: and I finally got that working in helix

**Reply by TeriyakiBomb** [reply]
Could you share that setup?

**Reply by jakswa** [reply]
> Could you share that setup?

sure it is:
```toml
# languages.toml

[language-server.standardrb]
command = "standardrb"
args = ["--lsp"]

[[language]]
name = "ruby"
language-servers = [ "standardrb" ]
auto-format = true
```
