### DISCUSSION TITLE
Texlab LSP not working after update to 23.10

### DISCUSSION THREAD

**Discussion by EnricoGhiorzi** [helix-editor/helix#8683] [Troubleshooting] [answered]
### Summary

On 23.05 I had a setup with build-on-save and forward-sync for LaTeX, which the update to 23.10 broke. I tried unsuccessfully to update my languages.toml configuration, but no build-on-save, diagnostics or forward-sync works. Curiously, the autocompletion seems to work. Diagnostic elements appear only after I build the document but do not update during editing.

### Reproduction Steps

 

I tried this:

1. `languages.toml`:

```toml
[language-server.texlab]
command = "texlab"
config = {build = { onSave = true }, chktex = { onOpenAndSave = true, onEdit = true }}

[[language]]
name = "latex"
language-servers = [
  { name = "texlab" }
]
```

2. `hx file.tex`

I expected this to happen: some degree of lsp support (build-on-save, diagnostics). I left out forward-sync to keep the MWE simple.

Instead, this happened: no noticeable lsp support

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

Only including relevant lines, but I don't think they are very significative.

```
2023-10-31T17:01:25.036 helix_lsp::transport [ERROR] texlab err: <- StreamClosed
2023-10-31T17:01:52.789 helix_lsp::transport [ERROR] texlab err: <- StreamClosed
```

</details>

### Platform

Linux (Ubuntu 23.10)

### Terminal Emulator

Alacritty 0.12.1

### Helix Version

helix 23.10
