### DISCUSSION TITLE
Very slow formatting with Prettier

### DISCUSSION THREAD

**Discussion by Nintron27** [helix-editor/helix#8693] [Troubleshooting]
Just messing around with setting up formatting on JavaScript/TypeScript files using Prettier. Currently my hack-y attempt is the following config:

```toml
[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
roots = ["svelte.config.js"]
# formatter: the svelteserver LSP automatically uses prettier (I think)
language-servers = ["tailwindcss-ls", "svelteserver"]

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "javascript"] }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
```

When formatting JS/TS files it takes about 1-2 seconds to apply, which is exactly how long it takes to format using the cli command directly `cat {FILE} | npx prettier --parser typescript`, so I suspect it's my method of going about this. When saving any svelte file, and using that formatter, it's pretty much "instant", despite the fact that I think the svelteserver LSP uses prettier under the hood.

If anyone has any other suggestions on how to go about this better I'd greatly appreciate any help!
