### DISCUSSION TITLE
Enforce syntax highlight

### DISCUSSION THREAD

**Discussion by waldauf** [helix-editor/helix#8694] [Q&A]
Hi,

I'm working a lot of with Kubernetes configuration files named `config`. These files are YAML but without the suffix `yml|yaml`. In vim is possible to type the command `:set syntax=yaml` and it's applied (if fits). Also when you read stdout from a command that has some structure/format it is useful to set appropriate syntax. 

My questions:
* How can I enforce syntax highlight for the file?
* For my example of Kubernetes config - how to add `config` into regex in `language.toml` file to apply there yaml LSP? Something as the example below, which doesn't work for me 
```toml
[[language]]
name = "yaml"
scope = "source.yaml"
injection-regex = "yml|yaml"
comment-token = "#"
file-types = [ "yaml", "yml"]
roots = [ "~/.kube/config.*" ]
language-servers = [ "yaml-ls" ]
indent = { tab-width = 2, unit = "  " }
```
