### DISCUSSION TITLE
Ocaml formatting

### DISCUSSION THREAD

**Discussion by arpangreat** [helix-editor/helix#8752] [Q&A] [answered]
Hey, if anyone can share how to format ocaml code in helix it would be really great.

**Comment by lentil32** [comment, marked as answer]
```toml
[[language]]
name = "ocaml"
formatter = { command = "ocamlformat", args = [
  "-",
  "--impl",
  # "--enable-outside-detected-project", # Enable only if you want to format files outside of projects
] }
```

Refer to: [Editor setup | ocamlformat 0.26.1 (latest) · OCaml Package](https://ocaml.org/p/ocamlformat/latest/doc/editor_setup.html)
