### DISCUSSION TITLE
How to add indent style for non-supported language

### DISCUSSION THREAD

**Discussion by Landflier** [helix-editor/helix#8799] [Q&A] [answered]
I want to configure helix to have a specific indent style for .tcl and .tk files. Currently, each time I open a .tcl file, I have to manually set this up using :indent-style 3. Since tcl and tk are not supported in the official languages listed in `helix --health`, I tried to add them in the languages.toml, but got some errors, like no roots found etc.

**Comment by the-mikedavis** [comment, marked as answer]
Creating an entry in `~/.config/helix/languages.toml` or `.helix/languages.toml` is the proper way to do this, you'll just need to fill in the required keys:

```toml
[[language]]
name = "tcl"
scope = "source.tcl"
file-types = ["tcl"]
roots = []
indent = { unit = "   ", tab-width = 3 }
```
