### DISCUSSION TITLE
Current workspace root as variable for languages.toml

### DISCUSSION THREAD

**Discussion by thfsilvab** [helix-editor/helix#8812] [Q&A]
Hi! I'm adding Angular language server support to my local installation, and the command needs two things:

- path to the language server installation, which is in the global node/bun installation dir
- path to the TS installation, which can be either the global one or preferably the one in the project (version compatibility)

I was going through the docs and didn't find anything that could help me get the current directory to use in the command, is it possible?

My `languages.toml`, the `tsProbeLocation` parameter is the one I need to use the workspace root

```toml
[language-server.angularls]
command = "ngserver"
args = ["--stdio", "--tsProbeLocations", "~/.bun/install/global/node_modules", "--ngProbeLocations", "~/.bun/install/global/node_modules"]

[[language]]
name = "angular"
scope = "source.angular"
roots = ["angular.json"]
language-servers = ["angularls"]
file-types = ["ts", "html"]
```

Thanks in advance!
