### DISCUSSION TITLE
How to use vscode-json-language-server JSON schemas

### DISCUSSION THREAD

**Discussion by matzxrr** [helix-editor/helix#8823] [Q&A]
I'm trying to configure the `vscode-json-language-server` to use JSON schema files.

We should be able to define these schemas so I can get autocomplete / validation for json properties.
[Vscode JSON ls Config Docs](https://github.com/microsoft/vscode/blob/main/extensions/json-language-features/server/README.md)

Here is my current attempt at getting it to work.

```toml
[[language]]
name = "json"
language-servers = ["jsonls"]
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }
```

```toml
[language-server.jsonls]
args = ["--stdio"]
command = "vscode-json-language-server"

[language-server.jsonls.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[[language-server.jsonls.json.schemas]]
fileMatch = ["tsconfig.json", "tsconfig.*.json"]
url = "https://json.schemastore.org/tsconfig.json"
```

**Comment by David-Else** [comment]
Just add this, don't worry about duplicating stuff from the Helix config:

```toml
[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = ["tsconfig.json", "tsconfig.*.json"]
url = "https://json.schemastore.org/tsconfig.json"

[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = [ "package.json" ]
url = "https://json.schemastore.org/package.json"
```

I have a new question, can this be written in a better way to avoid all the duplication?

I am using Biome to format, it copies Prettier and is much faster:
```toml
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome"]
```

PS This might be of interest: https://github.com/b0o/SchemaStore.nvim/blob/main/lua/schemastore/catalog.lua

**Reply by eliliam** [reply]
@David-Else did you ever determine if the deduplicated snippet you provided works, or does Helix require using the format from your first snippet?

**Comment by jochumdev** [comment]
Thanks all, came up with this:

```toml
[language-server.jsonls]
args = ["--stdio"]
command = "vscode-json-languageserver"

[language-server.jsonls.config]
json = { validate = { enable = true }, format = { enable = false } }
jsonc = { validate = { enable = true }, format = { enable = false } }
provideFormatter = false

[[language]]
name = "json"
language-servers = ["jsonls"]
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }

[[language]]
name = "jsonc"
language-servers = ["jsonls"]
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsonc"] }
```
