### DISCUSSION TITLE
How to make LSP work on all files?

### DISCUSSION THREAD

**Discussion by RoloEdits** [helix-editor/helix#8850] [Q&A]
Now with the ability to use multiple lps for file types, I am using https://github.com/tekumara/typos-vscode for spell checking in my rust files via:

```toml
[language-server.typos]
command = "typos-lsp"

[[languages]]
name = "rust"
language-servers = ["rust-analyzer", "typos"]
```

Is it possible, without having to go to each language and add this? With little knowledge of the codebase, or how everything comes together, I know, for example, that some comments, like `TODO` or `WARN` work in all files, or at least files I have used then in.

**Comment by chrissimon-au** [comment]
I was about to start a similar discussion - I have a language server called [contextive](https://github.com/dev-cycles/contextive) that provides documentation support for domain specific terminology in a programming language-agnostic way.

In other IDEs, I've been able to nominate as part of the language server configuration which languages it should be used for, and to use a `*` to indicate that it should be used for all files.  This appears to be the inverse of the helix approach, which is to nominate the language servers to be used for a given language.  

There may be better ways to do this for helix, but one option is if the `[language-server]` table could have a `languages` key to define languages it is used for.  To co-exist with the existing approach I guess they could be effectively merged so any language/lsp combo could be defined from either the language or the lsp.

If the languages key in the lsp config would also accept `*` to indicate it should be used in all files, that would be super helpful for my users!

**Comment by CAESIUS-TIM** [comment]
Ask for help 🙏. Could you show me your `languages.toml`?

Here is mine:

```toml
[language-server.typos-lsp]
command = "typos-lsp"

[language-server.typos-lsp.config.typos] # BUG
diagnosticSeverity = "Hint" # ["Error", "Warning", "Information", "Hint"]
logLevel = "info"           # ["off", "error", "warn", "info", "debug", "trace"]
```

Warning is here but hint is expected.

![bug](https://github.com/helix-editor/helix/assets/60285058/4ec285d9-3973-4097-bbf4-37bdf59c1053)

It's weird that typos-vscode's README and package.json are different.

https://github.com/tekumara/typos-vscode/blob/3701061a2e6afb685493964881c1962a26053f71/package.json#L51-L56

https://github.com/tekumara/typos-vscode/blob/3701061a2e6afb685493964881c1962a26053f71/README.md?plain=1#L42

**Comment by daaku** [comment]
Would be great to be able to have this. My situation is similar in that I would like to add a language server to all files in a specific project.

**Comment by tekumara** [comment]
Try this:
```toml
[[language]]
name = "all-files"
scope = ""
file-types = [{glob="*"}]
language-servers = ["typos"]
```

PS: for a complete typos-lsp config [see here](https://github.com/tekumara/typos-lsp/blob/main/docs/helix-config.md).
