### DISCUSSION TITLE
Turn off automatic code suggestions

### DISCUSSION THREAD

**Discussion by RGBCube** [helix-editor/helix#8867] [Q&A] [answered]
As the title says. I currently have `idle-timeout = 10000` but that isn't a good fix, is there a way to turn it off completely?

**Comment by dead10ck** [comment, marked as answer]
```toml
[editor]
auto-completion = false
```
