### DISCUSSION TITLE
Enabling inlayHints with deno

### DISCUSSION THREAD

**Discussion by vinpogo** [helix-editor/helix#8889] [Q&A] [answered]
Hi all, 

I am trying to get inlay hints to show with deno. Anyone know what i a m doing wrong?

I am using helix v23.10 and deno v1.38.2

my `language.toml` looks the following:
```toml
[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config]
enable = true
unstable = true

[lanuage-server.deno-lsp.config.inlayHints]
functionLikeReturnTypes = { enabled = true }

[[language]]
name = "typescript"
roots = ["deno.jsonc"]
indent = { tab-width = 2, unit = "  "}
scope = "source.ts"
file-types = ["ts"]
auto-format = true
language-servers = [ "deno-lsp" ]
```

in my `config.toml` i have set
```toml
[editor.lsp]
display-inlay-hints = true
```
