### DISCUSSION TITLE
Remapping C-m and C-i in normal mode doesn't work

### DISCUSSION THREAD

**Discussion by med1844** [helix-editor/helix#8906] [Q&A] [answered]
I'm using colemak-dhm. `hjkl` in qwerty corresponds to `mnei` in colemak-dhm.

Now I'm trying to simplify window mode commands `C-w mnei` to `C-mnei` by remapping like this:

```toml
[keys.normal]
"C-m" = "jump_view_left"
"C-n" = "jump_view_down"
"C-e" = "jump_view_up"
"C-i" = "jump_view_right"
```

The `C-n` and `C-e` work as expected, but `C-m` and `C-i` don't. Passing `-vvv` when start up also doesn't record key press information in the log file.

I'm using

- Ubuntu 22.04.2 LTS on WSL2
- Windows Terminal 1.18.2822.0
- helix 23.10 (f6021dd0)

What should I do to help debug this issue? I have some rust experience so should be able to dig deeper in case it needs. Thank you.

**Comment by the-mikedavis** [comment, marked as answer]
By default terminals send ambiguous key sequences for C-i and C-m. You can use a terminal emulator that support's Kitty's enhanced keyboard protocol (for example Kitty): https://github.com/helix-editor/helix/wiki/Terminal-Support#enhanced-keyboard-protocol

**Reply by med1844** [reply]
Thank you. I also checked why neovim supports C-i and C-m and it turns out that they simply mapped that ambiguous key to corresponding functions. Here's the updated config that doesn't require enhanced keyboard protocol:

```toml
ret = "jump_view_left"
"C-n" = "jump_view_down"
"C-e" = "jump_view_up"
tab = "jump_view_right"
```
