### DISCUSSION TITLE
How to use `select_register` in config.toml?

### DISCUSSION THREAD

**Discussion by rkshthrmsh** [helix-editor/helix#8958] [Q&A]
How to write a key-mapping to yank something into a register, for example `t`?
```toml
# -- snip --
space = ["select_register", "t", "yank"] # Does not work
space = ["select_register t", "yank"] # Also does not work
```
