### DISCUSSION TITLE
templ autoformat does not apply

### DISCUSSION THREAD

**Discussion by jonfriesen** [helix-editor/helix#8965] [Troubleshooting] [answered]
### Summary

When working with the templ LSP autoformating does not work. Running `:format` will trigger a format successfully.

> edit: `auto-format` is set to `true` in my config.

Here's a quick recording of my experience, in the clip: https://www.youtube.com/watch?v=tKoeQ7kArsc

1. I delete some whitespace
2. I save
3. No formatting occurs (which I expect)
4. I use `:format`
5. Formatting occurs correctly

Thanks, I realize this could (likely) a user error. 

### Reproduction Steps

 

I tried this:

1. `hx a-templ-file.templ`
2. add some poorly indented html inside of a `templ someFunc() { .... }`
3. `:w`

I expected this to happen:
The html it be indented using the lsp guidelines.

Instead, this happened:
No formatting occurs.

### Helix log

There are no related logs.

### Platform

macOS

### Terminal Emulator

iterm2 Build 3.4.22

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by jonfriesen** [comment]
I may have prematurely made this bug report.

It seems that adding a formatter to the languages.toml could do the trick? I would appreciate a more experienced contributors take on this :)  If this looks correct, I can submit a PR!

Eg: https://github.com/helix-editor/helix/blob/master/languages.toml#L2922

```toml
[[language]]
name = "templ"
scope = "source.templ"
file-types = ["templ"]
roots = ["go.work", "go.mod"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "templ" ]

# adding this line?
formatter = { command = "templ" , args = ["fmt", "--stdin"] }
```

**Reply by the-mikedavis** [reply, marked as answer]
That sets up an external formatter, so the file will be piped through that command. Instead I think you should just be able to enable the auto-format for templ:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "templ"
auto-format = true
```
