### DISCUSSION TITLE
How to set diagnostic level?

### DISCUSSION THREAD

**Discussion by CAESIUS-TIM** [helix-editor/helix#8975] [Q&A] [answered]
Since the ability to add to your user dictionary while running Helix is not supported in typos, cspell and ltex, it's annoying for a mess of warnings and info.

Can diagnostic level be set in Helix?

**Comment by David-Else** [comment, marked as answer]
Not yet, but they will be soon: https://github.com/helix-editor/helix/pull/6417

You can set the diagnostic level in `ltex-ls` to change the anxiety inducing red errors to a more relaxing yellow:

```toml
[language-server.ltex-ls.config]
ltex.diagnosticSeverity = "warning" 
```
