### DISCUSSION TITLE
Allow repository to define which formatter to use

### DISCUSSION THREAD

**Discussion by ssiltanen** [helix-editor/helix#8986] [Ideas]
Currently we setup language formatter in `languages.toml` eg:

```toml
[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
```

This config uses global prettier from the path, which effectively forces all my typescript repositories to use the global prettier installation.

This is a problem when different repositories use different prettier versions, especially when major versions change with breaking changes and possibly creates a discrepancy between how my editor formats the code and how the repository is formatted.

**Comment by dead10ck** [comment]
I'm a little confused about what you're suggesting. It is already possible to override the formatter in your own `~/.config/helix/languages.toml`.

**Reply by ssiltanen** [reply]
That configuration example I provided was the override from `~/.config/helix/languages.toml`, but it is configured to use the global prettier installation.

I have tried to bypass this issue with the following setup to make helix use the locally installed prettier, but I have noticed irregularities how this setup works compared to other editors.

```toml
[[language]]
name = "typescript"
formatter = { command = "npx", args = ["--no-install", "prettier", "--parser", "typescript"] }
auto-format = true
```

For instance, after version 3.0.0 this does not work without the `--parser` even though, it should be now ignored, because prettier infers the parser from input filepath [docs](https://prettier.io/docs/en/options#parser). If the parser isn't passed we get the following error in helix logs:

```
[ERROR] Formatter error: [error] No parser and no file path given, couldn't infer a parser.
```
Although, this might be also issue with Prettier, but the flags work as expected when used outside the above setup.

**Reply by ssiltanen** [reply]
But in any case, I think we should have a better story on how to specify a repository level formatter instead of just a global installation that uses the same version for every repo.

I don't know how it should look or if it is difficult only in Node ecosystem. E.g. the .NET and F# seem to tip-toe around this issue nicely with their dotnet tool-manifest where you install the formatter locally only and specify the version locally.

**Reply by danriedl** [reply]
Hi @ssiltanen , i do have this in my `.helix/languages.toml` workspace config on the repo im working on:
```toml
[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript", "--config", ".config/prettierrc.json"] }
```
Before i start the editor i source automatically a profile file with `source .profile`:
```bash
# .profile
# Project settings
PROJ_HOME="$HOME/Documents/my_project"

# NPX Binaries
export PATH="$PROJ_HOME/node_modules/.bin:$PATH"
```

This makes the projects prettier available for your workspace-helix config.
