### DISCUSSION TITLE
Configuration to make Clippy Work with Workspaces

### DISCUSSION THREAD

**Discussion by vbosch** [helix-editor/helix#9006] [Q&A]
Hi, 

First of all I would like to thank all of you for the great work that is being done on Helix. 

Currently I am trying to make helix work with clippy on a rust project with workspace and many crates. My languages.toml is as follows: 

```toml
[language-server.rust-analyzer.config]
 check = { command = "clippy", features = "all", workspace = true }
 diagnostics = { experimental = { enable = true } }
 hover = { actions = { enable = true } }
 typing = { autoClosingAngleBrackets = { enable = true } }
 cargo = { allFeatures = true }
 procMacro = { enable = true }
```
 
 This configuration works perfectly well with other work projects that do not have a workspace with different folders. 
 
 When I run "cargo build" or "cargo clippy" on the workspace project I get the myriad of warnings and helpful code issue report but they are not appearing inside helix when I save the file as they do in the other non-worspace type projects. 
 
 I have reviewed the issues (open and closed) regarding the config on this subject and also the clippy documentation regarding the flags but I am not able to make it work :-( 
 
 If anyone can provide a working example I would appreciate it. 
 
 Thank you in advance.
