### DISCUSSION TITLE
Add parameters to the search command

### DISCUSSION THREAD

**Discussion by CAESIUS-TIM** [helix-editor/helix#9037] [Q&A] [answered]
Is it impossible to implement a feature as adding parameters to the search command?

```toml
[keys.normal."space".u]
z = "search \\p{Han}"
```
