### DISCUSSION TITLE
BiomeJS now works with Helix! (You can replace Prettier and ESLint)

### DISCUSSION THREAD

**Discussion by David-Else** [helix-editor/helix#9084] [General]
The latest nightly has an update that means the LSP formatter now works in Helix:

```sh
sudo npm i -g @biomejs/biome@1.4.1-nightly.570d680
```
The [Helix config](https://github.com/biomejs/biome/blob/4211b499eb96c688ff1c20fd02028246358b2203/editors/helix/manual.md) is waiting to be merged into the Biome docs in this PR, please give it a go and report any problems (there shouldn't be any) [in the PR](https://github.com/biomejs/biome/pull/1031)

**Comment by forivall** [comment]
Also, it took me more digging than necessary, but for lsp config, you need to define it like

```toml
[language-server.biome.config.biome]
experimental.rename = true

[language-server.biome.config.biome.inlineConfig]
linter.rules.suspicious.noConsole = "off"
```
