### DISCUSSION TITLE
Failed to config `dotenv`

### DISCUSSION THREAD

**Discussion by CAESIUS-TIM** [helix-editor/helix#9147] [Q&A]
os: Win10
helix: helix 23.10 (f6021dd0)

## Bugs

1. No `Highlight queries`
2. File type identification
    1. Recognize `./.env.prod` as the plain text type; 
    2. Recognize `./.env` as the `env` but not `dotenv`

## `languages.toml`

```toml
[[language]]
name = "dotenv"
scope = "source.dotenv"
injection-regex = "env(\\.\\w+)?"
# injection-regex = "env"
file-types = ["dotenv", "env"]
comment-token = "#"
roots = []
language-servers = ["typos-lsp"]

[[grammar]]
name = "dotenv"
source = { git = "https://github.com/EpocSquadron/tree-sitter-dotenv", rev = "d19d0193a3fee97f3fccecc98c8fbcf965b6f503" }
```

## Upgrade Grammar

```shell
> hx -g fetch
Fetching 165 grammars
123 up to date git grammars
41 updated grammars
        ...
        dotenv             now on d19d0193a3fee97f3fccecc98c8fbcf965b6f503
        ...
Failure 1/1: gemini Git command failed.
Stdout:
Stderr: fatal: unable to access 'https://git.sr.ht/~sfr/tree-sitter-gemini/': The requested URL returned error:
403

Error: 1 grammars failed to fetch
```

```shell
> hx -g build
Building 165 grammars
163 grammars built now
        [...,"dotenv",...]
Failure 1/1: gemini Failed to execute C/C++ compiler

Error: 1 grammars failed to build
```

## Health

```shell
> hx --health dotenv
Configured language servers:
  ✓ cspell-lsp: C:\Program Files\nodejs\cspell-lsp.cmd
Configured debug adapter: None
Highlight queries: ✘
Textobject queries: ✘
Indent queries: ✘
```
