### DISCUSSION TITLE
Extremely slow LSP performance with Godot

### DISCUSSION THREAD

**Discussion by rcorre** [helix-editor/helix#9209] [Troubleshooting] [answered]
I'm using the [suggested](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#gdscript) configuration for godot4:

```toml
[language-server.godot]
command = "nc"
args = ["localhost", "6005"]

[[language]]
name = "gdscript"
language-servers = ['godot']
formatter = { command = "git", args = ["stripspace"] }
auto-format = true
```

LSP diagnostics are extremely slow, and some strings seem to come in one character at a time:

https://asciinema.org/a/629621?t=20.

Has anyone experienced this, or have any idea how to troubleshoot? Thanks!

FWIW, I've tried both `nc` and `netcat`, and both are similarly slow.
[hx.log](https://github.com/helix-editor/helix/files/13812020/hx.log)
