### DISCUSSION TITLE
Region management

### DISCUSSION THREAD

**Discussion by tryoxiss** [helix-editor/helix#9241] [Q&A] [answered]
Hi, I am fairly new to this whole "terminal editor" thing, and I had a few questions about how to do some basic things. The first is hilighting/selecting a region. In most editors I have used I can put my cursor somewhere and use CTRL+{Left Arrow, Right Arrow} to select a region, but that dosen't work here.

The seccond is how do I copy stuff? I was able to set up a remap to make CTRL+V paste, but I cant seem to do anything about copying data.

I did a search for related discussions but there seems to be nothing on the matter.

EDIT:
For anyone in ther future reading this, to get a more normal editor experince you want want to do these rebinds:

```toml
[keys.normal]
"C-s" = ":w"
#"C-f" = "z/"
"C-S-x" = ":q"

#   W
# A S D
# 
# use 'c' or 'i' to enter edit since this overrides 'a'
#"w" = "move_line_up"
#"a" = "move_char_left"
#"s" = "move_line_down"
#"d" = "move_car_right"

"C-f" = "search"
"C-c" = ":clipboard-yank"

"S-left" = "select_mode"
"S-right" = "select_mode"
"S-up" = "select_mode"
"S-down" = "select_mode"

[keys.insert]
"C-s" = ":w"
#"C-f" = "z/"
"C-S-x" = ":q"

"C-c" = ":clipboard-yank"
"C-v" = ":clipboard-paste-before"

"C-f" = "search"

"S-left" = "select_mode"
"S-right" = "select_mode"
"S-up" = "select_mode"
"S-down" = "select_mode"

[keys.select]
"C-c" = ":clipboard-yank"

"S-left" = "move_char_left"
"S-right" = "move_char_right"
"S-up" = "move_line_up"
"S-down" = "move_line_down"

"tab" = "indent"
"S-tab" = "unindent"
```
