### DISCUSSION TITLE
DAP documentation required, and is anybody using dap with Helix?

### DISCUSSION THREAD

**Discussion by mabasic** [helix-editor/helix#9269] [Troubleshooting]
I have just spend an entire day trying to figure out how to use debug with Helix ... still no success.

I am trying to configure https://github.com/microsoft/vscode-js-debug so that i can debug Deno programs.

This is what I have so far:

```
[language.debugger]
name = "test"
transport = "stdio"
quirks = { absolute-paths = true }
command = "node"
args = ["/home/mabasic/bin/js-debug/src/dapDebugServer.js", "8123"]

[[language.debugger.templates]]
type = "pwa-node"
name = "source"
request = "launch"
completion = [ { name = "main", completion = "filename", default = "index.js" } ]
args = { program = "{0}", runtimeExecutable = "deno", runtimeArgs = ["run", "--unstable-kv", "--inspect-wait", "--allow-all"], attachSimplePort = "9229" }
```

it returns request 0 timed out when I do `ctrl g l` and then select "source".

I have managed to start the dap in a separate terminal and use `:debug-remote 127.0.0.1:8123` and it would connect, but the dap  would respond with config unknown or something like that every time in the terminal. I have tried changing everything that I could find. I have tried changing to "tcp", but it complains about incorrect transport...

Can somebody help with this?

What are the available options and what do they do and what values can I enter and why. So much unknown.

This is my reference:

- https://github.com/sigmaSd/deno-nvim
- https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#javascript-deno

**Comment by tye-exe** [comment]
Did you ever find an answer as I'm experiencing the same issue?
Might have to switch to vim or Neo-vim if i can't get the debugger to work.

**Comment by Kurren123** [comment]
@mabasic any update on what you did?

**Reply by mabasic** [reply]
Nope. Haven't tried again since. But as a workaround I have used the browsers built in v8 debugger to debug deno. Start deno in debug mode then open developer tools in the browser and you will see a green node js button. Once you click on that a debugger will attach to the deno process

**Reply by Kurren123** [reply]
Thanks. Won't help me much with C# debugging however!

**Comment by deriamis** [comment]
I think you might be somewhat confused here. `vscode-js-debug` only communicates via TCP, not `stdio`, so the configuration you have won't work. You also likely want to let Helix substitute a random port for you, which you can do with a template. This is what I have, from the [built-in configuration](https://github.com/helix-editor/helix/blob/master/languages.toml#L572):

```toml
[[language]]
name = "javascript"

[language.debugger]
name = "vscode-js-debug"
transport = "tcp"
command = "node"
args = [ "~/.local/libexec/vscode-js-debug/src/vsDebugServer.js" ]
port-arg = [ "{}" ]

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { mode = "local", processId = "{0}" }

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "main", completion = "filename", default = "index.js" } ]
args = { program = "{0}" }
```

Note, however, that recent versions of `vscode-js-debug` might not work right now due to an [unimplemented reverse request type](https://github.com/helix-editor/helix/issues/11906). Also, you can likely add other debugger templates to, for example, connect to the DAP from a browser so you can test it live.

**Comment by jasonwilliams** [comment]
Please see this thread https://github.com/helix-editor/helix/issues/11906

**Comment by leaf-node** [comment]
Okay, it seems like I almost have Deno DAP working with Helix. The problem I'm running into is that Deno listens on a websocket with a path as a part of the URI, which I suspect Helix does not pick up on, so it fails to connect.

Here's the config I have so far, collected and adjusted from various places:

```toml
[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
file-types = ["ts", "tsx"]
language-servers = ["deno-lsp"]
roots = ["deno.json", "package.json", "tsconfig.json"]
# auto-format = true

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true
# unstable = true
suggest.imports.hosts = { "https://deno.land" = true }

[language-server.deno-lsp.config.deno.javascript.inlayHints]
parameterNames.enabled = "all"
parameterTypes.enabled = true
variableTypes.enabled = true
propertyDeclarationTypes.enabled = true
functionLikeReturnTypes.enabled = true
enumMemberValues.enabled = true

[language-server.deno-lsp.config.deno.typescript.inlayHints]
parameterNames.enabled = "all"
parameterTypes.enabled = true
variableTypes.enabled = true
propertyDeclarationTypes.enabled = true
functionLikeReturnTypes.enabled = true
enumMemberValues.enabled = true

[language.debugger]
name = "deno-debug"
command = "deno"
args = ["repl", "-A"]
port-arg = "--inspect=127.0.0.1:{}"
transport = "tcp"

[[language.debugger.templates]]
name = "Launch Deno Script"
request = "launch"
completion = [{ name = "main", completion = "filename", default = "src/index.ts" }]
args = { address = "127.0.0.1", program = "{0}" }
```

**Comment by leaf-node** [comment]
This LSP and DAP config in `~/.config/helix/languages.toml` works for me for [debugging](https://github.com/microsoft/vscode-js-debug) with Node.js:

```toml
[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
file-types = ["ts", "tsx"]
roots = ["package.json"]

[language.debugger]
name = "node-debug"
command = "node"
port-arg = "{} 127.0.0.1"
args = ["/home/andrew/.local/lib/js-debug/src/dapDebugServer.js"]
transport = "tcp"

[[language.debugger.templates]]
name = "Launch Node.js Script"
request = "launch"
completion = [{ name = "main", completion = "filename", default = "src/index.ts" }]
args = { program = "{0}", address = "127.0.0.1", type = "pwa-node" }
```
I had to install TypeScript `6.0.3` instead of `7.0.2` to avoid the following error:
```
2026-07-28T23:40:43.963 helix_lsp::transport [ERROR] typescript-language-server <- InternalError: Request initialize failed with message: Could not find a valid TypeScript installation. Please ensure that the "typescript" dependency is installed in the workspace or that a valid `tsserver.path` is specified. Exiting.
2026-07-28T23:40:43.963 helix_lsp [ERROR] failed to initialize language server: protocol error: InternalError: Request initialize failed with message: Could not find a valid TypeScript installation. Please ensure that the "typescript" dependency is installed in the workspace or that a valid `tsserver.path` is specified. Exiting.
2026-07-28T23:40:52.837 helix_lsp::client [WARN] language server failed to terminate gracefully - server closed the stream
```
```sh
npm install typescript@6.0.3 typescript-language-server --global
```
