### DISCUSSION TITLE
Default options for all languages in languages.toml

### DISCUSSION THREAD

**Discussion by bogdan-ov** [helix-editor/helix#9299] [Q&A]
Now my `languages.toml` file looks something like this:
```toml
[[language]]
name = "rust"
auto-format = false
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "typescript"
auto-format = false
indent = { tab-width = 4, unit = "    " }
[[language]]
name = "json"
auto-format = false
indent = { tab-width = 4, unit = "    " }

# ...
```

But I want to set the default value for `auto-format` and `indent` for all langs.

Maybe it will look something like this:
```toml
[[language]]
name = "*"
auto-format = false
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
auto-format = true # And maybe override some values in the future...

# ...
```

How can I do this?
**Thanks!**
