### DISCUSSION TITLE
HTML indent is always space ("soft tab")

### DISCUSSION THREAD

**Discussion by Rudxain** [helix-editor/helix#9419] [Troubleshooting] [answered]
Project `.editorconfig` (not global)
```editorconfig
root = true

[*]
charset = UTF-8
end_of_line = lf
indent_style = tab
indent_size = 4
insert_final_newline = false
trim_trailing_whitespace = true
```
EC was never honored by helix nor the LSP.

`~/.config/helix/languages.toml`
```toml
[[language]]
name = "html"
indent = { tab-width = 4, unit = "\t" }
```
This is **partially honored**. `tab-width` works, but `unit` is ignored (defaults to `" "`)

LSP: `vscode-langservers-extracted`

Should I open an issue?
