### DISCUSSION TITLE
Helix config files JSON schemas

### DISCUSSION THREAD

**Discussion by o-az** [helix-editor/helix#9431] [Q&A]
Looking for the schemas for Helix config files: `.config.toml`, `.language.toml`, etc. Are they available by chance? This provides autocomplete if there's a schema: https://taplo.tamasfe.dev.

I read [this issues](https://github.com/helix-editor/helix/issues/3901) but not sure if that exists or not.

**Comment by David-Else** [comment]
I think taplo is as good as dead, and TOML is on the way out in Helix. I know it is not what you were asking, but out of general interest, If you want some actual JSON schemas for JSON you can do:

```toml
[[language-server.vscode-json-language-server.config.json.schemas]]
fileMatch = [ "package.json" ]
url = "https://json.schemastore.org/package.json"
```
