### DISCUSSION TITLE
Tree-sitter (Syntax Highlighting) turns off color on variable when function parameter goes out of view (Rust)

### DISCUSSION THREAD

**Discussion by Amberwq** [helix-editor/helix#9433] [Q&A] [answered]
When programming in Rust (With Bevy specifically) whenever a variable defined in a function goes out of view, the colors for it turn off and default to white

OS: Fedora Silverblue 39, Helix is running inside of an Arch Linux distrobox
Installation method: Pacman
Theme: Catppuccin Macchiato

![image](https://github.com/helix-editor/helix/assets/109248857/6f7c56f0-855f-4614-8b9a-355c8518c9c2)
![image](https://github.com/helix-editor/helix/assets/109248857/96c3d442-a924-408d-b8ca-ec11d2a6d85a)

<details>
<summary>config.toml</summary>

```toml
theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
cursorline = true
bufferline = "multiple"
color-modes = true
scrolloff = 0
idle-timeout = 0

# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[editor.statusline]
left = ["mode", "separator", "version-control", "file-name", "file-modification-indicator", "spinner"]
center = ["read-only-indicator"]
separator = " "

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"A-w" = ":buffer-close"
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
H = "unindent"
L = "indent"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
H = "unindent"
L = "indent"
```
</details>

<details>
<summary>languages.toml</summary>

```toml
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
file-types = ["html"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "html"] }
language-servers = ["emmet-lsp"]

[[language]]
name = "css"
file-types = ["css"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "css"]}

[[language]]
name = "svelte"
roots = [".git"]
file-types = ["svelte"]
auto-format = true
language-servers = ["emmet-lsp", "svelteserver"]
# Unfortunately this causes two emmet auto completes to be displayed at once; Svelte's and Emmets. But it works better this way so?

[[language]]
name = "typescript"
file-types = ["ts"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
file-types = ["js"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[language-server.rust-analyzer.config]
check.command = "clippy"
```
</details>

The logs don't show any errors or anything related to tree-sitter, just LSP stuff working properly. I don't really know what to do here, any help?
