### DISCUSSION TITLE
How to config the formatter to just reload the file after format instead of read from the output of the formatter ?

### DISCUSSION THREAD

**Discussion by Dangerise** [helix-editor/helix#9501] [Q&A] [answered]
I'm using dioXus in my rust project, and I need to use the custom formatter from dioxus because of its special macro, but the output infomation will cover my source code, instead of the code after formatting

**Comment by pascalkuthe** [comment, marked as answer]
The formatter needs to output to stdout otherwise it won't work. Every formatter I ever encountered has an option for that.

Reloading the file from disk unsuited since that is essentially a race condition

**Comment by Dangerise** [comment]
@pascalkuthe
I found that dioxus has provide a way to support helix

now I'm trying to cargo fmt first and then do dx fmt

but It's seems that it has a problem

![Issue1](https://github.com/helix-editor/helix/assets/88434542/b0c36ca3-c8ac-47dc-9d7f-19c79c1335c0)

![Issue2](https://github.com/helix-editor/helix/assets/88434542/6a04b3d8-b241-4a5d-9c68-69c458f63312)

**Reply by Dangerise** [reply]
my formatter config

```
[[language]]
name = "rust"
formatter = { command = "bash", args = ["-c", "cargo fmt && dx fmt -f -"] }
```

**Comment by Dangerise** [comment]
all right, solved by
```
[[language]]
name = "rust"
formatter = { command = "bash", args = ["-c", "rustfmt | dx fmt -f -"] }
```

**Reply by aqirruujaq** [reply]
rustfmt requires specifying the edition of rust to be used. such as `rustfmt --edition 2024`

**Reply by vladislav-yemelyanov** [reply]
@Dangerise It works for me, thanks!  🙏

**Reply by Marsevil** [reply]
I've added `-o pipefail` to return if `rustfmt` failed, otherwise `rustfmt` push an empty string through stdout and so `dx fmt` which basically empty the buffer. 

```toml
[[language]]
name = "rust"
formatter = { command = "bash", args = ["-o", "pipefail", "-c", "rustfmt | dx fmt -f -"] }
```

**Reply by j03-dev** [reply]
```toml
[[language]]
name = "rust"
auto-format = true
formatter = { command = "bash", args = ["-c", "rustfmt | dx fmt -f -"] }
```

This is my config and, when I format the code, it's delete everything all my code.

**Reply by Dangerise** [reply]
> ```toml
> [[language]]
> name = "rust"
> auto-format = true
> formatter = { command = "bash", args = ["-c", "rustfmt | dx fmt -f -"] }
> ```
> 
> This is my config and, when I format the code, it's delete everything all my code.

maybe something have been changed over the year, if your code has any syntax errors that lead to parse failure , the buffer will be clear .

@Marsevil  has given the solution

**Reply by rrrrigel** [reply]
> ```toml
> [[language]]
> name = "rust"
> auto-format = true
> formatter = { command = "bash", args = ["-c", "rustfmt | dx fmt -f -"] }
> ```
> 
> This is my config and, when I format the code, it's delete everything all my code.

same here

**Reply by j03-dev** [reply]
```toml
[[language]]
name = "rust"
auto-format = true
formatter = { command = "dx", args = ["fmt", "-f", "-"] }
```

So I use this; it works for me, but Steel can't use it with rustfmt.
