### DISCUSSION TITLE
File extension overrides not working.

### DISCUSSION THREAD

**Discussion by 1BADragon** [helix-editor/helix#9593] [Troubleshooting] [answered]
### Summary

File overrides in languages.toml are not taking for file extensions for pre-associated types. Specifically I want C header files (.h) to have language C but helix is setting the language to CPP even with the following language config:

```
[[language]]
name="c"
scope="source.c"
auto-format=true
file-types = ["h", "c"]
``` 

### Reproduction Steps

 

I tried this:

Using this config
```
[[language]]
name="c"
scope="source.c"
auto-format=true
file-types = ["h", "c"]
```

I expected this to happen:
open .h file and have language set to "c"

Instead, this happened:
language was set to "cpp"

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty

### Installation Method

Build master from commit d570c29ce37ffbb46a9c49708c31dfd81daa27cf

### Helix Version

d570c29ce37ffbb46a9c49708c31dfd81daa27cf

**Comment by the-mikedavis** [comment, marked as answer]
You also need to remove the `h` file-type from C++'s configuration: https://github.com/helix-editor/helix/blob/d570c29ce37ffbb46a9c49708c31dfd81daa27cf/languages.toml#L438-L445

For example:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "C", "H", "cu", "cuh", "cppm", "h++", "ii", "inl", { suffix = ".hpp.in" }, { suffix = ".h.in" }]
```
