### DISCUSSION TITLE
Can't configure for vscode-html-languageserver (it doesn't work with default or basic configuration)

### DISCUSSION THREAD

**Discussion by JustAnotherCodemonkey** [helix-editor/helix#9605] [Troubleshooting] [answered]
When I installed the VS Code language server via Nix (nodePackages.vscode-html-languageserver-bin package using `nix profile install`), Helix did not detect it and could not find the bin. This is likely because it was looking for "vscode-html-languageserver" or something like that but the actual bin installed was "html-languageserver".

I modified languages.toml, adding
```toml
[[language]]
name = "html"
language-servers = [ "html-languageserver" ]
```

However, I get the message "helix_view::editor [ERROR] Failed to initialize the language servers for `text.html.basic` - `html-languageserver` { Language server 'html-languageserver' not defined }" in the log and get no lsp when editing HTML.

**Comment by the-mikedavis** [comment, marked as answer]
You should use the `nodePackages.vscode-langservers-extracted` package from nixpkgs instead, `vscode-html-languageserver-bin` is something else.

The `language-servers` key under `[[language]]` controls which `language-server` entry you use. For example the default ones: https://github.com/helix-editor/helix/blob/786b5c533e32cfe88dbf8742fdbc18829fb46334/languages.toml#L6-L19

If you want to change the command name for an existing language server you can modify that instead:

```toml
# ~/.config/helix/languages.toml
[language-server.vscode-html-language-server]
command = "my-language-server-command"
args = []
config = {}
```
