### DISCUSSION TITLE
How to get themes to show deprecated and dead code from rust-analyzer

### DISCUSSION THREAD

**Discussion by willhansen** [helix-editor/helix#9635] [Q&A]
I'm reasonably certain that rust-analyzer can tell which functions have been marked with `#[deprecated]`, and which functions are dead code, but I'm having trouble trying to figure out how to have them displayed as part of a theme.  Maybe strikethrough any uses of the deprecated functions, and grey out any dead code.

Are there any public configurations where someone has this working?

**Comment by the-mikedavis** [comment]
Highlighting is done through tree-sitter rather than LSP so this information is not exposed for theming

**Reply by willhansen** [reply]
Fair.  Is there anything along the lines of applying specific visual effects to code with LSP warnings that match a given regex?  As near as I can tell right now, the circles on the left of the screen are red or yellow for errors and warnings, but they have no other differentiation within those categories (at least before putting the cursor on the line itself and I can read the associated messages).

**Reply by kirawi** [reply]
Highlighting the diagnostics in the buffer depends on the theme you use.

**Reply by willhansen** [reply]
Looking at the theme `toml`s, I'm seeing diagnostic style definitions like this:

```toml
"diagnostic.info" = { underline = { color = "blue", style = "dotted" } }
"diagnostic.hint" = { underline = { color = "green", style = "dashed" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
```

I'm now wondering if there's a way to get something that looks like this:

```toml
"diagnostic.info" = { underline = { color = "blue", style = "dotted" } }
"diagnostic.hint" = { underline = { color = "green", style = "dashed" } }
"diagnostic.warning" =  [
           { 
               "diagnostic-message-matches-regex" = ".*", 
               style = { underline = { color = "yellow", style = "curl" } 
           },
           { 
              "diagnostic-message-matches-regex" = ".*deprecated.*", 
               style = { underline = { color = "red", style = "curl" }, fg = "grey", modifiers = ["crossed-out"] }
           }
]
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
```
