### DISCUSSION TITLE
Multiline tables for keymaps

### DISCUSSION THREAD

**Discussion by vincevargadev** [helix-editor/helix#9669] [Troubleshooting] [answered]
I'd like to create a keymapping for "my favorite stuff".

As I see, the `;` is still free in normal mode, so I thought I prefix everything with that so that I don't overwrite existing stuff.

In the below example, I want to duplicate the current line below or above the current line, and I can imagine adding more and more stuff here.

Unfortunately, as this list grows, it's less and less readable in one line, so I wanted to split it up, but I can't find a way to do this and get it accepted after reloading the Helix config. I thought TOML supports what I'm doing, but obviously, I'm doing something wrong.

How can I split this up into multiple lines correctly?

```toml
";" = {
    d = ["extend_line_below", "yank", "paste_after"],
    D = ["extend_line_below", "yank", "paste_before"],
}

# This doesn't work
```

![Screenshot 2024-02-19 at 20 50 51](https://github.com/helix-editor/helix/assets/9061239/3a20f5eb-8950-4e4f-8632-d58c35c99654)

If I do it without newlines, it works as expected:

```toml
";" = {d = ["extend_line_below", "yank", "paste_after"], D = ["extend_line_below", "yank", "paste_before"]}
```

**Comment by the-mikedavis** [comment, marked as answer]
```toml
[keys.normal.";"]
";" = { d = ["extend_line_below", "yank", "paste_after"], D = ["extend_line_below", "yank", "paste_after"] }
```

uses an inline table and it would be equivalent to:

```toml
[keys.normal.";"]
d = ["extend_line_below", "yank", "paste_after"]
D = ["extend_line_below", "yank", "paste_after"]
```

which is a regular table and supports multiple lines
