### DISCUSSION TITLE
C/C++: replace dot operator with arrow operator intelligently

### DISCUSSION THREAD

**Discussion by GeekZJJ** [helix-editor/helix#9685] [Ideas]
Hi! I try to use helix to replace vscode to write C/C++ code recently. Everything is good, but I notice that helix can't show the struct member suggestions when I type a `.` after a struct pointer automatically. I use the same clangd args in vscode, everything works fine. So I'm guessing this is a feature we haven't being implemented currently. Am I right?
My `language.toml` file is as below:
``` toml
[language-servers.clangd]
command = "/usr/bin/clangd"
args = ["--pretty", "--background-index", "-j=2", "--clang-tidy", "--clang-tidy-checks=performance-*,bugprone-*", "--all-scopes-completion", "--completion-style=detailed", "--header-insertion=iwyu", "--pch-storage=disk"]

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = false
```

Edited:
I found that in the `language.toml` file I make some mistake, which make clangd's args I configured don't make any sense. The `[language-servers.clangd]` should be `[language-server.clangd]`. Correct file is as below.

``` toml
[language-server.clangd]
command = "/usr/bin/clangd"
args = ["--pretty", "--background-index", "-j=2", "--clang-tidy", "--clang-tidy-checks=performance-*,bugprone-*", "--all-scopes-completion", "--completion-style=detailed", "--header-insertion=iwyu", "--pch-storage=disk"]

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = false
```
