### DISCUSSION TITLE
Too high RAM usage in tests

### DISCUSSION THREAD

**Discussion by mo8it** [helix-editor/helix#9710] [Troubleshooting]
After running `cargo t --workspace`, all of my RAM is used and my OOM starts killing processes. I have 16 GB of RAM. The tests that cause that are those of `helix-tui`. I tried using the `-j 1` option, but it didn't help.
I can skip the tests of `helix-tui` for now. But are you planning to address this issue? A unit test shouldn't require 16 GB of RAM.

**Comment by mo8it** [comment]
After running `cargo t --workspace --exclude helix-tui`, the unit tests run to completion, but my RAM was at about 95% until the end. It might be worth reducing the memory usage of all tests if possible.

**Comment by kirawi** [comment]
I can't replicate. The highest it ever went was 1gb. What system & OS are you running, what is your system environment, and do you have a custom config for Rust?

**Reply by mo8it** [reply]
## Hardware Information:
- **Memory:**                                      16,0 GiB
- **Processor:**                                   AMD Ryzen™ 7 5800H with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics

## Software Information:
- **OS Name:**                                     Fedora Linux 39.20240223.0 (Silverblue)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.5-200.fc39.x86_64

---

Content of `~/.cargo/config.toml`:

```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=/usr/bin/mold",
  "-C",
  "target-cpu=native",
]

[profile.release]
lto = true
codegen-units = 1
```
