### DISCUSSION TITLE
Limit memory usage of a language server

### DISCUSSION THREAD

**Discussion by automainint** [helix-editor/helix#9753] [Ideas]
I just got a system crash because of [clangd memory leak bug](https://github.com/llvm/llvm-project/issues/75105)

It would be great to have a config option to prevent that kind of a problem, e.g.
```toml
[language-server.clangd]
command = "clangd"
max-memory = 2000
```
