### DISCUSSION TITLE
Any Elixir users having issues with Tailwind Completion in .heex files?

### DISCUSSION THREAD

**Discussion by mkellyxp** [helix-editor/helix#9969] [Q&A]
I've been using and loving Helix for the past month, and it's been working great for PHP, and it mostly works great for Elixir.  However, I for the life of me, can't get TailwindCSS completion in .heex templates, and i'm not sure why.

I know the tailwind-ls works, as it works in plain HTML and PHP files fine.  And I know my languages.toml file is handling heex files, because it seems to be handling elixir-ls and html just fine.  But not tailwind.  What am I missing here?

Here is my hx --health heex

```
Configured language servers:
  ✓ elixir-ls: /run/current-system/sw/bin/elixir-ls
  ✓ tailwindcss-language-server: /run/current-system/sw/bin/tailwindcss-language-server
  ✓ vscode-html-language-server: /run/current-system/sw/bin/vscode-html-language-server
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✘
```

And here is my languages.toml file

```
[[language]]
name = "php"
language-servers = [ "intelephense", "tailwindcss-ls", "vscode-html-language-server" ]
auto-format = true

[[language]]
name = "html"
language-servers = [ "tailwindcss-ls", "vscode-html-language-server" ]

[[language]]
name = "elixir"
auto-format = true

[[language]]
name = "heex"
language-servers = [ "elixir-ls",  "tailwindcss-ls", "vscode-html-language-server" ]
auto-format = true
```
![Screenshot from 2024-03-22 15-22-10](https://github.com/helix-editor/helix/assets/6528226/25e29c75-a673-42a2-b6b5-76d92ca34a48)
![Screenshot from 2024-03-22 15-22-29](https://github.com/helix-editor/helix/assets/6528226/f006c008-d4bf-45b0-85eb-8fab14617fc5)
![Screenshot from 2024-03-22 15-23-00](https://github.com/helix-editor/helix/assets/6528226/4220aba8-2a97-449f-9df4-d54d6e9c2c48)
![Screenshot from 2024-03-22 15-23-51](https://github.com/helix-editor/helix/assets/6528226/896ec998-a877-452c-b40a-1ed6fb3d305f)

**Comment by mkellyxp** [comment]
Figured it out!  Just needed the language id to be "phoenix-heex"!  Works as expected now

![image](https://github.com/helix-editor/helix/assets/6528226/5794da97-0cb9-4481-b7bb-2d4b4d5bd651)

**Reply by djpowers** [reply]
Thanks for circling back to share your solution! This got me started, but I needed to configure Tailwind to include HEEx as HTML.

Here's the bare minimum setup I ended up with in case it helps anyone:
```toml
[[language]]
name = "elixir"
auto-format = true

[language-server.tailwindcss-ls]
config.tailwindCSS.includeLanguages = { "heex" = "html" }

[[language]]
name = "heex"
language-servers = [ "elixir-ls", "tailwindcss-ls", "vscode-html-language-server" ]
auto-format = true
```
