### DISCUSSION TITLE
small suggestion for `--health`

### DISCUSSION THREAD

**Discussion by goyalyashpal** [helix-editor/helix#9989] [Ideas]
### details

```console
$ hx --health c-sharp
```

The above command gives following output currently (slightly augmented for illustration):

```yaml
Configured language servers:
  ✘ OmniSharp: 'OmniSharp' not found in $PATH
  ✓ ansible-language-server: D:\msys64\clang64\bin\ansible-language-server.exe
Configured debug adapter: netcoredbg
Binary for debug adapter: 'netcoredbg' not found in $PATH
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✘

```

Suggestion for binaries of "lang servers" or "debug adapters" is to make it to not start with a `'` quote.

possible rewordings:
from this original:

```
- '{}' not found in $PATH
```

to any among:

````
- not found '{}' in $PATH
- $PATH doesn't contain '{}'
- no '{}' found in $PATH
- $PATH missing '{}'
- missing '{}' in $PATH
- missing '{}' from $PATH
- $PATH lacks '{}'
````

<details>
<summary>example / reworded sample:</summary>

```yaml
Configured language servers:
  ✘ OmniSharp: no 'OmniSharp' found in $PATH
  ✓ ansible-language-server: D:\msys64\clang64\bin\ansible-language-server.exe
Configured debug adapter: netcoredbg
Binary for debug adapter: no 'netcoredbg' found in $PATH
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✘

```

</details>

### why

this small change makes the output yaml-parseable, so allows to do lots of cool things with it:

```console
$ # For trying this yourself, only put a language with no `✘` for either of 
$ # "lang-server", "debug-adapter" in its hx --health. "None" is okay though.
$ hx --health c-sharp
$ declare hxh=$(!! | sd '\x1b\[[0-9;]+m' '')
declare hxh=$(hx --health c-sharp | sd '\x1b\[[0-9;]+m' '')
```

```console
$ echo "$hxh" | yq [.[][]]
- not found 'OmniSharp' in $PATH
- D:\msys64\clang64\bin\ansible-language-server.exe

$ echo "$hxh" | yq 'keys | .[]'
Configured language servers
Configured debug adapter
Binary for debug adapter
Highlight queries
Textobject queries
Indent queries

$ echo "$hxh" | yq -o json
{
  "Configured language servers": {
    "✘ OmniSharp": "not found 'OmniSharp' in $PATH",
    "✓ ansible-language-server": "D:\\msys64\\clang64\\bin\\ansible-language-server.exe"
  },
  "Configured debug adapter": "netcoredbg",
  "Binary for debug adapter": "not found 'netcoredbg' in $PATH",
  "Highlight queries": "✓",
  "Textobject queries": "✓",
  "Indent queries": "✘"
}

$ echo "$hxh" | nu --stdin -c 'from yaml | table --expand'
╭─────────────────────────────┬────────────────────────────────────────────────────────────────────╮
│                             │ ╭───────────────────────────┬────────────────────────────────────╮ │
│ Configured language servers │ │ ✘ OmniSharp               │ not found 'OmniSharp' in $PATH     │ │
│                             │ │ ✓ ansible-language-server │ D:\msys64\clang64\bin\ansible-lang │ │
│                             │ │                           │ uage-server.exe                    │ │
│                             │ ╰───────────────────────────┴────────────────────────────────────╯ │
│ Configured debug adapter    │ netcoredbg                                                         │
│ Binary for debug adapter    │ not found 'netcoredbg' in $PATH                                    │
│ Highlight queries           │ ✓                                                                  │
│ Textobject queries          │ ✓                                                                  │
│ Indent queries              │ ✘                                                                  │
╰─────────────────────────────┴────────────────────────────────────────────────────────────────────╯

```

### versions

```console
$ hx -V
helix 23.10 (f6021dd0)

$ yq -V
yq (https://github.com/mikefarah/yq/) version v4.42.1

$ nu -v
0.19.0
```
