### DISCUSSION TITLE
Integration/configuration of tree-sitter-rstml

### DISCUSSION THREAD

**Discussion by vincentberthier** [helix-editor/helix#9993] [Q&A]
There is a project intended to offer better syntax highlighting when developing with Rust web frameworks such as Leptos: https://github.com/rayliwell/tree-sitter-rstml

Problem is, I have absolutely no idea of how to do this. It explains how for Neovim, so hopefully it isn’t that hard though?

Anyone willing to have a look and share how it’s done?

**Comment by rayliwell** [comment]
Maintainer of tree-sitter-rstml here,

Helix queries and instructions should probably be up within a few days.

Once they are mature enough, I'd be happy to open a pull request to merge them into helix.

**Comment by vincentberthier** [comment]
Cool!

**Comment by erasin** [comment]
My config is [helix config](https://github.com/erasin/helix-config/).

- languages.toml
```toml
[[language]]
name = "rstml"
scope = "scope.rstml"
injection-regex = "rstml"

[[grammar]]
name = "rstml"
source = { git = "https://github.com/rayliwell/tree-sitter-rstml", subpath = "rstml", rev = "07a8e3b9bda09b648a6ccaca09e15dea3adf956f" }
```

- runtime/queries/rust/injections.scm
```scheme
; leptos
((macro_invocation
   macro:
     [
       (scoped_identifier
         name: (_) @_macro_name)
       (identifier) @_macro_name
     ]
   (token_tree) @injection.content)
 (#eq? @_macro_name "view")
 (#set! injection.language "rstml")
 (#set! injection.include-children))
```
- runtime/queries/rstml/hightlights.scm and injections.scm

About: #10322 #9622 #9219
