### ISSUE TITLE
Indent configuration not working for C++

### ISSUE THREAD

**Issue by Ha5hBr0wn** [helix-editor/helix#10028]
Hi I am using the Helix text editor and my indents in C++ are just 2 spaces and I want them to be 4. I can't figure out how to make it work

I have been adding the indent to the languages.toml file as the docs tell me to:

```
[[language]]
name = "cpp"
auto-format = true
formatter = {command = 'clang-format', args= ["--style=Google"]}
indent = { tab-width = 4, unit = "    " }
```

I was on version 20.05 at first and I also tried on latest master but I alway just get 2 spaces in auto indent and when I press tab

I know the languages.toml file is getting picked up because if I change the style for the formatter that does take effect as expected. So just the indent key is not working as expected for me

**Comment by woojiq** [comment]
If you have a file that already has an indent of 2 spaces, you will have 2 spaces despite your configuration. Try in a new file or format yours with 4 spaces manually (or using formatter).
Fyi, this configuration works for me:
```toml
 [[language]]
 name = "c"
 indent = { tab-width = 4, unit = "    " }
 [[language]]
 name = "cpp"
 indent = { tab-width = 4, unit = "    " }
```
