### ISSUE TITLE
Don't remove whitespaces after pressing Enter 

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#10073]
It's convenient to navigate indented code, it's better to implement an option that allows you to keep trailing spaces. Removing trailing spaces interferes with indentation and navigation

**Comment by DoctorRyner** [comment]
Fixed with:
```toml
"S-ret" = "open_above"
"ret" = "open_below"
```
