### ISSUE TITLE
Helix open JS file with `typescript-language-server` crash

### ISSUE THREAD

**Issue by zongUMR** [helix-editor/helix#1048]
### Reproduction steps
1. Set local `languages.toml` in `~/.config/helix`:
```toml
[[language]]
name = "javascript"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
```
2. Open any js file
3. Helix exists automatically, with such error message:
```bash
thread 'tokio-runtime-worker' panicked at 'failed to initialize capabilities: Rpc(Error { code: InternalError, message: "Request initialize failed with message: The \"path\" argument must be of type string or an instance of Buffer or URL. Received undefined", data: None })', helix-lsp/src/lib.rs:340:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Environment
- MacOS: 12.0.1
- Helix version: 0.5.0

<details><summary>~/.cache/helix/helix.log</summary>

```
2021-11-10T08:48:16.588 helix_lsp::transport [ERROR] <- Internal error: Request initialize failed with message: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
```

</details>
