### ISSUE TITLE
Theme Toml not allowing Bare keys

### ISSUE THREAD

**Issue by Conando025** [helix-editor/helix#10509]
### Summary

When writing a theme using bare keys / table names leads to malfunction.
The spec says that 

> Best practice is to use bare keys except when absolutely necessary.

### Reproduction Steps

I tried this:

1. create the file `~/.config/helix/theme/broken.toml`with the following content
```toml
[ui.selection]
bg = "black"
```
2. open helix and type `:theme broken`

I expected this to happen:

It loads my theme as it would if it was
```toml
["ui.selection"]
bg = "black"
```
Also
```toml
# Works
"ui.selection" = { bg = "black" }
# Broken
ui.selection = { bg = "black" }
```

Instead, this happened:
It refused to load my theme as ui.selection is missing.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.12.2

### Installation Method

apt

### Helix Version

helix 24.3 (2cadec0b)
