### ISSUE TITLE
Configurable rendering of invisible characters like space, tab, and line feed

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#1068]
Some config option for whether to display invisible characters like rendering spaces as dots, tabs as arrows, etc.

The config option would have 3 possible values:
* `none`: Don't render invisible characters.
* `selection`: Render invisible characters that fall into a selection.
* `all`: Render all invisible characters.

I presume this would also add a field to themes?

**Comment by Curiosidad-Racional** [comment]
Usually the most annoying invisible characters are those at the end of the line. In my opinion an option to highlight them is very useful.

**Comment by Omnikar** [comment]
Perhaps the config option could allow things like this:
#### Render all whitespace
```toml
[editor]
render-whitespace = "all"
```
#### Render all newlines
```toml
[editor]
render-whitespace = { newline = "all" }
```
```toml
[editor.render-whitespace]
newline = "all"
```
#### Render all newlines, render other whitespace when selected
```toml
[editor]
render-whitespace = { default = "selection", newline = "all" }
```
```toml
[editor.render-whitespace]
default = "selection"
newline = "all"
```

**Comment by pickfire** [comment]
We definitely could take some user experience from vscode, last time I used it setting this part they have some sort of presets, we could do that with what you showed.

```toml
[editor]
render-whitespace = "all"
```

And when customization is needed, we can can always fall back to

```toml
[editor.render-whitespace]
default = "selection"
newline = "all"
```

But I think, should we also let the users choose the characters of their choice like what you can do in vim. Or should we also allow theming this one? Since I sometimes see different foreground and background color for these texts, like in doom emacs?
