### ISSUE TITLE
LSP: Default golangci-lint config not working

### ISSUE THREAD

**Issue by YuukanOO** [helix-editor/helix#10807]
### Summary

On a fresh helix installation, after installing `golangci-lint-langserver` with `go install github.com/nametake/golangci-lint-langserver@latest` , the LSP report `exec: "golangci-lint": executable file not found in $PATH`.

The executable is indeed called `golangci-lint-langserver`.

### Workaround

Updating the `.config/helix/languages.toml` with:

```toml
[language-server.golangci-lint-lsp.config]
command = ["golangci-lint-langserver", "run", "--out-format", "json", "--issues-exit-code=1"]
```

### Reproduction Steps

 

I tried this:

1. `go install github.com/nametake/golangci-lint-langserver@latest`
2. open a golang project with `hx .`

I expected this to happen:

Correctly highlight issues with the LSP.

Instead, this happened:

`exec: "golangci-lint": executable file not found in $PATH`

### Platform

macOS

### Terminal Emulator

iTerm 3.5.0

### Installation Method

brew

### Helix Version

helix 24.3 (2cadec0b)
