### ISSUE TITLE
Helix + pyright + kitty has wrong working directory

### ISSUE THREAD

**Issue by carrascomj** [helix-editor/helix#10815]
### Summary

When I open a new kitty tab in the current working directory from within helix, the directory is set to a pyright directory.

This only happens if pyright is enabled (others LS including other python LS do not produce this result).

### Reproduction Steps

 

First, configure helix to use [pyright](https://github.com/microsoft/pyright) (needs to be installed separately). At your languages.toml:

```toml
[language-server]
pyright = { command = "pyright-langserver", args = ["--stdio"], config = {} }
[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = [ "pyright" ]
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "4bfdd9033a2225cc95032ce77066b7aeca9e2efc" }
```

Then configure [kitty](https://sw.kovidgoyal.net/kitty/) accordingly to spawn a new tab at `Ctrl+Shift+T`:

```conf
map ctrl+shift+t new_tab_with_cwd
```

Finally, cd into a python project, open a file with helix and press `Ctrl+Shift+T`.

_I expected this to happen:_

The new tab is at the project directory (proper current working directory).

_Instead, this happened:_

The current working directory of the new tab is `~/.cache/pyright-python/1.1.336/node_modules/pyright/dist`.

I am posting here because this does not occur with nvim+pyright+kitty.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```2024-05-24T22:28:23.179 helix_lsp::transport [ERROR] ruff err <- "warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `.venv/lib/python3.9/site-packages/pandas/pyproject.toml`:\n"
2024-05-24T22:28:23.179 helix_lsp::transport [ERROR] ruff err <- "  - 'ignore' -> 'lint.ignore'\n"
2024-05-24T22:28:23.179 helix_lsp::transport [ERROR] ruff err <- "  - 'select' -> 'lint.select'\n"
2024-05-24T22:28:23.179 helix_lsp::transport [ERROR] ruff err <- "  - 'unfixable' -> 'lint.unfixable'\n"
2024-05-24T22:28:23.179 helix_lsp::transport [ERROR] ruff err <- "  - 'per-file-ignores' -> 'lint.per-file-ignores'\n"
2024-05-24T22:28:23.181 helix_lsp::transport [ERROR] ruff err <- "warning: `PGH001` has been remapped to `S307`.\n"
2024-05-24T22:28:23.334 helix_lsp::transport [ERROR] ruff err <- "   0.180889s INFO ruff_server::server Configuration file watcher successfully registered\n"
2024-05-24T22:28:27.531 helix_lsp::transport [ERROR] ruff err <- "   4.377227s INFO ruff_server::server::connection Shutdown request received. Waiting for an exit notification...\n"
2024-05-24T22:28:27.531 helix_lsp::transport [ERROR] ruff err <- "   4.377660s INFO ruff_server::server::connection Exit notification received. Server shutting down...\n"
2024-05-24T22:28:27.539 helix_lsp::transport [ERROR] err: <- Other(failed to send a message to server

Caused by:
    channel closed)
2024-05-24T22:28:27.539 helix_lsp::transport [ERROR] ruff err: <- StreamClosed
```

</details>


### Platform

Linux

### Terminal Emulator

kitty 0.33.1

### Installation Method

source

### Helix Version

24.03
