### ISSUE TITLE
Some configs do not work

### ISSUE THREAD

**Issue by python128** [helix-editor/helix#1085]
I am not able to allow certain keymaps to work.
Here is my `config.toml`
```toml
theme = "bogster"

[lsp]
display-messages = true

[keys.normal]
S-left = "extend_char_left"
S-right = "extend_char_right"
S-up = "extend_line_up"
S-down = "extend_line_down"

"#" = "toggle_comments"
C-c = "no_op"
q = { q = "wclose" }
"space" = { "space" = "keep_primary_selection" }

A-o = "add_newline_below"
A-O = [ "open_above", "normal_mode" ]

[keys.insert]
C-backspace = "delete_word_backward"
```

- Here, `C-O` and `C-backspace` doesn't work.
- I have tried `C-O` with `add_newline_above` and the given config both.
- `A-o` seems to work perfectly fine.

### Environment

- Platform: Linux(WSL)
- Helix version: v0.5.0-94-gd3def16 (from `git describe`)

[Link](https://python128.github.io/gifs/issue1.gif) to gif.
