### ISSUE TITLE
The Prompt should use a `bar` cursor if the user has configured Insert mode to use a `bar` cursor

### ISSUE THREAD

**Issue by frou** [helix-editor/helix#10874]
The configuration:

```toml
[editor.cursor-shape]
insert = "bar"
```

...is basically indicating that we want a bar cursor when writing. Since writing is what happens in the prompt, it should respect that setting rather than use a block cursor.
