### ISSUE TITLE
Autosave after-delay doesn't work

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#10927]
### Summary

I'm testing auto-save update, new focus-lost setting works but after-delay doesn't

```toml
[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1
```

### Reproduction Steps

1. Build from a64dbf825fe99096ab6899551c391b55287d4c94

2. Set auto-save settings as:
```toml
[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1
```

3. try editing a file

### Platform

macOS

### Terminal Emulator

iTerm 2

### Installation Method

source

### Helix Version

a64dbf825fe99096ab6899551c391b55287d4c94
