### ISSUE TITLE
ruff line length not respected

### ISSUE THREAD

**Issue by davisssamuel** [helix-editor/helix#10939]
My `.config/helix/languages.toml` file looks like so:

```toml
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
line-length = 200

[[language]]
name = "python"
language-servers = [ { name = "pyright", except-features = [ "format", "diagnostics" ] }, "ruff" ]
auto-format = true
```

When I save, ruff still reformats lines that are less than 200 characters in length. How can I make ruff respect a 200 character line length when formatting?
