### ISSUE TITLE
Using the built-in emmet tools in vue-language-server

### ISSUE THREAD

**Issue by overbyte** [helix-editor/helix#11000]
Hi

I asked this question in the emmet-language-server (https://github.com/olrtg/emmet-language-server/issues/41) and the answer was that emmet is bundled with the vue language tools already.

I tried to use it in the same way - by removing the "emmet-lsp" from the vue language config

 ```toml
[[language]]
name = "vue"
language-servers = [ "vue-language-server", "emmet-lsp"]
```

however when i test it in the `<template>` in an sfc by adding `SelfClosing/` and hitting tab, nothing happens.

Do you have any insight on how to use the tool please?

thanks
;oB
