### ISSUE TITLE
Dynamically determine config value

### ISSUE THREAD

**Issue by Gbr22** [helix-editor/helix#11049]
```toml
[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]
config = { typescript = { tsdk = "C:\\Program Files\\nodejs\\node_modules\\typescript\\lib" } }
```
I have configured the vue language server on my windows device, but I want to have a single portable configuration file which I can use on linux as well. It would be nice to have a way to dynamically determine a value in the config file at runtime via some scripting language (bash, lua, js, python, whatever)

I would imagine it as something like this:
```toml
[[dynamic]]
key = "[language-server.vue-language-server].config.typescript.tsdk"
type = "string"
value = { command = "bash", args = ["-c", "echo '$(npm root -g)/typescript/lib'"] }
```

Keep in mind I don't often use toml, so the exact toml syntax for setting the value can be different, I'm just trying to get my point across.
