### ISSUE TITLE
Allow remapping of dot

### ISSUE THREAD

**Issue by ellbur** [helix-editor/helix#11054]
Currently, with this in `config.toml`:

```toml
[keys.normal]
"." = "move_char_left"
```

the <kbd>.</kbd> key continues to have its default function (repeat last insert).

It would be nice to allow it to be remapped.
