### ISSUE TITLE
cmake-format not working as cmake formatter

### ISSUE THREAD

**Issue by steckes** [helix-editor/helix#11075]
### Summary

I tried to use cmake-format as formatter for cmake files.
Instead of formatting, the whole content of the file gets deleted.
I tried adding `-i` as argument for in-place formatting, what does not help.

Here my config:

```Toml
[[language]]
name = "cmake"
auto-format = false
formatter = { command = "cmake-format", args = ["-i"] }
``` 

Do you see something I messed up?
When I call `cmake-format -i CMakeLists.txt` in the commandline it works.

### Reproduction Steps

 

I tried this:

1. `hx`

hx CMakeLists.txt

:format

I expected this to happen:

File gets formatted

Instead, this happened:

Content gets deleted

### Helix log

Logfile stays empty

### Platform

Linux

### Terminal Emulator

alacritty 0.13.2

### Installation Method

pacman

### Helix Version

helix 24.3
