### ISSUE TITLE
Keybind to exit sticky view mode

### ISSUE THREAD

**Issue by lefp** [helix-editor/helix#11166]
As far as I can tell, there is no way to exit sticky view mode (Z) except by pressing Esc.
I don't like reaching over to hit Esc.

The ability to configure a keybind for this would solve this problem. E.g. via a dedicated command:
```toml
[keys.normal.Z]
C-l = "exit_minor_mode"
```
