### ISSUE TITLE
Add support for Liquid

### ISSUE THREAD

**Issue by r3morce** [helix-editor/helix#11207]
Add support for the Shopify Liquid Language.
Also add a preset here: https://github.com/helix-editor/helix/blob/master/languages.toml

Reference:
- https://shopify.github.io/liquid/
- https://shopify.dev/docs/storefronts/themes/tools/cli/language-server

**Comment by egeesin** [comment]
For those who need basic Liquid lang config in Helix:

- Install Shopify CLI: `npm install -g @shopify/cli@latest`
- Make sure `shopify` is in `$PATH`
- Edit `~/.config/helix/languages.toml` or `%AppData%\helix\languages.toml` like below:
```toml
[language-server.shopify-theme-check]
command = "shopify"
args = ["theme", "language-server"]

# npm install -g @shopify/cli@latest
[[language]]
name = "liquid"
scope = "source.liquid"
file-types = ["liquid"]
injection-regex = "^liquid$"
indent = { tab-width = 2, unit = "  "}
language-servers = ["shopify-theme-check"]
block-comment-tokens = { start = "{% comment %}", end = "{% endcomment %}" }

[[grammar]]
name = "liquid"
source = { git = "https://github.com/hankthetank27/tree-sitter-liquid", rev = "d269f4d52cd08f6cbc6636ee23cc30a9f6c32e42"}
# Feel free to edit rev value by the latest commit hash they made.
# In order to add syntax highlighting you must follow this:
# https://docs.helix-editor.com/guides/adding_languages.html#queries
```
- Don't forget to  `hx -g fetch` and `hx -g build`
- For highlighting,
    - copy queries from tree-sitter-liquid repo (`<CONFIG_DIR>/helix/runtime/grammars/sources/liquid/queries/`) we've just fetched,
    - then make target directory and paste to `<CONFIG_DIR>/helix/runtime/queries/liquid/`.
- `hx --health liquid` to confirm that configured language server, tree-sitter parser and highlight queries are ticked.
