### ISSUE TITLE
Support `.surql` SurrealDB files

### ISSUE THREAD

**Issue by johnbchron** [helix-editor/helix#11303]
It's SQL-like, and already has a full grammar: https://github.com/DariusCorvus/tree-sitter-surrealdb

This is the config I use with it, and it's well-formed AFAICT:
```toml
[[language]]
name = "surrealdb"
scope = "source.surrealdb"
file-types = [ "surql" ]
comment-tokens = "--"
indent = { tab-width = 2, unit = "  " };
grammar = "surrealdb"

**Comment by pascalkuthe** [comment]
A grammar needs a source descirption to be effective:
``` toml
[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "473634230435c18033384bebaa6d6a17c2523281" }
```

and (helix-specific) query definitions. One you have all that setup feel free to open a PR, no need to create an issue for something like this first.
