### ISSUE TITLE
soft wrapped lines count for lines when jumping

### ISSUE THREAD

**Issue by Takkaryx** [helix-editor/helix#11328]
### Summary

When jumping with motions such as `10j` or `25k` and the jump crosses softwrapped lines, the softwrapped filler lines count as lines for the jump.

This means that with relative lines, the cursor might not land where you expect.

### Reproduction Steps

in config.toml have

```toml
[editor]
text-width = 80
line-number = "relative"

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
```

open a file with softwrapped lines from this configuration.  open a file with a few lines in it, but with multiple 'softwrapped' lines

should look something like this:
![image](https://github.com/user-attachments/assets/a1afa83a-f3b5-473b-829b-d3f43f0f3793)

from here, can use a vim motion, I will type `4j`

I expect the cursor to move to the `config.vbus_detection = true;` line.

Instead, it goes to the commented line `// to enable vbus_detection to comply with...`

### Platform

MacOS

### Terminal Emulator

wezterm

### Installation Method

source

### Helix Version

24.07-62-g4c183550
