### ISSUE TITLE
Fetched grammar queries not discovered

### ISSUE THREAD

**Issue by heaths** [helix-editor/helix#11378]
I'm trying to add grammar / LSP support for [TypeSpec](https://typespec.io) and its mostly working, but `hx --health typespec` shows:

```text
Configured language servers:
  ✓ tsp-server: /usr/bin/tsp-server
Configured debug adapter: None
Configured formatter: None
Highlight queries: ✘
Textobject queries: ✘
Indent queries: ✘
```

I successfully ran `hx -g fetch` and `hx -g build` (with only the warning `cargo:warning=Compiler version doesn't include clang or GCC: "c++" "--version"`) and `~/.config/helix/runtime/grammars` does include both a `typespec.so` and `sources/typespec`, where the latter contains a `queries` subfolder:

```text
grammars/sources/typespec/queries
  grammars/sources/typespec/queries/highlights.scm
  grammars/sources/typespec/queries/indents.scm
  grammars/sources/typespec/queries/injections.scm
grammars/typespec.so
```

Should the `queries` subfolder be copied up under the `runtime` directly directly, or what else is expected here?

The additions I made to `languages.toml` are:

```toml
use-grammars = { only = ["typespec"] }

[[grammar]]
name = "typespec"
source = { git = "https://github.com/happenslol/tree-sitter-typespec", rev = "28821d0d6da5f0a6b5eb02b9bad953fecafd7248" }

[[language]]
name = "typespec"
scope = "source.tsp"
injection-regex = "(tsp|typespec)"
file-types = ["tsp"]
roots = ["tspconfig.yaml"]
auto-format = true
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 2, unit = "  " }
language-servers = ["typespec"]

[language-server.typespec]
command = "tsp-server"
args = ["--stdio"]
```

The `scope` matches our [TextMate grammar](https://github.com/microsoft/typespec/blob/main/grammars/typespec.json), but I've also tried `source.typespec` here as well, which matches the [tree-sitter grammar](https://github.com/happenslol/tree-sitter-typespec/blob/main/grammar.js) @happenslol created that I'm using above.
