### ISSUE TITLE
pylsp error occured and formatter doesn't work 

### ISSUE THREAD

**Issue by TheWaveLab** [helix-editor/helix#11446]
languages.toml
```toml
[[language]]
name = "python"
scope = "source.python"
injection-regex = "py(thon)?"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = [ "pylsp" ]
formatter = { command = "black", args = ["-"] }
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }


[language-server.pylsp.config.pylsp]
plugins.black.enabled = true
plugins.pylint.enabled = true
plugins.pyflakes.enabled = true
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = false
plugins.isort.enabled = true
plugins.rope_autoimport.enabled = true

```
log
```bash
Caused by:
    channel closed)
2024-08-08T15:46:02.422 helix_lsp::transport [ERROR] pylsp err: <- StreamClosed
```

config.toml
```toml
[editor]
auot-format = true
```

it seems everything was set up, I don't why this happened, format on write doesn't work，also `:format` command.
