### ISSUE TITLE
sequences of commands interact poorly with interactive commands in mappings

### ISSUE THREAD

**Issue by jyn514** [helix-editor/helix#11482]
### Summary

i tried the following config:
```toml
[keys.normal]
"g" = { "q" = ["select_textobject_inner", ":reflow"] }
```
i expect that this allows me to type `gqp` to reflow a paragraph. instead, it reflows the current selection, and then pops up a "Match inside" dialogue that changes, but does not reflow, the selection.

### Reproduction Steps

 

I tried this:

1. `hx helix-term/src/commands/engine/components.rs:387`
2. `xxx`
3. `gqp`

I expected this to happen: `gqp` reflows the macro call.
Instead, this happened: it reflows the 3 selected lines.

https://asciinema.org/a/qwFuppLrNvUG3vxDx0LuQwB2x

### Helix log

nothing relevant

### Platform

linux

### Terminal Emulator

tmux next-3.5, embedded in kitty 0.35.1, with TERM=tmux-256color

### Installation Method

built from source

### Helix Version

helix 24.7 (a632904d)

**Comment by glfmn** [comment]
Also, it would be really useful to be able to to `select_textobject_{around,inside}_paragraph` directly as a command rather than it only having the interactive version; this would be useful to integrate things like[ tidalcycles](https://club.tidalcycles.org/t/language-server-protocol/1525/12) as one could do this:

```toml
[keys.normal.t]
ret = ["select_textobject_around_paragraph", ":pipe-to ~/tidal_send.sh"]
```
