### ISSUE TITLE
Syntax highlighting for typescript stopped unexpectedly

### ISSUE THREAD

**Issue by BambooRaptor** [helix-editor/helix#11511]
Syntax highlighting for typescript stopped for some reason.

The LSP seems to be working fine. I'm getting type hints and goto definition and everything is working, but the syntax highlighting is not.
![image](https://github.com/user-attachments/assets/2950356f-0f2f-492e-9886-44ef27269035)

The issue seems to be only with the typescript files though...
![image](https://github.com/user-attachments/assets/7907d402-1553-4a42-aaa1-753a4043da24)
HTML files seem to work.

And so do zig files apparently, even though I don't have the zig lsp installed
![image](https://github.com/user-attachments/assets/70aa4b0c-dd66-4bab-be4e-736c5e6075a6)

I can't seem to figure out why this is.

This is my `config.toml`
```toml
theme = "gruber-darker"

[editor]
auto-completion = true
auto-format = true
scrolloff = 10
cursorline = true
completion-trigger-len = 1
completion-replace = true
rulers = [80, 120]
bufferline = "multiple"
# color-modes = true

[editor.statusline]
right = ["diagnostics", "selections", "position", "total-line-numbers", "file-encoding"]

[editor.lsp]
display-messages = true
display-inlay-hints = true
# auto-signature-help = false

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
")" = "goto_next_paragraph"
"(" = "goto_prev_paragraph"
"A-)" = "goto_next_parameter"
"A-(" = "goto_prev_parameter"
"C-left" = "jump_view_left" 
"C-right" = "jump_view_right" 
"C-up" = "jump_view_up" 
"C-down" = "jump_view_down" 

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
")" = "goto_next_paragraph"
"(" = "goto_prev_paragraph"
"A-)" = "goto_next_parameter"
"A-(" = "goto_prev_parameter"

[keys.normal.space]
v = { h = "signature_help" }
"=" = ":format"

[keys.normal.space.space]
s = ":write"
q = ":buffer-close"
```

And I haven't created a `languages.toml`.

And in case it helps, these are the results of running `hx --health`
```
Language         LSP              DAP              Formatter        Highlight        Textobject       Indent
html             ✓ vscode-html…   None             None             ✓                ✘                ✘
tsx              ✓ typescript-…   None             None             ✓                ✓                ✓
typescript       ✓ typescript-…   None             None             ✓                ✓                ✓
zig              ✘ zls            ✘ lldb-dap       ✓ zig            ✓                ✓                ✓
```
