### ISSUE TITLE
Selected word highlighting is basically not visible in the `everblush` theme

### ISSUE THREAD

**Issue by leo-unglaub** [helix-editor/helix#11527]
### Summary

If you use the `everblush` theme, the selected word is barley visible. In other themes the contrast is much bigger and better readable.
![image](https://github.com/user-attachments/assets/d526aa0d-e0cd-4140-ab41-b02f480418e2)

### Platform

Linux desktop 6.10.3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.3-1 (2024-08-04) x86_64 GNU/Linux

### Terminal Emulator

GNOME Terminal - Version 3.52.2 for GNOME 46 (VTE version 0.77.91 +BIDI +GNUTLS +ICU +SYSTEMD)

### Installation Method

Binary from the release page

### Helix Version

helix 24.7 (079f5442)

**Comment by RoloEdits** [comment]
This follows the neovim theme one-for-one as far as I can tell. 

`helix:`
```toml
[palette]
black = "#232a2d"

"ui.selection" = { bg = "black" }
"ui.selection.primary" = { bg = "black" }
```

`neovim`:
```lua
local palette = {
    color0 = '#232a2d',
}

Visual = { fg = p.foreground, bg = p.color0 },
```
