### ISSUE TITLE
Count doesn't work properly when remapping with multiple commands

### ISSUE THREAD

**Issue by imsuck** [helix-editor/helix#11550]
### Summary

As stated in the bug report title, remapped keys with multiple commands doesn't behave properly with a count modifier.

See reproduction step for more details.

### Reproduction Steps

In `config.toml`
```toml
[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after", "collapse_selection"]
```

Open a file with the following content:
```
##
1
2
```
With cursor on line 1, the key sequence `2<A-j>` produces:
```
1
##
##
2
```
Expected result:
```
1
2
##
```

### Platform

Linux

### Terminal Emulator

alacritty 0.13.2 (bb8ea18e)

### Installation Method

pacman

### Helix Version

helix 24.7
