### ISSUE TITLE
Invalid key code 'diagnostics' when trying to set end-of-line-diagnostics according to 

### ISSUE THREAD

**Issue by jerabaul29** [helix-editor/helix#11591]
I am setting my config similar to:

https://github.com/helix-editor/helix/blob/af7a1fd20c0a2915e0dae1b5bea7cb6bde6c2746/book/src/editor.md?plain=1#L432-L434

by appending this snippet at the end of my config. However, I then get the following error:

```
Bad config: TOML parse error at line 40, column 1
   |
40 | end-of-line-diagnostics = "hint"
   | ^^^^^^^^^^^^^^^^^^^^^^^
Invalid key code 'diagnostics'

Press <ENTER> to continue with default config
```

commenting out the first line, i.e. appending

```
# end-of-line-diagnostics = "hint"
[editor.inline-diagnostics]
cursor-line = "warning"
```

works fine; should the `end-of-line-diagnostics` be set in another way somehow? :)

**Comment by the-mikedavis** [comment]
Since we don't have any other config in that block I think it would make sense to add the `[editor]` above that line, i.e.:

```toml
[editor]
end-of-line-diagnostics = "hint"
[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
```

We can also switch that codefence to use <code>```toml</code> to get TOML syntax highlighting like the rest of the config snippets. Feel free to open up a PR
