### ISSUE TITLE
Default x/X key bindings

### ISSUE THREAD

**Issue by PitiBouchon** [helix-editor/helix#11599]
I don't understand the default keybindings of :
`x = "extend_line_below"` / `X = "extend_to_line_bounds"`

It is so un-natural and different from the other default keybindings like : f/F, t/T, n/N, o/O where pressing SHIFT kind of do the opposite of the action.

Thus, I think it should be changed to :
```toml
X = "select_line_above"
x = "select_line_below"
```
which would feel more natural along the other default keybindings, and easier for beginner to use
