### ISSUE TITLE
Keymapping which utilizes multiple commands doesn't work in 0.5

### ISSUE THREAD

**Issue by raygervais** [helix-editor/helix#1161]
### Reproduction steps

- Edit `~/.config/helix/config.toml` to include the following

```toml
[keys.normal]
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode
```

- Open helix, note the error: 
```
Error: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 7 column 1
```

Sample Config for context: 
```toml
theme = "everforest"

[lsp]
display-messages = true
line-numbers = "relative"

[keys.normal]
g = { a = "code_action" } # <- Works, but if I were to add additional commands such as below, fails.
"ret" = ["open_below", "normal_mode"] # Does not work
```

 

### Environment

- Platform: MacOS
- Helix version: helix 0.5.0

<details><summary>~/.cache/helix/helix.log</summary>

*Appears to be unrelated*

```
2021-11-24T09:57:42.975 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
```

</details>
