### ISSUE TITLE
Using blade formatter for php blade files

### ISSUE THREAD

**Issue by ZayRTun** [helix-editor/helix#11628]
Hi

I've been trying to setup blade formatter https://github.com/shufo/blade-formatter.

I think I have set it up correctly but when I format the document it clears out everything leaving a blank document. I have also checked the `helix.log` file but there are no errors relating the formatter.

Please advise.

My `languages.toml` file
```toml
[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "blade"
roots = ["composer.json", "index.php"]
language-servers = ["emmet-lsp", "tailwindcss-ls"]
formatter = { command = "blade-formatter", args = ["--write", "--wrap-line-length", "9999", "--wrap-attributes", "preserve-aligned"] }
auto-format = true
```

**Comment by ZayRTun** [comment]
I figured out the problem, I had to add `--stdin` to args and now it works perfectly.

```toml
[[language]]
name = "blade"
roots = ["composer.json", "index.php"]
language-servers = ["emmet-lsp", "tailwindcss-ls"]
formatter = { command = "blade-formatter", args = ["--write", "--stdin", "--wrap-line-length", "9999", "--wrap-attributes", "preserve-aligned"] }
auto-format = true
```
