### ISSUE TITLE
Marksman configuration may not work without adjusting verbosity levels

### ISSUE THREAD

**Issue by jsco2t** [helix-editor/helix#11638]
### Summary

I have the following versions installed:

```txt
MacOS: 14.5
Helix: 24.7 (079f5442) - from homebrew
Marksman: 1.0.0-2023-12-09 - from homebrew
```

**Issue:**
Using a Marksman configuration based on the `languages.toml` in this repo - I was getting the following error:

```
2024-09-05T15:39:10.685 helix_lsp::transport [ERROR] marksman err <- "[15:39:10 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
```

It took me some playing around with `Marksman` to realize the above statement is what Marksman was logging to standard out when its started with: `marksman server`. 

Example:
```bash
❯ marksman server
[16:38:11 INF] <LSP Entry> Starting Marksman LSP server: {}
```

I found that by adjusting Marksman's verbosity levels I could get the transport error to go away:

Example:

```bash
❯ marksman server --verbose 0

```

This lead me to adjust how I was starting `Marksman` in my `languages.toml` configuration:

```toml
[language-server]
marksman = { command = "marksman", args = ["server", "--verbose", "0"] }

.....truncated......

[[language]]
name = "markdown"
language-servers = ["vale", "marksman"]
file-types = ["md", "mdx"]
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
text-width = 100
rulers = [100]
auto-format = true
indent = { tab-width = 2, unit = "  " }
block-comment-tokens = { start = "<!--", end = "-->" }
```

This seems to have resolved any errors I was seeing in the Helix log related to Marksman. In addition (as best I can tell) Marksman is offering it's advertised functionality in Markdown documents.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-09-05T15:39:10.685 helix_lsp::transport [ERROR] marksman err <- "[15:39:10 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
```

</details>

### Platform

macOS

### Terminal Emulator

kitty v0.36.1

### Installation Method

brew

### Helix Version

Helix 24.7 (079f5442)
