### ISSUE TITLE
Default keybinding for move between windows

### ISSUE THREAD

**Issue by bestouff** [helix-editor/helix#1175]
Would it be possible to have these bindings by default ?
```toml
[keys.normal]                                                                                                                                                                                                                                                                                                                                                                                                                                         
"C-left" = "jump_view_left"                                                                                                                                                                                                                                                                                                                                                                                                                           
"C-right" = "jump_view_right"                                                                                                                                                                                                                                                                                                                                                                                                                         
"C-up" = "jump_view_up"                                                                                                                                                                                                                                                                                                                                                                                                                               
"C-down" = "jump_view_down"                                                                                                                                                                                                                                                                                                                                                                                                                           
```
Thanks
