### ISSUE TITLE
[LSP QUESTION] Get full default config for given lsp

### ISSUE THREAD

**Issue by Bowarc** [helix-editor/helix#11800]
Im having a hard time configuring the lsp s

My settings seems to be ignored.

Here is my config: (language.toml)
```toml
[[language]]
name = "rust"

[language.config]
hostInfo = "rust"
locale = "en-GB"

[language-server.rust-analyzer.config]
check.command = "clippy" 
inlayHints = { closureReturnTypeHints = { enable = "never" } }    
```
From this test script it looks like that: 
![helix_rust_closure_inlay](https://github.com/user-attachments/assets/5c51ad60-94c3-4dd7-ae4f-9d10aaec21fe)

But the same setting
```json
{
    "settings": {
        "rust-analyzer.inlayHints.closureReturnTypeHints.enable": "never",
    }
}
```
in sublime text look like: 
![st_rust_closure_inlay](https://github.com/user-attachments/assets/6079851a-00f9-433d-b4cb-c7587ed60990)

My config seem to be uploaded as: (hx -v)
```console
2024 - 09 - 30 T09: 01: 16.866 helix_lsp::client[INFO] Using custom LSP config: {
    "inlayHints": {
        "bindingModeHints": {
            "enable": false
        },
        "closingBraceHints": {
            "minLines": 10
        },
        "closureReturnTypeHints": { // ? >:c
            "enable": "with_block"
        },
        "discriminantHints": {
            "enable": "fieldless"
        },
        "lifetimeElisionHints": {
            "enable": "skip_trivial"
        },
        "typeHints": {
            "hideClosureInitialization": false
        }
    }
}
```

It would be nice having a complete default config for all lsp to use as a base
