### ISSUE TITLE
support for jai

### ISSUE THREAD

**Issue by EriKWDev** [helix-editor/helix#11845]
I've tried adding language support for `jai` using the lsp https://github.com/SogoCZE/Jails and tree-sitter grammar at https://github.com/SogoCZE/tree-sitter-jai, but I can't get it to work. Nothing gets highlighted in the editor, and this is the error messages in the helix log

```log
2024-10-07T08:05:27.905 helix_lsp::transport [ERROR] jails err: <- StreamClosed
2024-10-07T08:05:29.600 helix_core::syntax [ERROR] Failed to load tree-sitter parser for language "jai": Failed to load symbol tree_sitter_jai
```

I have added the following to the `languages.toml` 
```toml
[[language]]
name = "jai"
scope = "source.jai"
file-types = ["jai"]
roots = ["build.jai", "first.jai", "jails.json"]
shebangs = ["jai", "jai-linux"]
language-servers = [
  "jails"  
]
indent = { tab-width = 4, unit = " " }
grammar = "jai"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[[grammar]]
name = "jai"
source = { git = "https://github.com/SogoCZE/tree-sitter-jai", rev="dd2d38d44bf71a0db95c7e745f86b06c3aa7e4d6" }
```

And without knowing much about the setup I did minimal modifications to the `runtime/queries/odin` stuff and put into a `runtime/queries/jai` folder. grammars have been fetched and built and seem to be identified correctly, just don't work

**Comment by Byteron** [comment]
I tried this a few days ago, I did get the LSP to work, but syntax highlighting I did not get working.

```
[language-server.jails]
command = "jails"

[[language]]
name = "jai"
scope = "source.jai"
injection-regex = "jai"
file-types = ["jai"]
comment-tokens = "//"
language-servers = [ "jails" ]

[[grammar]]
name = "jai"
source = { git = "https://github.com/St0wy/tree-sitter-jai", rev = "35c0d66c772900eae3d36b996672884960e35477" }
```

with this LSP works, (it does still output the same error for me, but jump to definition etc still works)
just the [[grammar]] bit does not work as mentioned.

**Comment by Byteron** [comment]
I had just read on the odin tree sitter page that tree sitter stuff needs to be defined at compile time and a helix rebuild is required. Is that true, or is that perhaps an outdated information?

**Comment by EriKWDev** [comment]
I tried your config and indeed I get rudimentary goto definition working! 

And hmm, by copying https://raw.githubusercontent.com/St0wy/tree-sitter-jai/refs/heads/main/queries/highlights.scm and putting it in `runtime/queries/jai` I also get some very basic highlighting though it seems to fall apart pretty quickly on multi-line comments and confusing some number-literals for types.

Don't know if this is just the state of the project or what to expect

I did try to recompile as you said but not with my modified odin stuff

**Comment by the-mikedavis** [comment]
The issue is the capital J in Jai here: https://github.com/SogoCZE/tree-sitter-jai/blob/dd2d38d44bf71a0db95c7e745f86b06c3aa7e4d6/grammar.js#L2

That needs to be lowercase to match `name = "jai"` in the `[[grammar]]` section. It might work (I haven't tested this) to use `name = "Jai"` in `languages.toml` instead but the convention with all other tree-sitter grammars is to use lowercase for the name so I would recommend suggesting this change upstream

**Comment by SaumitraLohokare** [comment]
Hello,
I haven't been able to solve this issue completely but I can share my progress. I managed to get decent syntax highlighting (although not the best).

Firstly I used this implementation of tree-sitter for Jai: https://github.com/constantitus/tree-sitter-jai
The repo contains the required queries as well.

I did modify the `highlights.scm` query a little bit: [highlights.scm.txt](https://github.com/user-attachments/files/19213470/highlights.scm.txt)

Also, here is my `languages.toml` entry:
```toml
[[language]]
name = "jai"
scope = "source.jai"
file-types = ["jai"]
roots = ["build.jai", "first.jai", "main.jai"]
shebangs = ["jai", "jai-linux", "jai-macos"]
indent = { tab-width = 4, unit = " " }
grammar = "jai"
auto-format = false
comment-tokens = "//"
block-comment-tokens = { start = "/*", end = "*/" }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[[grammar]]
name = "jai"
source = { git = "https://github.com/constantitus/tree-sitter-jai", rev="889f8b310fa005c668853ba40a1c6cfc060b1a8b" }
```
