### ISSUE TITLE
Add amber-lang support

### ISSUE THREAD

**Issue by lens0021** [helix-editor/helix#12001]
Amber is
> The Programming Language compiled to Bash.
> -- https://amber-lang.com/

But currently in their alpha stage.

**Comment by lens0021** [comment]
I added the following

```toml
[[grammar]]
name = "amber"
source = { git = "https://github.com/amber-lang/tree-sitter-amber", rev = "01bf07600a9ddc3a7c8a00d9e207dd35b156d93a" }

[[language]]
name = "amber"
scope = "source.ab"
file-types = ["ab"]
comment-token = ["//"]
indent = { tab-width = 4, unit = "    " }
```

And executed `hx -g fetch amber` and `hx -g build` but could not make the syntax highlighting to work. (I don't understand how Helix and tree sitter work!)
