### ISSUE TITLE
vjx<esc> behaves differently if you map the equivalent motions to a key

### ISSUE THREAD

**Issue by nikitarevenco** [helix-editor/helix#12011]
With an empty `config.toml`, If we have the following file, with cursor at `*`:

```
This is a v*ery small
poem about sunflowers.
Maybe not.
```

Then pressing `vjx<esc>`, which is equivalent to `select_mode, move_visual_line_down, extend_line_below, normal_mode` will have the following result (visual selection indicated by `||`):

```
||This is a v*ery small
poem about sunflowers.||*
Maybe not.
```

With the following `config.toml`:

```toml
[keys.normal]
j = ["select_mode", "move_visual_line_down", "extend_line_below", "normal_mode"]
```

And the same initial file, and pressing `j`, we will have:

```
This is a v*ery small
||poem about sunflowers.||*
Maybe not.
```

helix version: `helix 24.7 (079f5442)`
