### ISSUE TITLE
Book/Documentation: keys are black on black in light mode

### ISSUE THREAD

**Issue by Release-Candidate** [helix-editor/helix#12053]
A screenshot of https://docs.helix-editor.com/master/keymap.html (on MacOS and Linux, Chrome and Firefox):

![helix_keymap](https://github.com/user-attachments/assets/ec2902d8-8fb9-4aba-b11a-78e44a4afecf)

A solution would be to not override the default background in 

```css
:where(.colibri) .hljs {
    /* background: #2f1e2e; */
    color: #a39e9b;
}
```

default, light grey:

```css
.hljs {
    display: block;
    overflow-x: auto;
    background: #f6f7f6;
    color: #000;
}
```
