### ISSUE TITLE
Inconsistent ordering of inlay hints at the same position

### ISSUE THREAD

**Issue by WaffleLapkin** [helix-editor/helix#12135]
### Summary

When multiple inlay hints share the same position they are ordered inconsistently. The order might change after a seemingly unrelated change. Note that LSP prescribes a set order:

> If multiple hints have the same position, they will be shown in the order they appear in the response.

nvim previously had a similar bug: https://github.com/neovim/neovim/issues/29647.

### Reproduction Steps

 

I tried this:

1. Use the following `languages.toml`
   ```toml
   [language-server.rust-analyzer.config] 
   inlayHints.expressionAdjustmentHints.enable = "always"
   # aren't technically required, you can get the same bug without these,
   # but my reproduction was test with them
   inlayHints.expressionAdjustmentHints.mode = "prefer_postfix"
   inlayHints.chainingHints.enable = false
   ```
2. `cargo new helix-inlay-ordering && cd helix-inlay-ordering`
3. Write the following to `src/main.rs`:
    ```rust
    fn main() {
        let _: &str = "";
        let _: &str = "";
        let _: &str = "";
        let _: &str = "";
        let _: &str = "";
        let _: &str = ""; // ???
        let _: &str = ""; // ???
        let _: &str = "";
        let _: &str = "";
        let _: &str = "";
        let _: &str = "";

        //
        //
        //
        //
        //
        //
        //
        //
        //
        //
        //
        //
        //
    }
    ```
4. `hx src/main.rs`
5. Observe that on lines with `// ???` the inlay hints are ordered as `.&.*` instead of `.*.&`:
   [![asciicast](https://asciinema.org/a/BWADPFST6i9ZQoR5JjqqXcq2S.svg)](https://asciinema.org/a/BWADPFST6i9ZQoR5JjqqXcq2S)

I expected this to happen: all lines have the exact same inlay hint of `.*.&`

Instead, this happened: some lines have `.&.*` instead

### Helix log

[helix.log](https://github.com/user-attachments/files/17925016/helix.log)

### Platform

Linux

### Terminal Emulator

alacritty 0.14.0

### Installation Method

nixpkgs

### Helix Version

helix 24.7 (079f5442)
