### ISSUE TITLE
Add toggle to completely disable diagnostic rendering

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#12154]
This has been a commonly asked feature and currently there isn't a way to completely disable them as far as I can tell (or it isn't obvious to me). It should be fairly straightforward from what I can tell.

**Comment by NikitaRevenco** [comment]
If such command is added it shouldn't hide the diagnostic symbols, but rather only hide the inline diagnostics or the overlay diagnostics (default action)

the reason why, is because gutter symbols are not intrusive. I may want to disable diagnostics for some time to avoid them getting in the way, but still having the information that there are errors on those lines is useful

**Comment by lando212pm** [comment]
I found some workarounds.

If you're using inline diagnostics:

```toml
[keys.normal.space]
# toggle inline diagnostics
"space" = ":toggle inline-diagnostics.max-diagnostics 0 10"
```

Pressing `<space><space>` will effectively toggle diagnostic rendering by setting the max number of diagnostics rendered to either 0 or 10 (helix's current default).

And if you're not using inline diagnostics (old diagnostics rendering):

```toml
[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"
max-diagnostics = 0

[keys.normal.space]
# toggle diagnostics 
"space" = ":toggle inline-diagnostics.cursor-line hint disable"
```

Works by toggling inline-diagnostics while max-diagnostics is set to zero effectively enabling/disabling diagnostics for those using the old diagnostics rendering. Takes advantage of the way old style diagnostics are automatically enabled when inline-diagnostics are turned off.

I haven't tested how this interacts with `editor.end-of-line-diagnostics`

_The yak shaving continues..._
