### ISSUE TITLE
`replace_selections_with_clipboard` doesn't remove `cr` on windows

### ISSUE THREAD

**Issue by sibouras** [helix-editor/helix#12329]
### Summary

when copying multiline text on windows and then replacing the selection with `space+R` the carriage return `cr` doesn't get removed which causes bugs in biome formatting, pasting with `space+p` works fine though

### Reproduction Steps

sample code to copy
```js
const people = [
	{ name: "one", year: 2000 },
	{ name: "two", year: 2001 },
	{ name: "three", year: 2002 },
	{ name: "four", year: 2003 },
];
```

https://github.com/user-attachments/assets/a2e67005-4881-45e9-ba74-d0f6fb18cc9c

I tried this:

1. open helix, paste the sample text and save
2. `biome format` , no `cr` is showing(expected)
3. replace the selection with `space+R`
4. `biome format` shows `cr`
5. run `fmt` multiple times and biome gets confused

this is my config
```toml
[[language]]
name = "javascript"
language-servers = [
  { name = 'biome' },
  { name = 'typescript-language-server', except-features = ['format'] },
]

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]
required-root-patterns = ["biome.json", "biome.jsonc"]

```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

windows

### Terminal Emulator

windows-terminal

### Installation Method

source

### Helix Version

helix 24.7 (91a5d407)
