### ISSUE TITLE
Nested macros

### ISSUE THREAD

**Issue by cgahr** [helix-editor/helix#12630]
The new macro expansion syntax is great. However, I just wanted to include one macro in another which does not work:
```toml
[keys.normal."["]
b = "@\"_?^#<space>%%<ret>"

[keys.normal.backspace]
t = "@[b<do something>"
```
`[b` finds the previous occurrence of `# %%` at the beginning of the line. I wanted to use this macro to make another macro more readable, but it did not work.

I assume that this is not trivial to do and also not high priority, but I think a tracking issue is useful nonetheless.
