### ISSUE TITLE
delay opening the hint menu in multi-keystroke commands (space, g, brackets...)

### ISSUE THREAD

**Issue by aster-void** [helix-editor/helix#12680]
issue:
the entire screen flickers for the hint menu, when the screen scaling is large (such as when on laptop)

suggestion:
add a configuration option to delay opening the hint menu.

```toml
[editor]
key-hint.enable = true # it would be nice if it can be disabled, but this is out of the scope of this issue
key-hint.delay = 500 # wait 500ms before opening the hint menu
```
