### ISSUE TITLE
Allow LSP to be enabled for any language

### ISSUE THREAD

**Issue by shikanime** [helix-editor/helix#12721]
Currently, Helix allows associating language servers with specific file types. This is great for precise control, but it can be cumbersome when you want to use a language server across *all* file types, especially for general-purpose language servers like those used for AI assistance.  This often requires redundant declarations for each language, even when supplementing existing language servers with AI assistance.

This issue proposes adding a feature to globally enable a language server, making it active regardless of the file type, without needing to redeclare the LSP for each language while also re-adding the default language-specific servers.

## Actual

```toml
[language-servers]
lsp-ai = { command = "ai-lsp-server", ... other configuration ... }
[[language]]
name = "rust"
language-servers = ["rust-analyzer", "lsp-ai"]
```

## Proposed Solution

Introduce a new section in the `languages.toml` configuration to define globally enabled language servers. Something like:

```toml
[language-servers]
lsp-ai = { command = "ai-lsp-server", ... other configuration ... }
[[language]]
name = "*"
language-servers = ["lsp-ai"]
```

**Comment by codingjerk** [comment]
I like this proposal a lot.

It will also be good for many other language servers, `cspell-lsp`, `harper-ls`, `ltex-ls`, `vale-ls`, `typos-lsp`, etc.

**Comment by shaleh** [comment]
See the branch above this comment. I have not made it a PR just yet. Still an exploration. It is not fully functional as I write this.

**Comment by shaleh** [comment]
An alternative would be something like a 'global' section instead of the __common__ hack.

**Comment by NikSneMC** [comment]
Any updates on this?

**Comment by camerondugan** [comment]
I've opened a PR #14804, I don't expect this to merge without changes I'm still new to contributing to helix. To reduce number of lines changed, config introduced in the pr looks like:
```toml
# languages.toml
global-language-servers = [ "your_global_lsp", "you_can_have_more_than_one" ]

[[language]]
ignore-global-language-servers = true # prevents global-language-servers from being added to this language.
name = "rust"
```
