### ISSUE TITLE
Allow setting just theme modifiers but not colors

### ISSUE THREAD

**Issue by arcstur** [helix-editor/helix#12740]
This

```toml
inherits = "catppuccin_mocha"

["markup.heading.1"]
modifiers = ["underlined"]
```

will remove `markup.heading.1` foreground color.

I would like for a way to just override the modifiers while not disabling the original theme's foreground color.

The original is `"markup.heading.1" = "lavender"`

**Use case**: I like switching themes and inherit them. Most themes don't have good markdown modifiers in my opinion, I usually like to easily distinguish h1, h2, h3, but they look the same in most themes.
