### ISSUE TITLE
Already supported for "Alloy"

### ISSUE THREAD

**Issue by PorcoRosso85** [helix-editor/helix#12803]
**This issue may be un-reported, yet.**

Already supported for "Alloy" ?

[alloy github](https://github.com/AlloyTools/org.alloytools.alloy)
  [LSP maybe](https://github.com/AlloyTools/org.alloytools.alloy/tree/master/org.alloytools.alloy.lsp)
[neovim sample](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs/alloy_ls.lua)

**Comment by marc-thieme** [comment]
I just setup this configuration
```toml
[language-server.alloy]
command = "sh"
args = ["-c", 'java -jar $(IFS=:;for path in $PATH; do [ -f "$path/org.alloytools.alloy.dist.jar" ] && echo "$path/org.alloytools.alloy.dist.jar" && exit 0; done) lsp']

[[language]]
name = "alloy"
scope = "source.alloy"
file-types = ["als"]
language-servers = ["alloy"]
grammar = "alloy"
comments-token = "//"

[[grammar]]
name = "alloy"
source = {git = "https://github.com/fore-stun/tree-sitter-alloy.git", rev = "26d70b6745d10380b87a98a25cd7159c68a0f668"}
```
