### ISSUE TITLE
config custom clipboard provider, inverted yank/paste

### ISSUE THREAD

**Issue by glcraft** [helix-editor/helix#12816]
### Summary

Configuration values `editor.clipboard-provider.custom.yank` and `editor.clipboard-provider.custom.paste` are inverted. yank acts like paste, and paste acts like yank.

### Reproduction Steps

I tried this:

1. `helix`
2. Open the config (`:config-open`)
3. I wrote the following config:

```toml
[editor.clipboard-provider.custom]
yank = { command = "copy-text" }
paste = { command = "paste-text" }
```
4. Save the file (`:w`)
5. Reload the config (`:config-reload`)

I found out that `<Space>-y` was using `editor.clipboard-provider.custom.paste` and `<Space>-p` was using `editor.clipboard-provider.custom.yank`

For instance, I just swapped both config in the config.toml to work around this issue : 
```toml
[editor.clipboard-provider.custom]
paste = { command = "copy-text" }
yank = { command = "paste-text" }
```

### Helix log

*(there is no bug strictely speaking, no need of log I guess)*

### Platform

Arch Linux

### Terminal Emulator

Konsole 24.12.2

### Installation Method

pacman

### Helix Version

helix 25.01.1

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/discussions/12661#discussioncomment-11947967. I think it would be ok to make a breaking change here and rename these fields, either swapping them or naming them something more specific

**Comment by 1nkwell** [comment]
I have also noticed this issue, but it hasn't been fixed yet. Is there a problem with my understanding?

**Comment by kendfss** [comment]
> I think it would be ok to make a breaking change here and rename these fields, either swapping them or naming them something more specific

how about

```toml
[editor.clipboard-provider.custom]
write = { command = "copy-text" }
read = { command = "paste-text" }
```
