### ISSUE TITLE
Allow use of Environment variables in languages.toml (and/or config.toml)

### ISSUE THREAD

**Issue by tahir-hassan** [helix-editor/helix#12843]
It would be cool if I could do:

```toml
[[language]]
name = "markdown"
formatter = { command = "pwsh", args = ["-noprofile", "-f", "${env:PS_SCRIPTS}\\format_md.ps1"]}
auto-format = true
```

Where `${env:PS_SCRIPTS}` is a reference to a variable.  It might make configuration a bit easier for people.
