### ISSUE TITLE
Word splitting for %sh{} expansions?

### ISSUE THREAD

**Issue by postsolar** [helix-editor/helix#13096]
Is it currently possible? I remember it worked fine with one of the earlier PRs for expansions, but it doesn't seem to be possible with the one recently merged.

I believe the use cases for this should be pretty obvious and popular. For instance, opening multiple files at once with an external tool.

To reproduce my issue:
1. `:open %sh{ printf %%s\n a b c }
2. Doesn't work, a single file named "abc" opens up
3. `:open %sh{ echo a b c }`
4. Doesn't work either, a single file named "a b c" opens up

**Comment by nik-rev** [comment]
Maybe we could have some kind of spread syntax?

```
:open %sh{ echo a b c }
```

Expands to `:open "a b c"`

```
:open ...%sh{ echo a b c }
```

Expands to `:open "a" "b" "c"`

**Comment by RoloEdits** [comment]
This is due to how the parsing now works. It basically becomes this: `["open", "%sh{ echo a b c }"]`.

And then when the replacement happens: `["open", "a b c "]`, with `"a b c"` being passed to open. I guess this is one of the downsides of not treating the expansions as a replace-like function, which then gets parsed and passed, now populated, to the command.

Not sure what would be simplest way to get this functionality, as you cant just split on whitespace for everything.

**Comment by acramsay** [comment]
Has anyone put more thought into this? A solution here would really solve some issues with tool integrations. In my case, I'm trying to not rely on a terminal multiplexer which _really_ makes it hard to swap out tools.

```TOML
[keys.normal.space]
# o = """:sh wezterm cli split-pane sh -c "yazi --chooser-file=/dev/stdout | while read -r; do wezterm cli send-text --pane-id ${WEZTERM_PANE} --no-paste \\":o \\${REPLY}\r\\"; done" > /dev/null"""
o = [
    ":open %sh{echo $(yazi --chooser-file /dev/stdout 2> /dev/null)}",
    ":redraw"
]
```

While the new command is sooo much simpler, it can't handle multiple file names being returned by yazi. 

The current behavior is quite confusing because field splitting (thanks for the terms @postsolar!) is definitely the behavior I expected. IMO, a new syntax shouldn't be implemented as the parameter expansion of `%sh{}` should not effectively be quoted. If someone needs quotes, then they could be added by the end user in TOML.
