### ISSUE TITLE
Support runtime environment

### ISSUE THREAD

**Issue by dwpeng** [helix-editor/helix#13093]
When I use clangd as a lsp, I want to configure `include path` by the following settings
```toml
[language-server.clangd]
auto-format = true
config = { "fallbackFlags" = [
    "-I./",
    "-I./include",
    "-I./deps",
    "-I./deps/**/include",
    "-I./src/include",
    "-I./**/include",
    "-I./third_party/**/include",
    "-I./third_party/",
] }
command = "clangd"

[[language]]
name = "c"
indent = { tab-width = 2, unit = " " }
file-types = ["c", "h", "cc", "cpp", "cxx", "hpp", "hxx"]
language-servers = ["clangd"]
formatter = { command = "clang-format" }
```

My dir-tree is
```bash
seqio.c
seqio.h
test/test-seqio.c
```

And I open a source file in sub-dir

```bash
# first
hx test/test-seqio.c
``` 

```c
#include <seqio.h>
// other
```

The clangd can't find the header file.

In vscode, it provides a environment var `workspaceFolder`, and I can config clangd like 
```json
"clangd.fallbackFlags": [
    "-I${workspaceFolder}",
    "-I${workspaceFolder}/include",
    "-I${workspaceFolder}/deps",
    "-I${workspaceFolder}/deps/**/include",
    "-I${workspaceFolder}/src/include",
    "-I${workspaceFolder}/**/include",
    "-I${workspaceFolder}/third_party/**/include",
    "-I${workspaceFolder}/third_party/"
  ],
```

So I guess if helix could provide function like this.
