### ISSUE TITLE
rust-analyzer: problems with handling generated code with default lsp settings

### ISSUE THREAD

**Issue by njeisecke** [helix-editor/helix#13123]
### Summary

`rust-analyzer` fails to provide information about generated code on subsequent runs.

### Reproduction Steps

A projects uses some build time code generation (e.g. prost for protobuf). On initial run (after `cargo clean`) everything works, rust-analyzer correctly provides information (hover, goto, ...) for generated code. On subsequent runs "no hover results available" errors occur and symbol navigation fails to work for generated code. 

Also macro invocations like `tonic::include_proto!("myproto")` result in "failed to load ..rs" errors.

In Visual Studio Code or neovim (astronvim) it works as expected.

Fix:

```
[language-server.rust-analyzer.config]
files.excludeDirs = [ ".direnv", ".git", "target" ]
```

This is also what the astronvim rust-lsp configuration does. `target` is actually the cruical entry.

Seems `files.excludeDirs` is not documented (or lacking documentation updates) for rust analyzer, but it works.

It might make sense to add this to the default helix rust-lsp configuration.

### Platform

macOS

### Terminal Emulator

iTerm2

### Installation Method

source

### Helix Version

e56d3abb0ac76ea6e94333b7b70de092d309a912

**Comment by donottellmetonottellyou** [comment]
#13141

Has this been reported upstream @njeisecke ?

**Comment by njeisecke** [comment]
@donottellmetonottellyou No, wasn't able to create a minimal reproducer. This just happens in one of my more complex projects.

**Comment by TheSylex** [comment]
I just spent like 7 hours trying to get to the root of this f*ck me.  However I've got a pretty minimal reproducer so I'm posting it in case it's useful.

**Comment by TheSylex** [comment]
main.rs
```rust
use bevy::DefaultPlugins;
use bevy::prelude::*;
use bevy_immediate::BevyImmediatePlugin;
use bevy_immediate::ui::CapsUi;

fn main() {
    App::new()
        .add_plugins((
            DefaultPlugins,
            // LogDiagnosticsPlugin::default(),
            BevyImmediatePlugin::<CapsUi>::new(),
        ))
        .run();
}
```

Cargo.toml
```toml
[package]
name = "minimal-example"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.2" }
bevy_enhanced_input = "0.19.0"
bevy_framepace = "0.19.1"
bevy_gearbox = "0.4.0"
bevy_immediate = { version = "0.3.0" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
```
