### ISSUE TITLE
lsp server config from languages.toml not merged

### ISSUE THREAD

**Issue by Kritzefitz** [helix-editor/helix#13129]
### Summary

When both a global `~/.config/helix/languages.toml` and a project-local `~/.helix/languages.toml` are present, configuration data for lsp servers, such as under `[language-server.rust-analyzer.config]` don't get merged correctly. Instead, any configuration specified in the project-specific file causes all configuration from the global file for that lsp server to be ignored.

### Reproduction Steps

1. Create `~/.config/helix/languages.toml` with the following content:

  ```toml
  [language-server.rust-analyzer.config]
  inlayHints.closureReturnTypeHints.enable = "always"
  ```
2. Open a suitable rust file and observe that inlay hints for closure return types are rendered
3. Create a project-local configuration in `./.helix/languages.toml` with the following content:

  ```toml
  [language-server.rust-analyzer.config]
  inlayHints.closureCaptureHints.enable = true
  ```

4. Open the same rust file again and observe that there are now no inlay hints for closure return types, but the closure capture hints from the project-specific configuration are now enabled.

I've recorded a reproduction in asciinema here: [recording.txt](https://github.com/user-attachments/files/19291268/recording.txt)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2025-03-17T17:19:40.129 helix_lsp::transport [ERROR] rust-analyzer <- ServerError(-32801): content modified
2025-03-17T17:19:43.728 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(3)), original request likely timed out
```

</details>

### Platform

Debian Trixie

### Terminal Emulator

# GNOME Terminal 3.55.90 using VTE 0.79.90 +BIDI +GNUTLS +ICU +SYSTEMD

### Installation Method

releases page

### Helix Version

helix 25.01.1 (e7ac2fcd)
