### ISSUE TITLE
Add RDF Turtle language treesitter

### ISSUE THREAD

**Issue by xubaiwang** [helix-editor/helix#13145]
Please add support for RDF Turtle language, which is a W3C standard for knowledge graph representation.
This can be done using the tree-sitter format from [GordianDziwis](https://github.com/GordianDziwis/tree-sitter-turtle), along with some simple highlight rules written by me.

I'm not sure how to add language support to helix project, so I just post my config here.

#### What it looks like (with catppuccin-latte theme):

![Image](https://github.com/user-attachments/assets/b7a46a2f-4521-4992-bb0e-fbd84c11a074)

The example is taken from [Introduction](https://www.w3.org/TR/turtle/#h2_sec-intro) part of W3C specification.

#### `languages.toml`

```toml
[[language]]
name = "turtle"
scope = "source.turtle"
injection-regex = "turtle"
file-types = ["ttl"]
comment-tokens = "#"
indent = { tab-width = 2, unit = "  " }
grammar = "turtle"

[[grammar]]
name = "turtle"
source = { git = "https://github.com/GordianDziwis/tree-sitter-turtle", rev = "7f789ea7ef765080f71a298fc96b7c957fa24422" }
```

#### `highlights.scm`

```scm
(comment) @comment.line
(namespace) @namespace
(iri_reference) @string.special.url

; literals
(string) @string
(integer) @constant.numeric.integer
(decimal) @constant.numeric.float
(double) @constant.numeric.float
(boolean_literal) @constant.builtin

(pn_local) @variable

[ "," ";" "." ] @punctuation.delimiter
[ "@prefix" "PREFIX" "@base" "BASE" ] @keyword.directive
[ "[" "]" "(" ")" ] @punctuation.bracket

(lang_tag) @attribute
[ "^^" ] @operator
("a") @keyword.operator
```
