### ISSUE TITLE
Missing documentation for `editor.terminal` config option

### ISSUE THREAD

**Issue by RoloEdits** [helix-editor/helix#13227]
### Summary

Since cb7615e0ed119f292eabdce784e4635247ed1eb1 it became possible to have:

```toml
[editor.terminal]
command = "wezterm"
args = ["cli", "split-pane"]
```

But there is no reference to this config option on the documentation on the website.

(Not sure if lack of documentation is considered a bug or not, some places do)

### Platform

...

### Terminal Emulator

...

### Installation Method

...

### Helix Version

...
