### ISSUE TITLE
Support BrowserBack/Forward events in key remapping

### ISSUE THREAD

**Issue by fnuttens** [helix-editor/helix#13303]
I’m not sure it is possible to catch these from the terminal, but it sure would be neat for those of us who use custom keyboard layouts.

Example:

```toml
[keys.normal]
"browserback" = "jump_backward"
"browserforward" = "jump_forward"
```
