### ISSUE TITLE
Allow choosing formatter from LSP servers

### ISSUE THREAD

**Issue by aster-void** [helix-editor/helix#13353]
Currently, if I want to use a specific formatter for a language,

I need to either:

- use a stdio-style formatter
- exclude feature "format" from every LS except for the wanted one

I would like to set it like this instead:

```toml
[[language]]
formatter = { server = "my-formatter-lsp-server-name" }
```
