### ISSUE TITLE
Setting "tab" = expand_selection also sets C-i to expand_selection

### ISSUE THREAD

**Issue by danielkarch** [helix-editor/helix#13456]
### Summary

When I map `expand_selection` to `tab`, `C-i` does not map to `jump_forward` any more, but also expands the selection.

This used to work. I just updated to Fedora version 42, it could be that this triggered the issue.

### Reproduction Steps

I tried this:

I mapped `expand_selection` to `tab`.

I expected this to happen:

`tab` should expand the selection, and no other mappings should be affected.

Instead, this happened:

`tab` maps to `expand_selection`, but `C-i` also expands the selection, instead of jumping forward in the jump list.

This is the relevant section from my `Config.toml`:

```toml
[keys.normal]
j = "move_char_left"
l = "move_char_right"
h = "move_visual_line_up"
k = "move_visual_line_down"
"tab" = "expand_selection"
"S-tab" = "shrink_selection"
"ret" = "goto_word"
```

Here is a screen recording. I jump back and forth between two buffers with `C-o` and `C-i`, then uncomment the line that maps `tab` to `expand_selection`. Then I press  `C-i` again and it now expands the selection instead of jumping.

 
https://github.com/user-attachments/assets/ec88de6f-841c-4454-bd46-2599920d5abe

### Platform

Fedora Linux 42

### Terminal Emulator

wezterm, gnome-terminal

### Installation Method

cargo

### Helix Version

helix 25.01.1 (aac0ce5f)
