### ISSUE TITLE
Cursor shape not changing on multiple cursors

### ISSUE THREAD

**Issue by benniestudios** [helix-editor/helix#13471]
I have this as my config:
```TOML
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
```

But when I enter insert mode for example, it only changes the last cursor to "bar". Not all cursors if I have multiple. At first I thought only the second one was in insert mode. Is it possible to make all cursors change shape? 

![Image](https://github.com/user-attachments/assets/e97d9dbb-fd89-409e-a0c7-cb1278ace9c6)
In the image above I have two cursors and only the second one is a bar cursor.
