### ISSUE TITLE
`required-root-patterns` negative pattern

### ISSUE THREAD

**Issue by xubaiwang** [helix-editor/helix#13611]
Currently, the `required-root-patterns` option allows only positive glob pattern. It would be helpful to also have negative patterns like `!package.json`.

The negative pattern is very useful if user want to disable the LSP when specific files exists.

## Concrete Example

A real world use case is `deno-lsp` and `typescript-language-server`. Users may want to enable deno globally (for scripting), while disable it in Node.js specific projects.

This can be achieved with following configuration (adapted from https://github.com/helix-editor/helix/discussions/8372#discussioncomment-9716443):

```toml
[language-server.deno-lsp]
args = ["lsp"]
command = "deno"
required-root-patterns = ["!package.json"]

[language-server.typescript-language-server]
required-root-patterns = ["package.json"]
```

## Detailed Syntax

The syntax is taken from [gitignore](https://git-scm.com/docs/gitignore) file.
Only prefix `!` matters, and can be escaped with `\!`.

**Comment by xubaiwang** [comment]
If you think this approach is feasible, I can help make a pull request.

**Comment by xubaiwang** [comment]
Any comment on this?

**Comment by xbwwj** [comment]
It has been a long time since creation of this pull request without any review, so I suppose this feature will not get merged.

Here is a **workaround** for other users who want to use `deno` globally but disable it in `nodejs` projects:

1. Set `deno-lsp` globally in `~/.helix/language.toml` instead of `~/.config/helix/languages.toml`. Since helix' search of project local config will not go across git repo, this setting will be invalidated in any git repo.
2. Set both `deno-lsp` and `typescript-language-server` regularly in `~/.config/helix/languages.toml`.

The full configuration is as below:

```toml
# ~/.helix/languages.toml
[language-server.deno-lsp]
required-root-patterns = []
```

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["ts", "tsx"]
auto-format = true
language-servers = ["deno-lsp", "typescript-language-server"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["js", "jsx"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
required-root-patterns = ["deno.json", "deno.jsonc"]
config.deno.enable = true

[language-server.typescript-language-server]
required-root-patterns = ["package.json"]
```
