### ISSUE TITLE
Uiua LSP only partially works

### ISSUE THREAD

**Issue by mi2ebi** [helix-editor/helix#13622]
### Summary

Formatting and autocomplete work, but syntax highlighting and diagnostics don't. I assume this is a Helix problem because everything works fine in e.g. VS Code.

### Reproduction Steps

I tried this:

1. `cd Documents/uiuatest; hx main.ua`
2. enter `i`nsert mode
3. `F = back(/*+ran) 1`, newline, `F`
4. exit insert mode, `:w`

I expected this to happen:
- format (the first line to `F ← ˜(/×+⇡)1`)
- highlight
- diagnostics (the call to `F` without an argument is invalid; running `uiua run` produces this:
```
Error: Stack was empty when getting argument 2
  at main.ua:1:5
1 | F ← ˜(/×+⇡)1
        ─
  in F at main.ua:2:1
```
)

Instead, this happened: only format

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2025-05-26T20:56:23.073 helix_lsp::util [WARN] LSP position Position { line: 4294967295, character: 4294967295 } out of range assuming EOF
2025-05-26T20:58:23.518 helix_lsp::util [WARN] LSP position Position { line: 4294967295, character: 4294967295 } out of range assuming EOF
```

</details>

### Platform

fedora 42 kde

### Terminal Emulator

konsole

### Installation Method

dnf

### Helix Version

helix 25.01.1 (e7ac2fcd)

**Comment by mi2ebi** [comment]
Relevant config:
```toml
[[language]]
name = "uiua"
scope = "source.uiua"
file-types = ["ua"]
language-servers = ["uiua-lsp"]
auto-format = true

[language-server.uiua-lsp]
command = "uiua"
args = ["lsp"]
```
