### ISSUE TITLE
[Syntax Highlighting] Documentation comments not coloured differently

### ISSUE THREAD

**Issue by lmmx** [helix-editor/helix#13658]
I read the docs and it says I should be able to colour docstrings in Rust (`///`) differently to regular comments (`//`), but when I tried to do this in a custom theme ([link](https://gist.github.com/lmmx/ab3cd0bdff9d3436c858b1b0c55cb26a)) I found it not possible.

- The theme is the `heisenberg` one with minor amendments. I updated to latest helix release but saw no difference.

I can't see this reported before, but since it's documented otherwise I suspect a regression may have occurred and this behaviour was lost.

![Image](https://github.com/user-attachments/assets/038129cf-0cc8-479a-8f92-0a8f1621811d)

Here I had tried to style with variations like

```toml
"comment" = { fg = "teddy_bear_pink_intense", modifiers = ["italic"] }
"comment.line" = { fg = "teddy_bear_pink", modifiers = ["italic"] }
"comment.block" = { fg = "hazmat_yellow" }
"comment.block.documentation" = { fg = "orange" }
```

etc but it had no effect: all remained the same (whatever had been set as `comment`)
