### ISSUE TITLE
ESLint: Does Not Resolve Relative Project Path for tsconfig

### ISSUE THREAD

**Issue by covelloz** [helix-editor/helix#13679]
### Summary

I know ESLint isn't _fully_ supported yet. However, many basic features of the LSP do work if you use v4.8: https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#eslint. Still, I wanted to get this "bug" on the radar as it is a bit annoying to deal with.

If you use a JSON file configuration for eslint and provide a relative path to a specific tsconfig.lint.json file (an extension/override for linting - this is a common pattern). The LSP fails to find the tsconfig.

An error diagnostic occurs at the very top of the file. I've blurred out the path for privacy reasons, but it is basically the absolute path to the current buffer - which is _not_ where helix should be looking for the tsconfig.lint.json file.
![Image](https://github.com/user-attachments/assets/b6b3be57-a018-4f13-ac06-c92998b863c6)

I've found two workarounds:
* A - provide the full, absolute path to the tsconfig.lint.json file in eslintrc.json 
* B - use .js file configuration with node's `$__dirname` as a prefix: `${__dirname}/tsconfig.lint.json`

Neither of which is ideal as it requires changes your project itself in order to use helix with eslint 🙅 

---

`languages.toml`
```toml
[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]
```

`eslintrc.json`
```json
{
...
    "overrides": [
    {
        ...,
        "parserOptions": {
            "project": ["./tsconfig.lint.json"], <-- relative path should properly resolve
            "createDefaultProgram": true
         },
        ...
    }, 
    ...]
}
``` 

_Note:_
My project is an Angular mono-repo & we use a JSON file configurations `eslintrc.json`.
Neovim, vscode, and IntelliJ ESLint servers all work out-of-the-box & can discover the tsconfig.lint.json file.

```
root_dir
├── project1
│   ├── eslintrc.json
│   ├── tsconfig.json
│   ├── tsconfig.lint.json
│   └── ...
├── project2
│   ├── eslintrc.json
│   ├── tsconfig.json
│   ├── tsconfig.lint.json
│   └── ...
├── shared
│   ├── eslintrc.json
│   ├── tsconfig.json
│   ├── tsconfig.lint.json
│   └── ...
└── ...
```

### Reproduction Steps

* Use JSON file configurations for eslintrc
* Define the project tsconfig path explicitly via an override: 
`overrides::parserOptions::project` and use a relative path `./tsconfig.lint.json`
* tsconfig.lint.json and eslintrc.json are in the same directory

**Expected:** ESLint LSP successfully finds & resolves the tsconfig
**Actual:** ESLint LSP fails to find the tsconfig & looks for it in the path of the current file in the buffer

### Helix log

No log output but rather an LSP error diagnostic at the top of the file
![Image](https://github.com/user-attachments/assets/b6b3be57-a018-4f13-ac06-c92998b863c6)

### Platform

macOS

### Terminal Emulator

iterm2

### Installation Method

brew

### Helix Version

helix 25.01.1

**Comment by NfNitLoop** [comment]
I'm having the same issue in v25.07.1.

But, I assume this bug is actually in the upstream eslint LSP, since it's the one parsing the config file.
https://www.npmjs.com/package/vscode-langservers-extracted
https://github.com/hrsh7th/vscode-langservers-extracted

Unfortunately, the [last commit in that repository is from 2024][1] and the owner has disabled the "Issues" tab on that repo, so I'm a bit wary of depending on it.

[1]: https://github.com/hrsh7th/vscode-langservers-extracted/commit/0a7a86dd080ec1adfb61732c17ba59492719c001

**Comment by NfNitLoop** [comment]
FWIW, I ended up using efm-langserver to get eslint working in Helix:
https://github.com/mattn/efm-langserver

I can configure it entirely in Helix's languages.toml (no need for efm-langserver's yaml configi file, you can pass all config in at LSP server startup).

My config looks like:

```toml
[[language]]
name = "typescript"
language-servers = [
   "efm-eslint",
   "typescript-language-server",
]

[language-server.efm-eslint]
# See: https://github.com/mattn/efm-langserver/blob/master/schema.md#languages_pattern1
# And: https://github.com/mattn/efm-langserver?tab=readme-ov-file#example-for-configyaml
command = "efm-langserver"

[language-server.efm-eslint.config]
# Sent to efm-langserver at startup to configure it. 🎉
# See: https://github.com/mattn/efm-langserver?tab=readme-ov-file#initializeparams
documentFormatting = true
documentRangeFormatting = true
hover = true
documentSymbol = true
codeAction = true
completion = true

[[language-server.efm-eslint.config.languages.typescript]]
lintCommand = "pnpm eslint --stdin --stdin-filename ${INPUT}"
lintStdin = true
lintIgnoreExitCode = true
lintAfterOpen = true
lintFormats = [
   # Very helpful examples. Need to parse multi-line messages where file only appears once:
   # See: https://vimhelp.org/quickfix.txt.html#errorformats
   # And: https://reviewdog.github.io/errorformat-playground/
   "%+P%f", # a file-like string on a single line.
   "%*[ ]%l:%c%*[ ]%t%*[^ ]%*[ ]%m",
   "%-O", # if not a match, pop filename from %P stack.

   # Example eslint output:
   # 
   # /full/path/to/your/source.file.ts
   #    16:1  error    There should be no empty line within import group  import/order
   #   472:1  warning  Missing return type on function                    @typescript-eslint/explicit-function-return-type
   #   479:3  warning  Missing return type on function                    @typescript-eslint/explicit-function-return-type
]

# (optional)
# You can configure formatters as well:
[[language-server.efm-eslint.config.languages.typescript]]
formatCommand = "pnpm prettier --stdin-filepath ${INPUT}"
formatStdin = true
```

Though you may want to build a version that includes [this fix][1] 😅 

[1]: https://github.com/mattn/efm-langserver/pull/291
