### ISSUE TITLE
Chord bindings for normal keys

### ISSUE THREAD

**Issue by piersy** [helix-editor/helix#13785]
In vim I use [Vim Arpeggio](https://github.com/kana/vim-arpeggio) to be able to map simultaneous keypresses of any keys. This is really useful for providing the possibility for many shortcuts at your fingertips. My main usecase is mapping `df` to `<esc>` which really makes the vim experience seamless, rather than having to reach for a key every time you want to switch modes.

It would be great if this was supported by helix.

**Comment by tsdevau** [comment]
@piersy, you can kind of do that now if you're wanting to `esc` back to **normal** mode from **insert** mode.  It's a sequence, not a _simultaneous_ key press, but it's close.  Add this to your `config.toml`:

```toml
[keys.insert]
d = { f = "normal_mode" }
```

or

```toml
[keys.insert.d]
f = "normal_mode"
```

If you also want it from **select** mode, you can add:

```toml
[keys.select]
d = { f = "normal_mode" }
```

or

```toml
[keys.select.d]
f = "normal_mode"
```

**Comment by piersy** [comment]
Hi @tsdevau, thanks! I actually already tried that but it doesn't really work.

The problem is you can't write something in insert that ends with d, maybe this is a bug or expected. But what happens for me is that I press d and the menu opens and then if I press d again two d's are inserted and typing f just inserts f after the two d's.

**Comment by tsdevau** [comment]
I wasn't aware of that quirk.  I use `jk` as my binding and have apparently not yet come across a situation where I needed to escape after the last character being `j`.

**Comment by piersy** [comment]
Hmmm, very few words end in 'j' it seems 🤔

**Comment by AlexanderBrevig** [comment]
You can just press `space` and carry on? (confirmed from `master`)

EDIT: and with this:
```toml
d = { f = "normal_mode" }
f = { d = "normal_mode" }
```
You can chord them and it always works :)
