### ISSUE TITLE
Haskell syntax highlighting?

### ISSUE THREAD

**Issue by 414owen** [helix-editor/helix#1384]
Adding this to `languages.toml` gets LSP working:

```toml
[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "haskell"
file-types = ["hs"]
roots = []
auto-format = false
comment-token = "--"
language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }
indent = { tab-width = 2, unit = "  " }
```

But there's no syntax highlighting. I'm not sure why, `tree-sitter-haskell` is a submodule of the repo, and there seem to be queries under `runtime/queries`.

I'm on `helix 0.5.0` from `nixpkgs`,but I've also tried `master`, although when I build `master` I don't even get rust syntax highlighting.

Any pointers?
