### ISSUE TITLE
Improve treesitter indentation

### ISSUE THREAD

**Issue by Triton171** [helix-editor/helix#1440]
I'm opening this to continue the discussion from https://github.com/helix-editor/helix/pull/1293. The current indentation configuration is somewhat limited and could be improved upon. For example, there is currently no way to write an `indents.toml` for C that handles:
```c
if (condition)
   do_smth();
```
and:
```c
if (condition)
{
   do_smth();
}
```
correctly without breaking the rest of the indentation.

To make writing indent queries easier and more intuitive (right now, `indent` and `outdent` work differently which might be confusing), we could [borrow some ideas from emacs](https://github.com/emacsmirror/tree-sitter-indent/blob/5f80e89b7da2074ea7f083b769448eb7026865dc/tree-sitter-indent.el#L83-L104) as @archseer suggested.
This still wouldn't be enough to fix the above issue, as that requires some sort of context-dependence. My suggestion is to also allow specifying a list of nodes in an indent query. The corresponding indentation will then only be applied if all of these nodes are directly nested in the given order. The `indents.toml` file might then look like this (for C):
```toml
[indent]
# This indents the whole node one level
all = []
# This indents everything except for the first and last child one level
body = [
   "compound_statement",
# ...
]
# This indents everything except for the first child one level
tail = [
   "init_declarator",
   "case_statement",
   # We need this to correctly indent if statements without braces (the first case in the above example)
   "if_statement",
# ...
]

[outdent]
all = [
   # This means that every compound statement (statements inside braces) inside an if statement is outdented one level.
   # Together with the indentation for the if_statement in indents.tail and the indentation for the compound statement in
   # indents.body, this yields the correct indentation
   ["if_statement", "compound_statement"]
]
body = [
# ...
]
```

If we want to go in that direction, the current indent queries could easily be adjusted for this and eventually be updated to take advantage of the new features.
