### ISSUE TITLE
Set command list's name and sticky bit in a config

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1487]
Helix allows you to group commands together to show a dialog list of commands — very helpful for keybind chaining
It also has two nice features about such dialogs: name and a sticky bit with the latter preventing the dialog from closing after a command is executed

I understand how to set the first part in my config, but then don't know how to change a name and add a sticky bit, they seem to be hardcoded in the `keymap.rs` only without the ability to add/change them from a config

```toml
  [keys.normal."a"]  # how to assign a custom name and make it sticky
   "b"	= "move_prev_word_end"
   "c"	= "move_prev_long_word_start"
```
