### ISSUE TITLE
Exit insert mode on key hold

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1494]
Given the high frequency of exiting various modes it makes sense to find the easiest keybind way possible to switch back
Helix has a helpful suggestion:

```toml
[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
```

However, the first requires a modifier and the second introduces a typing delay (`j` isn't shown after <kbd>j</kbd> is pressed until the next key is pressed)
(likewise, binding <kbd>Esc</kbd> to <kbd>Caps</kbd> is a pinky move, so not that great either)

I think an even better alternative would be to get rid of a useless letter repetition (if only for a single letter) to have an __"on hold"__ `normal_mode` command so that you could hold an extremely convenient home row key, e.g., <kbd>a</kbd> for 0.5 seconds and that would switch back to normal mode (and, importantly, not execute any normal mode commands bound to <kbd>a</kbd> until it's released) instead of typing `aaa`

(you might also need to delay the first `a` character before exiting after an "on hold" event to avoid typing delays and also avoid extraneous `a`)
