### ISSUE TITLE
Way to remap groups in the TOML file. And the ablility to give names to the groups

### ISSUE THREAD

**Issue by IsotoxalDev** [helix-editor/helix#1508]
Is there a way to remap groups in the config TOML file?.
![image](https://user-images.githubusercontent.com/62714538/149516890-de9dfef7-6b2c-4cef-b503-e059060cdba8.png)

**Comment by NNBnh** [comment]
Try:

```toml
[keys.normal."g"]
  "g" = "goto_file_start"
  "e" = "goto_last_line"
```
