### ISSUE TITLE
Allow composition of configs to avoid duplication

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1513]
Currently if you change a lot of normal mode keybinds (e.g., change the GoTo mode as `[keys.normal."g"]`), you'd have to copy these changes several times to other modes so they keep working there (e.g., as `[keys.select."g"]` since), which is rather cumbersome, especially when you tweak the configs.
The source code uses a nifty `let mut select = normal.clone();` trick that allows only editing the keybinds that are different

Would you please allow a similar ease of composition for the user configs?

**Comment by dead10ck** [comment]
Duplicate of #1498

**Comment by eugenesvk** [comment]
Not sure these is a duplicate. Let's assume I want to do the following:

- I create a custom "minor mode" called __key__ with a list of 10 commands
- I want other minor modes (window mode, space mode, goto mode) to all have this __key__ mode on <kbd>k</kbd>
- I don't want Normal mode to have <kbd>key</kbd> have this mode, it's taken by something more useful

You suggestion in the other issue (which fits this one better) would be to allow me to set `'k'.isn` to work in Major modes like Insert/Select/Normal (if I wanted to)
However, how would it allow making __key__ work as an additional key in the minor modes? 
The 'reusing a list of commands for dialogs' issue meant I could insert in each minor mode (default or custom) the following line (or something)
```toml
[keys.normal.'space']
'k' = 'my_Custom_Command_That_Is_Actually_A_Minor_Mode_Of_10_Commands_With_A_Name'
[keys.normal.'c-w']
'k' = 'my_Custom_Command_That_Is_Actually_A_Minor_Mode_Of_10_Commands_With_A_Name'
[keys.select.'space']
'k' = 'my_Custom_Command_That_Is_Actually_A_Minor_Mode_Of_10_Commands_With_A_Name'
[keys.select.'c-w']
'k' = 'my_Custom_Command_That_Is_Actually_A_Minor_Mode_Of_10_Commands_With_A_Name'
[keys.select.'x']              	# my custom minor mode
'a' = 'delete_char_forward'    	# builtin commands
'b' = 'delete_selection'       	# builtin commands
'c' = 'delete_selection_noyank'	# builtin commands
'k' = 'my_Custom_Command_That_Is_Actually_A_Minor_Mode_Of_10_Commands_With_A_Name'
```

and then if I replace those 10 commands in this minor __key__ mode with something else, I wouldn't even have to change anything here

**Comment by dead10ck** [comment]
Oh, so you mean like being able to define an alias for a list of commands. In the proposed format in the other issue, this would still be moderately better:

```toml
[keys]
"<Space>.ns" = { k = { ... } }
C-w.ns = { k = { ... } }
x.ns = { k = { ... } }
```

but yeah I see what you mean, it would help to be able to use an alias. Could be something like:

```toml
[alias]
my-alias = [ "a", "b", ... ]

[keys]
"<Space>.ns" = { k = "my-alias" }
C-w.ns = { k = "my-alias" }
x.ns = { k = "my-alias" }
```

**Comment by eugenesvk** [comment]
> would help to be able to use an alias

Yep, that would be great to have and is what I meant in the other issue: I set a list once and then refer to it via an alias

The solution to this issue would then allow you to set regular keys in various modes with a dot-mode `.nsi` notation (or something)

**Comment by eugenesvk** [comment]
By the way, aliases might help solve this issue https://github.com/helix-editor/helix/issues/1499 as well — I can map a command to call an alias it's defined in to make the dialog "sticky", but only for come commands

```toml
[my-space-mode-alias]
 "a" = "a_cmd"                	# dialog closes once this command is run
 "b" = "b_cmd"                	# same
 "c" = ["c_cmd",              	# dialog remains open after this one,
        "my-space-mode-alias"]	#    making this key "Sticky"

[keys]
'space'.ns = 'my-space-mode-alias'
```
