### ISSUE TITLE
Book shows features before they're released

### ISSUE THREAD

**Issue by Aloso** [helix-editor/helix#1607]
Go to <https://docs.helix-editor.com/configuration.html>. It includes the following example config:

  ```toml
  theme = "onedark"
  
  [editor]
  line-number = "relative"
  mouse = false
  
  [editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"
  
  [editor.file-picker]
  hidden = false
  ```

However, if you copy+paste this into `~/.config/helix/config.toml`, helix shows this error on startup:

```markdown
Bad config: unknown field `cursor-shape`, expected one of `scrolloff`, `scroll-lines`, `mouse`, `shell`, `line-number`, `middle-click-paste`, `smart-case`, `auto-pairs`, `auto-completion`, `idle-timeout`, `completion-trigger-len`, `auto-info`, `file-picker`, `true-color` for key `editor` at line 7 column 1
Press <ENTER> to continue with default config
```

The reason is that the `cursor-shape` config option [was introduced](https://github.com/helix-editor/helix/pull/1154) _after_ the latest version, helix v0.6.0. The book published at <https://docs.helix-editor.com> should reflect the state of the current version, not of the master branch.
