### ISSUE TITLE
[question] Using Rust Clippy and fmt with Helix?

### ISSUE THREAD

**Issue by MarkuBu** [helix-editor/helix#1756]
Is it possible to automatically run fmt and Clippy in Rust projects, e.g. if I save a file? Or do I need to run it manually from a terminal?

If not, is it planned to integrate support for it?

**Comment by sudormrfbin** [comment]
Formatting is already done on save by rust-analyzer, and clippy can be enabled by putting the following in your [`languages.toml` file](https://docs.helix-editor.com/languages.html):

```toml
[[language]]
name = "rust"

[language.config.checkOnSave]
command = "clippy"
```

(LSP configuration should really be documented in the book, along with a typical example like this.)
