### ISSUE TITLE
Add "highlight current line"

### ISSUE THREAD

**Issue by MarkuBu** [helix-editor/helix#1761]
A standard feature of most editors is highlighting the current line. 

This is something I miss in Helix.

**Comment by trcm** [comment]
I'd like to work on this

**Comment by thienpow** [comment]
yes having a current line highlighted is absolutely nice, adding to that the cursor should show | instead of a big block when inserting text. big block cursor should only be shown when not in insert mode

look at this video to "feel" how nice is it with | cursor and full current line highligted
https://www.youtube.com/watch?v=FW2X1CXrU1w

**Comment by workingJ** [comment]
> 

There is a setting for that:

```toml
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
````
