### ISSUE TITLE
"Bad config: unknown field `cursor-shape`" when using doc configuration

### ISSUE THREAD

**Issue by tnahs** [helix-editor/helix#1857]
### Summary

Using the documentation's configuration:

```toml
theme = "onedark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
```

Full error:
```
Bad config: unknown field `cursor-shape`, expected one of `scrolloff`, `scroll-lines`, `mouse`, `shell`, `line-number`, `middle-click-paste`, `smart-case`, `auto-pairs`, `auto-completion`, `idle-timeout`, `completion-trigger-len`, `auto-info`, `file-picker`, `true-color` for key `editor` at line 12 column 1
Press <ENTER> to continue with default config
```

### Reproduction Steps

1. Create new config file at `~/.config/helix/config.toml`
2. Copy/paste config from documentation found here: <https://docs.helix-editor.com/configuration.html>
3. Run `hx`

### Helix log

No log output.

### Platform

macOS

### Terminal Emulator

Kitty 0.24.4 (0.24.4)

### Helix Version

Typing `hx -V` outputs no version number just: `helix `.
