### ISSUE TITLE
Make insert mode have a thin cursor

### ISSUE THREAD

**Issue by mscofield0** [helix-editor/helix#1934]
It's currently hard to see when you're in insert mode just by looking at your cursor and also it's unclear where the insertion will be.
I would rather it be like in Neovim, a thin cursor inbetween the characters where the insertion will be.

**Comment by sudormrfbin** [comment]
This is already configurable via the [config.toml file](https://docs.helix-editor.com/configuration.html):

```toml
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
```
