### ISSUE TITLE
Vue lsp support

### ISSUE THREAD

**Issue by EpsilonKu** [helix-editor/helix#2010]
What about support of [Volar](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-language-server) or [Vetur](https://github.com/vuejs/vetur/tree/master/server)?

**Comment by the-mikedavis** [comment]
Have you tried them out? You can test them out by modifying your `languages.toml`

```toml
# on unix: ~/.config/helix/languages.toml
[[language]]
name = "vue"
language-server = { command = "vue-language-server" } # or whatever the command is
```

(it gets merged in with the default `languages.toml` from this repo.)

If either work well, you can open up a PR to add that change to the default `languages.toml` [here](https://github.com/helix-editor/helix/blob/d37369c1e056e41d405bc95b13efd550c57fa933/languages.toml#L569-L575).
