### ISSUE TITLE
Re-mapping digit keys doesnt work

### ISSUE THREAD

**Issue by donpdonp** [helix-editor/helix#2036]
### Summary

I'm trying to remap 0/$ to work like vim. The $ mapping works but the 0 does not. 

```toml
[keys.normal]
'0' = "goto_line_start"
'$' = "goto_line_end"
```

### Platform

linux

### Terminal Emulator

gnome-terminal

### Helix Version

helix 22.05-dev (b03421a8)
