### ISSUE TITLE
Error when remapping some commands.

### ISSUE THREAD

**Issue by Mosaab-Emam** [helix-editor/helix#2072]
### Summary

When editing config.toml, some remaps for normal mode work as expected.

```toml
# This works
[keys.normal]
C-m="normal_mode"
```

However, trying to remap other commands raises an error.

```toml
# This does not work
[keys.normal]
C-m="percent"
```

The Error:
`Bad config: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 1 column 1`

### Reproduction Steps

1. Build helix from source.
2. Edit config.toml.
3. Map any key to "percent".
4. Reload config or restart hx.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

</details>

### Platform

Linux

### Terminal Emulator

xterm-256color and st

### Helix Version

22.03 and 22.05-dev
