### ISSUE TITLE
Improve LSP diagnostics visually with distinct colors in edit area

### ISSUE THREAD

**Issue by workingJ** [helix-editor/helix#2157]
#### Describe your feature request

Right now to my knowledge its only possible to set one color for the affected line(s) in the edit area via the theme

```toml
diagnostic = {fg = 'color1' , bg = 'color2' }
```

it would be nice to have some thing like this:

```toml
diagnostic.hint = {fg = 'color1' , bg = 'color2' }
diagnostic.warning = {fg = 'color1' , bg = 'color2' }
diagnostic.error = {fg = 'color1' , bg = 'color2' }
```

so the users can easier distinguish whats happening in the code
