### ISSUE TITLE
Language server not active for current buffer

### ISSUE THREAD

**Issue by archwebio** [helix-editor/helix#2164]
Hello,

I have a Mac with Apple M1 chip.

I just installed the app running:

```sh
brew tap helix-editor/helix
brew install helix

hx --grammar fetch
hx --grammar build
```

I added a configuration to change the theme under `~/.config/helix/config.toml` and it works fine.

I created a JS file containing a function:

```js
// erase.js
const hello = () => {
  console.log("Hello")
}

hello()
```

When trying to go to definition by `g` + `d` I get a notification:

![image](https://user-images.githubusercontent.com/94804349/163867126-5ae6d082-c2d7-4210-9758-e96849cbf03d.png)

I read through the docs but did not read any specifics on how to connect to the LSP.

Any help is much appreciated.

Thanks,

**Comment by the-mikedavis** [comment]
You'll need to install the default language server for JavaScript: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#tsserver

**Comment by archwebio** [comment]
Indeed. Yes, thanks. That worked for me

**Comment by workingJ** [comment]
Better guiding for language server usage in helix seems to be e thing...

**Comment by archwebio** [comment]
I started with the docs on https://helix-editor.com.

I just saw the link in the repo pointing to the installation.

Sorry,

**Comment by Max0nyshchenko** [comment]
@workingJ  Can you provide some example with helix LSP, I've installed helix lsp by ghcup, added language to languages.toml but cannot get it to work anyway, still have "Language server not active for current buffer" issue.

**Comment by workingJ** [comment]
well currently i have only the configuration for rust, hope this helps:

```toml
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "	" }

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

```
