### ISSUE TITLE
Remapped movement keybindings don't extend selections

### ISSUE THREAD

**Issue by Paveloom** [helix-editor/helix#2200]
### Summary

Mapped `move_next_word_start` and `move_prev_word_start` commands don't extend selections in the select mode.

### Reproduction Steps

Consider the following config:

```toml
# ~/.config/helix/config.toml
# <...>
[keys.normal]
C-S-left = ["select_mode", "move_prev_word_start"]
C-S-right = ["select_mode", "move_next_word_end"]

[keys.select]
C-S-left = "move_prev_word_start"
C-S-right = "move_next_word_end"
# <...>
```

This is an attempt to recreate the text selection behavior that is common in other programs.

To reproduce: try to use these keybindings.

*I expected this to happen:*
I can select text by holding <kbd>Ctrl + Shift</kbd> and pressing arrow keys. That is, like using <kbd>b</kbd>/<kbd>e</kbd> in Select mode.

*Instead, this happened:*
Selections change like in Normal mode.

### Helix log

Reproducing this issue doesn't emit relevant log messages.

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD

### Helix Version

helix 22.05-dev (35d2693)
