### ISSUE TITLE
Block Cursor Disappear in base16_terminal

### ISSUE THREAD

**Issue by i3elj** [helix-editor/helix#2242]
### Summary

* **OS:** Arch Linux
* **Tested terminals:** Alacritty, xterm, urxvt, xfce4-terminal
* **Helix:** build from source
* **Version:** 22.03
* **What's happening?** when you set the base16_terminal theme, the block cursor disappear. The "underline" and "bar" cursors are normal and doesn't show any weird behaviour.

### Onedark theme with cursor at the beginning of line 6
![image](https://user-images.githubusercontent.com/61887184/164912339-587fb57b-b04a-4cd2-b4a0-d1f8111e4b31.png)

### Base16_terminal theme with cursor at the beginning of line 6
![image](https://user-images.githubusercontent.com/61887184/164912476-bc896f36-cc0f-41d3-aa3d-1c6c91d4dd6e.png)
* **With other cursors:**
    * Bar
![image](https://user-images.githubusercontent.com/61887184/164912538-aa8b3eeb-ef26-4b31-bff4-56ba15b90f8f.png)
    * Underline
![image](https://user-images.githubusercontent.com/61887184/164912611-71feeada-4bf0-452d-80d0-e328757325fa.png)

### My `config.toml`:
```toml
theme = "base16_terminal"

[editor]
line-number = "relative"
mouse = false
true-color = true
scrolloff = 5

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.lsp]
display-messages = true
```

### Platform

Linux

### Terminal Emulator

Alacritty, Xterm, Urxvt, Xfce4-terminal

### Helix Version

22.03
