### ISSUE TITLE
Remapping default sequence keybindings doesn't overwrite them

### ISSUE THREAD

**Issue by Paveloom** [helix-editor/helix#2282]
### Summary

All default sequence keybindings are unchangeable.

### Reproduction Steps

Consider the following config:

```toml
# ~/.config/helix/config.toml
# <...>
[keys.normal]
a = "move_char_left" # Default is "append_mode"
g = { a = "code_action" } # Default is "goto_last_accessed_file"
# <...>
```

This example is taken from the [documentation](https://docs.helix-editor.com/master/remapping.html).

*I expected this to happen:*
Both keybindings should overwrite the existing ones.

*Instead, this happened:*
Only the first one, which is a one-key keybinding, does.

### Helix log

Reproducing this issue doesn't emit relevant log messages.

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD

### Helix Version

helix 22.05-dev (b65fb0f6)

**Comment by the-mikedavis** [comment]
I think this may be a problem with the `code_action` binding rather than that it's within the `g` menu.

```toml
[keys.normal]
a = "move_char_left"
g = { a = "move_char_right" }
```

Works fine for me.

**Comment by the-mikedavis** [comment]
I just gave

```toml
[keys.normal]
a = "move_char_left"
g = { a = "code_action" }
```

a try and I see `ga` triggering code actions when available and giving the statusline "Language server not active for current buffer" when the LSP is off.

What behavior do you see when using `ga` with those bindings?

**Comment by the-mikedavis** [comment]
Oh actually I think that's caused by the way TOML works. You can try

```toml
[keys.normal]
g = { a = "..", b = ".." }
```

or

```toml
[keys.normal.g]
a = ".."
b = ".."
```
