### ISSUE TITLE
(Question) Setting up custom commands?

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#2297]
I want to setup custom commands to do Flutter development with `helix`. I'm guessing this will have to wait for https://github.com/helix-editor/helix/issues/998 or https://github.com/helix-editor/helix/issues/122, but I will describe the use case here for tracking.

- Adding `flutter` command line tool commands to command pallet, keybindings etc.
- Run `flutter devices`, store a list of devices in editor state, then dispatch run commands on these devices
- After running `flutter run`, it allows pressing keys to dispatch subsequent commands to the device, would be nice to hook these into command pallet entries, or hooks like saving a file triggering `hot reload`

For reference: here's a `CoC` plugin that achieves most of these items in vim https://github.com/iamcco/coc-flutter

**Comment by thomkeh** [comment]
The first item on the list should be possible to do already, but the other two seem to require scripting capabilities.

**Comment by n0s4** [comment]
If by context menus you mean the bottom-right popups which show available follow up keybindings, you can already make these. E.g, to add an item to the space menu:
```toml
[keys.normal]
space = { foo = "bar" }
```
You can also construct your own menus, I have this for example:
```toml
```

**Comment by d12bb** [comment]
Support for adding custom commands for command mode (I think that's what op wants) is possible even before having a plugin system for having shortcuts one doesn't want to add as keybinds. Later these could be enhanced for calling API or plugin functions. I have something like this in mind:

```toml
# config.toml
[commands]
"ToggleMyGreatPlugin" = "myPlugin.toggle()"

# maybe better in languages.toml
[commands.rust]
"Test" = ":sh cargo test"
"Lint" = ":sh cargo clippy"
[commands.go]
"Test" = ":sh go test"
```
