### ISSUE TITLE
Add Odin language support

### ISSUE THREAD

**Issue by DaveTheGameDev** [helix-editor/helix#2340]
Odin is a very nice language and it would be nice if it got out of the box support.

https://odin-lang.org/

![image](https://user-images.githubusercontent.com/21057342/166097581-324ab7bf-11cc-48b7-8e1c-edc91c19cb18.png)

**Comment by colaxdev** [comment]
https://github.com/MineBill/tree-sitter-odin

**Comment by DaveTheGameDev** [comment]
@colaxdev  Is there anything else I need? I did the fetching for the grammar stuff, but no luck on highlighting.

**Comment by colaxdev** [comment]
@DaveTheGameDev Did you build the grammar ? Show your `languages.toml` file please

**Comment by DaveTheGameDev** [comment]
@colaxdev Yeah I built it.
![image](https://user-images.githubusercontent.com/21057342/166099616-bf3744ee-13c4-40e4-9b94-fc0c966680c1.png)


```toml
[[language]]
name = "odin"
auto-format = false
scope = "source.odin"
file-types = ["odin"]
roots = []
comment-token = "//"
indent = { tab-width = 4, unit = "  " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[[grammar]]
name = "odin"
source = { git = "https://github.com/MineBill/tree-sitter-odin", rev = "da885f4a387f169b9b69fe0968259ee257a8f69a" }


```
