### ISSUE TITLE
Change default formatter for any language

### ISSUE THREAD

**Issue by frexsdev** [helix-editor/helix#2362]
# Idea

Adding an option like this:

```toml
[[lang]]
name="yeah"
formatter="youhou" // command to execute when formatting instead of the lsp' default 
```

# Why ?

Because, for example, whe **CAN'T** format any Zig code with **ZLS** (just an example 😡)
