### ISSUE TITLE
tree-sitter ssh client config

### ISSUE THREAD

**Issue by midnightexigent** [helix-editor/helix#2443]
I am looking into adding the [tree-sitter-ssh-client-config](https://github.com/metio/tree-sitter-ssh-client-config) but am having trouble, specifically making helix detect the file (it's the `.ssh/config` file), I have no idea what to put in `file-types` and `root`

```toml
[[language]]
name = "ssh-client-config"
scope = "source.ssh-client-config"
file-types = [] # I tried .ssh/config with no success
roots = []
[[grammar]]
name = "ssh-client-config"
source = { git = "https://github.com/metio/tree-sitter-ssh-client-config.git", rev = "769d7a01a2e5493b4bb5a51096c6bf4be130b024" }
```
