### ISSUE TITLE
Entering `Insert` mode after motion places cursor/beam in position before motion.

### ISSUE THREAD

**Issue by iktefish** [helix-editor/helix#2463]
### Summary

Trying to enter `Insert` mode after motion such as `e`/`E`/`w`/`W` puts the cursor/beam at the starting position of selection.

### Reproduction Steps

I tried this:

1. `e` or `E` or `w` or `W` in `Normal` mode
2. then `i` to get into `Insert` mode

I expected this to happen:
I should be placed in `Insert` mode with cursor/beam at the new position (after motion due to `e` used in `Normal` mode).

Instead, this happened:
Entered `Insert` mode with cursor/beam at last place before motion.

### Platform

Linux (Pop_OS! Helix installed via Nix)

### Terminal Emulator

kitty 0.21.2

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by the-mikedavis** [comment]
The cursor goes to the left-hand side of the selection when inserting with <kbd>i</kbd> and this is intended behavior. You can insert on the right-hand side by appending with <kbd>a</kbd>.

**Comment by iktefish** [comment]
Oh I see, on that note I just tried `b` and `a` and the same behavior is shown. Thanks for the speedy response, I'm slowly trying to get used to this coming from Vim.

**Comment by iktefish** [comment]
Aye, just a few days with it and I can say this is a welcome change. At this point I think it'd be better if `g-h` and `g-l` also selected the text it jumps across. To test it out, I overridden the keybindings in `config.toml`:
```toml
[keys.normal.g]
h = [ "collapse_selection" ,"select_mode", "goto_line_start", "normal_mode" ]
l = [ "collapse_selection" ,"select_mode", "goto_line_end", "normal_mode" ]
```
This way it not only is consistent but also allows be to jump backward using `i` or `a`.
