### ISSUE TITLE
imitate kakoune selection pattern in extend mode

### ISSUE THREAD

**Issue by nrdxp** [helix-editor/helix#2499]
#### Describe your feature request
One thing I really liked about kakoune was that I was able to dynamically select matches on searches. So if I search for `foo` and it appears in the file _n_ times, but I only want to work on _n-1_ matches, then I can simply skip that search from being selected by not holding <kbd>Shift</kbd> on that particular match when pressing <kbd>n</kbd> or <kbd>Alt+n</kbd>. So far I haven't been able to mimic this behavior nicely in helix in extend mode, which makes this workflow, which I find myself using quite frequently, much more difficult.

Here's a quick asciinema of what I'm talking about, in case my explanation is confusing:
<a href="https://asciinema.org/a/cZDhPLwolgXdwdxTDixYmjqiS" target="_blank"><img src="https://asciinema.org/a/cZDhPLwolgXdwdxTDixYmjqiS.svg" /></a>

**Comment by the-mikedavis** [comment]
To do this in helix you can go into select mode with <kbd>v</kbd> and then use <kbd>n</kbd> to extend the selection to include the next match and <kbd>N</kbd> to include the previous.

**Comment by nrdxp** [comment]
right but what I want is to skip something that would otherwise be selected

**Comment by the-mikedavis** [comment]
Ah I think I see what you're saying. I think you can emulate this by switching back into normal mode by hitting <kbd>v</kbd> again and then suing <kbd>n</kbd> - it looks like that has the same behavior as <kbd>Shift</kbd><kbd>n</kbd> vs. <kbd>n</kbd> in kakoune.

**Comment by nrdxp** [comment]
Well at least there is a way to do it, but it is a lot more keypresses. Perhaps add the same functionality using the <kbd>Alt</kbd> would be more convient?

**Comment by the-mikedavis** [comment]
It should be easy to add this to select mode in your `config.toml`:

```toml
[keys.select]
"A-n" = "search_next"
```

The default bindings are roughly:

```toml
[keys.normal]
n = "search_next"
N = "search_prev"

[keys.select]
n = "extend_search_next"
N = "extend_search_prev"
```

**Comment by nrdxp** [comment]
Nice so I guess my dersired functionality is ultimately just a config change. I actually would prefer this if possible:
```toml
[keys.normal]
n = "extend_search_next"
N = "extend_search_prev"
"A-n" = "search_next"
"A-N" = "search_prev"
```

To essentially mimic the default kakoune behavior, which works beautifully! Thanks, I'll close this now.
