### ISSUE TITLE
Regression: Trying to auto-complete a large amount of modules results in error

### ISSUE THREAD

**Issue by VarLad** [helix-editor/helix#2505]
To be specific, the error is, `Async job failed: request timed out` and the LSP stops working before restarting Helix.
The master of Helix as of https://github.com/helix-editor/helix/commit/8493b5fca68097efd258ff0ffbcb6863e0c362c9 was built on Fedora 36 using the same instructions as on the README.md

This doesn't occur in the last stable release (tried using the binaries provided on Github)
The autocomplete also feels somewhat slower but I'd rather not comment on that.
To try, build the latest master and try playing around by typing `Base.` in a `.jl` file and playing around with it for a while. Remove the dot, type some stuff after the dot, etc.  (Note that you need to have Julia installed and the LanguageServer package installed in Julia)

**Comment by the-mikedavis** [comment]
Since https://github.com/helix-editor/helix/pull/2405, you can configure a longer request timeout for a language server:

```toml
[[language]]
name = "julia"
language-server.timeout = 30 # in seconds, 20 is the default
```

This is unlikely to be a regression within helix though: that timeout is caused by the language server being slow rather than helix. You can follow the log file and start helix in verbose mode (`hx -vv`, up to three `v`s) to see the requests and responses to/from the language server to verify.

**Comment by VarLad** [comment]
Can't replicate anymore. Sorry for the inconvenience

**Comment by tahir-hassan** [comment]
Just in case anyone is trying to get `typescript-language-server` working, I had to put the following in a `languages.toml` file, because the language server is quite slow to start up:

```toml
[[language]]
name="typescript"
[language-server]
command = "typescript-language-server.cmd"
args = ["--stdio"]
timeout = 40
```
