### ISSUE TITLE
Feature request: Open file picker at typed directory

### ISSUE THREAD

**Issue by langbamit** [helix-editor/helix#2558]
Sometimes I need a quick search outside of the current project.
A command like this is super helpful:
```
:file-picker ../other-project
```
And if it happens too often, I will:
```toml
[keys.normal]
"space" = { z = ":file-picker ~/projects/rust/library/std" }
```
