### ISSUE TITLE
Macro is ignoring key remapping

### ISSUE THREAD

**Issue by nitish-17** [helix-editor/helix#2652]
**context:**

- I remapped `o` to `<A-semicolon>`
```toml
[keys.normal]
      "ret" = ["open_below", "normal_mode"] 
          t = "command_mode"
          w = ":write"
        "'" = "repeat_last_motion"
          o = ["flip_selections", "select_mode"]

[keys.select]
          o = "flip_selections"
        "'" = "repeat_last_motion"
```
- I was trying to accomplish alignment around `=` sign ,as shown above, using a macro

**what I did :** 

- I recorded a macro as \<percent>s\<space>=\<ret>\<S-B>`o`&
- executed it

**what I expected:** 

- macro to do  \<percent>s\<space>=\<ret>\<S-B>`<A-semicolon>`&

**what actually happened:** 

- it did exactly \<percent>s\<space>=\<ret>\<S-B>`o`& 
- i.e, inserted new-line instead of flip\_selection 
- i.e, _**ignored my key remapping**_. (`o = "flip_selections"`)
