### ISSUE TITLE
Syntax Highliting Dissapears when theme foreground is transparent

### ISSUE THREAD

**Issue by aydaultani** [helix-editor/helix#2665]
### Summary

Syntax Highliting Dissapears when theme foreground is transparent

### Reproduction Steps

 

I tried this:

1. `hx`
2. make the theme this
```toml
key = { fg = "#ffffff", bg = "#000000", modifiers = ["bold", "italic"]}
"ui.selection" = "black"
"ui.text" = {fg = "#D6D5CB", modifiers = ["bold"]}
```
3. make a python file
4. type some python into it
5. you should see the higlight
6. turn the theme on
7. it should be gone

I expected this to happen:

to see stuff

Instead, this happened:

i did not see said stuff

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

iTerm

### Helix Version

latest
