### ISSUE TITLE
How to use a linter (e.g. pylint) in Helix?

### ISSUE THREAD

**Issue by MarkuBu** [helix-editor/helix#2743]
I follow the exercism track for Python and I noticed a hint from pylint on the exercism page. That wasn't shown in Helix. But Python LSP is running and shows errors, even formatting errors.

Is it possible to use a linter in Helix, manually or automatically?

**Comment by seshotake** [comment]
If you're using `pylsp`, you just need to install pylint `pip install "python-lsp-server[pylint]" and then edit your `languages.toml` something like this:

```toml
[[language]]
name = "python"
config = { pylsp.plugins.pylint.enabled = true } 
```

You can check [python-lsp-server/CONFIGURATION.md](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md) for more detail about configuration
