### ISSUE TITLE
:w selects the whole file, thus losing caret placement.

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#2752]
### Summary

https://user-images.githubusercontent.com/62802897/173198242-64d36aa5-4fb3-4b66-b15d-7ef8999015f3.mp4

as seen in the video above, when keying in `:w`, the entire file gets selected, and my caret always returns to the start when i exit it.

settings:
```toml
theme='onedark'
[keys.normal]
't'='move_line_down'
'n'='move_line_up'
's'='move_char_right'
'j'='find_till_char'
'k'='search_next'
'l'='select_regex'
[keys.insert]
','={'.'='normal_mode'}
[editor]
scrolloff=255
mouse=false
auto-completion=true
idle-timeout=0
completion-trigger-len=2
rulers=[80,100,120]
[editor.cursor-shape]
insert='bar'
[editor.whitespace]
render='all'
[editor.lsp]
display-messages=true
```

thank you!

### Reproduction Steps

 

I tried this:

1. `:w`

I expected this to happen:
no selections made.
Instead, this happened:
above video.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
none
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal Preview 1.14.1451.0

### Helix Version

helix 22.05 (27609f50)
