### ISSUE TITLE
Don't switch to insert mode for "o" and "O" 

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#2817]
Since `hx` has it's own style of bindings then I think implementing:
```toml
    o = ["add_newline_below", "move_line_down"]
    O = ["add_newline_above", "move_line_up"]
```
by default would be a nice idea. These bindings are better than vim's "o" and "O".
