### ISSUE TITLE
Markdown Preview

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#2824]
Markdown preview similar to this plugin:
https://github.com/davidgranstrom/nvim-markdown-preview

**Comment by zim0369** [comment]
> An in-terminal preview using the builtin markdown view would be a nice option, too.

I don't think so. I've used similar with neovim and it's terrible. It has all wrong colors and no way to view images.

**Comment by felix-u** [comment]
Subjectively, this sounds more like a plugin than a core feature.

**Comment by zim0369** [comment]
@felix-u Ya, a plugin  would suit better.

**Comment by Jedsek** [comment]
This should be a plugin

**Comment by aikomastboom** [comment]
I found this: https://pypi.org/project/markdown-server/

might be helpful

**Comment by MDeiml** [comment]
Markdown preview could actually (efficiently) be handled by a language server. There is already https://github.com/euclio/mdpls which does exactly that.

**Comment by MDeiml** [comment]
Actuall installing that and adding
```toml
[[language]]
name = "markdown"
language-server = { command = "/path/to/mdpls" }
config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }
```
to your `language.toml` already gives you a markdown preview. The repo I linked seems to be missing a few core features though, e.g. images don't work and I would love some auto-scrolling.

**Comment by TheCaptainCraken** [comment]
@MDeiml I tried that but it looks like it does not support the $\neq$ :(

**Comment by MDeiml** [comment]
Not sure if latex is supported for that repo, seems like it uses https://github.com/euclio/aurelius under the hood which might support latex? I'm not sure.

You could open an issue in that repo and ask the author.

**Comment by TheCaptainCraken** [comment]
Yep I looked into that and it should support latex. I checked and it supports all other symbols like $\sqrt$ $\gt$ etc.
It actually prints the $\ne$ butit renders it like \  = wich is odd. I'll open an isse there.

**Comment by 0xlilith** [comment]
> 

how do I open the preview ?

**Comment by 0xlilith** [comment]
> Actually installing that and adding
> 
> ```toml
> [[language]]
> name = "markdown"
> language-server = { command = "/path/to/mdpls" }
> config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }
> ```
> 
> to your `language.toml` already gives you a markdown preview. The repo I linked seems to be missing a few core features though, e.g. images don't work and I would love some auto-scrolling.

how do I open the preview?

**Comment by MDeiml** [comment]
The preview should also open automatically if you open a markdown file. It works for me at least.

**Comment by sgon00** [comment]
Hopefully, helix will have better markdown preview or highlight support in the future. So far, I am using vscode for markdown editing.

**Comment by rawToast21** [comment]
> Actually installing that and adding
> 
> ```toml
> [[language]]
> name = "markdown"
> language-server = { command = "/path/to/mdpls" }
> config = { markdown.preview.auto = true, markdown.preview.browser = "firefox" }
> ```
> 
> to your `language.toml` already gives you a markdown preview. The repo I linked seems to be missing a few core features though, e.g. images don't work and I would love some auto-scrolling.

Is there a way to control the presentation theme in the Firefox preview? e.g. not white text on black background. Don't think I want to manage the css directly in the markdown files as that would impact it's presentation everywhere

**Comment by MDeiml** [comment]
Doesn't seem like it, but it doesn't seem to hard to implement yourself. Maybe create an issue or pull request in https://github.com/euclio/mdpls? Or you could just fork that repo and edit the template to your liking.

**Comment by David-Else** [comment]
I am using `gh extension install yusukebe/gh-markdown-preview`, it is great and has live reload, but no mirroring the line position in Helix and the browser. Can anything do that in Helix? Does [mdpls](https://github.com/euclio/mdpls) do anything extra?

**Comment by rasmus-kirk** [comment]
I use nix to do this for pandoc-flavoured markdown to pdf:

https://gist.github.com/rasmus-kirk/c56267f2256a5b1326eefdcb2da33d92

Place the following file as `flake.nix` in the directory containing the `md` file and run `nix develop -c pandoc-compile-continuous`. For html, simply edit the `pandoc-script` in the flake accordingly. Works on mac and linux.

**Comment by arcstur** [comment]
I think that choosing a good theme makes a lot of difference. I saw that only a few themes have different colors for heading levels. Kanagawa, sonokai and papercolor have, for example. Only a few themes use colors for italic and bold, monokai being one of them. I think that using that, markdown already looks a lot better.

The only theme I found that had different colors _both_ for h1/h2 and for bold/italic is onelight. I wonder if we can modify other themes to also differentiate colors on bold/italic/h1/h2. Doing that I think will make the markdown experience much better.

Markdown is made such that seeing it as code already makes it good, so I don't think we need different sizes for headings for example.

The only thing I would miss is having image previews. If someone that understands the codebase could guide me into where to start developing this, I would like it very much. I know it would be a plugin and we still need a plugin system haha.

**Comment by arcstur** [comment]
Looking at the code in /runtime/themes/ we can see that some themes define what I mentioned.

Kanagawa using colors for heading levels:

```toml kanagawa
"markup.heading.marker" = "springViolet2"
"markup.heading.1" = { fg = "surimiOrange", modifiers = ["bold"] }
"markup.heading.2" = { fg = "carpYellow", modifiers = ["bold"] }
"markup.heading.3" = { fg = "waveAqua2", modifiers = ["bold"] }
"markup.heading.4" = { fg = "lightBlue", modifiers = ["bold"] }
"markup.heading.5" = { fg = "oniViolet", modifiers = ["bold"] }
"markup.heading.6" = { fg = "springViolet1", modifiers = ["bold"] }
```

Monokai using colors for bold and italic

```toml
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
```

In my personal opinion, having colors for both heading levels and bold + italic make reading markdown much easier.

I wonder if we also can do that for other themes, or that is defined by the theme authors and we would violate their intetions. What are the maintainer thoughts on this?
