### ISSUE TITLE
Italics not reset for diagnostics text

### ISSUE THREAD

**Issue by mtoohey31** [helix-editor/helix#2856]
### Summary

When language server diagnostic summary text is rendered on the screen in a spot where the file's text is italicized due to syntax highlighting, the diagnostic text is also italicized.

This screenshot demonstrates the issue:

![2022-06-21T22:07:28,186693692-04:00](https://user-images.githubusercontent.com/36740602/174928360-7399cf97-113f-450a-ac55-2eb630869391.png)

The words "not enough" in the diagnostics text are italicized, but the rest of the line isn't.

### Reproduction Steps

 

I tried this:

1. `hx <filename>` (with language server active)
2. Position window/cursor so diagnostics appear overlapping text that is italicized.

`config.toml`:

```toml
theme = "base16_terminal_kitty"
```

<details>
<summary><code>themes/base16_terminal_kitty.toml</code>:</summary>

```toml
# Authors: NNB <nnbnh@protonmail.com>, Matthew Toohey <contact@mtoohey.com>

"ui.menu" = { fg = "light-gray", bg = "opaque-black" }
"ui.menu.selected" = { modifiers = ["reversed"] }
"ui.linenr" = { fg = "gray", bg = "black" }
"ui.popup" = { bg = "opaque-black" }
"ui.window" = { bg = "opaque-black" }
"ui.linenr.selected" = { fg = "white", bg = "black", modifiers = ["bold"] }
"ui.selection" = { fg = "black", bg = "blue" }
"ui.selection.primary" = { fg = "white", bg = "blue" }
"comment" = { fg = "gray", modifiers = ["italic"] }
"ui.statusline" = { fg = "white", bg = "opaque-black" }
"ui.statusline.inactive" = { fg = "gray", bg = "opaque-black" }
"ui.help" = { fg = "white", bg = "opaque-black" }
"ui.cursor" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.virtual" = "light-gray"
"variable" = "light-red"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attributes" = "yellow"
"type" = "light-yellow"
"ui.cursor.match" = { fg = "light-yellow", modifiers = ["underlined"] }
"string"  = "light-green"
"variable.other.member" = "light-green"
"constant.character.escape" = "light-cyan"
"function" = "light-blue"
"constructor" = "light-blue"
"special" = "light-blue"
"keyword" = "light-magenta"
"label" = "light-magenta"
"namespace" = "light-magenta"

"markup.heading" = "light-blue"
"markup.list" = "light-red"
"markup.bold" = { fg = "light-yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "light-magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "light-red"
"markup.quote" = "light-cyan"
"markup.raw" = "light-green"

"diff.plus" = "light-green"
"diff.delta" = "yellow"
"diff.minus" = "light-red"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "black" }
"info" = "light-blue"
"hint" = "gray"
"debug" = "gray"
"warning" = "yellow"
"error" = "light-red"

[palette]
opaque-black = "#000000"
```

</details>

I expected this to happen:

- None of the diagnostics text should be italicized.

Instead, this happened:

- Part of the diagnostics text, up until the underlying italicized text ends, is italicized.

### Helix log

N/A

### Platform

Linux

### Terminal Emulator

kitty 0.25.1

### Helix Version

22.05-55-gd7bd4416
