### ISSUE TITLE
Add roots for haskell in default languages.toml

### ISSUE THREAD

**Issue by 0rphee** [helix-editor/helix#2952]
#### Describe your feature request
So, while trying to load a Haskell `stack` project with helix, I found that the lsp couldn't find imports from external libraries, nevertheless, borrowing a line from [the haskell-language-server configuration for kakoune](https://haskell-language-server.readthedocs.io/en/latest/configuration.html#kakoune) has fixed the problem. I think it would be nice to add this to the default `languages.tom` for a better out-of-box experience.

**Current configuration for haskell**
```toml
[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "haskell"
file-types = ["hs"]
roots = []
comment-token = "--"
language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }
indent = { tab-width = 2, unit = "  " }
```
**Improved configuration for haskell**

```toml
[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "haskell"
file-types = ["hs"]
roots = ["Setup.hs", "stack.yaml", "*.cabal"]                                        # <---- added roots
comment-token = "--"
language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }
indent = { tab-width = 2, unit = "  " }
```
