### ISSUE TITLE
change_selection command not implemented as key remap

### ISSUE THREAD

**Issue by im-skylar** [helix-editor/helix#3032]
### Summary

The `change_selection` command from the [keymap](https://docs.helix-editor.com/keymap.htmll) lets helix unwrap with `not implemented` error when used in a keymap like following:

```toml
[keys.normal]
h = ["extend_line", "trim_selections", "change_selection"]
```

when used alone like `h = "change_selection"` it works just fine.

### Reproduction Steps

 

I tried this:

`config.toml:`
```toml
theme = "dracula"

[keys.normal]
h = ["extend_line", "trim_selections", "change_selection"]
# h = ["trim_selections", "change_selection"]
# h = "change_selection"
```

1. `RUST_BACKTRACE=1 hx`
2. On line 2 press `h` 
```rust
fn main() {
    println!("Hello world");
}
```

I expected this to happen:
```rust
fn main() {
    <cursor>
}
```

Instead, this happened:
Helix panicked with
```
thread 'main' panicked at 'not implemented', helix-term/src/ui/editor.rs:1352:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
   4: helix_term::compositor::Compositor::handle_event
   5: helix_term::application::Application::handle_terminal_events
   6: helix_term::application::Application::event_loop_until_idle::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: std::thread::local::LocalKey<T>::with
   9: tokio::park::thread::CachedParkThread::block_on
  10: tokio::runtime::thread_pool::ThreadPool::block_on
  11: tokio::runtime::Runtime::block_on
  12: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-07-11T12:10:02.076 helix_view::theme [WARN] Theme: invalid style attribute: modifier
2022-07-11T12:10:07.864 helix_view::theme [WARN] Theme: invalid style attribute: modifier

```

</details>

### Platform

Artix Linux 5.18.10 x86_64

### Terminal Emulator

Konsole 22.04.3

### Helix Version

helix 22.05-234 (g0cb0c306)
