### ISSUE TITLE
Add config option to [editor.file-picker] to ignore specific files

### ISSUE THREAD

**Issue by 0rphee** [helix-editor/helix#3085]
#### Describe your feature request
It would be nice to have a way to ignore a specific directory or file so it doesn't shows up in the file picker. I'd imagine it to be something like this:

```toml
[editor.file-picker]
ignored = ["file.txt", ".file2", "dir"]
```
