### ISSUE TITLE
Add example for LSP specific config

### ISSUE THREAD

**Issue by rcastill** [helix-editor/helix#3250]
There should be an example [here](https://docs.helix-editor.com/languages.html) of how to use the `config` field in the languages.toml file.

There seems to be some [confusion](https://github.com/helix-editor/helix/discussions/747).

I found out that it can (must?) be given as an object (at least in the case of rust-analyzer).

As seen in the [discussion](https://github.com/helix-editor/helix/discussions/747), the following snippet may be useful as an example:

```toml
[[language]]
name = "rust"
# LSP config
config.cargo.features = "all"
```

**Comment by dam5h** [comment]
I still can't get the pyright config in `languages.toml` to work so I end up having to define in a `pyproject.toml`  [Here ](https://github.com/helix-editor/helix/issues/1898) it looks like it should be a string (and that string would be using the json config definition for the LSP), but its not being honored.  I will try it like the above instead and see how it goes.

**Comment by AndyJado** [comment]
bump

**Comment by paul-hansen** [comment]
There is now documentation for this here: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#rust

I found it a bit hard to get right though, so here's an example with all features enabled for anyone else struggling:
```toml
[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"
```

This fixed `code is inactive due to #[cfg] directives: feature = "x" is disabled` for me.
