### ISSUE TITLE
Add the option to turn off lsp

### ISSUE THREAD

**Issue by Xalfer** [helix-editor/helix#3386]
Since my computer does not handle rust-analyzer very well, so I'd like the option to turn off lsp.
Also, language server do not work with C code very well.

**Comment by the-mikedavis** [comment]
You can do this currently by creating a `~/.config/helix/languages.toml` with the contents:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "rust"
language-server.command = ""
```

Or alternatively, you may uninstall rust-analyzer from your computer.

**Comment by BioBox** [comment]
Can there be a command-line option to turn it off?

**Comment by stevenengler** [comment]
It would also be nice if we could turn it off by default, and use a command to start it. Rust analyzer uses a huge amount of memory (plus a separate rust-analyzer instance runs for each running helix instance) and it's not something I want running all of the time.

**Comment by ash-hashtag** [comment]
It would be nice to have a command line option, like 

`hx . --no-lsp`

or better option name
especially for when I want to quickly edit files without any lsp helping, the lsp just makes things slower. I can't quickly close after editing, because the lsp(some language's) is still loading

**Comment by the-mikedavis** [comment]
Fixed in https://github.com/helix-editor/helix/pull/4425

You can use the `editor.lsp.enable` key in a config file:

```toml
# ~/.config/helix/config.toml
[editor]
lsp.enable = false
```

https://github.com/helix-editor/helix/issues/6686 talks about a CLI flag but we try to keep the number of CLI flags minimal
