### ISSUE TITLE
Issue adding support for VHDL language

### ISSUE THREAD

**Issue by m-kru** [helix-editor/helix#3433]
I am trying to add support for the VHDL language. I have followed instruction from the https://docs.helix-editor.com/guides/adding_languages.html. 

I have added following section to the `languages.toml`:
```toml
[[language]]
name = "vhdl"
scope = "source.vhdl"
injection-regex = "vhdl"
file-types = ["vhdl", "vhd"]
comment-token = "--"
indent = { tab-width = 3, unit = "   " }
roots = []

[[grammar]]
name = "vhdl"
source = { git = "https://github.com/alemuller/tree-sitter-vhdl", rev = "a3b2d84990527c7f8f4ae219c332c00c33d2d8e5" }
```
Then, I have recompiled and installed helix. I have also added `highlights.scm` to the `~/.config/helix/runtime/queries/vhdl`.
However, when I open any `.vhd` file it looks like something is wrong, as there is no highlighting and `tree-sitter-scopes` command always returns `[]`, no matter where in the source code the cursor is placed.
