### ISSUE TITLE
Xml syntax highlight

### ISSUE THREAD

**Issue by sbergot** [helix-editor/helix#3479]
I was surprised to see that there was no support for xml yet. I am willing to give a shot to adding syntax highlighting. Is it something doable for a rust newbie?

**Comment by ChrHorn** [comment]
You could try to just enable the html highlighting for xml files.

Alternatively, there is also https://github.com/unhammer/tree-sitter-xml, but I don't know how good that implementation is.

**Comment by sbergot** [comment]
@ChrHorn yes I was about to try that. Adding xml to the html file types works. It is good enough for me but it might be an issue for those who have the html language server enabled.

Anyway I am closing this. Thanks for the help!

**Comment by kirawi** [comment]
You can alternatively create a new language entry for XML that uses the syntax highlighting for HTML:

```toml
[[language]]
name = "xml"
scope = "scope.xml"
injection-regex = "xml"
file-types = ["xml"]
roots = []
indent = { tab-width = 2, unit = "  " }
grammar = "html"
```
