### ISSUE TITLE
There is no way to `cd` to the directory of the current file

### ISSUE THREAD

**Issue by cole-h** [helix-editor/helix#3519]
#### Describe your feature request

I'd like to be able to to `cd` to the directory the current file is in.

**Comment by cole-h** [comment]
The discussion in https://github.com/helix-editor/helix/pull/3523 has somewhat changed this ticket. I've modified the title and body to reflect that.

**Comment by pascalkuthe** [comment]
`:cd <c-r>%<c-w>` makes this very convenience. Can be bound as a keymap as a macro or when command expansoon lands so closing as duplicate of either those two

**Comment by cole-h** [comment]
Now that https://github.com/helix-editor/helix/pull/4709 has merged, here's a macro you can use to get this functionality!

```toml
[keys.normal.space]
"c" = "@:cd <C-r>%<C-w><ret>"
```

Pressing <kbd>space</kbd><kbd>c</kbd> will `cd` helix to the directory containing the current file!

**Comment by ramdomPTM** [comment]
Sorry for replying to such an old thread. Thanks for providing a solution to a function I have needed. It worked well until there was whitespace in the path.

Now that command line expansions are available from 25.07, I think `":cd %sh{dirname '%{buffer_name}'}"` is a more robust solution for Linux/macOS users.

Cheers.

**Comment by Rudxain** [comment]
> ```toml
> [keys.normal.space]
> "c" = "@:cd <C-r>%<C-w><ret>"
> ```

I felt so dumb until I realized there are problems with that:
- spaces, as already mentioned
- multiple "words" per path component, which `<C-w>` won't delete

The `dirname` alternative is prone to code-injection if the path contains single-quotes: #14149

My solution is a register-buffer "dance" with proper parsing:
```toml
[keys.normal.backspace]
# clobbers reg-p and `repeat_last_motion` internal state
c = """@\
<C-s>\
:set-register p %{file_path_absolute}<ret>\
:n<ret>\
\"pp\
F/\
<A-d>\
x\
:cd %{selection}<ret>\
:bc!<ret>\
<C-o>\
"""
```
> [!note]
> set-reg is master-only (for now) #14779

I've now realized this won't work if the path has `'\n'` 🥲

I've wrote a more robust version (assuming [this](https://github.com/helix-editor/helix/pull/4709#issuecomment-1323713162)), and it no longer clobbers registers!
```toml
[keys.normal.backspace]
c = [
	# remember target buffer index
	"save_selection",
	# make temporary-memory / scratch-space
	":n",
	# delete all chars (last line-feed)
	"delete_selection_noyank",
	# remember tmp location
	"save_selection",
	# prepare register for future restore;
	# don't assume default `"`
	"@\"p",
	# spill register (I feel like a compiler, lol)
	"paste_after",
	# current jump is same buffer, "consume" it first
	"jump_backward",
	# goto target
	"jump_backward",
	# now we have proper context.
	# NOTE: cmd is master-only:
	# https://github.com/helix-editor/helix/pull/14779
	":set-register p %{file_path_absolute}",
	# goto tmp buf
	"jump_forward",
	# paste path to buf-start;
	# further operations "forget" where the prefix is,
	# so this ensures we know where it is
	# even if path contains "\n".
	# Note that the cursor is on the last char of the path.
	"@\"p", "paste_before",
	# select last component
	"@F/",
	# dirname done!
	"delete_selection_noyank",
	# adjust cursor to last path-char (again)
	"move_char_left",
	# select full dir-path
	"select_mode", "goto_file_start",
	# switch to it!
	":cd %{selection}",
	# del path, leaving copy of reg-p intact
	"delete_selection_noyank",
	# restore reg-p
	"select_all", "@\"p", "yank",
	# release/free mem
	":bc!",
	# "return"
	"jump_backward"
]
```
I'll have to remove the comments and re-write as a full macro
