### ISSUE TITLE
vscode-eslint-language-server does not work

### ISSUE THREAD

**Issue by wparsonsheins-globality** [helix-editor/helix#3520]
### Summary

The eslint language server expects to be passed a `workingDirectory` but `null` was given.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Open a tsx file

I expected this to happen:
The language server could spawn

Instead, this happened:
The language server did not spawn

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-08-23T16:49:42.652 helix_lsp::transport [ERROR] err <- "(node:12369) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'workingDirectory' of null\n"
```

</details>

### Platform

macOS

### Terminal Emulator

Iterm2-3.4.16

### Helix Version

helix 22.05

**Comment by the-mikedavis** [comment]
`workingDirectory` is not part of the LSP spec - this server is expecting it as a configuration option. You can provide configuration options with the `config` option in `languages.toml` like [here](https://github.com/helix-editor/helix/blob/e4c9d4082a139aac3aea4506918171b96e81f5b9/languages.toml#L91)

**Comment by wparsonsheins-globality** [comment]
I tried adding the config property but the logs show `workingDirectory` is still null.

```toml
[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "^(tsx)$" # |typescript
file-types = ["tsx"]
roots = []
language-server = { command = "vscode-eslint-language-server", args = ["--stdio"], language-id = "typescriptreact" }
indent = { tab-width = 4, unit = "  " }
config = { "workingDirectory" = "./" }
```

**Comment by Ganitzsh** [comment]
Experiencing the same issue, I have been digging within the `vscode-eslint-language-server` code and logged some stuff, it seems that no configuration is found for the workspace despite setting the `config` property in the TOML file.

**Comment by LEI** [comment]
Here is a minimal working configuration based on [lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/eslint.lua) but it requires a [fix](https://github.com/helix-editor/helix/pull/2507/files#diff-d9796de334de9f547d45fd8b7476be53c771200ab48f28266e5f62e3493b5df9R995-R996) present in #2507:

```toml
[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""
```

With these settings the eslint language server runs when opening a file without errors.
Additional options like `codeAction` can be enabled.
