### ISSUE TITLE
Add short cut duplicated current line to next

### ISSUE THREAD

**Issue by jinfagang** [helix-editor/helix#3680]
this is very important as an development IDE, duplicated current line.

Also, will it possible add shortcut for comment / uncomment current line?

helix is promising, if it could think more for developers would be a swisher knife for users. way more better than vim

**Comment by the-mikedavis** [comment]
<kbd>X</kbd><kbd>y</kbd><kbd>p</kbd> can be used to duplicate the current line. <kbd>Ctrl</kbd><kbd>C</kbd> already exists for commenting/uncommenting the current line.

**Comment by jinfagang** [comment]
@the-mikedavis thank u! even tough it looks need 3 steps but it works! BTW, what's the shortcut to delete current line

**Comment by jinfagang** [comment]
ok, I found it. It looks more vim, these operation can not do directly in the editing mode

**Comment by kirawi** [comment]
You can also configure a key to do these three actions: https://docs.helix-editor.com/remapping.html

**Comment by izznatsir** [comment]
Here is my shortcuts for both in normal mode and insert mode:

```toml
[keys.normal]
S-A-down = ["extend_to_line_bounds", "yank", "open_below", "normal_mode", "replace_with_yanked", "collapse_selection"]
S-A-up = ["extend_to_line_bounds", "yank", "open_above", "normal_mode", "replace_with_yanked", "collapse_selection"]

[keys.insert]
S-A-down = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
S-A-up = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]
```
