### ISSUE TITLE
Globally invert up and down (j and k)

### ISSUE THREAD

**Issue by jharrilim** [helix-editor/helix#3835]
I personally like to use j as up and k as down. I can configure it for normal mode:

```toml
[keys.normal]
j = "move_line_up"
k = "move_line_down"
```

However, I cannot currently configure it for view mode or window mode. It would be a neat enhancement to be able to configure these, but potentially in a more global fashion. That way if any new features added movement capabilities, inversion would automatically be applied.

**Comment by the-mikedavis** [comment]
> I cannot currently configure it for view mode or window mode

This should be possible, for example

```toml
[keys.normal.z]
j = "scroll_up"
k = "scroll_down"
```

I think it's distasteful to add config options for things achievable through rebinding.
