### ISSUE TITLE
Persistent State

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#401]
This feature will allow you to share the same file history between sessions, and could help in situations where the editor crashes. #290 #294

**Comment by bestouff** [comment]
Now the question is: what file format ? In the ideal case, like for vim, a script which can be edited.

**Comment by cole-h** [comment]
This should probably be implemented as a plugin (whenever that functionality is available).

---

That said, it would probably be prudent to use something easy to serialize. TOML is already used for the basic config, so why not stick with that? An example, totally fictional file might store information about the documents themselves like:

```toml
[[documents]]
path = "/canonical/file/path"
cursor = { line = 90, column = 1 }
alt_document = "/canonical/file/path2" # this is "last_accessed_doc"
# no focused here; would be deserialized as false
[[documents.selections]]
start = { line = 70, column = 10 }
end = { line = 100, column = 1 }
[[documents.selections]]
start = { line = 1, column = 1 }
end = { line = 2, column = 23 }

[[documents]]
path = "/canonical/file/path2"
cursor = { line = 1, column = 1 }
# no alt_document here because it doesn't have one; would be deserialized as None
focused = true # means this document is currently visible
[[documents.selections]]
start = { line = 1, column = 10 }
end = { line = 5, column = 1 }
[[documents.selections]]
start = { line = 10, column = 1 }
end = { line = 10, column = 3 }
```

I don't currently have any ideas on how we would serialize the current layout of views to TOML, though.
