### ISSUE TITLE
Allow chaining `find_next_char`, `select_textobject_around`, etc. together with other commands in keymaps

### ISSUE THREAD

**Issue by tmke8** [helix-editor/helix#4013]
There are quite a few commands that expect an argument in the form of a single character:
- `find_till_char`
- `find_next_char`
- `till_prev_char`
- `find_prev_char`
- `surround_add`
- `surround_replace` (this one even expects two arguments)
- `surround_delete`
- `select_textobject_around`
- `select_textobject_inner`

However, it doesn't seem possible to chain these together with other commands in keymaps.

For example:
```toml
[keys.normal]
f = ["find_next_char", "collapse_selection"]
```
does not work as expected. The `collapse_selection` command seems to be completely ignored.

Similarly, this
```toml
[keys.normal]
C = ["select_textobject_inner", "change_selection"]
```
seems to execute the `change_selection` command immediately, before `select_textobject_inner` has finished.

My enhancement request is that if these commands with arguments appear in a keymap, they should first finish completely and then the next command in the list should be called.
