### ISSUE TITLE
Solargraph context: `bundle exec`

### ISSUE THREAD

**Issue by williamtstanley** [helix-editor/helix#4032]
I am trying to get Solargraph up and running for my project but I am stalled at the moment.
It "works" with the default configuration but doesn't load the project config properly. Wrong ruby version and missing gem errors etc.

[helix_default.log](https://github.com/helix-editor/helix/files/9676917/helix_default.log)

Solargraphs documentation recommends running it with `bundle exec solargraph` if that problem occurs.

```toml
[[language]]
name = "ruby"
language-server = { command = "bundle exec solargraph", args = ["stdio"] }
config = { solargraph = { diagnostics = true, formatting = true } }
auto-format = true
```

Updating my toml to the above also doesn't work.
[helix_bundler.log](https://github.com/helix-editor/helix/files/9676932/helix_bundler.log)

I am hoping I just have the config args incorrect. Is there a way to make sure the command is running in the cwd and should the command differ?
