### ISSUE TITLE
[Enhancement] add default behavior for Ctl-n / Ctl-p in Normal mode

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4124]
Neovim appears to bind `C-n` and `C-p` to `j` and `k` behavior in Normal mode. These are currently not bound in Helix

It would be interesting if we could have it bind to `jzj` and `kzk`

```toml
[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
```
