### ISSUE TITLE
Add syntax definition / highlight for Groovy, specifically Jenkinsfiles

### ISSUE THREAD

**Issue by weakphish** [helix-editor/helix#4211]
Currently, no syntax highlighting exists for Jenkinsfiles, which are written in Groovy.

**Comment by zephaniahong** [comment]
Hey! I'd be happy to give this issue a shot. @the-mikedavis May I get some advice as to which files/directories I should be looking at?

Thank you!

**Comment by the-mikedavis** [comment]
Take a look at the adding languages guide https://docs.helix-editor.com/guides/adding_languages.html and recent PRs that added languages https://github.com/helix-editor/helix/pulls?q=is%3Apr+is%3Amerged+add+language and

**Comment by weakphish** [comment]
Any updates on this?

**Comment by jlebon** [comment]
If it helps anyone else, parsing it as Java works OK (definitely not perfect, but better than no highlighting at all). I've put this in my `~/.config/helix/languages.toml`:

```toml
[[language]]
name = "java"
file-types = ["java", "groovy", "Jenkinsfile", "jenkinsfile"]
```

**Comment by Lonestar137** [comment]
According to the Helix documentation [Language Config](https://docs.helix-editor.com/languages.html), adding the following to the languages.toml in your helix config location should provide syntax highlighting but it does not.  
``` toml
[[language]]
name = "groovy"
scope = "source.groovy"
injection-regex = "groovy"
file-types = ["groovy", "Jenkinsfile"]
roots = []

[[grammar]]
name = "groovy"
source = { git = "https://github.com/Decodetalkers/tree-sitter-groovy", rev = "gh-pages" }
```
I checked the runtime and the groovy.so file compiles correctly but it seems like it isn't applied to the buffer.  If I change `name= "groovy"` to `name = "java"` then I get Java syntax highlighting.  I also tried replacing the groovy.so file with other working .so files and no syntax highlighting.  So, in my opinion, this is a bug.
