### ISSUE TITLE
Only the last key sequence from the config is parsed if the first key is the same

### ISSUE THREAD

**Issue by HellConnector** [helix-editor/helix#4293]
### Summary

When i try to add some key binding in `config.toml` like this:
```[keys.normal]
backspace = { r = ":sh cargo run" }
backspace = { o = [":config-open"] }
```
only the last binding for `:config-open` is parsed.

### Reproduction Steps

 

I tried this:

1. Add this lines to config.toml
```[keys.normal]
backspace = { r = ":sh cargo run" }
backspace = { o = [":config-open"] }
```
2. Open `hx`
3. Press `backspace`

I expected this to happen:
see two available commands

Instead, this happened:
see only the last command for `:config-open` command
![Q2dImbUlMV](https://user-images.githubusercontent.com/50717671/195988331-0017198b-a1c9-418c-9e13-c85aaa3b171c.png)
![omlgyW7O2z](https://user-images.githubusercontent.com/50717671/195988378-6dfefd5f-766a-4cde-a68a-0c73d454f2cb.png)

### Platform

Linux / Windows

### Terminal Emulator

cmd, zsh

### Helix Version

helix 22.08.1 (5077ce76)

**Comment by infamous-711** [comment]
The correct way to set this up would be:

```toml
[keys.normal]
backspace = { r = ":sh cargo run", o = ":config-open" }

# or this
[keys.normal.backspace]
r = ":sh cargo run"
o = ":config-open"
```
