### ISSUE TITLE
Add shell command output into statusline

### ISSUE THREAD

**Issue by chorcheus** [helix-editor/helix#4310]
Hi, there!

In vim it has been possible to add shell command output into the statusline.

This is what I would have in mind:
```toml
[editor.statusline]
right = ["selections", {"shell-script": "/home/user/scripts.sh"}, "total-line-numbers"]
```

I have a simple but dirty solution that requires only small changes in code:
```toml
[editor.statusline]
right = ["selections", "shell-script", "total-line-numbers"]
scripts-right = ["/home/user/scripts.sh"]
```

I dont think the second example is very nice. To make it cleaner and merge ready and look like the first example, `StatusLineConfig` would need to be refactored and `StatusLineElement` will have to be replaced by a different type. I am not sure if this is a wanted feature since helix so far seems not to get anything from outside environment. Is this something in scope of helix's philosophy? Thx
