### ISSUE TITLE
Select text inserted by shell or paste (#4458)  doesn't work properly when pasting with multiple cursors

### ISSUE THREAD

**Issue by Itay123TheKing** [helix-editor/helix#4609]
### Summary

When I saw this got merged I was immediately excited to implement moving selections around with the following addition to my `config.toml`:
```toml
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
```
and it mostly works quite nicely, nice job @the-mikedavis.

...until I tried using more than one selection

### Reproduction Steps

Simply paste with more than one cursor active. the top selection will move to the pasted text properly, but the others move left weirdly.
