### ISSUE TITLE
Add support for helm (go-templates) 

### ISSUE THREAD

**Issue by souzaramon** [helix-editor/helix#4652]
The syntax became pretty weird when opening a helm chart yaml

**Comment by nikaro** [comment]
I think it would also need some changes on how languages are detected for files. Helm files use `yml|yaml` extension and thus are detected as YAML file, even though you add an Helm language config.

For the record here is what i tried:

```toml
[[language]]
name = "helm"
scope = "source.helm"
injection-regex = "^helm$"
file-types = ["helm.yaml", "templates/*.yaml", { suffix = "templates/*.yaml" }, { suffix = "helm.yaml" }]
roots = ["Chart.yaml"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "helm_ls", args = ["serve"] }
grammar = "helm"

[[grammar]]
name = "helm"
source = { git = "https://github.com/dannylongeuay/tree-sitter-go-template", rev = "395a33e08e69f4155156f0b90138a6c86764c979" }
```

My file `mychart/templates/configmap.helm.yaml` is still loaded as YAML.

If i use `:lang helm` it works, except for the grammar, it is still highlighted as YAML.

I don't think `file-types = ["templates/*.yaml"]` is supposed to work but i think it would be the way to go to avoid rename files from `myfile.yaml` -> `myfile.helm.yaml` (if `file-types = ["helm.yaml"]` worked).

PS: here is LSP i tested https://github.com/mrjosh/helm-ls
