### ISSUE TITLE
DAP should react to Terminated event

### ISSUE THREAD

**Issue by zobo** [helix-editor/helix#4674]
When a DA (debug adapter) sends the [Terminated Event](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Terminated) the client should send the [Disconnect Request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Disconnect).

**Comment by zobo** [comment]
I maintain the PHP DAP. Here is my very minimal languages.toml

```toml
[[language]]
name = "php"

[language.debugger]
name = "php-debug"
transport = "stdio"
command = "...path.to..\\node.exe"
args = ["...path.to..\\vscode-php-debug\\out\\phpDebug.js"]

[[language.debugger.templates]]
name = "Listen"
request = "launch"
completion = [ ]
args = { log = "true" }

[[language.debugger.templates]]
name = "Launch script"
request = "launch"
#completion = [ { name = "script", completion = "filename" } ]
completion = [ "filename" ]
args = { log = "true", program = "{0}", runtimeExecutable = "...path.to..\\php.exe" }
```
