### ISSUE TITLE
Unimpaired move up and down (`[e` and `]e`)

### ISSUE THREAD

**Issue by jzelinskie** [helix-editor/helix#4691]
I'm a big fan of remapping the arrow keys to be more useful in normal and visual mode.
I typically map them to move current line left, right, up, down.

Here's a snippet of lua that demonstrates what exactly I do in neovim:

```lua
          nmap('<Up>',    '[e')
          vmap('<Up>',    '[egv')
          nmap('<Down>',  ']e')
          vmap('<Down>',  ']egv')
          nmap('<Left>',  '<<')
          nmap('<Right>', '>>')
          vmap('<Left>',  '<gv')
          vmap('<Right>', '>gv')
```

`[e` and `]e` come from unimpaired, but I noticed these were missing from Helix.

**Comment by kirawi** [comment]
Is this a duplicate of #2245?

**Comment by jzelinskie** [comment]
Yep!

I was able to reproduce the mapping like this:

```toml
[keys.normal]
"up"= ["keep_primary_selection","extend_line","yank","move_line_up","open_above","normal_mode","replace_with_yanked", "move_line_down", "move_line_down", "extend_line", "delete_selection", "move_line_up", "move_line_up"]
"down" = ["keep_primary_selection","extend_line","delete_selection", "paste_after", "move_line_down"]
"left" = "unindent"
"right" = "indent"
```
