### ISSUE TITLE
Trasparency/opacity should not be a part of the  theme.

### ISSUE THREAD

**Issue by igor-petruk** [helix-editor/helix#4740]
It should be a separate setting that could be applied to any theme, instead of creating transparent version like `base16_transparent`. Otherwise users have to customize every single theme if they want to try it on transparent terminal.

**Comment by the-mikedavis** [comment]
Since #3067, you can inherit any theme and unset the `ui.background` scope:

```toml
# ~/.config/helix/dracula_transparent.toml
inherits = "dracula"
"ui.background" = {}
```

I don't like the idea of adding an extra config option for this.
