### ISSUE TITLE
Relative line numbers

### ISSUE THREAD

**Issue by gbaranski** [helix-editor/helix#483]
#### Describe your feature request

Vim-like relative line numbers, they're very helpful for code navigation.
![Screenshot_20210722-011704](https://user-images.githubusercontent.com/34353640/126571672-f23d57fe-6a16-4187-ad17-329a166e0f23.png)

this could be configured like that
```toml
line_numbers = "none" # No line numbers
line_numbers = "absolute" # Absolute line numbers(default)
line_numbers = "relative" # Relative line numbers
```

**Comment by gbaranski** [comment]
I can try implementing that after I'll finish #478

**Comment by Omnikar** [comment]
How will this work with multiple cursors?

**Comment by pickfire** [comment]
There will still be one main cursor with multi cursors.

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/blob/eba0bbda2ee10e9ba53f01f1d324d2c4c82229d2/helix-term/src/ui/editor.rs#L330

**Comment by Cons-Cat** [comment]
I hope this can be toggled while editing. In Kakoune, it is possible to make pressing 0 temporarily toggle relative line numbers until the next command executes, which is very cool.

**Comment by tryzniak** [comment]
Hello. I didn't want to open a new issue, so I'll report here.
I think the relative numbers option is not working in the ~/.config/helix/config.toml file. But this is not working:
```toml
[editor]
line-number = "relative"
```
Nor line_numbers = "relative".

I'm new to Helix so maybe I'm configuring it the wrong way. Thank you

**Comment by sudormrfbin** [comment]
@tryzniak Relative line numbers are only in master and not yet released, so you'll have to [build from source](https://docs.helix-editor.com/install.html#build-from-source).

**Comment by tryzniak** [comment]
@sudormrfbin Thanks, I didn't notice that 😄

**Comment by blex-max** [comment]
Any word on this becoming something you can switch to temporarily from within helix? I'd find that very useful!

**Comment by djpowers** [comment]
> Any word on this becoming something you can switch to temporarily from within helix? I'd find that very useful!

I was looking for the same ability and added the following to my config:
```toml
[keys.normal.space]
n = ":toggle line-number absolute relative"
```

It will switch between absolute and relative numbering when pressing <kbd>\<space>n</kbd> ("n" for number). Of course you could also run the `toggle` command directly from the Helix command line, or use `set` instead if you don't care about flipping the setting back and forth: `:set line-number relative`
