### ISSUE TITLE
Helix mangled all open buffers when trying to create a macro

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4840]
### Summary

I had three buffers open, with two visible in a vertical split. I tried to create a macro with `Qmip` `C-c` `Q`. It froze for about 15 seconds, and then mangled every open buffer. It appeared to blend the output from multiple buffers. Here is my log file. I would rate this a P0 or P1 bug depending on how often it happens.

### Reproduction Steps

 

No reproduction available

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

[helix-log.log.zip](https://github.com/helix-editor/helix/files/10058247/helix-log.log.zip)

</details>

### Platform

macOS

### Terminal Emulator

iTerm Build 3.4.16

### Helix Version

helix 22.08.1 (eada6d53)

**Comment by archseer** [comment]
Is it possible that you were previously accidentally recording the macro? None of those keypresses should trigger a save.

**Comment by lukepighetti** [comment]
Anything is possible, are we able to see this in the logs?

**Comment by the-mikedavis** [comment]
It's visible in the UI with a `[@]` indicator in the bottom right-hand corner but I don't believe we log anything for that.

Do you have any custom keymaps? And can you reproduce this behavior?

**Comment by lukepighetti** [comment]
My recollection is that I hit `Q` and it started recording. It was when I ended recording that it mangled everything. 

I do not have a reproduction.

This my config

```toml
theme = "tokyonight_storm"
# theme = "solarized_light"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
shell = ["zsh", "-c"]

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
```
