### ISSUE TITLE
F# for Helix?

### ISSUE THREAD

**Issue by MarkuBu** [helix-editor/helix#4943]
I wonder why there is no support for F# in Helix until now. Is there any plan to add F# to Helix in the near future?

**Comment by christianfosli** [comment]
It seems there is no finished F# tree-sitter grammar (https://github.com/baronfel/tree-sitter-fsharp is very WIP), so I guess it's hard to get syntax highlights.

**Comment by MarkuBu** [comment]
That's not a good news :(

**Comment by EluciusFTW** [comment]
This is sad, I just found Helix, and love it out of the box, but fsharp syntax highlighting is mandatory for me. Hope it will be added soon :)

**Comment by askreet** [comment]
Status update here for future contributors:

* Linked PR (#6002) shows an example of getting started with this, with some good feedback on how to improve the highlight queries.
* Tree-Sitter implementation for F# is still buggy, so we'll keep an eye on it's progress to see when a complete implementation is possible.
* An LSP is also available and should be added at the same time.

**Comment by d4h0** [comment]
After the [F# tree-sitter implementation](https://github.com/Nsidorenco/tree-sitter-fsharp) adds tree-sitter queries ([which some plan to implement when the grammar stabilized](https://github.com/Nsidorenco/tree-sitter-fsharp/issues/11)), we should have everything to add F# support to Helix.

However, the language server currently [seems to be broken](https://github.com/fsharp/FsAutoComplete/issues/833). I've tried to use the LSP server with `neovim`, and it displays error messages on almost every cursor move.

Until that is fixed (or Helix enables a workaround), the F# language server is basically unusable.

For now, I switched to VSCode for F#. This seems to be by far the best solution at the moment (and isn't too bad in combination with the `neovim` extension for VSCode).

**Comment by Eliemer** [comment]
This is pretty unofficial, but this is my working LSP config for using FSAC. Provides errors messages and jump to definition and other LSP stuff. The FSAC team is working, albeit slowly, on generalizing a lot of the endpoints that are Ionide (VSCode extension) specific.
```bash
dotnet tool -g fsautocomplete
```
```toml
[[language]]
name = "fsharp"
scope="source.fs"
roots = ["fsproj", "sln", ".git"]
injection-regex = "^fsharp$"
file-types = ["fs", "fsx", "fsi"]
comment-token = "//"
indent = { tab-width = 4, unit = " " }
auto-format = true
language-server = { command = "fsautocomplete", args = ["--verbose"] }
config = { AutomaticWorkspaceInit = true, FSharp.ExternalAutocomplete = true }
```
