### ISSUE TITLE
Offer white cursor option

### ISSUE THREAD

**Issue by jacob-emery** [helix-editor/helix#5007]
At the moment, the cursor color adapts to the color of the text. Because of this, sometimes the cursor is hardly noticeable, e.g., anywhere inside an empty line.

This is particularly frustrating with the following setting:
```toml
[editor.cursor-shape]
insert = "bar"
```

I tried to change the cursor settings in the theme to white (#FFFFFF), however it didn't work as desired.

I think that a white cursor option for the `insert = "bar"` case would solve the issue.

**Comment by pascalkuthe** [comment]
Could post a screenshot of what your problem?
For me the theme is always white aslong as the cursor sets the forground color  (fg) for the cursor (`ui.cursor` and `ui.cursor.primary`).
For example in the `onedark` theme this is accomplished by the following lines:

``` toml
"ui.cursor" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "blue", modifiers = ["underlined"]}
```
