### ISSUE TITLE
goto_window_top + align_view_center not working together

### ISSUE THREAD

**Issue by mezdelex** [helix-editor/helix#5034]
### Summary

![image](https://user-images.githubusercontent.com/59997405/206106548-aa1a0a59-8e45-4552-902b-2ffd9f625a4c.png)

goto_window_bottom works, but not goto_window_top with the same motions.

### Reproduction Steps

Description provided in the config screenshot.

1. Expected behaviour: gt should go to window top and center the view.
2. Actual behaviour: gt goes to top of the window but doesn't center the view.

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Helix Version

helix 22.12 (96ff64a8)

**Comment by the-mikedavis** [comment]
I believe this is just a TOML issue: the subtable for `g` declared in the `g = { t = ..` line is being replaced with the second `g` subtable in the `g = { b = ..` line. These should be declared together in one subtable

```toml
[keys.normal]
g = { t = ["goto_window_top", "align_view_center"], b = ["goto_window_bottom", "align_view_center"] }
```

or you can use this syntax:

```toml
[keys.normal.g]
t = ["goto_window_top", "align_view_center"]
b = ["goto_window_bottom", "align_view_center"]
```
