### ISSUE TITLE
helix 22.12: custom theme fails to deserialize

### ISSUE THREAD

**Issue by dssgabriel** [helix-editor/helix#5043]
Hi! I updated today to helix 22.12 and my custom theme fails to load, although it worked fine under  helix 22.08.1.

Looking at the log file, I get the following warning at helix's startup:
```
2022-12-07T14:05:08.163 helix_term::application [WARN] failed to load theme `chocolate` - Failed to deserialize theme
```

I rebuilt helix from source today (latest commit to `master` at the moment of writing):
```
$ hx --version
helix 22.12 (a4de86e7)
```

I have no idea where this issue can come from. Reading through the changelog, I do not see anything in the breaking changes that could have messed up my theme configuration. Any idea of what could be causing this?
Otherwise, my config works fine.

<details>
<summary>Below is my theme config file, just in case I missed something in there:</summary>

```toml
# Chocolate (dark)
# Author: Gabriel Dos Santos <dss.gabriel@protonmail.com>
# Originally made by snakedye: https://gitlab.com/snakedye/chocolate
# License: MIT License
# -----------------------------------------------------------------------------

# User interface
# -----------------------------------------------------------------------------
"markup.heading" = "yellow"
"markup.list" = "beige"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "yellow", modifiers = ["italic"] }
"markup.link.url" = { fg = "aqua", modifiers = ["underlined"] }
"markup.link.text" = "aqua"
"markup.quote" = "beige"
"markup.raw" = "green"

"ui.background" = { fg = "white", bg = "black" }
"ui.background.separator" = "lightgray"

"ui.cursor" = { fg = "black", bg = "white" }
"ui.cursor.select" = { fg = "white", bg = "lightgray" }
"ui.cursor.match" = { fg = "white", bg = "lightgray" }
"ui.cursor.primary" = { fg = "black", bg = "white" }

"ui.linenr" = "lightgray"
"ui.linenr.selected" = { fg = "yellow", modifiers = ["bold"] }

"ui.statusline" = { fg = "white", bg = "gray" }
"ui.statusline.insert" = { fg = "gray", bg = "aqua" }
"ui.statusline.select" = { fg = "gray", bg = "magenta" }

"ui.popup" = { fg = "white", bg = "gray" }
"ui.window" = { fg = "white", bg = "darkgray" }
"ui.help" = { fg = "white", bg = "lightgray", modifiers = ["bold", "italic"] }

"ui.text" = "white"
"ui.text.focus" = { fg = "white", bg = "lightgray" }
"ui.text.info" = { fg = "white", bg = "gray" }

"ui.virtual.ruler" = { bg = "darkgray" }
"ui.virtual.whitespace" = "darkergray"
"ui.virtual.indent-guide" = "darkergray"

"ui.menu" = { fg = "white", bg = "lightgray" }
"ui.menu.selected" = { fg = "yellow", bg = "gray", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "white", bg = "gray" }

"ui.selection" = { bg = "gray" }

"ui.cursorline.primary" = { bg = "darkgray" }
"ui.cursorline.secondary" = { bg = "darkergray" }

"warning" = "orange"
"error" = "red"
"info" = "green"
"hint" = "aqua"
"diagnostic" = "magenta"

# Syntax highlighting
# -----------------------------------------------------------------------------
"keyword.directive" = "magenta"
"keyword.operator" = "aqua"
"keyword.storage.type" = "red"
"keyword.storage.modifier" = "aqua"
"keyword" = "red"

"namespace" = "green"
"type" = "yellow"
"constructor" = "aqua"
"attribute" = "magenta"

"function.macro" = "magenta"
"function.special" = "magenta"
"function.special" = "aqua"
"function" = "blue"

"variable.builtin" = "orange"
"variable.other" = "magenta"
"variable.parameter" = "green"
"variable" = "beige"

"string.url" = { fg = "aqua", modifiers = ["italic", "underlined"] }
"string" = "green"

"constant" = "orange"
"label" = "magenta"
"tag" = "beige"
"comment" = "lightergray"
"operator" = "white"
"punctuation" = "white"
"escape" = { fg = "gray", bg = "gray" }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "yellow"

# Color palette
# -----------------------------------------------------------------------------
[palette]
black = "#252221"
red = "#c65f5f"
green = "#859e82"
yellow = "#d9b27c"
blue = "#728797"
magenta = "#998396"
aqua = "#829e9b"
gray = "#3d3837"
orange = "#d08b65"
beige = "#ab9382"
lightgray = "#413c3a"
lightergray = "#645f5d"
darkgray = "#2f2c2b"
darkergray = "#2b2827"
white = "#c8baa4"
```
</details>
