### ISSUE TITLE
IME control

### ISSUE THREAD

**Issue by hh9527** [helix-editor/helix#5086]
Vim has this feature for many years.

This feature is very useful for non-western document writing.

for example, I use helix to edit a markdown file:
```md
这是一句中文 this is a Chinese sentence.
```

When I enter the `insert mode`, I switch to use Chinese IME, input some Chinese chars,
and then I switch back to `normal mode`, want to move cursor to next line by press `j`, the IME input pane will poped up.

What is the behaviour I need is same as Vim, when I switch back `normal mode`, the IME is auto disabled,
and when re-enter `insert mode`, IME is restored automaticaly.

I found all other editors except vim (vim-for-vscode, neovim, neovim-qt) are so smart like vim. I hope this can be done in `helix`.

**Comment by erasin** [comment]
This is a config for mac, I use [macism](https://github.com/laishulu/macism) / [im-select](https://github.com/daipeihust/im-select) controll ime with shell.

~/config/helix/config.toml

```
[key.normal]
"esc" = [":sh macism com.apple.keylayout.ABC", "normal_mode"]

[keys.insert]
"esc" = [":sh macism com.apple.keylayout.ABC", "normal_mode"]
```

> vscode / nvim has used im-select.
> im-select support macos/window/linux.

This is a tmeporary way, if you want more ,may be need wait a plugin that somebody write.
这个是临时解决用法，如果需要智能的部分，大概率要等插件系统来实现了，或者等待有人实现。

**Comment by zhenyuanlau** [comment]
@erasin It works. But there is a slight mistake here,  using "keys.normal" instead of "key.normal".

@hh9527 Turn on "Automatically switch to a document’s input source" for macOS. It will keep the previous input method source when switching back to the desktop application.  I think there is no need to disable IME, at least for macOS.

**Comment by pickfire** [comment]
Although there is something like https://github.com/vim-scripts/fcitx.vim/blob/master/plugin/fcitx.vim for only fcitx but I don't think there is a common protocol for other ime like ibus.

**Comment by erasin** [comment]
@hh9527 



- Rime  `Vim Mode` https://github.com/rime/squirrel/commit/08ed4f4590e17c969f1536b347bbe1f05737d4aa 
- Rime config for Vim https://github.com/einverne/einverne.github.io/commit/ec2f2d8e3f6035f6816bfdd97b2bd2c967f84121

**Comment by HippieRocket** [comment]
I managed to get a solution for Fcitx5 users.

我有了一个对Fcitx5用户有用的解决方案。

For some reason I found that running shell command in Helix cannot set variables so I write the fcitx5 state to `/tmp/fcitx5state` when entering normal mode. So here goes my clunky solution. Hope you find it useful. I use shuangpin and please replace it with your input method. You can get it by execute `fcitx5-remote -n`.

不知为何在Helix中执行shell命令无法设置变量，所以我只能把进入普通模式时Fcitx5的状态写入`/tmp/fcitx5state`。总之能用但有点蹩脚，希望对有类似需要的人有所帮助。我使用双拼，请将配置中的shuangpin替换为您使用的输入法，通过执行`fcitx5-remote -n`获取。

In `.config/helix/config.toml`:

在`.config/helix/config.toml`中：

```toml
[keys.insert]
"esc" = [":sh echo $(fcitx5-remote -n) > /tmp/fcitx5state; fcitx5-remote -c", "normal_mode"]

[keys.normal]
"i" = [":sh if [ -e \"/tmp/fcitx5state\" ] && [ $(cat /tmp/fcitx5state) = \"shuangpin\" ]; then fcitx5-remote -o; fi", "insert_mode"]
"a" = [":sh if [ -e \"/tmp/fcitx5state\" ] && [ $(cat /tmp/fcitx5state) = \"shuangpin\" ]; then fcitx5-remote -o; fi", "append_mode"]
"c" = [":sh if [ -e \"/tmp/fcitx5state\" ] && [ $(cat /tmp/fcitx5state) = \"shuangpin\" ]; then fcitx5-remote -o; fi", "change_selection"]
```

**Comment by HippieRocket** [comment]
> I managed to get a solution for Fcitx5 users.
> 
> 我有了一个对Fcitx5用户有用的解决方案。

If you happens to be a fcitx5-rime user, I managed to come up with a new solution thanks to the dbus interface fcitx5-rime provides.

如果您使用fcitx5-rime扩展，可使用如下配置，使用Fcitx5的dbus服务来切换rime自身的中英文状态。

```toml
[keys.insert]
"esc" = [":sh echo $(busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 IsAsciiMode) > /tmp/rime-state; busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b true", "normal_mode"]

[keys.normal]
"i" = [":sh if [ -e \"/tmp/rime-state\" ] && [ \"$(cat /tmp/rime-state)\" = \"b false\" ]; then busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b false; fi", "insert_mode"]
"a" = [":sh if [ -e \"/tmp/rime-state\" ] && [ \"$(cat /tmp/rime-state)\" = \"b false\" ]; then busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b false; fi", "append_mode"]
"c" = [":sh if [ -e \"/tmp/rime-state\" ] && [ \"$(cat /tmp/rime-state)\" = \"b false\" ]; then busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b false; fi", "change_selection"]
"o" = [":sh if [ -e \"/tmp/rime-state\" ] && [ \"$(cat /tmp/rime-state)\" = \"b false\" ]; then busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b false; fi", "open_below"]
"I" = [":sh if [ -e \"/tmp/rime-state\" ] && [ \"$(cat /tmp/rime-state)\" = \"b false\" ]; then busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b false; fi", "insert_at_line_start"]
"A" = [":sh if [ -e \"/tmp/rime-state\" ] && [ \"$(cat /tmp/rime-state)\" = \"b false\" ]; then busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b false; fi", "insert_at_line_end"]
"O" = [":sh if [ -e \"/tmp/rime-state\" ] && [ \"$(cat /tmp/rime-state)\" = \"b false\" ]; then busctl call --user org.fcitx.Fcitx5 /rime org.fcitx.Fcitx.Rime1 SetAsciiMode b false; fi", "open_above"]
```
