### ISSUE TITLE
goto_line_end goes to the character before \n

### ISSUE THREAD

**Issue by hzb-ykpcx** [helix-editor/helix#5128]
I find the command "goto_line_end" no longer goes to the end of line ('\n'), instead it goes to one character before the end.

**Comment by the-mikedavis** [comment]
That's the expected behavior for `goto_line_end` and AFAIK the command hasn't changed recently. There is a closely related `goto_line_end_newline` command which goes to the newline at the end of the line. You could replace the binding for `goto_line_end` with `goto_line_end_newline`:

```toml
# ~/.config/helix/config.toml
[keys.normal]
end = "goto_line_end_newline"
g.l = "goto_line_end_newline"
```
