### ISSUE TITLE
[Feature] Harpoon like bookmarks

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#5167]
Harpoon: https://github.com/ThePrimeagen/harpoon

Harpoon is like bookmarks, but better.

Something to save files with option to be per cwd (project).

- Navigate on files with telescope.
- Navigate between files with SPC 1, SPC 2, SPC 3 or something like that.
- Save, delete, clear files on helix bookmarks.

I miss this so much from vim, would be awesome to have natively

**Comment by kellpossible** [comment]
additionally it supports a bookmark set per git branch which I get a lot of use out of

**Comment by cdecompilador** [comment]
without plugin system is impossible, but would be a simple task to bundle it to the code, when i have time i will try and post the git patch here just i case someone else wants to try

**Comment by hakan-demirli** [comment]
Here is a simple harpoon implementation for tmux users.

https://github.com/helix-editor/helix/assets/78746991/70e78c1d-da60-444a-a105-7f976c04cbc3

**Usage**
Keymap is adjustable in helix:
* Ctrl+h:
    * Add current file:cursor_position to harpoon list
* Ctrl+<jkl;>:
    * Switch to 1st, 2nd, 3rd or 4th entry in the harpoon list.
* Ctrl+n:
    * Edit harpoon list on floating helix instance
 
**Installation**
Add these files to your path:
https://github.com/hakan-demirli/dotfiles/blob/main/.local/bin/helix_harpoon_add
https://github.com/hakan-demirli/dotfiles/blob/main/.local/bin/helix_harpoon_switch
https://github.com/hakan-demirli/dotfiles/blob/main/.local/bin/helix_harpoon_edit
https://github.com/hakan-demirli/dotfiles/blob/main/.local/bin/helix_harpoon_update
https://github.com/hakan-demirli/dotfiles/blob/main/.local/bin/helix_harpoon_parse

**Add your keymaps**
```toml
[keys.normal]
"C-h" = ":pipe-to helix_harpoon_add"
"C-n" = ":pipe-to helix_harpoon_edit"
"C-j" = ":pipe-to helix_harpoon_switch 1"
"C-k" = ":pipe-to helix_harpoon_switch 2"
"C-l" = ":pipe-to helix_harpoon_switch 3"
"C-;" = ":pipe-to helix_harpoon_switch 4"
```
Note: Anything that changes your current buffer has to call helix_harpoon_update first if you want to return where you were using harpoon shortcuts. So, you must prepend it to all of these commands:
```toml
[keys.normal.g]
"n" = [":pipe-to helix_harpoon_update","goto_next_buffer"]
"p" = [":pipe-to helix_harpoon_update","goto_previous_buffer"]
"d" = [":pipe-to helix_harpoon_update","goto_definition"]
"y" = [":pipe-to helix_harpoon_update","goto_type_definition"]
"r" = [":pipe-to helix_harpoon_update","goto_reference"]
# There are more. Expand as you need.
```
