### ISSUE TITLE
More case conversions

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#5197]
converting through different patterns of cases would be awesome, like:

convert to snake_case
convert to camel case
convert to js case (like camel, but with first letter downcased)

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/pull/4615, this can probably be covered by macro keybinds (#1383)

**Comment by otavioschwanck** [comment]
> See #4615, this can probably be covered by macro keybinds (#1383)

i love the solution for #4615 , i think it is more interesting then binding commands to a macro.

**Comment by NomisIV** [comment]
The macro solution would be to create macros converting to and from each case, if I understand correctly. That would be 42 different macros and 42 different keybinds in total for converting between each casing. The key benefit of the proposed (original) solution in the #4615 PR is that seven different keybinds is enough, one for each target casing.

**Comment by rcorre** [comment]
FWIW, I was able to do this using `:pipe` and [ccase](https://github.com/rutrum/ccase):

```toml
[keys.normal.g.c]
p = ":pipe ccase --to pascal"
c = ":pipe ccase --to camel"
C = ":pipe ccase --to uppercamel"
k = ":pipe ccase --to kebab"
s = ":pipe ccase --to snake"
S = ":pipe ccase --to screamingsnake"
```

**Comment by workingj** [comment]
just_in_case, SomeOne Wants_A_Complete CONFIG 😃

```toml
# cargo install ccase
[keys.normal.g.C]
# '_' underscore
s = ":pipe ccase -t snake"       # snake_case
C = ":pipe ccase -t constant"    # CONSTANT_CASE
A = ":pipe ccase -t ada"         # Ada_Case
# '-' hyphen
k = ":pipe ccase -t kebab"       # kebab-case
K = ":pipe ccase -t cobol"       # COBOL-CASE
t = ":pipe ccase -t train"       # Train-Case
# '' no delimiter
f = ":pipe ccase -t flat"        # flatcase
F = ":pipe ccase -t upperflat"   # UPPERFLATCASE
p = ":pipe ccase -t pascal"      # PascalCase
c = ":pipe ccase -t camel"       # camelCase
# ' ' space
l = ":pipe ccase -t lower"       # lower case
U = ":pipe ccase -t upper"       # UPPER CASE
T = ":pipe ccase -t title"       # Title Case
S = ":pipe ccase -t sentence"    # Sentence case
# other
n = ":pipe ccase -t alternating" # aLtErNaTiNg CaSe
r = ":pipe ccase -t random"      # ranDom CAsE
g = ":pipe ccase -t toggle"      # tOGGLE cASE
R = ":pipe ccase -t surreal"     # s u r r e a l c a s e
```
