### ISSUE TITLE
Hilighting broken on themes which use italics

### ISSUE THREAD

**Issue by glfmn** [helix-editor/helix#5216]
### Summary

When setting the styling of comments for a theme, the following results in unexpected styling:

```toml
"comment" = { fg = "gray1", modifiers = ["italic"]  }
```
![image](https://user-images.githubusercontent.com/14112725/208493725-be73aaa6-727c-472a-913b-cac1e6885fbf.png)

However, it does work when using the following forms:

```toml
"comment" = "gray1"
"comment" = { fg = "bg0", bg = "gray1" }
"comment" = { fg = "gray1", modifiers = ["bold"] }
```

![image](https://user-images.githubusercontent.com/14112725/208493569-d65d4d3b-2bd9-47c6-8aaf-7f64bbe576b9.png)

### Reproduction Steps

Select the gruvbox theme (or any theme which uses italics for comment syntax hilighting).

Create a new theme which inherits from it and override the comment style.  Toggle between the themes and observe that themes with modifiers do not have the correct output.

```toml
# Modify the gruvbox theme
inherits = "gruvbox"

# Change the look of comments
"comment" = "gray1"
```

I have not tested anything other than comments, but it could just be an issue with italics in general.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-12-19T13:18:16.648 helix_view::theme [WARN] Theme: malformed hexcode: test
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.9.0

### Helix Version

helix 22.12 (ec9aa669)
