### ISSUE TITLE
Quarto support

### ISSUE THREAD

**Issue by jfb-h** [helix-editor/helix#5365]
Is it possible to get syntax highlighting for [Quarto](https://quarto.org/) documents? I tried adding a naive adaptation of the rmarkdown block to the `languages.toml`,  but to no avail:

```toml
[[language]]
name = "quarto-markdown"
scope = "source.qmd"
injection-regex = "(q|Q)md"
file-types = ["qmd", "Qmd"]
roots = []
indent = { tab-width = 2, unit = "  " }
grammar = "markdown"
language-server = { command = "R", args = ["--slave", "-e", "languageserver::run()"] }
``` 

Thanks!
