### ISSUE TITLE
python pyright-langserver not working

### ISSUE THREAD

**Issue by aspizu** [helix-editor/helix#5367]
```toml
[[language]]
name = "python"
file-types = ["py", "pyi"]
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
formatter = { command = "black", args = ["-", "-q"] }
auto-format = true
```

The language server does not work. Doing anything results in:
`Async job failed: request timed out`
after a while
I have installed pyright using pip.
