### ISSUE TITLE
add shotcut key for close buffer  

### ISSUE THREAD

**Issue by fastfading** [helix-editor/helix#5480]
since bufferline is enabled,  we need a shortcut key to close buffer

**Comment by the-mikedavis** [comment]
You can remap `:buffer-close` to do this:

```toml
# ~/.config/helix/config.toml

[keys.normal]
C-x = ":buffer-close"
```
