### ISSUE TITLE
Improve behavior of `xc` (selecting line, deleting it, entering insert mode)

### ISSUE THREAD

**Issue by effinsky** [helix-editor/helix#5501]
Currently when I'm on a line and want to clear it out and start typing in it, the behavior is quirky (at least as I find it):

Once I press `x`, this happens (ok):
![Screenshot 2023-01-11 at 09 55 05](https://user-images.githubusercontent.com/54535543/211761963-53c40e69-e6f5-498d-8f02-6ec85c7143d5.png)

Then, when I press `c`, this happens (weird; the entire line is deleted and the cursor needs to be moved to create a line above): 
![Screenshot 2023-01-11 at 09 55 41](https://user-images.githubusercontent.com/54535543/211762011-3816e85d-9249-45d9-9a4d-29b819cc12a0.png)

What I would like to happen immediately after hitting `c` is this:
![Screenshot 2023-01-11 at 09 56 57](https://user-images.githubusercontent.com/54535543/211762088-3efb2819-d399-417e-9a6b-33f3d213be5c.png) -- stay in the cleared-out line and immediately start typing at the correct indentation level.

Thanks in advance!

**Comment by the-mikedavis** [comment]
This is the expected behavior of that motion. You can use `X_c` to edit that scenario: `_` trims the whitespace in the selection so you keep the end-of-line character and the indentation.

More generally you can use `XdO`:

* `X`: extend to line bounds (like `x` but doesn't select the next line when you already have the full line selected)
* `d`: delete the current line selected by `X`
* `O`: enter insert mode by entering a newline above the selection. This command calculates the indentation just like pressing Enter in insert mode.

If this is a very common edit you make, you can make keybindings for them, for example:

```toml
# ~/.config/helix/config.toml

[keys.normal]
# X_c
C = ["extend_to_line_bounds", "trim_selections", "change_selection"]
# XdO
C = ["extend_to_line_bounds", "delete_selection", "open_above"]
```
