### ISSUE TITLE
External binary formatter docs for Prettier sets up wrong formatter for TSX

### ISSUE THREAD

**Issue by mazei513** [helix-editor/helix#5689]
In the wiki for the [prettier section](https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration#prettier), the configs are listed with using the `--parser` arg to let prettier know what kind of parser to use. However, when adding an additional config for TSX, I had set up

```toml
[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
```

Looking through the [Prettier docs](https://prettier.io/docs/en/options.html#parser) there doesn't seem to be a TSX specific parser and the `typescript` parser worked well enough, except it formats the following wrongly.

```tsx
const foo = <T,>(a: T): T => return a;
// becomes
const foo = <T>(a: T): T => return a;
```

The trailing comma, which is required for the generic function declaration, is removed. The fix was was to instead configure prettier with the `--stdin-filename` arg instead to let Prettier decide on a parser based on the file extension.

```toml
[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--stdin-filename", "file.html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--stdin-filename", "file.json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--stdin-filename", "file.css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--stdin-filename", "file.js"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--stdin-filename", "file.ts"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--stdin-filename", "file.tsx"] }
auto-format = true
```

Would like to suggest the wiki page to be updated to this as it would avoid a hiccup for what I would think is a common usecase for web dev. The additional `tsx` configuration doesn't need to be included even, just having the wiki docs showing the use of `--stdin-filename` would help lead readers down a path that would avoid the above issue.
