### ISSUE TITLE
unable to setup "yaml-language-server" configuration on helix

### ISSUE THREAD

**Issue by seungwoo-lee-518-at-proton-me** [helix-editor/helix#5700]
I'd like to Enable Kubernetes on YAML via [yaml-language-server](https://github.com/redhat-developer/yaml-language-server).

However It's tricky (for me that I'm new to TOML Languages :cry: ) to add configuration on `languages.toml`, how can I add json configuration to enable this feature?

for example

```json
yaml.schemas: {
    "kubernetes": ["*.yaml"]
}
```

**Comment by seungwoo-lee-518-at-proton-me** [comment]
![2023-01-27-233659_screenshot](https://user-images.githubusercontent.com/108667785/215112891-4619bed7-9413-4ff4-8698-2cc3cf614941.png)

Ah! I've found a solution from "nvim-lspconfig" Repository's [Issue](https://github.com/neovim/nvim-lspconfig/issues/1207)!

Here is my configuration to Enable Kubernetes from YAML.

```toml
[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
config = { yaml = { schemas = { kubernetes = "/*.yaml" }, format = { enable = true } } }
```

But, when I type **`:format`** command on helix. It doesn't formatted. and on log (a.k.a `.cache/helix/helix.log`), helix got a malformed notification from LSP Server.

```
2023-01-27T23:48:26.086 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
2023-01-27T23:48:26.086 helix_term::application [ERROR] received malformed notification from Language Server: Unhandled
```

Anyway, It worked!
