### ISSUE TITLE
Highlighted code get wrong indentation but none highlighted code is indented right.

### ISSUE THREAD

**Issue by H4ckint0sh** [helix-editor/helix#5756]
### Summary

Self explanatory.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

Kitty 26.5

### Helix Version

22.12 (96ff64ab)

**Comment by CptPotato** [comment]
> ### Summary
> 
> Self explanatory.

Please provide more information. The title is not self explanatory at all.

**Comment by pascalkuthe** [comment]
This is not an actual bug but intentional. Your code is probably indented with tabs rather than spaces. Helix allows configuring the amounts of spaces used to render a tab per language. Without highlight usually means that no language config was found for a file which means that tabwidth default to 4 but for json the `tab-width` is set to `2` on purpose.

If you are unahppy with this default you can change it by adding the following to your languages.toml:
``` toml
[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" } # by default helix inserts two spaces when pressing tab in json this changes the setting to insert a tab instead and render a tab with a width of 4 instead of 2. 
```
