### ISSUE TITLE
Mapping unicode characters with Ctrl doesn't work (but Alt does)

### ISSUE THREAD

**Issue by kristian-clausal** [helix-editor/helix#5765]
### Summary

Mapping "C-ö" or "C-å" does not work, but "A-ö" and "A-å" does.

### Reproduction Steps

MATE Terminal, Helix built from source today.

config.toml:
```toml
theme = "gruvbox"

[editor]
true-color = true
rulers = [80]

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
h = "insert_mode"
...

[keys.insert]
"C-ö" = "normal_mode"
```

I'm using a Finnish keyboard layout (with modifications) and I will be continuing using a Finnish keyboard layout, so it would be handy to rebind characters on the keyboard, and Ctrl is in a much more comfortable position, so it's a shame that it doesn't seem to work. I could have sworn that it worked for a hot minute earlier today, but I am probably confusing it with an attempt to use Alt-ö instead, which *does* work, as does Alt-å. Ctrl-p (just to test) works fine.

I checked what is actually written in config.toml (in case something funky like decomposing ö into o+combinding diaresis happened), and it's just Unicode decimal point 246.

### Helix log

The log did not contain anything pertinent. Mostly complaining I haven't bothered to install a .toml LSP.

### Platform

Linux Mint 20.2

### Terminal Emulator

MATE 1.24.0

### Helix Version

22.12-200-g0f562dfe
