### ISSUE TITLE
pyright lsp not working

### ISSUE THREAD

**Issue by senevr** [helix-editor/helix#6043]
I don't know if this is a problem with helix or if there is a silly step i've missed in the configuration. Let me start by saying that I have checked most other pyright related issues on this github and tried the different solutions I found, so far nothing has worked and I don't know why. I was initially using pylsp which was the default lsp on ``hx --health``, oddly enough I got no diagnostics, error reporting/warnings, and no intellisense/autocompletion. I saw a common patterns of people switching to pyright in this repository's issues, so I gave it a try. Similarly to pylsp, i get no support, but on top of that I get an error; ``Async job failed: request timed out``

I checked these issues: https://github.com/helix-editor/helix/issues/5479, https://github.com/helix-editor/helix/discussions/5369#discussioncomment-4574449

So I saw that setting ``config = {}`` solved their error, but it didn't with mine. Here is my configuration:
```toml
[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
formatter = { command = "black", args = ["--quite", "-"] }
auto-format = true
diagnostic-severity = "Hint"
```

When I check python's health using ``hx --health python`` I get the following:
```
Configured language server: pyright-langserver
Binary for language server: /opt/homebrew/bin/pyright-langserver
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

And this is my ``config.toml`` incase it helps:
```toml
theme = "dark_plus"

[editor]
cursorline = true

[editor.lsp]
display-messages = true
```

I'm running on **MacOS Ventura 13.2.1** and I used **Homebrew 4.0.1** to install **helix 22.12** and **pyright 1.1.294**.
