### ISSUE TITLE
Adding Markdoc (`.mdoc`) support

### ISSUE THREAD

**Issue by chopfitzroy** [helix-editor/helix#6229]
### Background

[Markdoc](https://markdoc.dev/) is a new way to write Markdown files developed by [Stripe](https://github.com/stripe) and largely operates in the same space as [MDX](https://mdxjs.com/).

For a more thorough breakdown of the differences between Markdoc and MDX I highly recommend [withastro/roadmap#478](https://github.com/withastro/roadmap/discussions/478) and [withastro/roadmap#496](https://github.com/withastro/roadmap/issues/496) which go into considerable detail.

### Language integration

Ideally I would like to open a PR for this long term but I am currently having some issues getting the LSP / Tree-sitter integrations working locally.

From my understanding a language integration ideally includes an LSP, Queries and Grammar. 

Fortunately [Markdoc Extra](https://github.com/markdoc-extra) adds experimental support for all of the above:

- [LSP](https://github.com/markdoc-extra/markdoc-ls)
- [Grammar and Queries](https://github.com/markdoc-extra/tree-sitter-markdoc)

So far I have tried adding the following to me `languages.toml`:

```toml
[[language]]
name = "markdoc"
scope = "text.markdoc"
roots = []
file-types = ["mdoc"]

[[grammar]]
name = "markdoc"
source = { git = "https://github.com/markdoc-extra/tree-sitter-markdoc", rev = "89c62c8f3b407fbd46f08b569342a3469c5b374b" }
```

And if I run `hx -g fetch` and `hx -g build` it does appear to successfully build but unfortunately `.mdoc` files are still not highlighted.

Any help on this would be much appreciated, I am hoping to open a PR once I figure it out.

### Considerations

As stated above both the LSP and Tree-sitter grammar and queries are experimental so it may be worth waiting before _officially_ adding support for these.
