### ISSUE TITLE
Add support for SVG files

### ISSUE THREAD

**Issue by IvanGoncharov** [helix-editor/helix#6337]
SVG files contain XML so it should be easy to add since Helix already supports XML.
I tried to add SVG support locally by adding following to my `languages.toml`:
```toml
[[language]]
name = "svg"
file-types = ["svg"]
scope = "svg"
injection-regex = "svg"
indent = { tab-width = 2, unit = "  " }
roots = []
grammar = "XML"
```

But it doesn't work 🤷‍♂️
