### ISSUE TITLE
version-control status bar element doesn't have spacing

### ISSUE THREAD

**Issue by cd-a** [helix-editor/helix#6408]
### Summary

Just tested the version-control element on the status bar that was added in https://github.com/helix-editor/helix/pull/5682.

It seems to be the only element that lacks spacing before and after. I tested it with the other elements, and those do provide spacing. (like you can see on left element)

### Reproduction Steps

config.toml on master:
```toml
[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "separator", "position", "separator", "file-line-ending", "separator", "file-type", "file-encoding"]
separator = "│"
```

I expected this to happen:
Spacing between spinner and version-control

Instead, this happened:
![image](https://user-images.githubusercontent.com/75008413/226965417-f1c4ee64-dfc5-49f0-9866-631c6891ddd2.png)

This also happens on the right side.

### Platform

macOS 13.2.1

### Terminal Emulator

kitty 0.27.1

### Helix Version

22.12-466-gf9a25a7e
