### ISSUE TITLE
lean language server ignoring default options

### ISSUE THREAD

**Issue by danjenson** [helix-editor/helix#6411]
### Summary

I am using the lean language server for Lean 4, however,  none of the options listed here: https://github.com/leanprover/vscode-lean appear to be working. In particular, I'd like it to replace commands like \to with unicode symbols. I even added 

```toml
[[language]]
name = "lean"
config = { lean.input.eagerReplacementEnabled = true }  # should already be the default
```
to my `languages.toml`, but it seems to have no effect. 

### Reproduction Steps

1. Install elan: `curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh`
2. Update elan: `elan self update`
3. Install Lean 4, set as default: `elan default leanprover/lean4:stable`
4. `hx t.lean`
5. Try to type anything, i.e. `a \to b`, where `\to` should be replaced with right arrow.

### Helix log

![image](https://user-images.githubusercontent.com/4793438/227000408-794d1ade-6bd1-45b9-83a7-3512b865772f.png)

### Platform

Void Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.12
