### ISSUE TITLE
Rust Shebang Highlighting Is Not Correct

### ISSUE THREAD

**Issue by KoBruhh** [helix-editor/helix#6429]
### Summary

```rust
#!/usr/bin/env run-cargo-script
```

![image](https://user-images.githubusercontent.com/101834410/227614357-ac9dd9a9-5560-4cdb-b455-463131e04980.png)

### Reproduction Steps

create a rust file (ending with '.rs') and open it with helix.

add a shebang which is generally represented as:

```rust
#!/usr/bin/env run-cargo-script
```

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/11065652/helix.log)

### Platform

Linux

### Terminal Emulator

alacritty 0.13.0-dev (66d742d0)

### Helix Version

helix 22.12 (77049651)

**Comment by kirawi** [comment]
You have to define a `shebangs` key in your `languages.toml` for Rust, i.e.
https://github.com/helix-editor/helix/blob/9a651188998bbc1584519ebf658cb5c2c31f4b21/languages.toml#L616

**Comment by the-mikedavis** [comment]
Is your nvim setup using nvim-treesitter for rust highlighting?

I don't see anything in tree-sitter-rust for parsing the shebang so this would require a change upstream there

**Comment by KoBruhh** [comment]
No, I don't use nvim-treesitter for highlighting. If you are interested, [here is my neovim config file](https://github.com/KoBruhh/nvim)

**Comment by KoBruhh** [comment]
> You have to define a `shebangs` key in your `languages.toml` for Rust, i.e.
> 
> https://github.com/helix-editor/helix/blob/9a651188998bbc1584519ebf658cb5c2c31f4b21/languages.toml#L616

This is my current Rust language section:
```toml
# Rust
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
shebangs = ["run-cargo-script"]
language-server = { command = "rust-analyzer" }
formatter = { command = "rustfmt" }
indent = { tab-width = 2, unit = "  " }
```
I wonder does it serve a purpose as an auto shebang generator? (Or even is there any)
