### ISSUE TITLE
Soft-wrap enable toggle does not work.

### ISSUE THREAD

**Issue by gibbz00** [helix-editor/helix#6605]
### Summary

`:toggle-option softwrap-enable` returns "Key `soft-wrap.enable` is not toggle-able" when soft-wrap is not set to true before. Works after a `:set-option softwrap-enable true`.

### Platform

Linux

### Terminal Emulator

foot

### Helix Version

23.03-16-g2bdb58fb

**Comment by gibbz00** [comment]
Hmm okay, what was the reasoning behind wrapping it in an Option?

**Comment by webdev23** [comment]
As shown in https://helix-editor.com/news/release-23-03-highlights , since v23.03
, the commands to toggle text wrapping from Helix, are:
```
:set soft-wrap.enable true
:set soft-wrap.enable false
```
Setting a default value in the config.toml seems to be mandatory:

```
[editor.soft-wrap]
enable = true
```

**Comment by Rudxain** [comment]
> [!note]
> Self-hiding as dupe of #12594

Same issue here, commit 2ec59f8ff6d43f5ac72e745ec614c26de192aedd. I could repro with markdown files, because of my `languages.toml`:
```toml
# (snip)
[[language]]
name = "markdown"
soft-wrap.enable = true
# (snip)
```

After commenting the relevant line, I can toggle it freely.

`editor.soft-wrap.enable` has no effect. Presence or absence of `.editorconfig` has no effect

**Comment by bcspragu** [comment]
This is still the case on a fairly recent build (`helix 25.07.1 (e1fd2e34)`). E.g. if my `languages.toml` contains:

```toml
[[language]]
name = "markdown"
text-width = 80
soft-wrap = { enable = true, wrap-at-text-width = true }
```

Then doing `:set soft-wrap.enable false` and `:set soft-wrap.wrap-at-text-width false` have no effect on Markdown files. Commenting out the `soft-wrap = { ... }` line makes it so I can toggle things as expected. I think the bug is that the expectation is that `:set ...` always overrides whatever is in the config for the running Helix instance it is applied in.
