### ISSUE TITLE
Helix doesn't have autocomplete support for locally imported packages in a cargo project

### ISSUE THREAD

**Issue by thatsbrandon** [helix-editor/helix#6654]
While trying to install a local package into another executable I noticed that autocomplete doesn't work for the imported local package. The following is the import process.

```toml
[dependencies]
kvm_rs = { path = "../../kvm_rs" }
# Other deps...
```

```rs
use kvm_rs::Providers; // <----- No autocomplete while using this
```

Of course other added dependencies work with autocomplete but so far any locally installed ones don't, can anyone suggest a workaround?
