### ISSUE TITLE
Bar cursor disappears in front of space/newline with cursorline enabled and nightfox theme

### ISSUE THREAD

**Issue by ToppDev** [helix-editor/helix#6658]
### Summary

When moving the cursor in front of a space or at the end of the line, it disappears when the nightfox theme is selected and the cursorline is enabled.

![helix-bar-cursor-nightfox-cursorline](https://user-images.githubusercontent.com/17766093/230723090-8243de81-c70a-4249-a44f-2ce066b018d3.gif)

### Reproduction Steps

1. Settings:
    ```toml
    theme = "nightfox"
    [editor]
    cursorline = true
    [editor.cursor-shape]
    insert = "bar"
    ```
1. Move the cursor in insert mode to a space or at the end of the line.

I expected this to happen: Cursor staying visible.

Instead, this happened: Cursor vanished.

### Helix log

Nothing relevant in the log.

### Platform

Linux

### Terminal Emulator

st

### Helix Version

helix 23.03
