### ISSUE TITLE
Is there any plan to support typst?

### ISSUE THREAD

**Issue by Qinka** [helix-editor/helix#6688]
Is there any plan to support [typst](https://github.com/typst/typst) ?

**Comment by kirawi** [comment]
https://github.com/typst/typst/issues/118

**Comment by KMikeeU** [comment]
Looks like typst doesn't have a proper tree-sitter grammar yet, we'll have to wait on that

**Comment by kirawi** [comment]
It does seem to have two:
https://github.com/frozolotl/tree-sitter-typst
https://github.com/SeniorMars/tree-sitter-typst

**Comment by ElDifinitivo** [comment]
I've just started testing out typst for personal use, and although it's new, [nvarner/typst-lsp](https://github.com/nvarner/typst-lsp) seems to work well with `language-server = { command = "typst-lsp" }` as the config.

**Comment by ElDifinitivo** [comment]
> could you share the specific part of your `language.toml` that configures typist? I cannot get it to work, the LSP wont start, though it is on path.

@nluetts here's what I have:

```toml
[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typst"
roots = []
comment-token = "//"
file-types = ["typ"]
indent = { tab-width = 2, unit = " " }
language-server = { command = "typst-lsp" }
text-width = 100
rulers = [100]
soft-wrap.wrap-at-text-width = true
```

I've also tried the two grammars posted above. I can't get SeniorMars' to work, but frozolotl's does although it's very limited at the moment.

```toml
[[grammar]]
name = "typst"
source = { path = "/path/to/git-clone/tree-sitter-typst" }
```
