### ISSUE TITLE
The Ins key should switch to insert mode

### ISSUE THREAD

**Issue by vp2177** [helix-editor/helix#6740]
In normal mode, pressing the <kbd>Ins</kbd> key, I would expect it to change to insert mode. Exactly like pressing `i`.  
In turn, when pressed while in insert mode, it could perhaps switch back to normal mode?

**Comment by the-mikedavis** [comment]
You can map this for yourself in config:

```toml
# ~/.config/helix/config.toml
[keys.normal]
ins = "insert_mode"

[keys.insert]
ins = "normal_mode"
```
