### ISSUE TITLE
Add syntax highlighting for asciidoc

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#6781]
Hi.
It would be nice to add syntax highlighting for asciidoc(tor).
Thanks.

**Comment by kirawi** [comment]
There doesn't appear to be a tree-sitter parser yet.

**Comment by mth** [comment]
Now there seems to be one: https://github.com/cathaysia/tree-sitter-asciidoc

**Comment by mixolydianmel** [comment]
> However, I couldn't build the grammar with Helix.

I also experienced this issue. The problem seems to be that the repo for the grammar has two subdirectories in it: `tree-sitter-asciidoc` and `tree-sitter-asciidoc_inline`. Assuming `tree-sitter-asciidoc` is the one we want, I changed my config to this (the language section is the same as @sudomateo's):
```toml
[[language]]
name = "asciidoc"
language-id = "asciidoc"
scope = "source.adoc"
injection-regex = "adoc"
file-types = ["adoc"]
comment-tokens = ["//"]
block-comment-tokens = [{ start = "////", end = "////" }]
grammar = "asciidoc"

[[grammar]]
name = "asciidoc"
source = {
  git = "git@github.com:cathaysia/tree-sitter-asciidoc.git",
  rev = "a94558880d2d5d51659c1d9c2579f21af273cb3d",
  # From https://docs.helix-editor.com/languages.html#tree-sitter-grammar-configuration
  subpath  =  "tree-sitter-asciidoc"
}
```
After this, it just uses `gcc` for compilation, so no need to install `pnpm` with this approach. Now, I get this when building:
```
Building 220 grammars
219 grammars already built
1 grammars built now
	["asciidoc"]
```
...and a new `asciidoc.so` file shows up in `runtime/grammars`. The only remaining problem is that it doesn't actually seem to work properly for some reason 😭. I'm thinking this might be because I'm on NixOS, which doesn't like dynamically linked things, though then I'm not sure how all the other grammars got built properly 🙁

I'd be interested to see if this setup works for other folks, or if there's some more things to be ironed out in this approach.
