### ISSUE TITLE
`hx --health` has strange result for Javascript in DAP

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#6784]
### Summary

When running `hx --health` the output is:
```              
go                 ✘ gopls            ✘ dlv              ✓                  ✓                  ✓                  
godot-resource     None               None               ✓                  ✘                  ✘                  
...  (removed for brevity)     
java               ✘ jdtls            None               ✓                  ✓                  ✘                  
javascript         ✘ typescript-la…   ✘                  ✓                  ✓                  ✓                            
```
Where in the `DAP` column javscript has an `✘` without any name. This would be quite confusing for users as it's unclear whether there is no configured `DAP` (`None`), or there is one configured but its not found (ie `✘ dlv`)

This is because `languages.toml` doesn't specify a command for javascript, leaving it to user configuration:
```toml
[language.debugger]
name = "node-debug2"
transport = "stdio"
# args consisting of cmd (node) and path to adapter should be added to user's configuration
quirks = { absolute-paths = true }
```

### Reproduction Steps

 

I tried this:

1. `hx --health javascript`

### Platform

Linux

### Terminal Emulator

Gnome console

### Helix Version

helix 23.03
