### ISSUE TITLE
Goto reference include declaration customization

### ISSUE THREAD

**Issue by mcdoker18** [helix-editor/helix#6885]
The goto references action always returns declarations in the helix. LSP specification has [includeDeclaration option](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_references).

Allow to customize the option, for example:
```toml
[[editor.lsp]]
goto_reference_include_declaration = true
```
