### ISSUE TITLE
Add new keys for diferent styling of "ui.statusline.separator" depending on editor mode

### ISSUE THREAD

**Issue by 0rphee** [helix-editor/helix#6936]
It'd be great to have more options for styling "ui.statusline.separator", like there are for the editor mode indicator in order to prevent stuff like this:

<img width="1436" alt="ss" src="https://user-images.githubusercontent.com/79347623/235553965-60e9555c-38df-41f6-b5e2-0750cc24d56c.png">

There already exists:
```toml
"ui.statusline" = {}
"ui.statusline.normal" = {}
"ui.statusline.insert" = {}
"ui.statusline.select" = {}
"ui.statusline.inactive" = {}
```
I propose to add
```toml
"ui.statusline.separator" = {} # already exists
"ui.statusline.separator.normal" = {}
"ui.statusline.separator.insert" = {}
"ui.statusline.separator.select" = {}
"ui.statusline.separator.inactive" = {}
```
Probably related to: #5022 &  #5722
