### ISSUE TITLE
Transparent background (bg = "reset") cause cursor invisible

### ISSUE THREAD

**Issue by codehz** [helix-editor/helix#697]
### Reproduction steps

 
use this theme (modified from dark_plus, just for demo)
```toml
# Author: Shafkath Shuhan <shafkathshuhannyc@gmail.com>

"namespace" = { fg = "type" }
"module" = { fg = "type" }

"type" = { fg = "type" }
"type.builtin" = { fg = "type" }
"type.enum.variant" = { fg = "constant" } 
"constructor" = { fg = "constant" }
"property" = { fg = "variable" }

"keyword" = { fg = "keyword" }
"keyword.directive" = { fg = "keyword" }
"keyword.control" = { fg = "special" }
"label" = { fg = "keyword" }

"special" = { fg = "text" }
"operator" = { fg = "text" }

"punctuation" = { fg = "text" }
"punctuation.delimiter" = { fg = "text" }

"variable" = { fg = "variable" }
"variable.parameter" = { fg = "variable" }
"variable.builtin" = { fg = "keyword" }
"constant" = { fg = "constant" }
"constant.builtin" = { fg = "keyword" }

"function" = { fg = "fn_declaration" }
"function.builtin" = { fg = "fn_declaration" }
"function.macro" = { fg = "keyword" }
"attribute" = { fg = "fn_declaration" }

"comment" = { fg = "#6A9955" }

"string" = { fg = "#ce9178" }
"number" = { fg = "#b5cea8" }
"escape" = { fg = "#d7ba7d" }

"ui.background" = { fg = "text", bg = "background" }

"ui.window" = { bg = "widget" }
"ui.popup" = { bg = "widget" }
"ui.help" = { bg = "widget" }
"ui.menu.selected" = { bg = "widget" }

"ui.cursor" = { fg = "red", bg = "white" }
"ui.cursor.primary" = { fg = "cursor", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "#3a3d41", modifiers = ["underlined"] }

"ui.selection" = { bg = "#3a3d41" }
"ui.selection.primary" = { bg = "#264f78" }

"ui.linenr" = { fg = "#858585" }
"ui.linenr.selected" = { fg = "#c6c6c6" }

"ui.statusline" = { fg = "#ffffff", bg = "#007acc" }
"ui.statusline.inactive" = { fg = "#ffffff", bg = "#007acc" }

"ui.text" = { fg = "text", bg = "background" }
"ui.text.focus" = { fg = "#ffffff" }

"warning" = { fg = "#cca700" }
"error" = { fg = "#f48771" }
"info" = { fg = "#75beff" }
"hint" = { fg = "#eeeeeeb3" }

diagnostic = { modifiers = ["underlined"] }

[palette]
type = "#4EC9B0"
keyword = "#569CD6"
regex = "#CE9178"
special = "#C586C0"
variable = "#9CDCFE"
fn_declaration = "#DCDCAA"
constant = "#4FC1FF"

background = "reset"
text = "#d4d4d4"
cursor = "#a6a6a6"
widget = "#252526"

```
![image](https://user-images.githubusercontent.com/13158903/131832888-bc82e4f6-0d1f-4f22-801f-bfa1d851c904.png)

### Environment

- Platform: linux / windows
- Helix version: v0.4.1

(no need for log, since it didn't crash)
