### ISSUE TITLE
pyright config error in latest version => helix 23.05 (7f5940be)

### ISSUE THREAD

**Issue by lost22git** [helix-editor/helix#7086]
pyright config from wiki

![Screenshot 2023-05-20 at 11-08-36 How to install the default language servers · helix-editor_helix Wiki](https://github.com/helix-editor/helix/assets/65008815/4569a23b-d24a-4a72-8529-d685d5c3dd8e)

error message when helix start

Bad language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`

**Comment by lost22git** [comment]
resolve it with below config

```toml
[language-server.pyright-langserver]
command  = "pyright-langserver"
args = ["--stdio"] 
[language-server.pyright-langserver.config]
```
