### ISSUE TITLE
Issue with language settings

### ISSUE THREAD

**Issue by bq-wrongway** [helix-editor/helix#7099]
After update from 23.03 to 23.05, i get always warning when trying to run helix :

```
Error parsing user language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`

Using default language config
Configured language server: rust-analyzer
Binary for language server: /usr/local/bin/rust-analyzer
Configured debug adapter: lldb-vscode
Binary for debug adapter: 'lldb-vscode' not found in $PATH
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```
And here is language. toml file settings 
https://pastebin.com/bx592Ugk

**Comment by gabydd** [comment]
Looks like you are running from master, https://github.com/helix-editor/helix/pull/2507 was recently merged which changes language server config to be per language server instead of per language, so you would need something like:

```toml
[language-server.rust-analyzer]
config = {}
```
See https://docs.helix-editor.com/master/languages.html#language-server-configuration

**Comment by bq-wrongway** [comment]
I managed to get most of it working , but i dont know how (or where to add) 

[language.config.check]
command = "clippy"

when i enable this it complains right away
here is new pastebin link https://pastebin.com/wqCQLAy9

**Comment by gabydd** [comment]
It should be 
```toml
[language-server.rust-analyzer.config.check]
command = "clippy"
```

**Comment by chkilel** [comment]
Hello, I need some help please 🙏🏻.
I'm running master to try out multiple language servers, I converted the config that I had for `Vue - Volar` to the new one format but I didn't manage to make it work, here are my old and new `languages.toml` configuration:

- Old
```toml
[[language]]
name = "vue"
file-types = ["vue"]
language-server = { command = "vue-language-server", args = ["--stdio"] }
scope = "text.html.vue"
roots = ["package.json"]
injection-regex = "vue"
auto-format = true

[language.config.typescript]
tsdk = "/opt/homebrew/lib/node_modules/typescript/lib"

[language.config.languageFeatures]
semanticTokens = true
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
completion = { defaultTagNameCase = 'both', defaultAttrNameCase = 'kebabCase' }
schemaRequestService = true
documentHighlight = true
documentLink = true
codeLens = true
diagnostics = true

[language.config.documentFeatures]
documentColor = false
selectionRange = true
foldingRange = true
linkedEditingRange = true
documentSymbol = true
documentFormatting = { defaultPrintWidth = 100 }
```

- New

``` toml
[[language]]
name = "vue"
scope = "text.html.vue"
injection-regex = "vue"
file-types = ["vue"]
auto-format = true
roots = ["package.json"]
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["vue-language-server"]

# Language Server configuration
[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]

[language-server.vue-language-server.config]
typescript = { tsdk = "/opt/homebrew/lib/node_modules/typescript/lib" }

[language-server.vue-language-server.config.languageFeatures]
semanticTokens = true
references = true
definition = true
typeDefinition = true
callHierarchy = true
hover = true
rename = true
renameFileRefactoring = true
signatureHelp = true
codeAction = true
completion = { defaultTagNameCase = 'both', defaultAttrNameCase = 'kebabCase' }
schemaRequestService = true
documentHighlight = true
documentLink = true
codeLens = true
diagnostics = true

[language-server.vue-language-server.config.documentFeatures]
documentColor = false
selectionRange = true
foldingRange = true
linkedEditingRange = true
documentSymbol = true
documentFormatting = { defaultPrintWidth = 100 }
```
I appreciate your help.
