### ISSUE TITLE
Helix doesn't respect the custom lsp settings

### ISSUE THREAD

**Issue by mycraftmw** [helix-editor/helix#7134]
### Summary

I have put some custom settings for rust-analyzer in `language.toml`, but it seems that Helix doesn't use it.
The custom settings are shown as below:
```toml
[language-server.rust-analyzer.config]
procMacro.enable = true
procMacro.attributes.enable = true
check.overrideCommand = [
    "cargo",
    "xtask",
    "check",
    "--json-output",
    "-p",
    "beast",
]
cargo.buildScripts.enable = true
cargo.buildScripts.overrideCommand = [
    "cargo",
    "xtask",
    "check",
    "--json-output",
    "-p",
    "beast",
]
completion.autoimport.enable = true


[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-server = { command = "rust-analyzer" }
```

But when I started Helix with `-vvvv` and what I found in the log is that:
```
2023-05-25T11:34:52.899 helix_lsp::client [INFO] Using custom LSP config: {"inlayHints":{"bindingModeHints":{"enable":false},"closingBraceHints":{"minLines":10},"closureReturnTypeHints":{"enable":"with_block"},"discriminantHints":{"enable":"fieldless"},"lifetimeElisionHints":{"enable":"skip_trivial"},"typeHints":{"hideClosureInitialization":false}}}
```
Those are, I believe, the default settings.
I looked around the code to find this specific log. However I'm not familiar with the codebase. So I apologize if I get this wrong.

### Reproduction Steps

 

I tried this:

1. add the specific settings to `language.toml`
2. run `helix -vvvv --log this_time.log the_rust_project`

I expected this to happen:
Check the `this_time.log`, there should be some text like `Using custom LSP config` and `"[ERROR rust_analyzer::lsp_utils] failed to run build scripts\n"`

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-05-25T11:34:52.899 helix_lsp::client [INFO] Using custom LSP config: {"inlayHints":{"bindingModeHints":{"enable":false},"closingBraceHints":{"minLines":10},"closureReturnTypeHints":{"enable":"with_block"},"discriminantHints":{"enable":"fieldless"},"lifetimeElisionHints":{"enable":"skip_trivial"},"typeHints":{"hideClosureInitialization":false}}}
2023-05-25T11:34:57.318 helix_lsp::transport [ERROR] err <- "[ERROR rust_analyzer::lsp_utils] failed to run build scripts\n"
```

</details>

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

helix 23.05

**Comment by gabydd** [comment]
Looks like you are using the release version of helix so config should be a table under [[language]]

So it should look something like this
```toml
[[language]]
name = "rust"
...
[language.config]
procMacro.enable = true
...
```
