### ISSUE TITLE
Config is not passed to the LSP with the new multi LSP support

### ISSUE THREAD

**Issue by Marsevil** [helix-editor/helix#7149]
I'm trying to make the new multi LSP support works with `ltex-ls` and `texlab`.
My problem is that `ltex-ls` do not use the `en-GB` and do not use my custom dictionary. I guess that the config is not passed to the language server.

Here is my config file.

```toml
[[language]]
name = "latex"
language-servers = [ "ltex-ls-custom" ,"texlab" ]
file-types = ["tex"]
scope = "source.tex"
roots = []

[language-server.ltex-ls-custom]
command = "ltex-ls"
args = ["--log-file=/tmp"]
config = { language = "en-GB", dictionary = { "en-GB" = ["somecustomwords"] } }

[language-server.texlab]
command = "texlab"
```

Did I miss something or is it a bug ??

> **Note** : On the last release `ltex-ls` works as expected.
> I renamed the LSP `ls-ltex-custom` because I already have a default configuration and I would like to be sure that is not a conflict.

**Comment by gabydd** [comment]
Can you try putting all the language-server stuff above ``[[language]]`` that seems to have worked for other people

**Comment by Marsevil** [comment]
I'd already tried but, in doubt, I double checked and it does not work

**Comment by gabydd** [comment]
I got ltex to work with the configuration below, there are two important parts the first is all the regular tables ``[]`` have to go before the arrays of tables ``[[]]`` or else the language-servers wont get defined, The second part is ltex-ls takes the config as ``{ltex = {<actual settings>}`` so that needs to be specified for it use your settings. Checking the logs with: ``:log-open`` is very helpful for debugging something like this if you have issues in the future.

```toml
[language-server.ltex-ls-custom]
command = "ltex-ls"
args = ["--log-file=/tmp"]

[language-server.ltex-ls-custom.config.ltex]
language = "en-GB"
dictionary = { "en-GB" = ["somecustomwords"] } 

[language-server.texlab]
command = "texlab"

[[language]]
name = "latex"
language-servers = [ "ltex-ls-custom" ,"texlab" ]
file-types = ["tex"]
scope = "source.tex"
roots = []
```
