### ISSUE TITLE
Syntax highlighting should be available for general assembly files (`.S`)

### ISSUE THREAD

**Issue by caoimhebyrne** [helix-editor/helix#7243]
Right now, they look pretty ugly, just from a quick search on Google, I've found [tree-sitter-asm](https://github.com/rush-rs/tree-sitter-asm), which supports a generic asm syntax. I'm not sure if we can configure Helix to use it, but it would also be nice to have built-in support for this.

<img width="861" alt="image" src="https://github.com/helix-editor/helix/assets/71222289/b888e374-473e-4a61-9fe7-5799ece7ec7a">

**Comment by caoimhebyrne** [comment]
I tried using tree-sitter-asm myself, but it doesn't work.
```toml
[[language]]
name = "asm"
scope = "source.asm"
file-types = ["S", "s"]
roots = []
comment-token = "//"

[[grammar]]
name = "asm"
source = { git = "https://github.com/rush-rs/tree-sitter-asm", rev = "36dc26acc7818920de2e103e20a9f42358caf926" }
```

Also ran:
```bash
❯ hx --grammar fetch
Fetching 7 grammars
6 up to date git grammars
1 updated grammars
	asm now on 36dc26acc7818920de2e103e20a9f42358caf926

❯ hx --grammar build
Building 7 grammars
7 grammars built now
	["asm", "bash", "c", "cpp", "javascript", "tsx", "typescript"]
```
