### ISSUE TITLE
Ignore "Error: Timed out waiting for language servers to shutdown" for LTEX

### ISSUE THREAD

**Issue by getreu** [helix-editor/helix#7446]
I am using the language server _LTEX_ for grammar checking in Markdown files and git commit messages.

```toml
[[language]]
name = "markdown"
language-servers = [{ name = "ltex"}]
auto-format = false
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []

[[language]]
name = "git-commit"
language-servers = [{ name = "ltex"}]
auto-format = false
```

LTEX is a Java program that takes quite some time to start up. During this process it can not be shut down gracefully. When trying to do so, by quickly editing a commit message for example, Helix terminates with:

```
Error: Timed out waiting for language servers to shutdown
```

and come process error code. The later causes the commit to fail!

Maybe it is possible to add a config option in `languages.toml`, that instructs Helix to silently ignore timeouts when shutting down a certain language server?
