### ISSUE TITLE
Typescript: Preferred path style for auto imports

### ISSUE THREAD

**Issue by danriedl** [helix-editor/helix#7696]
Hi,

I'd like to ask for a feature where I don't know much about the technical burdens this would bring.
I'm working on a big Angular project where we decided to do [path aliases](https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353), to declutter our imports.

From this 
```typescript
import { ThemeService } from './services/theme.service';
```

To this
```typescript
import { ThemeService } from '@projectname/services';
```

This is achieved by setting up `tsconfig.json` like that:
```json
{
  "compilerOptions": {
    "paths": {
      "@projectname/services/*": [
        "./src/app/services/*"
      ]
    }
  }
}
```

So what I'd like to ask is, could we have something that the "auto-import" thing which is going on respects my `tsconfig.json` and suggests to use the path alias for importing instead of the filepath and filename like it is right now?

This works in VSCodium (VSCode) by setting `typescript.preferences.importModuleSpecifier` to `non-relative`.

I hope this is not too confusing, and would love to answer questions if there are some.

**Comment by gabydd** [comment]
That should be configured through the lsp config which on the latest release you can specify like this (you might also be able to specify this in a tsconfig.json):

```toml
[[language]]
name = "typescript"
[language.config.preferences]
importModuleSpecifier = "non-relative"
```

On master it would be
```toml
[language-server.typescript-language-server.config.preferences]
importModuleSpecifier = "non-relative"
```
