### ISSUE TITLE
rust go to definition not work

### ISSUE THREAD

**Issue by tkkcc** [helix-editor/helix#7705]
### Summary

writing rust code, `gd` always give `no definition`, also `gr`, `<space>k` not work. but inline errors hints works. rust-analyzer process does not quit.

i also try nvim, it works.

rust-analyzer --version
rust-analyzer 1.73.0-nightly (0308df2 2023-07-21)

rustc --version                                                                                                     
rustc 1.73.0-nightly (0308df23e 2023-07-21)

### Reproduction Steps

src/main.rs
```rust
fn main() {
    // let proxy = minreq::Proxy::new("localhost:1080").unwrap();
    let x = "main.rs";

    let response = minreq::get("http://example.com").send();
    println!("{response:?}");
    test(x, i);
}
fn test(s: &str, i: u8) {}

```

cargo.toml
```toml
[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minreq = { version = "2.8.0", features=  ["proxy"] }
```

~/.config/helix/config.toml
```toml
theme = "onelight"

[keys.normal]
#C-o = ":open ~/.config/helix/config.toml" # Maps the Control-o to opening of the helix config file
0 = "goto_line_start"
space = { i = ":format"}
"," = {w = ":write-all" ,  e = ":reload",r=":config-reload",q=":quit!"}

#[editor]
#idle-timeout =0


### Helix log

~/.cache/helix/helix.log

```
2023-07-22T16:26:36.565 helix_view::editor [ERROR] editor error: No definition found.
2023-07-22T16:26:38.836 helix_view::editor [ERROR] editor error: No definition found.
2023-07-22T16:26:39.511 helix_view::editor [ERROR] editor error: No definition found.
2023-07-22T16:26:55.583 helix_view::editor [ERROR] editor error: No definition found.

```

~/b/proxy helix --health rust
```
Configured language server: rust-analyzer
Binary for language server: /home/bilabila/.cargo/bin/rust-analyzer
Configured debug adapter: lldb-vscode
Binary for debug adapter: 'lldb-vscode' not found in $PATH
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

### Platform

linux

### Terminal Emulator

alacritty 0.12.2 (9d9982df)

### Helix Version

23.05
