### ISSUE TITLE
Add scdoc syntax highlight

### ISSUE THREAD

**Issue by kchibisov** [helix-editor/helix#7707]
This is widely used for man pages nowadays.

https://git.sr.ht/~sircmpwn/scdoc/

**Comment by markstos** [comment]
For someone interested in this, see the docs on adding a new language:

https://docs.helix-editor.com/guides/adding_languages.html

The primary thing to add would a new file at `runtime/queries/scdoc/highlights.scm`

See the Treesitter docs on defining new highlights:
https://tree-sitter.github.io/tree-sitter/syntax-highlighting#queries

For a formal definition of the SCDOC file format. you can see this:

https://man.archlinux.org/man/scdoc.5.en

For example from a similar file format, See how Markdown highlights are defined:

https://github.com/helix-editor/helix/blob/master/runtime/queries/markdown/highlights.scm

**Comment by rusty-snake** [comment]
As workaround until helix gets scdoc support, you can run ~`:languages-open`~ `:open ~/.config/helix/languages.toml` and add the following to get rid of the supercollider highlighting:

```toml
[[language]]
name = "scdoc"
scope = "text.scdoc"
# file-types = [".1.scd", ".2.scd", ".3.scd", ".4.scd", ".5.scd", ".6.scd", ".7.scd", ".8.scd", ".9.scd"]
file-types = ["scd"]
comment-token = "; "
indent = { tab-width = 4, unit = "\t" }
text-width = 80
```
