### ISSUE TITLE
How to add multiple formatters to languages.toml

### ISSUE THREAD

**Issue by AH-Merii** [helix-editor/helix#7748]
I am currently using `black` formatter to autoformat my python code on save. Is it possible to add `isort` as a formatter in order to format my imports?

Here is part of my `languages.toml` file:

```toml
[[language]]
name = "python"
rulers = [79,88]
auto-format = true
formatter = {command = "black", args = ["-",  "--quiet","--line-length=88",]}
```
