### ISSUE TITLE
SFZ Syntax Highlighting

### ISSUE THREAD

**Issue by deathchimera** [helix-editor/helix#7776]
SFZ is a file format for defining how a collection of audio samples are arranged for performance.

* Basic File Example:
https://sfzformat.com/tutorials/basic_sfz_file
* Implementations of Syntax Highlighting:
https://sfzformat.com/software/tools/#syntax-highlighting
(In depth documentation of the syntax found on main sites' top navigation bar)
* Surprisingly Healthy Usage of the Format:
https://github.com/orgs/sfzinstruments/repositories

Want to encourage support for the format. It's still actively used and what is made is quality. Currently throwing the idea into the air. Not sure how to go about implementing this, but if enough time lingers I'll probably try my hand.

**Comment by kanashimia** [comment]
I made an initial version of the grammar: https://github.com/kanashimia/tree-sitter-sfz

Language config:
```toml
[[language]]
name = "sfz"
scope = "source.sfz"
injection-regex = "sfz"
file-types = ["sfz"]
roots = []
comment-token = "//"

[[grammar]]
name = "sfz"
source = { git = "https://github.com/kanashimia/tree-sitter-sfz", rev = "9e9e9e588d95301e7f59ad9c44582fc052a25a06" }
```

Don't forget to copy queries manually for syntax highlighting.

Honestly that language is horrendous.
