### ISSUE TITLE
Dart lsp Server Configuration Bug or Help

### ISSUE THREAD

**Issue by nathananderson98** [helix-editor/helix#7968]
I'm trying to change the default dart lsp formatter line length from 80 (default) to 120.

Sources:
- Looking at the base language config [here](https://github.com/helix-editor/helix/blob/master/languages.toml)
- Looking at the Dart lsp documentation [here](https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server/tool/lsp_spec#client-workspace-configuration)https://docs.helix-editor.com/languages.html#language-configuration 
- And the helix documentation [here](https://docs.helix-editor.com/languages.html#language-configuration)

Would lead me to believe that I can change the default `dart.lineLength` for my formatter, but I have not been able to ge anything to work.

I know my `.config/helix/languages.toml` is working because I can change the autoformat option on and off. Any help on this? Is this possible?

My `languages.toml`:
```toml
[[language]]
name = "dart"
# formatter = { command = "format", args = [ "-l", "120"] }  # I tried changing the format command, didn't work either
config = { lineLength = 120 }
# I tried all of these, refreshing the config each time, to no avail.
# config = { dart.lineLength = 120 }
# config = { "dart.lineLength" = 120 }
# config = { dartls.settings.dart.lineLength = 120 }
# config = { dart = { lineLength = 120 } }
# config = { settings = { dart = { lineLength = 120 } } }
# config = { dartls = { settings = { dart = { lineLength = 120 } } } }
```
