### ISSUE TITLE
Statusline separator doesn't actually do anything

### ISSUE THREAD

**Issue by Connortsui20** [helix-editor/helix#8022]
### Summary

Title, no matter what I set the separator to, the statusline does not change.
```toml
[editor.statusline]
separator = "asdfasdfasdfasd\nasdfasdf\t\r" # or literally anything
```
I also don't see a `|` anywhere, which is supposedly the default?

From #6936 it seems like it works for other people?

### Reproduction Steps

Set the `editor.statusline.separator` to anything, nothing actually changes.

### Helix log

Nothing of importance

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 23.05 (e4c95f65)
