### ISSUE TITLE
nginx config syntax highlight support?

### ISSUE THREAD

**Issue by sgon00** [helix-editor/helix#8029]
Hi, I need to edit nginx config file a lot. Is that possible to enable nginx config syntax highlight? 
Thanks a lot.

Edited:
I try to replace `vim` with `helix`, but I find out helix is missing many file type support. It does not support many linux config file types, such as `nginx`, `systemd` etc..

**Comment by mahor1221** [comment]
I have the same problem. For a temporary fix, you can try adding this config to `~/.config/helix/languages.toml`:

```toml
# https://docs.helix-editor.com/languages.html

[[language]]
name = "ini"
file-types = [
  "conf",

  # from https://github.com/helix-editor/helix/blob/master/languages.toml
  "ini", "service", "automount", "device", "mount", "path", "service", "slice", "socket", "swap", "target", "timer", "container", "volume", "kube", "network",
]

[[language]]
name = "bash"
file-types = [
  "nginx.conf",

  # from https://github.com/helix-editor/helix/blob/master/languages.toml
  "sh", "bash", "zsh", ".bash_login", ".bash_logout", ".bash_profile", ".bashrc", ".profile", ".zshenv", "zshenv", ".zlogin", "zlogin", ".zlogout", "zlogout", ".zprofile", "zprofile", ".zshrc", "zshrc", ".zimrc", "APKBUILD", "PKGBUILD", "eclass", "ebuild", "bazelrc", ".bash_aliases", "Renviron", ".Renviron",
]
```

The first section will use `ini` syntax highlighting for files with `.conf` extension,
and the next one will use `bash` for `nginx.conf`. 
You can also use `toml` or `ini` for Systemd services.

This is not ideal but it does the job for me.
