### ISSUE TITLE
A command to discard autocompletion

### ISSUE THREAD

**Issue by MaxVerevkin** [helix-editor/helix#8132]
Sometimes I start going though the completion list using tab and then realize that I want to to go back and just continue from the state before I started tab-ing. I tried

```toml
[keys.insert]
C-x = ["normal_mode", "undo", "insert_mode"]
``` 

which didn't work (#8131). But even if it worked, I think a dedicated command would be better.
