### ISSUE TITLE
Picker (nucleo) searches highest git repository instead of current directory on second open

### ISSUE THREAD

**Issue by Connortsui20** [helix-editor/helix#8183]
### Summary

When I run `hx .` inside a directory, the file picker opens with everything inside of the directory.

However, when I open it again for the second time, it opens in whatever repository I am working in.

Here are my file picker settings:
```toml
[editor.file-picker]
hidden = false
git-ignore = false # Want to still see files that are not being tracked
max-depth = 6
```
It may have to do with the fact that I have `git-ignore` set to false

### Reproduction Steps

Suppose we are in this repository:

```sh
$ cd <...>/helix
$ cd runtime/
$ hx .
```

On running `hx .`, the file picker opens the `runtime` directory, and 6645 files show up.

Close the the file picker and then reopen, 13256 files now show up.

### Helix log

No logs are emitted from the above steps

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 23.05 (e4c95f65)
