### ISSUE TITLE
Select mode does not work properly with remapped movement keys

### ISSUE THREAD

**Issue by kmicklas** [helix-editor/helix#8186]
### Summary

With a config like this:
```toml
[keys.normal]
o = "move_next_word_start"

[keys.select]
o = "move_next_word_start"
```

Pressing `v o o o ...` enters selection mode and moves the cursor by word, but the selection does not stay "anchored" at the start point as it does if you use a default motion key (e.g. `v w w w ...`).

### Helix log

There is no relevant information in `~/.cache/helix/helix.log`.

### Platform

Linux

### Terminal Emulator

alacritty 0.12.0

### Helix Version

helix 23.05
