### ISSUE TITLE
Soft wrap jump to relative line numbers.

### ISSUE THREAD

**Issue by hakan-demirli** [helix-editor/helix#8202]
### Summary

In normal mode when I type `2j` I expect it to move to the line that has a relative position of 2 (bbb...). But instead it goes to the line that has soft-wrap of 1st line (aaa...).

![image](https://github.com/helix-editor/helix/assets/78746991/55fd3758-7a59-479d-8c81-98aa24e08931)

### Reproduction Steps

```toml
[editor]
line-number = "relative"
mouse = false
bufferline = "always"
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true
```

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

23.05
