### ISSUE TITLE
Make ui.cursor.primary bg override ui.virtual.ruler bg so the cursor doesn't "disappear"

### ISSUE THREAD

**Issue by qtfkwk** [helix-editor/helix#8274]
`~/.config/helix/runtime/themes/mine.toml`:

```toml
inherits = "onedarker"

"ui.cursor.primary" = { fg = "#ffffff", bg = "#ff00ff" }
```

`~/.config/helix/config.toml`:

```toml
theme = "mine"

[editor]
# ...
rulers = [81, 101]
# ...
```

You see the cursor on column 80:

![Screenshot from 2023-09-13 14-58-16](https://github.com/helix-editor/helix/assets/6049908/b42aa766-fa70-4eef-9684-7b6ec9a28220)

The cursor "disappears" on column 81:

![Screenshot from 2023-09-13 14-58-37](https://github.com/helix-editor/helix/assets/6049908/b6f43393-77e4-4e21-a026-59b32531372e)

Unsure if this is a theme issue or something else. Different themes react differently, but setting a custom cursor color is consistently overridden instead of overriding.
