### ISSUE TITLE
Add Esbonio support

### ISSUE THREAD

**Issue by pzzxqj** [helix-editor/helix#8299]
I've tried use [Esbonio](https://docs.esbon.io/en/latest/index.html#) with helix, but it doesn't work,  
```toml
[language-server.esbonio]
command = "python3"
args = ["-m", "esbonio"]

[[language]]
name = "restructuretext"
scope = "source.rst"
file-type = ["rst"]
language-servers = [ "esbonio" ] 
indent = { tab-width = 3, unit = "   "}
```

Hope for official support.
Thanks.
