### ISSUE TITLE
inlayHints configuration options for rust are ignored.

### ISSUE THREAD

**Issue by adsnaider** [helix-editor/helix#8318]
### Summary

For instance, I have this configuration in my languages.toml

```toml
[[language]]
name = "rust"

[config]
inlayHints.chainingHints.enable = false
inlayHints.closingBraceHints.enable = false
```

However, when I open helix on my rust project, I still see both `closingBraceHints` and `chainingHints`.

### Reproduction Steps

Set the above configuration in languages.toml, and open a rust project.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-09-17T18:37:14.142 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"inlayHints":{"bindingModeHints":{"enable":false},"closingBraceHints":{"minLines":10},"closureReturnTypeHints":{"enable":"with_block"},"discriminantHints":{"enable":"fieldless"},"lifetimeElisionHints":{"enable":"skip_trivial"},"typeHints":{"hideClosureInitialization":false}}}}}
```

</details>

### Platform

Linux

### Terminal Emulator

gnome-term

### Helix Version

helix 23.05
