### ISSUE TITLE
Language servers fail if one is missing

### ISSUE THREAD

**Issue by QaidVoid** [helix-editor/helix#8361]
### Summary

If one of the language server from `language-servers` list is missing, none of the language servers work.

### Reproduction Steps

Configure multiple language servers

<details>
<summary>~/.config/helix/languages.toml</summary>

```toml
[[language]]
name = "jsx"
auto-format = true
language-servers = ["typescript-language-server", "biome", "emmet"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.jsx"]}
```
</details>

Expected behavior:
The existing language server should work even if other language servers are missing.

What happened:
The language server process is spawned but it doesn't work.

### Platform

Linux

### Terminal Emulator

foot version: 1.15.3

### Helix Version

helix 23.05 (1c88432e)
