### ISSUE TITLE
rust-analyzer: code is inactive due to #[cfg] directives: test is disabled (inactive-code)

### ISSUE THREAD

**Issue by cyanic-selkie** [helix-editor/helix#8373]
Hi,

When using `rust-analyzer` as Rust's LSP, I keep getting this warning for all `#[cfg(test)]` code. From what I understand, `rust-analyzer` is supposed to include the `test` feature by default.

My language configuration for Rust is:

```toml
[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "clippy" } 
```

I tried setting `allTargets` to true (which should be true by default anyway) and features to `all`, however it doesn't work. Any help is appreciated.

My helix version is 23.05.
