### ISSUE TITLE
C auto-indent has do not respect tab width. 

### ISSUE THREAD

**Issue by hakan-demirli** [helix-editor/helix#8424]
### Summary

Minimal reproducable example for https://github.com/helix-editor/helix/issues/4556 since the issue is not fixed.

Indentation is fixed to 2 spaces even though it is specified as 4.

### Reproduction Steps

languages.toml
```toml
[[language]]
name = "cpp"
# config = { "clangd.fallbackFlags" = ["-std=c++20"] }
language-server = { command = "clangd", args = [
  "--compile-commands-dir=./build",
] }
auto-format = true
indent = { tab-width = 4, unit = "    " }
```

main.cpp:
```cpp
#include <iostream>

int main(int argc, char *argv[]) {
  std::cout << "test";
  return 0;
}
```

clang version 16.0.6
helix version 

### Platform

Arch Linux

### Terminal Emulator

kitty 0.29.2

### Helix Version

helix 23.05
