### ISSUE TITLE
Can’t start LSP clients installed with nix

### ISSUE THREAD

**Issue by zoedsoupe** [helix-editor/helix#8455]
### Summary

Trying to set up helix with Home Manager and setting LSP clients commands up with isolated binaries (they aren’t available on `$PATH` directly), makes helix unavailable to find those executables. May I setting it up in a wrong way?

### Reproduction Steps

 

I tried this:

1. Set up Helix with Home Manager, as:
```nix
{
  pkgs,
  lib,
  custom-config,
  ...
}: let
  inherit (lib) mkEnableOption mkOption mkIf types;
  cfg = custom-config.helix;
in {
  options.helix = {
    enable = mkEnableOption "Enbales Helix Editor";
  };

  config = mkIf cfg.enable {
    programs.helix = {
      inherit (cfg) enable;
      settings = {
        theme = "catppuccin_latte";
        editor = {
          line-number = "relative";
          lsp.display-messages = true;
        };
        keys.normal = {
          esc = ["collapse_selection" "keep_primary_selection"];
        };
      };
      languages = {
        language-server = let
          erl = pkgs.beam.interpreters.erlang_25.overrideAttrs (old: {
            configureFlags = ["--disable-jit"] ++ old.configureFlags;
          });
          beam = pkgs.beam.packagesWith erl;
          vscode-lsp = pkgs.nodePackages.vscode-langservers-extracted;
        in {
          elixir-ls.command = "${beam.elixir-ls}/bin/elixir-ls";
          nil.command = "${pkgs.nil}/bin/nil";
          clojure-lsp.command = "${pkgs.clojure-lsp}/bin/clojure-lsp";

          vscode-html-language-server = {
            command = "${vscode-lsp}/bin/vscode-html-language-server";
            args = ["--stdio"];
          };
          vscode-css-language-server = {
            command = "${vscode-lsp}/bin/vscode-css-language-server";
            args = ["--stdio"];
          };
          vscode-json-language-server = {
            command = "${vscode-lsp}/bin/vscode-json-language-server";
            args = ["--stdio"];
          };
        };
      };
    };
  };
}
```

2. Build the configuration, which results in
```toml
[language-server]
[language-server.clojure-lsp]
command = "/nix/store/11xlc87rjqncr22hi03vifx86xv8pbi2-clojure-lsp-2023.05.04-19.38.01/bin/clojure-lsp"

[language-server.elixir-ls]
command = "/nix/store/bfcgy3kj2cj0pjm2vij9js3a1n319ayi-elixir-ls-0.14.6/bin/elixir-ls"

[language-server.nil]
command = "/nix/store/gx7dnibh4m07vywi77pbm1r1sv7zys5c-nil-2023-05-09/bin/nil"

[language-server.vscode-css-language-server]
args = ["--stdio"]
command = "/nix/store/aql6hz4y7z7czsmiff5gqfw074jdkc2w-vscode-langservers-extracted-4.7.0/bin/vscode-css-language-server"

[language-server.vscode-html-language-server]
args = ["--stdio"]
command = "/nix/store/aql6hz4y7z7czsmiff5gqfw074jdkc2w-vscode-langservers-extracted-4.7.0/bin/vscode-html-language-server"

[language-server.vscode-json-language-server]
args = ["--stdio"]
command = "/nix/store/aql6hz4y7z7czsmiff5gqfw074jdkc2w-vscode-langservers-extracted-4.7.0/bin/vscode-json-language-server"
```

I expected this to happen (had installed elixir-ls globally on my system):

https://github.com/helix-editor/helix/assets/44469426/5b1ad4b0-fe29-46d8-b66d-c00a29c4ef82

Instead, this happened:

https://github.com/helix-editor/helix/assets/44469426/618d5e67-3eaf-4513-9247-05387356ab2d

### Helix log

If I install `elixir-ls` (or any other LSP client) globally on my system, executing `hx —health elixir` results in:
```sh
$ hx --health elixir

Configured language server: elixir-ls
Binary for language server: /etc/profiles/per-user/zoedsoupe/bin/elixir-ls
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

Trying to configure with Home Manager and isolate LSP clients binaries I got:
```sh
$ hx --health elixir

Configured language server: elixir-ls
Binary for language server: 'elixir-ls' not found in $PATH
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

### Platform

macOS

### Terminal Emulator

Warp

### Helix Version

helix 23.05
