### ISSUE TITLE
Movement keys do not extend selection after remapping

### ISSUE THREAD

**Issue by danielkarch** [helix-editor/helix#8459]
### Summary

I am using the Colemak keyboard layout and want to remap the movement keys from `hjkl` to `jkhl`. My `config.toml` looks as follows:
```toml
[keys.normal]
j = "move_char_left"
l = "move_char_right"
h = "move_visual_line_up"
k = "move_visual_line_down"

[keys.select]
j = "move_char_left"
l = "move_char_right"
h = "move_visual_line_up"
k = "move_visual_line_down"
```

This works as expected in normal mode, but in select mode the movement keys only move the cursor without extending the selection. When I use the cursor keys to move the cursor, the selection is extended as expected. When something is selected and I press e.g. `k` to move to the next line, the cursor moves but the text is deselected. The editor stays in select mode though.

### Reproduction Steps

 

I tried this:

1. created the `config.toml` file shown above.
2. started `hx --tutor`
3. pressed `vk` 

I expected this to happen:

The current line should be selected and the cursor should move to the next line.

Instead, this happened:

The cursor moved to the next line without selecting anything.

### Helix log

nothing in the logs

### Platform

Linux

### Terminal Emulator

# GNOME Terminal 3.48.1 using VTE 0.72.2 +BIDI +GNUTLS +ICU +SYSTEMD

### Helix Version

helix 23.05
