### ISSUE TITLE
Documentation / support for configuring for use with Nixd?

### ISSUE THREAD

**Issue by alxpettit** [helix-editor/helix#8472]
Nixd has a number of advantages over the alternative LSPs, like `nil` including the fact that it compiles against the same code as the interpreter, and can analyze the entire nix codebase instead of just the current file.

However, when I add this to my languages.toml:
```toml
[[language]]
name = "nix"
language-servers = [ "nixd" ]
```

It fails silently, and `hx --health` shows `None` in the `nix` column. Note that I am currently on Helix 23.05.
