### ISSUE TITLE
keymap setting for command crashes hx

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#850]
config.toml:
```toml
[keys.command]
t={n="normal_mode"}
```
crashes, whereas insert works correctly:
```toml
[keys.insert]
t={n="normal_mode"}
