### ISSUE TITLE
LSP diagnostic are highlighted, even when disabled

### ISSUE THREAD

**Issue by yo-main** [helix-editor/helix#8550]
### Summary

I use multiple lsp and I disable `diagnostics` feature for one of them.  It hides the diagnotic message from that lsp as expected, however I still see the highlight in the editor.

Exemple:
![image](https://github.com/helix-editor/helix/assets/40139584/3cf3f974-b853-4ef4-bc94-622a965b98cd)

### Reproduction Steps

I guess you could reproduce it with any other language as long as you have are able to show some diagnostic messages and disable the `diagnostics` feature of your lsp.

I'm using python so I can reproduce that using a properly configured python env. 

This is my `language.toml` configuration:
```toml
[language-server.pylsp]
command = "pylsp"

[language-server.pylsp]
command = "pylsp"

[[language]]
name = "python"
language-servers = [{ name = "pylsp", except-features = [ "diagnostics" ]}]
```

Create a python env and install some dependencies:
```bash
mkdir helix_is_awesome
cd helix_is_awesome
python -m venv .venv
source .venv/bin/activate

pip install python-lsp-server
pip install flake8

cat 'print(1)' > test.py
cat import logging >> test.py

hx test.py
```

When you open `ŧest.py`, depending on whether or not `diagnostics` is enabled, you'll see the warning message. But the highlight will never disappear.

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

d9d7f67898a09816f51e9a699975a97734ec114f
