### ISSUE TITLE
A way to write a description in the remapping keys

### ISSUE THREAD

**Issue by TheAwiteb** [helix-editor/helix#8579]
## Summary
When remapping some keys in a node for example Goto mode node the remapping keys comes incomprehensible

> <img src="https://github.com/helix-editor/helix/assets/59842932/d7a11504-6d70-470f-aad2-0acb973cb08f" height=250>

>  <img src="https://github.com/helix-editor/helix/assets/59842932/6be90b54-4874-4ec4-beab-83c5c3021cf3" height=75>

And as you can see, it's really incomprehensible, and if I tried to share my confg with someone they would never understand it (and even if I came back after a while of setting it), so I thought it would be better to add a way to describe the keys.

### Config
The above config is 
```toml
[keys.normal.g]
"+" = ["vsplit", "jump_view_up", "goto_definition", "jump_view_down"]
"a" = ["vsplit", "jump_view_up", "goto_definition", "jump_view_down"]
"q" = ["vsplit", "jump_view_up", "goto_definition", "jump_view_down"]
"d" = {"d" = ["goto_definition"], "v" = ["vsplit", "jump_view_up", "goto_definition"], "h" = ["hsplit", "jump_view_up", "goto_definition"]}
"b" = {"d" = ["goto_definition"], "v" = ["vsplit", "jump_view_up", "goto_definition"], "h" = ["hsplit", "jump_view_up", "goto_definition"]}
"c" = {"d" = ["goto_definition"], "v" = ["vsplit", "jump_view_up", "goto_definition"], "h" = ["hsplit", "jump_view_up", "goto_definition"]}
```

## Notes
If this feature accepted I already worked on it and this is the result

> <img src="https://github.com/helix-editor/helix/assets/59842932/5cdbd7a9-d9bf-4067-9710-5371ff2c9cba" height=250>

>  <img src="https://github.com/helix-editor/helix/assets/59842932/ae658df9-25ab-4c69-baeb-5a4374a35c38" height=100>

### My description style
This is my description style, and the description is optional
```toml
"q: And Another thing" = ["vsplit", "jump_view_up", "goto_definition", "jump_view_down"]
"d: Super node1" = {"d: Super thing1" = ["goto_definition"], "v: Super thing2" = ["vsplit", "jump_view_up", "goto_definition"], "h: Super thing3" = ["hsplit", "jump_view_up", "goto_definition"]}
```

### The syntax
`<key>(:<description>)?` (I can change it if you seeing it not good)
