### ISSUE TITLE
Unable to load ruff-lsp since upgrade of helix from 23.05 to 23.10

### ISSUE THREAD

**Issue by jawuku** [helix-editor/helix#8618]
Sorry for my newbie question.

I have just upgraded `helix` from `23.05` to `23.10` on macOS Homebrew.
I had previously configured my ruff-lsp according to the guidelines on the [ruff-lsp github.](https://github.com/astral-sh/ruff-lsp)
which in `languages.toml`
```toml
# languages.toml
[[language]]
name = "python"
scope = "source.python"
language-server = { command = "ruff-lsp" }
config = { settings = { args = [] } }
```
This worked fine in 23.05, and `ruff-lsp` displayed in green with `hx --health`.

Since upgrading, I was greeted with this error message:
```
Bad language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`

Press <ENTER> to continue with default language config
```
I've tried to configure following the documentation at https://docs.helix-editor.com/languages.html
```toml
[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
scope = "source.python"
injection_regex = "python"
language-servers = [ "ruff-lsp" ]
```
but `ruff-lsp` does not show when I type `hx --health`

Could you please show me how to setup ruff-lsp?
