### ISSUE TITLE
How to add `clippy` diagnostics for Rust projects  in `22.10`?

### ISSUE THREAD

**Issue by mahor1221** [helix-editor/helix#8646]
Prior to `22.10`, I used this configuration to enable `clippy` diagnostics in Rust projects:

```toml
[[language]]
name = "rust"
[language.config.check]
command = "clippy"
```

I've tried using the new format explained [in the documentations](https://docs.helix-editor.com/languages.html#configuring-language-servers-for-a-language), but it doesn't work:
```toml
[[language]]
name = "rust"
language-servers = [ { name = "clippy", only-features = [ "diagnostics" ] } ]
```

Am I doing it wrong?

**Comment by l4l** [comment]
Try this:

```toml
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer.config]
check.command = "clippy"
```

Wiki seems to be already updated: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#rust
