### ISSUE TITLE
Can't add "register" to "editor.statusline"

### ISSUE THREAD

**Issue by onelikeandidie** [helix-editor/helix#8695]
### Summary

I wanted to add "register" to my right statusline using the _config.toml_ but helix says that the variant "register" is not known and refuses to load my config.

I saw the "register" element on the [configuration documentation](https://docs.helix-editor.com/configuration.html#editorstatusline-section) and tried to search up the problem here in the issues but all I found was that it was added in #7222.

Can it not be added to the right statusline section? Well I tried adding to the center and left sections and it still was not recognized. 

### Reproduction Steps

I tried adding "register" into my statusline in my _config.toml_ like bellow:

````toml
# ...
[editor.statusline]
left = ["mode", "version-control", "spinner", "file-name"]
center = []
# Added here, to the right status line
right = ["diagnostics", "register", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
# ...
````

I expected for it to just work but instead I got an error on start:

````
Bad config: unknown variant `register`, expected one of `mode`, `spinner`, `file-base-name`, `file-name`, `file-modification-indicator`, `file-encoding`, `file-line-ending`, `file-type`, `diagnostics`, `workspace-diagnostics`, `selections`, `primary-selection-length`, `position`, `separator`, `position-percentage`, `total-line-numbers`, `spacer`, `version-control`
in `statusline.right`

Press <ENTER> to continue with default config
````

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-11-02T10:04:50.737 helix_view::editor [ERROR] editor error: Failed to load config: unknown variant `register`, expected one of `mode`, `spinner`, `file-base-name`, `file-name`, `file-modification-indicator`, `file-encoding`, `file-line-ending`, `file-type`, `diagnostics`, `workspace-diagnostics`, `selections`, `primary-selection-length`, `position`, `separator`, `position-percentage`, `total-line-numbers`, `spacer`, `version-control`
in `statusline.right`
```

</details>

### Platform

Linux

### Terminal Emulator

Konsole 23.08.1

### Helix Version

helix 23.05
