### ISSUE TITLE
Hyphens break up the auto-completion suggestions

### ISSUE THREAD

**Issue by Nintron27** [helix-editor/helix#8701]
### Summary

Using the TailwindCSS LSP in Svelte files I noticed that auto-completion suggestions depend on the hyphens in the class names. WIthout hyphens, the TailwindCSS LSP offers perfect suggestions, just as it does in other editors, but when hyphens are introduced, the LSP's suggestions are based on all text after the hyphen. This can be seen in the two images below:
![image](https://github.com/helix-editor/helix/assets/47835714/09080c09-d0be-41bf-b730-7a1a2a7c5bd8)
![image](https://github.com/helix-editor/helix/assets/47835714/ba8d7657-1f45-467f-ae69-f151e9934faf)

My language config for this file is:
```toml
[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
roots = ["svelte.config.js"]
language-servers = ["svelteserver", "tailwindcss-ls"]
```

### Reproduction Steps

1. I configured my svelte language to also include the tailwindcss-ls language server (after svelteserver, otherwise tailwindcs-ls overrides some vital things).
2. Then proceeded to a svelte file inside of a Svelte/SvelteKit repo
3. Began editing a class list, attempting to use the tailwindcss class `bg-red-500`
4. After tying `bg-red-5` the suggestions I was expecting was something like `bg-red-50, bg-red-500, bg-red-950`, but instead got suggestions as if I had just typed `5`. Every class I try with a hyphen is as if just the text after the hyphen is what the TailwindCSS LS inputs for the suggestion.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
Too much to redact
```

</details>

### Platform

Linux (NixOS 23.05)

### Terminal Emulator

alacritty 0.12.0

### Helix Version

helix 23.10 (f6021dd0)
