### ISSUE TITLE
How to enable latex LSP for `COMMIT_EDITMSG`

### ISSUE THREAD

**Issue by Rot127** [helix-editor/helix#8724]
How do I enable the latex LSP for git commit messages?

My `language.toml` looks like this:

```toml
[language-server.latex]
command = "<path-to>/ltex-ls-16.0.0/bin/ltex-ls"

[[language]]
name = "git-commit"
language-servers = [ { name = "latex" } ]
```

`git-commit` is the "language" I am assume to choose, right? Since there is no way to use a LSP only for certain files.

But if I do `git commit` and `.git/COMMIT_EDITMSG` opens in helix the LSP does not start.
