### ISSUE TITLE
Helix not fetching custom grammer

### ISSUE THREAD

**Issue by IsotoxalDev** [helix-editor/helix#8769]
### Summary

I want to add a language not in helix. 
![image](https://github.com/helix-editor/helix/assets/62714538/d951d25a-c939-4d0e-8399-3c7f4f52e080)
This /\ is my configuration.

Output:
![image](https://github.com/helix-editor/helix/assets/62714538/b5a5f926-89ce-4445-9876-deb1f3ef7196)
No new grammar is being fetched nor build

### Reproduction Steps

paste the following code into language.toml in your config directory.
```TOML
[[language]]
name = "fountain"
scope = "source.fountain"
file-types = ["fountain"]
roots = []
indent = {tab-width = 2, unit = "  "}

[[grammer]]
name = "fountain"
source = {git = "https://github.com/UserNobody14/tree-sitter-fountain", rev = "1f8e7f77b6e9b8bdfd120cd65df0048d5cc9b147"}
```

### Helix log

I cleared the log and ran the build and fetch command and nothing is present in log

### Platform

Linux

### Terminal Emulator

Konsole

### Installation Method

Source

### Helix Version

23.10-39-g6ab774da
