### ISSUE TITLE
Syntax highlight for custom language not applying

### ISSUE THREAD

**Issue by Esgariot** [helix-editor/helix#8800]
### Summary

Given a definition of custom yaml-based dsl:
```toml
[[language]]
name = "dsl"
language-id = "yaml"
scope = "source.dsl"
file-types = ["yaml", "yml"]
roots = ["dsl.cabal"]
# grammar = "yaml"
language-servers = [ "dsl-language-server" ]

[language-server.dsl-language-server]
command = "dsl"
args = [ "lsp" ]


[[grammar]]
name = "dsl"
source = { git = "https://github.com/ikatyang/tree-sitter-yaml", rev = "0e36bed171768908f331ff7dff9d956bae016efb" }

```

Setting `grammar = "yaml"` or adding custom `[[grammar]]` that uses same tree-sitter lib doesn't work

BUT if I perform `:set-language yaml` -> `:set-language dsl` the syntax highlighting works for that particular file.

### Reproduction Steps

n/a

### Helix log

Nothing interesting there, only that `dsl-language-server` works as expected.

### Platform

Linux

### Terminal Emulator

kitty 0.31.0 created by Kovid Goyal

### Installation Method

releases page

### Helix Version

helix 23.10
