### ISSUE TITLE
Allow cancelling modifiers in themes

### ISSUE THREAD

**Issue by chtenb** [helix-editor/helix#8833]
Currently, when you pass a modifier to a certain scope, e.g. `"ui.statusline" = { modifiers = ["bold"] }`, it is impossible to undo this modifier in a more specific scope, like `ui.statusline.inactive`. 

I noticed that this is already supported in the code, but it's not yet exposed for toml configuration. 
One way to expose this functionality is by adding a `remove_modifiers` key with a list of modifiers that should be turned off.

**Comment by the-mikedavis** [comment]
The dots in theme keys are for falling back rather than merging: `theme.get("ui.statusline.inactive")` will get `ui.statusline.inactive` if it's defined or `ui.statusline` if not, then `ui`. So you should be able to just set `modifiers = []` in `ui.statusline.inactive` or omit the key since that's the default.

**Comment by chtenb** [comment]
That would make sense, but it doesn't seem to work that way, at least for `ui.statusline`. Modifiers on `ui.statusline` leak into `ui.statusline.inactive` regardless of what `modifiers` value I put on it.

Moreover, there are also situations where multiple scopes are merged by design, such as `ui.selection` with syntax highlighting scopes. For example, if you want your selections to always show as non-italic and non-bold, there is no way to do that without explicitly overriding those modifiers in case they are activated by lower-precedence highlight scopes.

**Comment by pascalkuthe** [comment]
I can not reproduce this and the code isn't implemented as you described either (even the workaround mike mentioned isn't needed). We never merge styles/modifier lists. We simply take the path (in this case `ui.statusline.inactive`) and use the first one that exists ignoring any other style. So if `ui.statusline.inactive` exists then `ui.statusline` is never considered in any way.


A quick test confirms this behavior. For example looking at the onedark theme:

``` toml
"ui.statusline" = { fg = "white", bg = "light-black" }
"ui.statusline.inactive" = { fg = "light-gray", bg = "light-black" }
```

and adding a modifier to the active part:

``` toml
"ui.statusline" = { fg = "white", bg = "light-black", modifiers = ["underlined"] }
"ui.statusline.inactive" = { fg = "light-gray", bg = "light-black" }
```

this works exactly as intended with only underlines visible in the focused split and not in this other split (see screenshot).

![image](https://github.com/helix-editor/helix/assets/61850714/d88138b6-e8d6-4034-a683-2874fc446cc2)
