### ISSUE TITLE
language server clangd for c++11 warning

### ISSUE THREAD

**Issue by Kurt-Shiwz** [helix-editor/helix#8843]
Is that  a warning? 
![image](https://github.com/helix-editor/helix/assets/7554917/fb521246-ac29-41dd-8744-4b4aebd5fc0b)

What should do in language.toml, i have try `args` and `config`, dont work.
```toml
[[language]]
name = "cpp"
# args = [ "-Wc++11-extensions" ]
# args = [ "-std=c++11" ]
# config = { "clangd.fallbackFlags" = [ "-Wc++11-extensions" ] }
# config = { "clangd.fallbackFlags" = [ "-std=c++11" ] }
# config = { "clangd.arguments" = [ "-std=c++11" ] }
# config = { "clangd.arguments" = [ "-Wc++11-extensions" ] }
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "C", "H", "cu", "cuh", "cppm", "h++", "ii", "inl", { suffix = ".hpp.in" }, { suffix = ".h.in" }]
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 4, unit = "    " }

```

```
$ clangd -version
Apple clangd version 15.0.0 (clang-1500.0.40.1)
Features: mac+xpc
Platform: x86_64-apple-darwin23.1.0; target=arm64-apple-darwin23.1.0

$ hx --version
helix 23.10 (f6021dd0)
```
