### ISSUE TITLE
Cursor color should take priority over visual indent guides

### ISSUE THREAD

**Issue by mandx** [helix-editor/helix#8909]
### Summary

I was expecting [this PR](https://github.com/helix-editor/helix/pull/8879) to fix my issue with indent guides coloring, but looks like it doesn't?

I have a custom theme, with just this override (this is the entire contents of the theme file):
```toml
inherits = "gruvbox_dark_hard"
"ui.virtual.indent-guide" = "#000000"
```

Without the `ui.virtual.indent-guide` override, it looks like this:
![image](https://github.com/helix-editor/helix/assets/535282/a0d3320b-7d9c-4c79-89e2-7fa5c79a1f57)

And with the latest local build (I checked I have this PR's already) and the override enabled, it looks like this:
![image](https://github.com/helix-editor/helix/assets/535282/b31c7ee0-9882-4b9a-abd4-914a58c14ca0)

The black indent guides look as expected, but I was expecting the cursor (and only the cursor) to look like in the first screenshot. 

These are my cursor shape and indent guide settings:

```toml
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
skip-level = 1
render = true
```

Which makes the issue more evident when I switch to Insert mode:
![image](https://github.com/helix-editor/helix/assets/535282/29a9c60a-70d4-4ca1-ae37-83a34b1d5929)

The cursor is at the same position as in the second screenshot, but it's effectively invisible.

### Reproduction Steps

 

I tried this:

1. Create and select a custom theme with just this in it:
```toml
inherits = "gruvbox_dark_hard"
"ui.virtual.indent-guide" = "#000000"
```
2. Set this in Helix settings:
```toml
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "▏"
skip-level = 1
render = true
```

I expected the cursor to look like this when positioned on an indent guide:
![image](https://github.com/helix-editor/helix/assets/535282/18e68c89-dfd2-45da-8dc9-6c386a5c3218)

Instead, it looks like this:
![image](https://github.com/helix-editor/helix/assets/535282/b31c7ee0-9882-4b9a-abd4-914a58c14ca0)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
```
[helix.log](https://github.com/helix-editor/helix/files/13464893/helix.log)
```
</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.12.3

### Installation Method

source

### Helix Version

23.10-75-g8c68074f
