### ISSUE TITLE
[':set auto-format false', ':write', ':set auto-format true'] doesn't work

### ISSUE THREAD

**Issue by andradei** [helix-editor/helix#9126]
### Summary

Manually running these commands works.

But automating them doesn't:

#### config.toml

```toml
[keys.normal.tab]
S = [':set auto-format false', ':write', ':set auto-format true']
```

It will always format the file when LSP is active and `auto-format = true` is set in `languages.toml`.

Is there a way to make this work like it does with the manual typing of these commands?

### Reproduction Steps

1. Add `S = [':set auto-format false', ':write', ':set auto-format true']` to `config.toml`
2. Add this to `languages.toml`
```toml
[[language]]
name = 'html'
auto-format = false
```
3. Try saving without formatting by running any save command: `:w`, or based on my configuration shown above `tab + S` (capital `S`)

### Platform

Linux

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Installation Method

AUR via yay

### Helix Version

helix 23.10
