### ISSUE TITLE
How to remap for select/extend mode?

### ISSUE THREAD

**Issue by sunn4room** [helix-editor/helix#9204]
> system: Archlinux
> version: 23.10

Documentation says:

> Select mode echoes Normal mode but changes any movements to extend selections rather than replace them. 

BUT when remap for Normal mode, it has no effect for select/extend mode.

An example:
```toml
[keys.normal]
h = "move_char_right"
l = "move_char_left"
```
In normal mode, `h` for right and `l` for left. But after type 'v' to enter select/extend mode, `h` for left and `l` for right.

Is there a way to remap for select/extend mode?
