### ISSUE TITLE
Wrong coloring in JSX treesitter syntax highlight

### ISSUE THREAD

**Issue by antarktidi4** [helix-editor/helix#9233]
### Summary
I'm trying deno fresh for the first time and get a terrible highlighting for JSX, idk if this is right place to start issue.

![image](https://github.com/helix-editor/helix/assets/66149987/f9436b3f-9004-4a7a-979a-1514129ea3a3)

(ik lsp doesn't do anything with syntax highlight but that's all I have done with configuration)
`languages.toml`
```toml
[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc"]
file-types = ["js", "ts", "jsx", "tsx"]
language-servers = ["deno-lsp"]
auto-format = true

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true
unstable = true
suggest = { completeFunctionCalls = false, imports = { hosts = { "https://deno.land" = true } } }
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled  = true
inlayHints.functionLikeReturnTypes.enabled = true
inlayHints.enumMemberValues.enabled = true
```

### Reproduction Steps
Create new fresh project, edit `language.toml`.

### Platform
Windows

### Terminal Emulator
windows terminal with nushell

### Installation Method
winget

### Helix Version
23.10 (f6021dd0)
