### ISSUE TITLE
"Area rulers" as alternative to "Line rulers"

### ISSUE THREAD

**Issue by rusty-snake** [helix-editor/helix#9354]
Currently rulers can be foreground or background rulers, but are always in one column. This is ambiguous between last-allowed and first-overflowing. To make this (for one ruler) more oblivious, it would be nice to have a half-open-range ruler.

It can already be emulated by putting a few hounded rulers in your config:  

```toml
[editor]
rulers = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255]
```

![screenshot](https://github.com/helix-editor/helix/assets/41237666/4d947c23-b955-4258-9333-3e1f7d555db2)

The config file could use a `rulers_style` key i.e. `foreground`, `background`, `background-area`.
