### ISSUE TITLE
Support spade-lang

### ISSUE THREAD

**Issue by nyabinary** [helix-editor/helix#9438]
Spade is a relatively new hardware description language that is inspired by Rust & Clash.
Homepage: https://spade-lang.org/

**Comment by kirawi** [comment]
The tree-sitter repository is at https://gitlab.com/spade-lang/tree-sitter-spade

**Comment by TheZoq2** [comment]
:wave: Spade author here

I used helix for a few weeks before I moved back to nvim, but this means I have a config that works and I never upstreamed. I should probably change that

```toml
[[language]]
name = "spade"
scope = "source.spade"
roots = ["swim.toml"]
file-types = ['spade']
comment-token = "//"

[[grammar]]
name = "spade"
source = {path = "/home/frans/Documents/spade/tree-sitter-spade"}
```

and the queries are here:

https://github.com/TheZoq2/helix/commit/71a2beaeee5db9dba989dbc43663a6462ab6ed78

(though now that helix and nvim queries are more similar to each other, it might be better to take the queries from https://gitlab.com/spade-lang/spade-vim/-/blob/master/queries/spade/highlights.scm?ref_type=heads which I'm more actively maintaining)
