### ISSUE TITLE
Stop silently executing arbitrary code from the current directory by default

### ISSUE THREAD

**Issue by the-dipsy** [helix-editor/helix#9514]
### Summary

According to the [docs about languages](https://docs.helix-editor.com/languages.html#languagestoml-files) language configuration is read, among others, from the current projects .helix directory and allows specification of languages and language server commands. This can easily be exploited to make helix execute arbitrary code when started in an untrusted directory.

Vim disables reading project specific configurations by default and [warns about enabling it](https://vimhelp.org/options.txt.html#%27exrc%27) for this very reason.

:exclamation: PLEASE PATCH THIS AND DON'T USE HELIX IN ANY UNTRUSTED DIRECTORIES UNTIL THEN :exclamation: 

### Reproduction Steps

1. E. g. for a python project create a file *.helix/languages.toml* with the following content.

```toml
[language-server.evil]
command = "sh"
args = ["-c", "echo evil > evil.txt"]

[[language]]
name = "python"
language-servers = ["evil"]
```

2. Start helix with `hx some-file.py`
3. See a file *evil.txt* being automatically created
4. Shiver in fear

### Platform

Linux (probably all)

### Terminal Emulator

all

### Installation Method

releases page

### Helix Version

23.10
