### ISSUE TITLE
Config Profiles

### ISSUE THREAD

**Issue by vTRaven** [helix-editor/helix#9526]
Hallo every one,

i thought it would be nice to be able to configure different profile based on the file type inside of the config.toml
For example i use helix for programming and writing with latex and i would like to use individuell themes for this.

Each profile would allow to define a local language and theme file. That could override the default global configuration File.  
I don't know how hard this would be to implement, but it would be nice to separated configurations for people which use a lot of different languages.

Some thing like this
````toml

theme = "serika-dark"

[editor]
true-color = true
line-number = "relative"
bufferline = "always"
completion-trigger-len = 1
soft-wrap.enable = false


[profile.name]
filetype = ["text","tex"]
theme = "serika-dark-latex"
language-config = "./language_latex.toml"

[profile.name.editor]
rulers = [150]
soft-wrap.enable = true
````

Please share you thoughts about this idear.

If this is already implemented in some way please let me know.
