### ISSUE TITLE
[Support] Rebuilding language grammar has no effect??

### ISSUE THREAD

**Issue by 7ombie** [helix-editor/helix#9531]
I'm trying to update the Swift grammar, and got it to build etc, but when I restart Helix, it uses the old grammar.

First, I ran `hx --grammar fetch` and `hx --grammar build`, without creating a `languages.toml` file.

Then, I created a `languages.toml` file (in `~/.config/helix`), and added this to it:

``` toml
[[language]]
name = "swift"
scope = "source.swift"
file-types = ["swift"]
injection-regex = "swift"
language-id = "swift"

[[grammar]]
name = "swift"
source.path = "/Users/carl/.config/helix/runtime/grammars/sources/swift"
```

Then, I edited `~/.config/helix/runtime/grammars/sources/swift/queries/highlights.scm`, and made a couple of changes.

I deleted `~/.config/helix/runtime/grammars/swift.so`, and ran `hx --grammar build`. It (re)built the Swift grammar (and only the Swift grammar) as expected. However, when I relaunched Helix, there was no difference??

I'd be grateful for any advice. Thanks.
