### ISSUE TITLE
Prevent scheduled builds from running on forks

### ISSUE THREAD

**Issue by dgkf** [helix-editor/helix#9591]
### Summary

There are a few hundred forks of the helix repo, and many are running [daily scheduled builds](https://github.com/dgkf/helix/actions). In the spirit of not wasting compute resources, could we add some rules to the actions to prevent future/updated forks from continuing to run these by default?

GitHub actions aren't my expertise, but I think this can be fixed using a combination of [`github.repository`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository) and [`github.event_name`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository) variables.

```yml
# .github/workflows/build.yml
jobs:
  <job>:
    if: github.repository == 'helix-editor/helix' || github.event_name != 'schedule'
```

### Reproduction Steps

Fork repo, observe [daily builds](https://github.com/dgkf/helix/actions)

### Helix log

_not applicable_

### Platform

NA

### Terminal Emulator

NA

### Installation Method

NA

### Helix Version

NA
