### ISSUE TITLE
nbsp not rendering

### ISSUE THREAD

**Issue by quentin-bettoum** [helix-editor/helix#9596]
### Summary

In my editor, no-break spaces are not rendered with the character set in the config, they are rendered with empty space.
I tried to change the font and terminal emulator used, but the result is still the same.
I also tried to set a differenc character for the nbsp, like the letter `a`, but with no result.

```toml
[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"
```

### Platform

Linux

### Terminal Emulator

Alacritty

### Installation Method

Pacman

### Helix Version

helix 23.10
