### ISSUE TITLE
[Enhancement] RISCV Assembly highlighting

### ISSUE THREAD

**Issue by hakan-demirli** [helix-editor/helix#9689]
Support RISCV Assembly highlighting.

* Current Problems:
    * `ctrl+c` comments are semicolumn and not #.
    * Inconsistent highlighting on variable/insruction names
    * C preprocessor macros are not highlighted. (`.S` files supports C preprocessor macros)
![image](https://github.com/helix-editor/helix/assets/78746991/05b6c8de-a68e-4bfc-ae14-81fa7d896aa7)

**Comment by hakan-demirli** [comment]
Looks like it has been [asked before](https://github.com/helix-editor/helix/issues/8347).
There is also a discussion about it. 
https://github.com/helix-editor/helix/discussions/7251

Looks like I need to add it as a new language myself.

**Comment by hakan-demirli** [comment]
```toml
[[language]]
name = "gas"
scope = "source.llvm"
roots = ["Makefile"]
file-types = ["S", "s"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = ["asm-lsp"]
auto-format = true
```
This one works.
