### ISSUE TITLE
Consider update from old Lua grammar

### ISSUE THREAD

**Issue by briandorsey** [helix-editor/helix#9726]
Helix appears to be referencing a two year old version of the Lua grammar:
https://github.com/helix-editor/helix/blob/928bf80d9a1d6206f864e9b375f67662a49a6265/languages.toml#L1104C75-L1104C115
```toml
[[grammar]]
name = "lua"
source = { git = "https://github.com/MunifTanjim/tree-sitter-lua", rev = "887dfd4e83c469300c279314ff1619b1d0b85b91" }
```

There is a more recent release (and new repo url, which appears to be the same repo, just moved):
https://github.com/tree-sitter-grammars/tree-sitter-lua/commit/88e446476a1e97a8724dff7a23e2d709855077f2

Is it possible/easy to update this? Is it just a matter of changing the values? eg, something like this: 
```toml
[[grammar]]
name = "lua"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-lua", rev = "88e446476a1e97a8724dff7a23e2d709855077f2" }
```

**Comment by briandorsey** [comment]
Follow up. I tested locally by adding a `.config/helix/languages.toml` file with the following content:
```toml
use-grammars = { only = [ "lua" ] }

[[grammar]]
name = "lua"
source = { git = "https://github.com/tree-sitter-grammars/tree-sitter-lua", rev = "88e446476a1e97a8724dff7a23e2d709855077f2" }
```

Then updated the grammar:
```zsh
% hx --grammar fetch
Fetching 1 grammars
1 updated grammars
	lua now on 88e446476a1e97a8724dff7a23e2d709855077f2
% hx --grammar build
Building 1 grammars
1 grammars built now
	["lua"]
```

Then confirmed that the new grammar is being used. It is, yea! 

This is also a work-around for anyone who needs updated Lua parsing before helix itself is updated.
