### ISSUE TITLE
C/C++: replace dot operator with arrow operator intelligently

### ISSUE THREAD

**Issue by GeekZJJ** [helix-editor/helix#9738]
I try to use helix to replace vscode to write C/C++ code recently. But I notice that helix can't show the struct member suggestions when I type a `.` after a struct pointer automatically. I use the same clangd args in vscode, everything works fine. So I'm guessing this is a feature we haven't being implemented currently. 
In order to troubleshoot this, I turn on clangd `--log=verbose` flag and find out helix doesn't send `context.triggerCharacter` and `context.triggerKind` to clangd. Maybe it's the root cause of this problem. But I didn't find out how to modify this behavior.
- helix's clangd output
```
I[12:28:28.089] <-- textDocument/didChange
V[12:28:28.089] <<< {
  "id": 4,
  "jsonrpc": "2.0",
  "method": "textDocument/completion",
  "params": {
    "position": {
      "character": 8,
      "line": 9
    },
    "textDocument": {
      "uri": "file://******/main.c"
    }
  }
}
```
- vscode's clangd output
```
I[12:29:34.626] <-- textDocument/didChange
V[12:29:34.652] <<< {
  "id": 24,
  "jsonrpc": "2.0",
  "method": "textDocument/completion",
  "params": {
    "context": {
      "triggerCharacter": ".",
      "triggerKind": 2
    },
    "position": {
      "character": 8,
      "line": 9
    },
    "textDocument": {
      "uri": "file://******/main.c"
    }
  }
}
```

_Originally posted by @GeekZJJ in https://github.com/helix-editor/helix/discussions/9685#discussioncomment-8601917_

### Discussed in https://github.com/helix-editor/helix/discussions/9685

<div type='discussions-op-text'>

<sup>Originally posted by **GeekZJJ** February 21, 2024</sup>
Hi! I try to use helix to replace vscode to write C/C++ code recently. Everything is good, but I notice that helix can't show the struct member suggestions when I type a `.` after a struct pointer automatically. I use the same clangd args in vscode, everything works fine. So I'm guessing this is a feature we haven't being implemented currently. Am I right?
My `language.toml` file is as below:
``` toml
[language-servers.clangd]
command = "/usr/bin/clangd"
args = ["--pretty", "--background-index", "-j=2", "--clang-tidy", "--clang-tidy-checks=performance-*,bugprone-*", "--all-scopes-completion", "--completion-style=detailed", "--header-insertion=iwyu", "--pch-storage=disk"]

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = false
```

Edited:
I found that in the `language.toml` file I make some mistake, which make clangd's args I configured don't make any sense. The `[language-servers.clangd]` should be `[language-server.clangd]`. Correct file is as below.

``` toml
[language-server.clangd]
command = "/usr/bin/clangd"
args = ["--pretty", "--background-index", "-j=2", "--clang-tidy", "--clang-tidy-checks=performance-*,bugprone-*", "--all-scopes-completion", "--completion-style=detailed", "--header-insertion=iwyu", "--pch-storage=disk"]

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = false
```
</div>
