### ISSUE TITLE
`half_page_up`/`half_page_down` does not work when combined with `align_view_center`

### ISSUE THREAD

**Issue by hoel-bagard** [helix-editor/helix#9760]
### Summary

Binding a key to `half_page_up` and `align_view_center` causes the cursor to only moves up by ~5 lines instead of half a page. `half_page_down` exhibits the same behavior.

### Reproduction Steps

I added the following to my config:

```toml
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
```

I expected to be able to go up/down by half pages while keeping my cursor centered on the page, but instead of half a page, the cursor only moves by ~5 lines.
(This can only be reproduced by opening a somewhat long file)

Probably unrelated, but doing the same changes to the search shortcuts seems to work fine.
```toml
n = ["search_next", "align_view_center"]
N = ["search_prev", "align_view_center"]
```

### Platform

Linux

### Terminal Emulator

I reproduced the issue on `wezterm 20240203-110809-5046fc22` and `konsole 23.08.5`

### Installation Method

pacman

### Helix Version

helix 23.10
