### ISSUE TITLE
Hide files within the folder and display it when its selected

### ISSUE THREAD

**Issue by amiyatulu** [helix-editor/helix#9847]
In the `Open file picker` of `spaces`, all files are displayed, making it overwhelming to find the necessary files, one has to always use search instead of tab. For example, an image folder may contain hundreds of images, which is not needed to be opened, but they are displayed in the file picker. It would be better to have an option to hide files within the folder and display them only when the folder is selected.

**Comment by pascalkuthe** [comment]
What you are describing is a file tree. Duplicate of  #200

**Comment by amiyatulu** [comment]
Thanks for the link. Using [Yazi](https://github.com/sxyazi/yazi)

.config/yazi/
[yazi.toml](https://yazi-rs.github.io/docs/configuration/overview)
```toml
[opener]
edit = [
	{ run = '${EDITOR:=hx} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]
```
