### ISSUE TITLE
Commands in keybinds block the viewport

### ISSUE THREAD

**Issue by postsolar** [helix-editor/helix#9861]
```toml
# .helix/config.toml
[keys.normal.A-space]
r = [ ":hs /dev/null", ":insert-output sleep 3; echo 1" ]
```

### Expected behavior

I would see a split open and then only the command I run would block.

### Actual behavior

The command first blocks. The split opens only when the command completes.

### Related discussion

The ideal solution for my use case would be the option to run a command and insert its output asynchronously. I admit it might sound somewhat close to the idea of an integrated terminal, but I think the key difference here is that there's no shell and no interaction with a shell involved — just non-blocking auto-reload of a file.
