### ISSUE TITLE
Better support for international keyboards

### ISSUE THREAD

**Issue by markus-oberhumer** [helix-editor/helix#9862]
I'm using a German keyboard layout and currently have to use quick hack/patch below to easily use `Left bracket` and `Right bracket`.

Would it be hard to implement keymaps for submenus like these?

```diff
--- a/helix-term/src/keymap/default.rs
+++ b/helix-term/src/keymap/default.rs
@@ -104,7 +104,7 @@ pub fn default() -> HashMap<Mode, KeyTrie> {
             "a" => select_textobject_around,
             "i" => select_textobject_inner,
         },
-        "[" => { "Left bracket"
+        "[" | "ü" => { "Left bracket" // better support for German keyboard
             "d" => goto_prev_diag,
             "D" => goto_first_diag,
             "g" => goto_prev_change,
@@ -117,7 +117,7 @@ pub fn default() -> HashMap<Mode, KeyTrie> {
             "p" => goto_prev_paragraph,
             "space" => add_newline_above,
         },
-        "]" => { "Right bracket"
+        "]" | "+" => { "Right bracket" // better support for German keyboard
             "d" => goto_next_diag,
             "D" => goto_last_diag,
             "g" => goto_next_change,
```

**Comment by TornaxO7** [comment]
Hi! May I suggest you to try [NeoQwertz](https://www.neo-layout.org/Layouts/neoqwertz/)? You won't have to relearn `QWERTZ` but you can access all special characters (brackets, backticks, etc.) easier through it. I can highly recommend it.

**Comment by pascalkuthe** [comment]
This can be handled by a simple remap with3 lines in your config. No need to change the default keymap.


I am also german and I would also recommend to save your hands and switch to a better keyboard layout. QWERTZ somehow manages to be significantly worse than QWERTY (which is itself not a good layout).

**Comment by sicher** [comment]
> > This can be handled by a simple remap with3 lines in your config. No need to change the default keymap.
> 
> Nice, but **how** can I change this? In vim/neovim I'm using
> 
> ```viml
> nmap ü [
> nmap + ]
> ```
> 
> but in helix something like this is invalid:
> 
> ```toml
> [keys.normal]
> "ü" = "["
> ```

https://docs.helix-editor.com/remapping.html

**Comment by TornaxO7** [comment]
@markus-oberhumer 
I think you can't just remap a key to imitate another key. Have you tried

```toml
[keys.normal.ü]
"d" = "goto_prev_diag"
"D" = "goto_first_diag"
"g" = "goto_prev_change"
```
for example?

**Comment by sicher** [comment]
> @TornaxO7 The point of this issue is that I want to remap `ü` to the "Left bracket submenu".

That's not possible atm. You have to create a new, or overwrite the bindings for a minor mode. Like in the docs.

**Comment by sicher** [comment]
> Well, that why my OT says:
> 
> > Would it be hard to implement keymaps for submenus like these?

Your example code showed a hard-coded solution for your specific keyboard. That's very easy to do (you did it), but it would not help me at all on my Swedish keyboard.

There are a few open PR:s that may be relevant. Check out #5046 for instance.

**Comment by sicher** [comment]
> @sicher @pascalkuthe My example code is explicitly annotated as `quick hack/patch` to show the work-around I'm currently using because of what I think is a **missing keymap feature**.

There are PR:s that intend to address remapping. I linked to one above.

**Comment by sicher** [comment]
> @sicher #5046 looks like something different (a complete keyboard remap, which is not what I suggested. I don't want to transform `ü` to `[` while in insert mode...)

I might misunderstand that PR totally, but one example given seems to me like exactly what you're after:

```
[[editor.layout-remap]]
from = 'э'
into = "'"
```

**Comment by the-mikedavis** [comment]
Easier remapping of minor modes like `[`/`]` is https://github.com/helix-editor/helix/issues/5734

The current way to remap this is:

```toml
# config.toml
[keys.normal."ü"]
d = "goto_prev_diag"
D = "goto_first_diag"
g = "goto_prev_change"
G = "goto_first_change"
f = "goto_prev_function"
t = "goto_prev_class"
a = "goto_prev_parameter"
c = "goto_prev_comment"
T = "goto_prev_test"
p = "goto_prev_paragraph"
space = "add_newline_above"

[keys.normal."+"]
d = "goto_next_diag"
D = "goto_last_diag"
g = "goto_next_change"
G = "goto_last_change"
f = "goto_next_function"
t = "goto_next_class"
a = "goto_next_parameter"
c = "goto_next_comment"
T = "goto_next_test"
p = "goto_next_paragraph"
space = "add_newline_below"
```
