### ISSUE TITLE
Define a Static Mode for inactive windows

### ISSUE THREAD

**Issue by 7ombie** [helix-editor/helix#9876]
When using multiple windows, mode indicators currently just disappear when their windows are inactive.

<img width="1280" alt="Screenshot 2024-03-15 at 12 00 42 AM" src="https://github.com/helix-editor/helix/assets/80077603/6c8db8b9-73bf-4d7c-8f62-2ba6628d4dcb">

I understand that the inactive window isn't in Insert, Normal or Select Mode (regardless of whatever mode it was in), so none of those make sense. Instead, I think there should be a fourth mode for inactive windows, called something like *Static Mode*.

Static Mode would be a first-class mode, with a six-letter name, and all of the same options as the current three. For example, we could do something like this (in `config.toml`) to make the mode indicator use the full mode-name:

``` toml
[editor.statusline]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.static = "STATIC"
```

And stuff like this (in a theme file) to color-code the indicator (when `color-modes` is enabled):

``` toml
"ui.statusline.insert" = { fg = "background", bg = "green"  }
"ui.statusline.normal" = { fg = "background", bg = "yellow" } 
"ui.statusline.select" = { fg = "background", bg = "red"    }
"ui.statusline.static" = { fg = "background", bg = "gray"   }
```

None of the existing themes style `ui.statusline.static` (obviously), and its default `fg` and `bg` would be inferred from the statusbar background, so the indicator would continue to look the same as it does now (basically, not there) when using an existing theme.

Static Mode will need a three-letter abbreviation (like `INS`, `NOR` and `SEL`) to default to. I can't see any reason not to use `STA`, but this requirement is something to keep in mind if suggesting an alternative mode-name.
