### ISSUE TITLE
.env.local file not showing in file picker

### ISSUE THREAD

**Issue by adriangalilea** [helix-editor/helix#9958]
### Summary

I've got this on my `config.toml`

``` toml
[editor.file-picker]
hidden = false
```

### Reproduction Steps

1. `cd nextjs_folder`
2. .env.local is present
3. `hx`
4. press space then f
5. .env.local is not present
6. press space then F
7. .env.local is not present
8. do `:o .env.local`
9. works

### Platform

macOS

### Terminal Emulator

kitty

### Installation Method

brew

### Helix Version

23.10

**Comment by adriangalilea** [comment]
Oops, just figured out.

```toml
[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

```
