### ISSUE TITLE
Render artifacts with Unicode 3.2 test page

### ISSUE THREAD

**Issue by helmesjo** [helix-editor/helix#9977]
### Summary

Pasting the [Unicode 3.2 test page](https://www.cogsci.ed.ac.uk/~richard/unicode-sample-3-2.html) into a new scratch buffer causes some odd rendering artifacts probably related to word-wrapping:

![helix-render-bug](https://github.com/helix-editor/helix/assets/2501070/3b2d3162-4e1a-4455-a946-dc8179dfc9ec)

```toml
# config.toml
theme = "dark_plus"

[editor]
line-number = "absolute"
color-modes = true
cursorline = true
bufferline = 'multiple'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
  "mode",
  "version-control",
  "spinner"
]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "│"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = false

[keys.normal]
X = "extend_line_up"
theme = "dark_plus"

[editor]
line-number = "absolute"
color-modes = true
cursorline = true
bufferline = 'multiple'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
  "mode",
  "version-control",
  "spinner"
]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "│"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = false

[keys.normal]
X = "extend_line_up"
```

### Reproduction Steps

 

I tried this:

1. Open a new scratch buffer and paste the content from [here](https://www.cogsci.ed.ac.uk/~richard/unicode-sample-3-2.html).
2. Notice that there are artifacts on the left-hand side when stepping through lines.

### Helix log

Nothing logged.

### Platform

Windows

### Terminal Emulator

cmd

### Installation Method

winget install Helix.Helix

### Helix Version

helix 23.10 (f6021dd0)
